### ISSUE TITLE
In Inverse, add autocompletion of our contacts in MUC invitation

### ISSUE THREAD

**Issue by linkmauve** [jcbrand/converse.js#1002]
The current participant invitation is a simple text input.  It would be much better to give it an autocompletion list of all of our contacts.

**Comment by linkmauve** [comment]
I didn’t see it was already done, nevermind. :x

**Comment by jcbrand** [comment]
I'm currently rebasing the UI on bootstrap4. Eventually I want the invite widget to be in a separate modal.
