### ISSUE TITLE
History

### ISSUE THREAD

**Issue by log69** [jcbrand/converse.js#1009]
Hi, congrats for the project. Whenever I log in to my friends XMPP server, converse.js forgets the history. Is this a missing feature? If so, then I'd like to request it. Thank you.

**Comment by jcbrand** [comment]
Can you please elaborate? I'm not sure what you mean. Converse.js supports MAM:2 for history retrieval, perhaps your XMPP server doesn't yet? I think Ejabberd is still on MAM:0 or MAM:1

**Comment by log69** [comment]
I'll check out the XMPP server then, maybe the problem is on that end. Thanks.
