### ISSUE TITLE
OTR usability issues

### ISSUE THREAD

**Issue by dkasak** [jcbrand/converse.js#1025]
I'm not sure whether I'm missing something, but I can't seem to find a way to display the OTR key fingerprint for manual verification on inverse.chat nor converjs.org. I also don't see a way of initiating OTR verification from conversejs.org/inverse.chat, but it seems to work when the other end requests it. 

Is this simply not possible yet?

**Comment by jcbrand** [comment]
@dkasak it is possible, but unfortunately it's been obscured by a UI bug. I've committed a fix which will be included in the next release.
