### ISSUE TITLE
version: 3.3.3 - converse & inverse don't work with IE11

### ISSUE THREAD

**Issue by MotoGP-Fan** [jcbrand/converse.js#1027]
As just tested on your homepage, both, converse and inverse do not work with IE11.
See the screenshot of the error message for converse:

![converse-ie11](https://user-images.githubusercontent.com/30147533/36898519-75644720-1e1b-11e8-9e70-028f8fd6af19.png)

**Comment by jcbrand** [comment]
Thanks, I've committed a fix for this.
