### ISSUE TITLE
XEP-0199 Ping Pong 

### ISSUE THREAD

**Issue by manishjodhpur** [jcbrand/converse.js#144]
Hello Jcbrand,

There is a idle connection timeout set on my openfire of 30 seconds, so if user become idle, the connection disconnects after 30 second, this is due to reason that server sends a ping stanza and i should send a pong to server.
can you please help me to send a pong stanza as a reply of ping

thanks

**Comment by thierrytiti** [comment]
I think this could be closed

**Comment by jcbrand** [comment]
True, I thought it was already closed.
