### ISSUE TITLE
Auto-connect to room?

### ISSUE THREAD

**Issue by tahnil** [jcbrand/converse.js#156]
Hello. Sorry, I don‘t know where to ask this question. Is it possible with converse.js to auto-connect to a specific room on the (pre-bound) xmpp server (in this case openfire)?

**Comment by gbonvehi** [comment]
This can be done using a plugin if needed, here's an example: https://gist.github.com/gbonvehi/376078bd6b702255a7e7

**Comment by gbonvehi** [comment]
Added another example using an external event (clicking a button) and the new rooms API.
https://gist.github.com/gbonvehi/a9d8882c8bf536693e3a

**Comment by jcbrand** [comment]
Just an update on this. Since @gbonvehi posted his examples, the API has changed a little bit.

Instead of using ``converse.chatboxes.create`` it should now be ``converse.chats.open`` for single-user chats and ``converse.rooms.open`` for chat rooms.

Please refer to the developer API docs for more info: https://conversejs.org/docs/html/development.html#developer-api

**Comment by altanai** [comment]
After converse initialize cal the listener on ready . Inside that call the room.open passing the roomname as parameter . Note that roomname id of format : roomanme@conferencer-server . It can be founf in openfire admin console under groupchat .

    converse.listen.on('ready', function (event) { 
      converse.rooms.open(roomname);
    });

you can also call a listener on group open event 

    converse.listen.on('chatRoomOpened', function (event, chatbox) {
      alert("chat room opened ");
    });

**Comment by kruegeba** [comment]
I am attempting to open a chatbox to a specific user.  Immediately after my initalize call I have:

converse.listen.on('ready', function (event) { 
  converse.chats.open(myjid);
});

and it doesn't work.  Stepping through the converse.min.js, it logs "Could not get roster item for JID".  I have confirmed it does exist, and the stranger thing is that when I move the open call to outside the ready listen statement and refresh the page, the chatbox then does pop up.  Is there an setup move that I need to wait for or add still in order to use the chats.open grouping?

Full code for reference:

    <script>
        require(['converse'], function (converse) {
            converse.initialize({
                bosh_service_url: 'http://chat.boshservice.com:5280/http-bind/', 
                keepalive: true,
                message_carbons: true,
                play_sounds: true,
                roster_groups: true,
                show_controlbox_by_default: false,
                xhr_user_search: false,
                auto_login: true,
                allow_dragresize: true,
                jid: 'loginjid',
                password: 'pasword'
            });

            converse.listen.on('initialized', function (event) { alert('initialized'); });

            converse.listen.on('reconnect', function (event) { alert('reconnect'); });

            converse.listen.on('ready', function (event) {
                console.log('ready');
                converse.chats.open(myjid);
                console.log('done ready');
            });
        });
    </script>

**Comment by jcbrand** [comment]
@kruegeba Most likely what's happening is that you're trying to open a chat before the roster has been populated. The roster gets populated upon first load and an event `roster` gets emitted, which you can listen to. However, be aware, the next time you load the same page (when `keepalive` is set to `true`), the roster will be loaded from the browser's `sessionStorage` and not fetched again from the server, so the `roster` event won't get emitted again.

**Comment by kruegeba** [comment]
I did find the hidden roster emit call...but still no luck.  I'm not sure if it's because the emit is being done at the beginning of the function:

onReceivedFromServer: function (iq) {
                /* An IQ stanza containing the roster has been received from
                 * the XMPP server.
                 */
                converse.emit('roster', iq);
                $(iq).children('query').find('item').each(function (idx, item) {
                    this.updateContact(item);
                }.bind(this));
                if (!converse.initial_presence_sent) {
                    /* Once we've sent out our initial presence stanza, we'll
                     * start receiving presence stanzas from our contacts.
                     * We therefore only want to do this after our roster has
                     * been set up (otherwise we can't meaningfully process
                     * incoming presence stanzas).
                     */
                    converse.initial_presence_sent = 1;
                    converse.xmppstatus.sendPresence();
                }
            }

So I moved it until after the "each" loop/bind, but still had no luck.

**Comment by knixeur** [comment]
@kruegeba I guess you already tried, but just in case, did you try listening to ready before calling initialize?

**Comment by singpolyma** [comment]
I also want to start a chat with a single user using API.  But the user will not be on the roster -- is it a problem?  I am getting errors so far.
