### ISSUE TITLE
XEP-0013: Flexible Offline Message Retrieval

### ISSUE THREAD

**Issue by jcbrand** [jcbrand/converse.js#174]
See the XEP spec: http://www.xmpp.org/extensions/xep-0013.html

and the mailing list discussion:
http://librelist.com/browser//conversejs/2014/5/29/offline-message/

**Comment by jcbrand** [comment]
Superseded by support for XEP-0313 Message Archive Management.

**Comment by disizlapeste** [comment]
please @jcbrand  so you can confirm to me that  current version of converse.js (that i'm using in my prosody installation) already implement xep 0160 and xep 0013 for offline messages???

**Comment by jcbrand** [comment]
XEP-0013 isn't supported. Instead, XEP-0313 (MAM) should be used.

XEP-0160 is only for servers.

**Comment by disizlapeste** [comment]
thank you @jcbrand  for your prompt response.. But i'm little confused.. I'm using converse with my prosody xmpp server.. And when i try to send msg to offline user, i'm still getting the same error message  "Sorry, an error occurred while trying to send your message."
I don't understand why.. on prosody, mod_offline is enabled by default.. so i dont understand what is the problem...
![enabled_modules_prosody](https://user-images.githubusercontent.com/30043392/124274041-15cc4d80-db41-11eb-93de-53729f834c75.jpg)
![msg_non_invitato](https://user-images.githubusercontent.com/30043392/124274045-1664e400-db41-11eb-8b52-2606a9193cc9.jpg)

**Comment by licaon-kter** [comment]
@disizlapeste did you enable mod_mam* too?

**Comment by disizlapeste** [comment]
> @disizlapeste did you enable mod_mam* too?

yes @licaon-kter .. as you can see in image, mod_mam is enabled.. 
![enabled_modules_prosody](https://user-images.githubusercontent.com/30043392/124280857-752e5b80-db49-11eb-96b2-ab8bc51a422f.jpg)

**Comment by disizlapeste** [comment]
i don't understand where is the problem.. i'm not getting errors from prosody.log.. so i dont understand..

**Comment by licaon-kter** [comment]
Other clients work ok?

**Comment by disizlapeste** [comment]
> Other clients work ok?

you say clients differents from conversejs???  i don't know.. because i've just used converse on my server.   can you suggest me some other clients please, that  i can integrate with prosody??

**Comment by licaon-kter** [comment]
Pick one https://joinjabber.org

**Comment by disizlapeste** [comment]
ok iì'll make some test now.. to check if problem is server or client.. Thank you @licaon-kter
