### ISSUE TITLE
Make MUC nickname optional

### ISSUE THREAD

**Issue by ghost** [jcbrand/converse.js#182]
Hi,

Do you think it'd be possible to make the required nickname optional for chatrooms? That is, it would default to the user jid, or anything provided at Converse initialization.

It can be confusing for already logged-in users.

Thanks.

**Comment by gbonvehi** [comment]
@jcbrand I think this is partially solved, the Nick seems to be autocompleted based on your jid https://github.com/jcbrand/converse.js/blob/master/converse.js#L2097

**Comment by jcbrand** [comment]
True. Can you think of anything else that's needed? Otherwise I'll close the ticket.

**Comment by gbonvehi** [comment]
Well, actually no, it's a business decision, to automatically select the nick if empty or validate that it cannot be empty and default to your jid when it starts as it's doing now.

**Comment by jcbrand** [comment]
cool, closing then.
