### ISSUE TITLE
Can not chat - send/receive message (when using JIDs with inconsistent text case).

### ISSUE THREAD

**Issue by vibiznet** [jcbrand/converse.js#234]
Hello,
I have a big problem with conversejs,
Of course, I used prebind.
But big problem is:
+ I can not chat with other users who use the same brower client(all client use conversejs with prebind enable, all client log in successfully)
+ Can not send message/receive message when use conversejs client, but I can send/receive if I use other clients (Pidgin - Window client)

There are no error code during this fails, even when i try to enable debug: true,
I am running my own XMPP (ejabberd and use external autheticate)
I tried all version, 0.6.6, 0.7.x, 0.8.3, but no lucky !
Even i tried with 0.8.4(add "return;" after "this.connection.attach(this.jid, this.sid, this.rid, this.onConnect);") but still does not works !
Please give an ideas and suggestion ?
(I am using the latest 0.8.3)
Thank you so much,

**Comment by jcbrand** [comment]
Should be fixed now by forcing the JID to lowercase when establishing a connection.
