### ISSUE TITLE
UI enhancement: provide non intrusive visual indicator if there's an unseen message or a pending task

### ISSUE THREAD

**Issue by priyadi** [jcbrand/converse.js#254]
If there's a pending contact request, right now converse will open controlbox. If I close the controlbox and move to another page, then converse will reopen the controlbox. It would be better if converse provides a visual indicator instead of forcing the controlbox open.

Similarly, if there's a new message, converse will open the chat window. I think non intrusive visual indicator is more preferable.

Visual indicator could be in the form of message icon, or task icon.

**Comment by jcbrand** [comment]
Related: #352
