### ISSUE TITLE
show_controlbox_by_default config not working

### ISSUE THREAD

**Issue by joe-liquid** [jcbrand/converse.js#261]
Hi, 

In my converse.initialize I have set show_controlbox_by_default to false and the control box is still opening by default. Is this a known bug? I am using version 0.8.3. 

Thanks, 

Joe

**Comment by fabiomontefuscolo** [comment]
https://github.com/conversejs/converse.js/blob/10da92ec5b51a3d2275e202494a234d7e3ab881a/src/converse-singleton.js#L51

I think this issue is back. I have to override the method `ChatBoxes::chatBoxMayBeShown` to get it working. I suggest making code around like 51 above like

```javascript
        if (chatbox.get('id') === 'controlbox') {
          return _converse.show_controlbox_by_default;
        }
```
