### ISSUE TITLE
XEP-0140: Shared Roster Groups?

### ISSUE THREAD

**Issue by darkpixel** [jcbrand/converse.js#265]
I'm not sure if this feature is supposed to work or not:

I have a client that currently uses ejabberd with Spark for all their chat needs.  They are moving to Roundcube for their e-mail, so I started to test the converse.js plugin for Roundcube.

Everything is up and running, they can send messages, but their rosters are blank.

ejabberd has a feature called 'Shared Rosters' (http://www.process-one.net/docs/ejabberd/guide_en.html#htoc61)

When I connect using Pidgin or Spark, I see the list of users in my 'shared roster' group.  When I connect with converse.js, I don't see anything.

When converse.js starts up, I see the following:

```
<body rid="3982764525" xmlns="http://jabber.org/protocol/httpbind" sid="07202e393802cfd8ea320c87ec3125f9131cc016"><iq type="get" id="1:roster" xmlns="jabber:client"><query xmlns="jabber:iq:roster"/></iq></body>

<body xmlns="http://jabber.org/protocol/httpbind"><iq xmlns="jabber:client" from="adebruyn@--redacted--" to="adebruyn@--redacted--/rc-544e9ca8cd7aa" id="1:roster" type="result"><query xmlns="jabber:iq:roster"/></iq></body>
```

So it appears my roster is blank...?  But the next logs show:

```
<body rid="3982764526" xmlns="http://jabber.org/protocol/httpbind" sid="07202e393802cfd8ea320c87ec3125f9131cc016"><presence xmlns="jabber:client"/></body>

<body xmlns="http://jabber.org/protocol/httpbind"><presence xmlns="jabber:client" from="adebruyn@--redacted--/rc-544e9bf76baf6" to="adebruyn@--redacted--/rc-544e9ca8cd7aa"><delay xmlns="urn:xmpp:delay" from="adebruyn@--redacted--/rc-544e9bf76baf6" stamp="2014-10-27T19:24:42Z"/><x xmlns="jabber:x:delay" stamp="20141027T19:24:42"/></presence><presence xmlns="jabber:client" from="asevilla@--redacted--/Spark 2.6.3" to="adebruyn@--redacted--/rc-544e9ca8cd7aa" id="0xb1x-49"><status>Away</status><priority>1</priority><show>away</show><delay xmlns="urn:xmpp:delay" from="asevilla@--redacted--/Spark 2.6.3" stamp="2014-10-27T19:20:42Z"/><x xmlns="jabber:x:delay" stamp="20141027T19:20:42"/></presence><presence xmlns="jabber:client" from="cmoss@--redacted--/EV-FRONT2" to="adebruyn@--redacted--/rc-544e9ca8cd7aa" id="oDk2Q-6"><status>Online</status><priority>1</priority><delay xmlns="urn:xmpp:delay" from="cmoss@--redacted--/EV-FRONT2" stamp="2014-10-27T19:21:38Z"/><x xmlns="jabber:x:delay" stamp="20141027T19:21:38"/></presence><presence xmlns="jabber:client" from="cspicer@--redacted--/Spark 2.6.3" to="adebruyn@--redacted--/rc-544e9ca8cd7aa" id="W2yPL-6"><status>Online</status><priority>1</priority><delay xmlns="urn:xmpp:delay" from="cspicer@--redacted--/Spark 2.6.3" stamp="2014-10-27T19:15:12Z"/><x xmlns="jabber:x:delay" stamp="20141027T19:15:12"/></presence>

--snip--

<presence xmlns="jabber:client" from="streffry@--redacted--/Spark 2.6.3" to="adebruyn@--redacted--/rc-544e9ca8cd7aa" id="0hOKD-270"><status>Away</status><priority>1</priority><show>away</show><delay xmlns="urn:xmpp:delay" from="streffry@--redacted--/Spark 2.6.3" stamp="2014-10-27T19:10:20Z"/><x xmlns="jabber:x:delay" stamp="20141027T19:10:20"/></presence><presence xmlns="jabber:client" from="adebruyn@--redacted--/rc-544e9ca8cd7aa" to="adebruyn@--redacted--/rc-544e9ca8cd7aa"/><presence xmlns="jabber:client" from="gweaver@--redacted-- " to="adebruyn@--redacted--/rc-544e9ca8cd7aa" type="error"><error code="404" type="cancel"><remote-server-not-found xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"/></error></presence></body>
```

So I'm being sent presence information on all the users that are in my shared roster group and _should_ be showing up on my roster.

I'm not familiar enough with the XMPP protocol or converse.js to know if this is expected behavior or a bug on either of the applications.

**Comment by jcbrand** [comment]
Shared roster groups should work now.

**Comment by darkpixel** [comment]
I downloaded and compiled from master a few minutes ago, and I don't see any of my shared roster groups or users.  I get a blob of debug output with all the users that *should* be on my list (and their status), but only users I manually add show up on my roster.

**Comment by jcbrand** [comment]
If you're ok with it that I see your contacts' JIDs, then please repeat your test in Chrome/Chromium and save the log output (converse.js must run in debug mode).

This post shows how to save the log output: http://stackoverflow.com/questions/7627113/save-the-console-log-in-chrome-to-a-file#31059700

And then email the log output to me. Then I can simulate your exact stanza-exchange in tests and get this to work.

**Comment by jcbrand** [comment]
My email address is the same as my chat JID, shown at the bottom of https://conversejs.org (under `Contact`).

**Comment by darkpixel** [comment]
I did some playing over the last few days.  It had to do with a vert out-dated ejabberd install.  I upgraded to the latest version and now the shared rosters show up.  Thanks for all the hard work @jcbrand.
