### ISSUE TITLE
Problem using converse.js v0.8.4 and newer without AMD and require.js

### ISSUE THREAD

**Issue by mjnaderi** [jcbrand/converse.js#286]
The method described in https://conversejs.org/docs/html/development.html#without-amd-and-require-js for using converse.js without AMD and require.js (https://github.com/jcbrand/converse.js/blob/master/non_amd.html) does not work with v0.8.4 and newer versions.

An error occurs in file `src/utils.js`:
```
define is not defined
```

**Comment by gbonvehi** [comment]
@mjnaderi @jcbrand I think this can be closed as commit 31cb3d4b6ecf79fcd9393f40f84aedb7d9ca3907 changes utils.js to not require AMD

**Comment by jcbrand** [comment]
Thanks @gbonvehi
