### ISSUE TITLE
Autojoin Chatrooms

### ISSUE THREAD

**Issue by c143** [jcbrand/converse.js#293]
It would be nice if you could autojoin Chatrooms. Its nice for Websites with support rooms or community rooms for example.

**Comment by gbonvehi** [comment]
@c143 @jcbrand This can be done using a plugin if needed, here's an example: https://gist.github.com/gbonvehi/376078bd6b702255a7e7

**Comment by gbonvehi** [comment]
This could be marked as a duplicate of Auto-connect to room? #156

**Comment by jcbrand** [comment]
yep, looks like it. Closing.
