### ISSUE TITLE
UI enhancement: Ability to adjust chatbox width

### ISSUE THREAD

**Issue by divanikus** [jcbrand/converse.js#294]
Chatrooms and chatboxes are allowed to stretch vertically but not horizontally. You might add config option for width or allow user to stretch boxes by dragging them.

**Comment by Sm0ke0ut** [comment]
I would love this enhancement as well. Especially for the group chats, as they're quite small in combination with the nicklist etc.

**Comment by jcbrand** [comment]
It's on my list of things to do :)

**Comment by pan1c** [comment]
Is there any way to make chat window bigger or fullscreen? It is impossible to read big number of formatted text (logs for example) with the current chat window width.

**Comment by jcbrand** [comment]
@pan1c Currently you can only drag it vertically to increase its height.

**Comment by jcbrand** [comment]
Possible since a while already.
