### ISSUE TITLE
Ability to predefine server to connect to

### ISSUE THREAD

**Issue by divanikus** [jcbrand/converse.js#296]
It would be nice to have an option to predefine XMPP server so users can login with their short names instead of full JIDs. Good option for internal usage with predefined corporate server.

**Comment by juniormendonca** [comment]
I'm trying to inject some jquey code on "converse.listen.on('ready')".... to get "[name=jid]" field and listen to keyup events... but no success...

**Comment by juniormendonca** [comment]
do that with jquery help (or not)


	setTimeout(function() {
		$('[name="jid"]').live('blur', function(e) {
			val = $(this).val();
			$(this).val(val.split('@')[0] + '@yourdomain')
		});
	}, 1000);

**Comment by Nepoxx** [comment]
+1

**Comment by jcbrand** [comment]
Closing in favor of #520
