### ISSUE TITLE
XEP-0313: Message Archive Management

### ISSUE THREAD

**Issue by phragment** [jcbrand/converse.js#306]
[![Bountysource](https://www.bountysource.com/badge/issue?issue_id=7883988)](https://www.bountysource.com/issues/7883988-xep-0313-message-archive-management?utm_source=7883988&utm_medium=shield&utm_campaign=ISSUE_BADGE)

It would be great to have support for [MAM](http://xmpp.org/extensions/xep-0313.html).
This would allow users to seamlessly continue their chats switching between converse.js and other XMPP clients, since messages received on another client while converse.js is offline could be retrieved from the server.

For example, this does work using prosody, gajim (Linux/Windows) and conversations (Android).

**Comment by jacekgrzybowski** [comment]
+1

**Comment by fpytloun** [comment]
+1 ;-)

**Comment by devendiran** [comment]
+1

**Comment by nickbroon** [comment]
:+1:

**Comment by nickbroon** [comment]
ejabbard and prosody both now have support for MAM http://modules.prosody.im/mod_mam.html and it being used by kaiwa https://github.com/digicoop/kaiwa#message-history-syncing

**Comment by jacekgrzybowski** [comment]
@jcbrand do you plan to implement this feature?

**Comment by jcbrand** [comment]
@jacekgrzybowski I prioritize what people pay me to do or what I'd like to work on for myself. I don't have a particular need for this feature so it's not high on my list of priorities.

**Comment by fpytloun** [comment]
And do you have some button like "Donate for XEP-0313"? :-)
If so, I think some people would support your project, especially this feature, expected by every modern-day chat.

**Comment by jcbrand** [comment]
@fpytloun You could post a bounty on [bountysource](https://www.bountysource.com). :)

**Comment by fpytloun** [comment]
Here it goes.. :-)

**Comment by jcbrand** [comment]
Thanks @fpytloun :)

**Comment by styoung** [comment]
@jcbrand please let me know how big this bounty would have to be in order to prioritize?

**Comment by jtrachtenberg** [comment]
@jcbrand - another request - please let @styoung and I know

**Comment by jcbrand** [comment]
@jtrachtenberg I appreciate it if people want to make smaller contributions towards getting something done, and I understand that not everyone can afford to pay a developer to implement a full feature. However, if you want to know what my quote is for a feature, then you can contact me personally, and not via the github issue tracker.  https://opkode.com/contact.html

**Comment by jcbrand** [comment]
This has feature now been implemented and merged into master.
