### ISSUE TITLE
0.86 room-role-list

### ISSUE THREAD

**Issue by lin20080369** [jcbrand/converse.js#307]
Dear Sir or Madam,

My name is lance Lin ,Nice to contact you.
We have use the converse js already has a period of time, However, we found that when we use the version 0.86 chat room, the user can join and leave the chat room in the first time, but if they refresh the page the room user list only show the current user, he other users list will be removed, even if other users still in the chat room. We really need you group to help us with this situation ASAP.
Hope we can receive you response soon.

Faithfully yours,

Lance.Lin

**Comment by jcbrand** [comment]
Lance, can you please provide step-by-step instructions how one can replicate this bug?

I think I've noticed this before when there is a connection timeout and the page is then reloaded, but I'm not sure whether this is what you are describing.

I'll can take a look at this problem but I cannot guarantee when exactly I'll get around to fixing it.

If you need it to be fixed very soon and are willing to pay for it, please contact me here: https://opkode.com/contact.html

**Comment by lin20080369** [comment]
jcbrand,Thank you for your prompt reply．

The test environment:

Converse js version：0.8.6 unmodified version (only modify bosh_service_url this variable),
server ： openfire 3.9.3
A typical  bug scenario is as follows::
We using different web browser log in two accounts A and B(we chose Chrome and Firefox), then joined the same chat room, A&B can saw their nickname when they join and leave the room on the chat room list but after A refresh the browser, A only can see his own nickname even both of users still in that room(we can see that on the open fire chat group) and can talk to each other. when B loged back in the chat room, Chat Room Roster can see all the nickname on the list again.
Look forward to your feedbacks and suggestions soon.

**Comment by babu3009** [comment]
i too face the same issue.

**Comment by lin20080369** [comment]
Find the cause of this bug is when I refresh the browser, only can see my own Online status in the chat room user list. We upon the solution is users loged back in the chat room， open fire MUC will send out the user's online status information to the all the users .

**Comment by emmanuel-florent** [comment]
Fixed on 0.10.0 for me !  confirm the problem still on 0.9.6  ....
