### ISSUE TITLE
Anonymously connect to chat rooms

### ISSUE THREAD

**Issue by camaran** [jcbrand/converse.js#313]
add support for anonymouse mode for connect to xmpp room only

**Comment by ge0rg** [comment]
It is possible to connect to an anonymous server by setting `authentication: "anonymous", jid: "anon.server.bare.jid"` however the `auto_join_rooms` option does not actually work then (opening an empty MUC tab).

You can still manually join a MUC, but this is a bit more complicated.

**Comment by jcbrand** [comment]
This is now possible, see for example this demo: https://conversejs.org/demo/anonymous.html

The example is in the demo folder of the git repo.

**Comment by curiousgeek123** [comment]
@jcbrand great, what would be the process to make random  anonymous rooms  dynamically ? even if the room does not already exist in prosody config file on server ?
I'm trying in a way that when 2 users come in the page a dynamic anonymous  room is created. if 3rd person comes, he is put in a new room and is on waiting and when 4th comes, 3rd and 4th are joined in 1 common room and so on. kind of private anonymous chatroom but only 2 people in each room on page load.

also, what would be a way to provide the room from url query param each time on page load?
e.g if I goto myconverse.com?room=anonymous-converse  or myconverse.com?room=anonymous-openfire should make a new room anonymous-converse and anonymous-openfire respectively even if these anonymous room dont already exist in the prosody xampp server config file?

I'm new in this, please guide me.

thanks
