### ISSUE TITLE
Add support for opening chat boxes via the URL query string

### ISSUE THREAD

**Issue by camaran** [jcbrand/converse.js#314]
add support for link in querystring users for chat

---

Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/8314624-add-support-for-opening-chat-boxes-via-the-url-query-string?utm_campaign=plugin&utm_content=tracker%2F194169&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F194169&utm_medium=issues&utm_source=github).
</bountysource-plugin>

**Comment by jcbrand** [comment]
I don't understand what you mean, please provide more information.

**Comment by camaran** [comment]
for example i have an user admin@host and i must chat with this, i link to website?converse=admin@host and it open converse (after login) and i can chat with the user

**Comment by jcbrand** [comment]
Thanks, it's clear now.

**Comment by jcbrand** [comment]
This is already implemented on master and will be released soon.

From the changelog:

> - #314 Add support for opening chat rooms with a URL fragment such as `#converse/room?jid=room@domain`
  and private chats with a URL fragment such as `#converse/chat?jid=user@domain`
