### ISSUE TITLE
Add support for private group chat

### ISSUE THREAD

**Issue by gpadbidri** [jcbrand/converse.js#320]
Users should be able to create a private group chat on the fly. Following is my Scenario :

    1. Opening a chat with one user
    2. Clicking an "add people" icon in SINGLE chat title bar (we can use same as room icon)
    3. Slide open same participant list used in room chat
    4. Search and invite users using same mechanism as room chat

Would emulating the Chat Room Code for Single User Chat involve modifying the "chatbox" template and adding an event on "ChatBoxView" only ? Or would I need to create JS functions to build xmpp formatted messages to instruct backend accordingly. i.e. covert chat to room etc. 
Also, any pointers on how I can achieve it ?

Please help, Thanks !

**Comment by jcbrand** [comment]
Let's keep this discussion in the mailing list where you started it. I've answered your questions there.
