### ISSUE TITLE
Get all contacts from given user

### ISSUE THREAD

**Issue by rubsilva** [jcbrand/converse.js#322]
Hello,

I'm trying to get the list of all contacts from currently user logged in, but all i got is an empty array. Maybe this is not an issue, but i cant get this working. 
I'm trying to call:
converse.contacts.get('buddy@example.com')
and i got:
[]
when i should get:
"array of users from given user" right?

Thank you
Rubem

**Comment by jcbrand** [comment]
Please read the [relevant documentation](https://conversejs.org/docs/html/development.html#contacts-grouping)

``converse.contacts.get("buddy@example.com")`` returns that specific roster contact (if you have a contact with that JID).

Version 0.8.6 doesn't have a way to return all roster contacts for the logged-in user. I've added this feature for the next release (where you'll call ``roster.contacts.get()`` to get all contacts).

**Comment by jcbrand** [comment]
Here's the commit where I add the ability to get all contacts:
https://github.com/jcbrand/converse.js/commit/c70561b898f1272b8b7a5cee4c98e5b48243071d

**Comment by rubsilva** [comment]
Thank you.

**Comment by jcbrand** [comment]
Ref: #46

**Comment by rubsilva** [comment]
Hi again,

When do you expect to launch a release? I am trying to build the project on my own but i am unable to do it.

Thank you.
Rubem

**Comment by jcbrand** [comment]
I don't know exactly. Should be within the next 2 weeks.

**Comment by rubsilva** [comment]
Ok thanks, until there i will try to build it on my own.

**Comment by jcbrand** [comment]
@rubsilva: It's pretty simple, you just run ``make build``

**Comment by rubsilva** [comment]
I was unable to do it because i was behind a proxy and didnt get all npm packages, now i got the build done.
Your new profile image is crazy, love it :)

Thank you.

**Comment by jcbrand** [comment]
@rubsilva Thanks :)

The code is now basically ready for the next release. I'll likely make it tomorrow or Sunday.

**Comment by anilljoshi** [comment]
Hello Here is my code
<script>
    converse.plugins.add('myplugin', {
      initialize: function() {
        var _converse = this._converse;
        Promise.all([
            _converse.api.waitUntil('rosterContactsFetched'),
            _converse.api.waitUntil('chatBoxesFetched'),
        
        ]).then(function() {
          // Note, test@conversejs.org must be in your contacts roster!
          //_converse.api.chats.open('test@conversejs.org');
          _converse.api.chats.open('bsr@192.168.8.81')
          var contacts = _converse.api.contacts.get();
          console.log(contacts)
         /* console.log( _converse.api.contacts)
          _converse.api.contacts.get()*/

        });
      }
    });
    converse.initialize({
        auto_away: 300,
        i18n: 'en',
        // websocket_url: 'ws://chat.example.org:5280/xmpp-websocket',
        muc_respect_autojoin: false,
        show_controlbox_by_default: true,

        bosh_service_url: 'http://chat.example.org:5280/http-bind/',
       
        auto_login:true,
        auto_list_rooms:true,
        allow_logout:false,
        jid:'anil@192.168.8.89',
        password:'123456',
        allow_chat_pending_contacts:true,
        message_archiving: 'always',
        debug: true,
         allow_non_roster_messaging:true,
        blacklisted_plugins: [
            'converse-register',
            
        ],
        whitelisted_plugins: ['myplugin'],
    });
</script>
but _converse.api.contacts.get() still return [] blank array could you please help how can i get my al contact
