### ISSUE TITLE
Cannot close/minimize control box programmatically 

### ISSUE THREAD

**Issue by metalaureate** [jcbrand/converse.js#323]
I'm trying

`converse.chats.get('controlbox').close()`

(after prebinding is complete and the controlbox `ready` event has fired);

This method does not seem to exist.

On inspection, this object supports:

```
endOTR: 
initiateOTR
minimize: 
maximize:
set:
open:
```

I confirmed that `open` works as expected. But how do I minimize? (Minimize does not do that.)

I looked at the commit you sent me:

https://github.com/jcbrand/converse.js/commit/c70561b898f1272b8b7a5cee4c98e5b48243071d

I don't understand github code management too well, so was unclear how to proceed.

**Comment by jcbrand** [comment]
The *close* method is added in line 5196.

You should be able to add it to your instance by cherry-picking that commit.

**Comment by metalaureate** [comment]
My ignorance is unbounded. I fetched the latest version (0.8.6), and it does not have a line 5196 in converse.js. How "do I get" this commit to do the cherry picking you speak of?

**Comment by jcbrand** [comment]
I'm referring to the commit I mentioned in the mailing list. See here: https://github.com/jcbrand/converse.js/commit/c70561b898f1272b8b7a5cee4c98e5b48243071d

To cherry pick it: ``git cherry-pick c70561b898f1272b8b7a5cee4c98e5b48243071d``

**Comment by metalaureate** [comment]
I clearly don't know what I am doing. 

`git cherry-pick c70561b898f1272b8b7a5cee4c98e5b48243071d
error: could not apply c70561b... Some API changes:
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
`

Do I need to master building converse.js from source first? I am accustomed to nuking my converse directory and copying the latest git clone contents into it. I have not progressed beyond that. :(

Also, after git cloning the latest repo, it looks like verbose logging is turned on by default, even though I have debug: false in the initialization config.

**Comment by jcbrand** [comment]
There were merge conflicts when you did the cherry-pick, that's why you got that message.

You could try to resolve them, but if you are used to nuking converse.js and starting with a newer version I'd suggest you do that.

"debug" only shows XML stanzas. If you don't see XML stanzas in your console, then you debug isn't turned on.

@gbonvehi recently made a commit to make logging less noisy: #309

**Comment by metalaureate** [comment]
@jcbrand I see that commit is merged, so if I pull the master, do I need to build the project? I have never built converse. The master project as-is still spews strophe.logs.

**Comment by jcbrand** [comment]
@metalaureate Yes, you need to build it.

To do that, you simply run ``make build``

More info here: https://github.com/jcbrand/converse.js/blob/master/docs/source/builds.rst
