### ISSUE TITLE
Private/Public Chat room

### ISSUE THREAD

**Issue by scags9876** [jcbrand/converse.js#325]
I'm trying to evaluate conversejs for use a new project, and I'm not sure if this is possible let alone simple to set up.

I've got 2 classes of users, lets call them admins and users.  I want the admins to have a single chat box open with which they can send private messages to the users, or public messages to all users in the chat.  The users should be able to send private messages to the admins, but not public message to all, and should be able to read private messages sent to them and public messages to all.  They should never see messages from other users, and they should not be able to see what other users are currently in the chat.

Will conversejs support such a requirement, and how difficult would it be to set up?

**Comment by jcbrand** [comment]
Sounds like you want a chat room where the room admins or moderators can send public room messages or send private messages, while normal participants can only write to room admins/moderators.

Converse.js doesn't currently support sending private messages to room occupants (although it shouldn't be much work to add support for that).

Besides adding support for private chatroom messages, you'll also need to add restrictions to whom one can send private messages (participants only to admins, admins to anyone) and who can send public messages (only admins can).

This can be done, but it's not a configuration issue, it would require writing a plugin.

Unfortunately there isn't currently any documentation on writing a plugin. It's on my TODO list.

**Comment by scags9876** [comment]
Thank you for the quick reply.
