### ISSUE TITLE
Can't add contact to chat

### ISSUE THREAD

**Issue by lapnd** [jcbrand/converse.js#332]
Hi all,
I have setup consersejs ver 0.90 together with openfire 3.9.1.
Currently, user can login to chat server. However, when a user try to add a contact, the target user didn't receive any request message to accept or decline. The sending site alway show "Pending Contacts"
Could you please tell me what are the additional steps to fix this issue?
Thank!
Lapd

**Comment by nodiscc** [comment]
@lapnd does anything show up in your XMPP server logs when you send _add contact_ requests? (`tail -f`)

**Comment by lapnd** [comment]
Hi Nodiscc,
This is the log message
2015.03.11 05:29:10 org.jivesoftware.openfire.session.LocalOutgoingServerSession - Error trying to connect to remote server: demo1(DNS lookup: demo1:5269): java.net.UnknownHostException: demo1 
2015.03.11 05:29:10 org.jivesoftware.openfire.session.LocalOutgoingServerSession - Error trying to connect to remote server: demo1(DNS lookup: demo1:5269): java.net.UnknownHostException: demo1 

demo1 is a target user I want to add.

**Comment by lapnd** [comment]
Hi all,
This is not the bug. I'm able to add contact now.
When add contact, I forgot to ad domain. The correct way to add contact is username@domain
Thank!
