### ISSUE TITLE
Chat State is not maintained across browser instances

### ISSUE THREAD

**Issue by gpadbidri** [jcbrand/converse.js#338]
Following are the steps to reproduce : 

    Load https://conversejs.org/ on GC
    Log into chat
    Open second tab / browser instance on GC (same browser)
    Load https://conversejs.org/
    User is required to log in again. (should not - state should match)
Expected : Use should already be logged in as he was already logged in the first tab.

**Comment by jcbrand** [comment]
I'm not aware of a sane, workable way to maintain a single BOSH session across tabs. Also not with websockets.

Instead, you need create a separate session for each tab and synchronize them via message carbons.
