### ISSUE TITLE
Force logout with single session support

### ISSUE THREAD

**Issue by pzia** [jcbrand/converse.js#339]
Step to reproduce :
- setup single session support
- login to the website with a FIRST user
   - conversejs load, authenticate, all is good
- logout off the website
- login as ANOTHER USER
  - still logged on converse with the FIRST user

Answer from @jcbrand :
No, thus is a bug. Converse.js uses the cached session tokens of the previous user.
You'll likely find that the user is still logged in to converse.js even after logging out of the website, right?

There are different ways in which we can attempt to solve this.

One way would be to explicitly call logout on conversejs when the user logs out of the website. This should then remove the session cache.

Another would be to always supply a JID together with the keepalive option, so that converse.js doesn't just blindly resume any session

Actually, I think both should be used. This will however require some changes to  be made to conversejs.

**Comment by jcbrand** [comment]
As a workaround for now, you can revert to the older way of doing things before **prebind_url** was introduced (in other words, don't use **prebind_url**).

It's explained in an earlier version of the documentation here: https://github.com/jcbrand/converse.js/blob/303a412b38e1a7da4a8ad5e34ae9f4dae1ff7ca3/docs/source/configuration.rst#using-prebind-in-connection-with-keepalive

When a new user logs in, you make sure to call the prebind url yourself and then manually pass in the RID, JID and SID tokens.

**Comment by jcbrand** [comment]
As a solution, I'll make the JID token required whenever **prebind** is set to true. This will prevent a cached session resuming when a new user logs in.

For added security I'll add a **logout** API method which must be called when the user logs out of the site, so that the session cache gets cleared.

**Comment by jcbrand** [comment]
@pzia I've now added the requirement that the JID needs to be provided when using ``keepalive`` and ``prebind``.

Can you please try it out and let me know whether it fixes your problem?

**Comment by pzia** [comment]
@jcbrand : I tried to test, but it seems I need to do the build and I've still not set up the proper environnement, but I will.
I read your commit and I understand it will reload pre binding url as soon as provided jid differs from session.jid, and that's fine enough.

As a side note, I wonder how the different session time out should match.
1- xmpp/converse timeout
2- "myapplication" session timeout
3- max-age header of the prebinding url

**Comment by jcbrand** [comment]
@pzia I've created new builds for you to test with.

**Comment by pzia** [comment]
Thanks. Tests OK.
