### ISSUE TITLE
API Documentation : converse.on vs. converse.listen.on

### ISSUE THREAD

**Issue by pzia** [jcbrand/converse.js#341]
https://conversejs.org/docs/html/development.html#listen-grouping is confusing.

Example given in section "listen grouping" : 
```converse.listen.on('message', function (event, messageXML) { ... });```

Example given in section "Event types" : 
```converse.on('initialized', function (event) { ... });```

I suspect the first one is the good one, but just to be sure...

**Comment by jcbrand** [comment]
You're right, should be ``converse.listen.on``. Fixed now.
