### ISSUE TITLE
On login ignore old room join requests

### ISSUE THREAD

**Issue by gpadbidri** [jcbrand/converse.js#342]
Hi JC,

I have modified code to create Private Chat Rooms programatically. However, when I have sent out the invite to users and the room does not exist anymore, the user still gets notifications. Following is my test case : 

1. Login as "User A"
2. Click some icon that opens the autocomplete text filed, which helps inviting users to join ChatRoom.
3. Send invites to "User B", "User C" and "User D".
4. Assuming the invite is accepted by "User B" and "User C". So now ChatRoom participants are : User A, User B, User C.
5. Consider that ALL users leave the ChatRoom. (Meaning the Chat Room does not exist as there are no participants)
6. Now "User D" logs in and he gets the invitation, but the room does not exist.

Result : I want to DISABLE the feature of users getting  "chatroom invites" immideately after login....Where in the Converse JS is the code that displays ALL the queued offline messages / invites, etc...Please let me know the API that is responsible for displaying users with invites immideately after login.

Best Regards,
Gauri Padbidri

**Comment by jcbrand** [comment]
@gpadbidri This is a support question and should therefore go to the mailing list. This issue tracker is only for bugs and features.
