### ISSUE TITLE
Path of sound and fonticons

### ISSUE THREAD

**Issue by camaran** [jcbrand/converse.js#344]
add a setting for path of asound and fonicons

**Comment by jcbrand** [comment]
The path of the fonticons cannot be configured because they're not being used in converse.js. They used in the CSS, you can change it there.

**Comment by jcbrand** [comment]
At the moment I don't really see the point of adding yet another config option (together with  new documentation) to set the sound files.

The documentation explains how you can change the sounds files:
https://conversejs.org/docs/html/configuration.html#play-sounds

**Comment by camaran** [comment]
But now must site/sound/ it's possible to not have this limit 

Inviato da iPhone

**Comment by jcbrand** [comment]
What limit? I don't understand what you mean.

**Comment by camaran** [comment]
yoursite/sound/sound.mp3 but i can have yoursite/conversejs/sound/sound.mp3
for example?

2015-04-08 13:44 GMT+02:00 JC Brand <notifications@github.com>:

**Comment by jcbrand** [comment]
Ok, I'll reopen the ticket.
