### ISSUE TITLE
Ready and Initialized events

### ISSUE THREAD

**Issue by rubsilva** [jcbrand/converse.js#350]
Hi there

I'm trying to figure out which of the above events can be used to display all the user contacts list after a connection is done. 
When i start the browser and then initialized converse, it seems like the last event is the initialized one, so i set that event to print to console the user array list of contacts. In the first load, is printed an empty array, but if i logout and login, the user contacts array is printed.
I set a setTimeout function after initialized event with 3s and the array is printed well at first load. I dont know if this is the right behavior or there is some issue here. Also i am receiving 2 ready events and i dont know why

My code:

require(['converse'], function (converse) {
            converse.listen.on('roster', function (items) {
                console.log(items);
            });
            converse.listen.on('initialized', function () {
                //hide control box when initialized
                console.log("init");
                $('#controlbox').css( "display", "none" );
                setTimeout(function(){printChatUserList(jid);}, 3000);
            });
            converse.listen.on('ready', function () {
                console.log("ready");
            });
            converse.initialize({
                bosh_service_url: 'http://'+url+'/http-bind', // Please use this connection manager only for testing purposes
                prebind: true,
                jid: jid,
                sid: sid,
                rid: rid,
                i18n: locales['en'], // Refer to ./locale/locales.js to see which locales are supported
                keepalive: true,
                message_carbons: true,
                play_sounds: true,
                roster_groups: true,
                show_controlbox_by_default: false,
                debug: false,
                xhr_user_search: false
            }); 

Thank you
Rub

**Comment by jcbrand** [comment]
This is a support question and should therefore go to the mailing list. conversejs@librelist.com

Also, when you paste code in Github, wrap it with three backticks `` ` `` so that it's properly formatted.
