### ISSUE TITLE
Non-minified development Javascript errors

### ISSUE THREAD

**Issue by gromiak** [jcbrand/converse.js#351]
Hi,
i tried to setup the development version with non-minified javascripts following https://conversejs.org/docs/html/development.html
make dev runs without errors, components directory is created

Then i uncomment <script data-main="main" src="components/requirejs/require.js"></script> and comment out <script src="builds/converse.website.min.js"></script> 
to use non compiled version, but in firebug it stops on:

 GET http://site.com/converse/components/crypto-js-evanvosberg/src/md5.js 404 (Not Found)
require.js:166 Uncaught Error: Script error for: crypto.md5
http://requirejs.org/docs/errors.html#scripterror
require.js:166 Uncaught Error: Load timeout for modules: bigint,crypto.evpkdf,crypto.cipher-core,crypto.aes,crypto.pad-nopadding,crypto.mode-ctr
http://requirejs.org/docs/errors.html#timeout

Further investigation leads me that converse/components/crypto-js-evanvosberg/src/md5.js is not exists and it exists in converse/components/crypto-js-evanvosberg/md5.js so i edited main.js, but then it cannot find core.js and many others.
What im doing wrong?
Please help me and sorry for my poor english.

**Comment by jcbrand** [comment]
You're not doing anything wrong. The last week the build has also been broken with a similar error.

The files in *crypto-js-evanvosberg* have been moved around and the version pin in bower.json wasn't strict enough.

Just do a  ``git pull``, remove ``components/crypto-js-evanvosberg`` and then do ``make dev`` again and it should work.
