### ISSUE TITLE
Some users don't show up

### ISSUE THREAD

**Issue by c143** [jcbrand/converse.js#353]
I joined a teamchat with converse and some users, two at the moment don't show up. They can write as many times as they want, but nothing appears. But i saw them in another client...

I had one of these users added, he doesn't even show up as online.

**Comment by jcbrand** [comment]
Without something concrete, like debug output or access to your instance there's not much I can do to help you.

**Comment by c143** [comment]
I use the instance on https://conversejs.org/ and i'm chatting on conference.jabber.lima-city.de. The chatroom is support@conference.jabber.lima-city.de and following JID's dont' show up:

xynopia@jabber.lima-city.de
burgi@jabber.lima-city.de

I saw them in another client, thats why i noticed the bug.

**Comment by jcbrand** [comment]
@c143

I cannot reproduce the problem because there seems to be a configuration error with your XMPP server.

When I try to connect to any room on your server, I get the following response:

``` XML
<body xmlns="http://jabber.org/protocol/httpbind">
<presence xmlns="jabber:client" to="jc@opkode.com/converse.js-33209566" type="error" from="null@conference.jabber.lima-city.de/jc">
<error type="cancel"><remote-server-not-found xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"/>      
    <text xmlns="urn:ietf:params:xml:ns:xmpp-stanzas">
        Server-to-server connection failed: DNS resolution failed
    </text>
</error>
</presence>
</body>
```

**Comment by c143** [comment]
Sorry, I forgot that you can't join with an account from another server. You would have to register on their website, but I can send you a test account as a private message.

Just tested, if the problem is on other accounts, too. It is. I don't see messages via converse.js, but I do see them in other clients.

**Comment by c143** [comment]
Additional information:
Just noticed a new JID that doesn't show up. But i saw the first message after he joined. In the other client:

florianleonsteenbuck joined
florianleonsteenbuck: msg1
florianleonsteenbuck: msg2
florianleonsteenbuck: msg3
florianleonsteenbuck: msg4

What I see in converse:
florianleonsteenbuck: msg1

JID: florianleonsteenbuck@jabber.lima-city.de

**Comment by jcbrand** [comment]
I logged in with converse.js and Gajim and don't see any difference between the two. The log output of converse.js doesn't show any errors.

The best way to test this would be some time when you are having the problem, but of course I would then also need to be available. I'm going on holiday tomorrow and won't be available for a while.

I suggest you set up a development environment of converse.js, so that you can enable debugging. Then, next time you experience this problem, check the debug output of converse.js in your browser console to see if there are any errors.

Here's the documentation on how to set up a dev environment for converse.js: 
https://conversejs.org/docs/html/development.html

On *nix systems you can simply run `` make dev `` and it should do everything for you. Then open the dev.html file in your browser and take it from there.

**Comment by c143** [comment]
A user just told me, that he doesn't see the same JID's in his smartphone client "Xabber".

I'll try to set up the dev enviroment, but 99% of the time I'm chatting in this room I'm at work.

**Comment by c143** [comment]
No, as I said i see the user chat in another client. He isn't muted, one of them is moderator...
Will try to debug when I'm at home or we might figure it out when you find time.

**Comment by c143** [comment]
I didn't have time to debug, but I figured out what the problem is. The messages that didn't show up were sent from jabber.lima-city.de, an other browser-client. I compared the XML that was sent and the only difference was the ID.

```
#Pidgin
id='purple37c0a934'

#jabber.lima-city.de
id='sess_1'

#Webchat on Lima-City.de
None
```

I wondered if the _ could be the problem - it was. Changed it and now the messages show up. But since it works with other clients, there is a bug in conversejs, too.

**Comment by jcbrand** [comment]
Hi @c143, congratulations on finding the cause of this problem.

Can you paste here the problematic message stanza which you receive from the other webchat client?

I can then write a test specifically for that stanza to expose the bug and fix it.

Thanks!

**Comment by c143** [comment]
I deleted the log. :/ The only thing that was diffrent was the ID. But i think the underline isn't the problem, because the changed version is live, but the problem is still here. I think its because the message isn't unique. That could make sense, since somtime i get one single message, like [mentioned here](https://github.com/jcbrand/converse.js/issues/353#issuecomment-87986261).

But you can test it, if you log in with the test account i sent you at https://jabber.lima-city.de/).

**Comment by jcbrand** [comment]
Thanks for the update.

I'm not going to change to code to accept different messages with the same ID. Converse.js then doesn't have the ability to detect and ignore duplicate messages being sent out.

**Comment by c143** [comment]
Yes, it would have the ability if you checked the id + message. If they're both the same, don't show it, if only one of them is diffrent its another message.
