### ISSUE TITLE
Single Session Support

### ISSUE THREAD

**Issue by saibalg78** [jcbrand/converse.js#363]
Hi,

I was trying to setup single session using converse.js along with Strophe.js. But I couldn't able to do the same. I verified that, all the sessions id, jid,sid and rid, having valid values. Though it seems that it able to login into chat but couldn't fetch contact list also not receving msg while send from another chat.

But it perfectly works while I manually lohin into chat.

I have added the code snippet for your reference.

<script>
	    var connection = null;

	    function onConnect(status,errorcondition) {
	        if (status == Strophe.Status.CONNECTED) {
	            alert("jid: " + connection.jid + "\n" + "sid: " + connection.sid + "\n"  + "rid: " + connection.rid);

	            require(['converse'], function (converse) {
	                converse.initialize({
	                    auto_list_rooms: true,
	                    auto_subscribe: true,
	                    bosh_service_url: 'http://saiballap:5280/http-bind/',
	                    hide_muc_server: false,
	                    i18n: locales.en, // Refer to ./locale/locales.js to see which locales are supported
	                    prebind: true,
	                    show_controlbox_by_default: true,
	                    roster_groups: true,
	                    jid: connection.jid,
	                    sid: connection.sid,
	                    rid: connection.rid,
                        keepalive: true
	                });
	            });
	        }
	    }

	    jQuery(document).ready(function () {
	        connection = new Strophe.Connection("http://saiballap:5280/http-bind/");
	        connection.connect("saibal@saiballap","saibal", onConnect);
});
	</script>

Please help me where I am making the mistakes.

**Comment by jcbrand** [comment]
This issue tracker is only for bugs and feature requests. For support and help with setup, please write to the mailing list: conversejs@librelist.com
