### ISSUE TITLE
Text selection impossible inside popups

### ISSUE THREAD

**Issue by pidupuis** [jcbrand/converse.js#364]
I can't select text that my contacts or I wrote. I can't even select text that I am typing (with both mouse and keyboard).

**Comment by jcbrand** [comment]
You mean inside the chat boxes? Works find for me on https://conversejs.org.

Are you using an older version?

**Comment by pidupuis** [comment]
I am using the demo on https://conversejs.org/.

I've just try on Chromium and it works. So it does not work only on my Firefox...

**Comment by jcbrand** [comment]
The problem is that FF doesn't show the selected text. Fixed (but not yet live).
