### ISSUE TITLE
Join/Left/Nick-change messages for chat rooms

### ISSUE THREAD

**Issue by c143** [jcbrand/converse.js#365]
It would be nice if you'd see when a user joins or leaves a chatroom.
There is a message if someone changes his username, but it doesn't say what his new one is.

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/10713870-join-left-nick-change-messages-for-chat-rooms?utm_campaign=plugin&utm_content=tracker%2F194169&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F194169&utm_medium=issues&utm_source=github).
</bountysource-plugin>

**Comment by jcbrand** [comment]
Done.
