### ISSUE TITLE
Show JIDs in non-anonymous rooms

### ISSUE THREAD

**Issue by c143** [jcbrand/converse.js#366]
I would like to be able to see a JID of a specific user. I can see the Nick in the list on the right, but if I wanted to add him I need the JID.

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/10714034-show-jids-in-non-anonymous-rooms?utm_campaign=plugin&utm_content=tracker%2F194169&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F194169&utm_medium=issues&utm_source=github).
</bountysource-plugin>

**Comment by jcbrand** [comment]
This is something which can only be allowed for non-anonymous rooms.

https://xmpp.org/extensions/xep-0045.html#enter-nonanon
