### ISSUE TITLE
Update from 0.8.4 to 0.9.2 via bower

### ISSUE THREAD

**Issue by teseo** [jcbrand/converse.js#381]
Hello,

We've been using so far the version 0.8.4 and I saw we were kind of out dated. I have been following the thread:

https://github.com/jcbrand/converse.js/issues/379

I was wondering, should we just wait until the next release where the cryptojs package issue is solved and after that update?

Dankie!

**Comment by jcbrand** [comment]
Yeah, we're unfortunately a bit screwed over by that change.

As a workaround you can make a source checkout and use ``bower link`` to link it into your repo. Otherwise you'll have to wait for a new release.
