### ISSUE TITLE
Problem in JSP file it not working

### ISSUE THREAD

**Issue by xiaoyaomimi** [jcbrand/converse.js#383]
Hi，
I am using converse.js-0.9.2.
The problem I am facing is the conversejs not working in my jsp file.I use the openfire as server and the
conversejs as client  and I can only make it work in html files.Another problem I meet is that when chat in chinese it comes out garbled words.The server and database I use utf-8 encode.
Any suggestions/help will be highly appreciated.
Sorry for my english.

**Comment by jcbrand** [comment]
The issue tracker on Github is only for bugs and feature requests.

If you have trouble setting up converse.js in a particular environment, then you can write to the mailing list: conversejs@librelist.com

I can't guarantee that anyone will help you there. I don't use Java or Java servlets, so I can't help you with this problem.

Also, if you can write in Chinese on https://conversejs.org, then the UTF-8 problem is not in converse.js but somewhere in your setup, which I also cannot help with.

**Comment by GitHub9527** [comment]
the chinese don't work
