### ISSUE TITLE
is converse.js altering require's define function, and thereby not allowing anonymous modules?

### ISSUE THREAD

**Issue by scags9876** [jcbrand/converse.js#384]
I'm trying to load up converse in an angular application using requirejs.  See the following tiny example of a require data-main file.   This shows that the define function before converse loads up and after is different.  
```
'use strict';
console.log(define);
require.config({
  baseUrl: "",
  paths: {
    "angular": "bower_components/angular/angular",
    "converse" : "bower_components/converse.js/builds/converse",
  },
  shim: {
    "angular": {
      exports: "angular"
    },
  }
});

require([
      "angular",
      "converse",
    ],
    function() {console.log(define)},
    function() {
      if (!window.angular || !window.angular.module || !window.angular.module('ng')) {
        // document.getElementByTagName because jQuery might not be available on error
        document.getElementsByTagName('html')[0].classList.add('unsupported-browser');
      }
    }
);
```

In the initial version, the first conditional shows:
```
       //Allow for anonymous modules
        if (typeof name !== 'string') {
            //Adjust args appropriately
            callback = deps;
            deps = name;
            name = null;
        }
```

In the post-converse load, it shows this:
```
        if (typeof name !== 'string') {
            throw new Error('See almond README: incorrect module build, no module name');
        }
```

This is causing an error in my application's load when another component that I am bringing in uses an anonymous module for loading (kendo).

Any help is appreciated.  Let me know if i can give any more info.

**Comment by jcbrand** [comment]
This issue tracker is meant to keep track of feature requests and bugs. Please, in future send support requests to the mailing list: conversejs@librelist.com

It's sometimes a fine line between a "support request" and a "bug report", but generally if you're not sure there is a bug and need help with integrating converse.js into your site, then it's best to write to the mailing list.

That said, to spare you the effort I'll reply here this time.

If you want to use require.js, then don't load the files from `build`.

Instead, load the individual files that make up converse.js separately, as is done in the [main.js](https://github.com/jcbrand/converse.js/blob/9f5f5da7eda17778a20a52a575369c945eed2481/main.js) file in converse.js. In other words, you need to update your own main.js file to have all those same dependencies (at least the ones you're going to use).

Also, then you can override the `converse-dependencies` path to point to a file where you specify only those dependencies you want. Similarly you can override the `locales` path to  use only those translations you want.

**Comment by scags9876** [comment]
Thanks for the quick reply.  I'll be sure to make use of the mailing list in the future

**Comment by jcbrand** [comment]
Someone asked a similar question on the mailing list yesterday:
http://librelist.com/browser//conversejs/2015/5/4/conversejs-without-the-amd-modules/

I replied but archive browser on librelist takes a while to update.
