### ISSUE TITLE
Make Serve

### ISSUE THREAD

**Issue by daMogli** [jcbrand/converse.js#388]
Hello, 

I'm following the instructions here: https://conversejs.org/docs/html/theming.html#setting-up-your-environment to try to set up the development environment. However, after running "make serve" I get this: 

bower ENORESTARGET  No tag found that was able to satisfy 3.1.2-5

Additional error details:
Available versions: 3.1.4, 3.1.3
make: *** [dev] Error 1

and there is nothing as localhost:8000

When i clone git repo works fine. However, when I download zip file doesn't work.

**Comment by jcbrand** [comment]
This is due to the crypto-js library removing previous releases from bower.
Please see here: https://github.com/jcbrand/converse.js/issues/379

Only thing to do is to manually change your bower.json file or to use the newest converse.js
