### ISSUE TITLE
Option to allow chatting with pending contacts

### ISSUE THREAD

**Issue by fpytloun** [jcbrand/converse.js#394]
Hello,

I haven't find a way how to convince ConverseJS to allow writing to pending contacts.
Such thing is absolutely fine by XEP and would be really appreciated by me :-)

**Comment by jcbrand** [comment]
I'm not sure I understand what you mean, please explain in greater detail.

**Comment by fpytloun** [comment]
Ok, when I add new contact in ConverseJS, it appears in roster under "Pending contacts" group. The group is not clickable so I can't open chat window to talk with such user, only delete the contact and subscription request.
But I can open the window and chat with user normally via ```converse.chat.open(...)``` so it seems to be just a thing about contact list rendering.

**Comment by jcbrand** [comment]
Yeah, I guess we could add a config option to allow chatting with pending contacts.

**Comment by fpytloun** [comment]
That would be great! :)

**Comment by thierrytiti** [comment]
You can close it, i presume
