### ISSUE TITLE
TypeError: bare is null

### ISSUE THREAD

**Issue by xDaizu** [jcbrand/converse.js#395]
Using the index.html that you provide, and the example provided in https://conversejs.org/docs/html/configuration.html#id10 I have the following code

 converse.initialize({

            bosh_service_url: 'http://localhost/http-bind', // Please use this connection manager only for testing purposes
            i18n: locales['en'], // Refer to ./locale/locales.js to see which locales are supported
            keepalive: true,
            jid: 'test@localhost',
            authentication: 'prebind',
            prebind_url: 'http://localhost/web/js/converse.js/xmpp-prebind-php-master/prebind.php',
            allow_logout: false,
            debug: true,

            expose_rid_and_sid: true,
            message_carbons: true,
            play_sounds: true,
            roster_groups: true,
            show_controlbox_by_default: true,
            xhr_user_search: false
        });

and it throws a strange error:

    **TypeError: bare is null**

on converse.js (line 26844) 

'prebind.php' example output:

    {"jid":"test@localhost","sid":"29d54a5b806d9f8b495bc4d2acc41e83bfc16fdd","rid":1331461282}

Note: this output is an echo of a json_encode($sessionInfo) array. The documentation [here](https://conversejs.org/docs/html/configuration.html#id35) isn't more specific

The reason of me posting this issue here is that I'm using everything "out-of-the-box", using the examples provided. These examples should work, and they aren't. For me, at least :S

**Comment by jcbrand** [comment]
That error implies that prebind.php didn't return a proper JID.
`test@localhost` is a valid JID, so that must not have been the value received.

Can you post a full stack trace for the TypeError?

**Comment by xDaizu** [comment]
Well, sure, I can try to give you what little information Firebug provides (if you know a way to get more info, please, just tell me :) ):

    Strophe.getBareJidFromJid(jid=null)converse.js (línea 26881)
    Strophe.getDomainFromJid(jid=null)converse.js (línea 26843)
    Strophe.Bosh.prototype._attach(jid=null, sid=null, rid=null, callback=function(status), wait=undefined, hold=undefined, wind=undefined)converse.js (línea 29677)
    Strophe.Connection.prototype.attach(jid=null, sid=null, rid=null, callback=function(status), wait=undefined, hold=undefined, wind=undefined)converse.js (línea 27832)
    .init/conn.attach(jid=null, sid=null, rid=null, callback=function(status), wait=undefined, hold=undefined, wind=undefined)converse.js (línea 30906)
    converse.initialize/this.startNewBOSHSession/<.success<(response="{"jid":"test@localhost","sid":"fd0fe18485f98bc31b2d8afdb838882de3f9ebe3","rid":1118567099}")converse.js (línea 40085)
    jQuery.Callbacks/fire(data=[Object { url="http://localhost/web/js/converse.js/xmpp-prebind-php-master/prebind.php", type="GET", isLocal=false, más...}, ["{"jid":"test@localhost","sid":"fd0fe18485f98bc31b2d8afdb838882de3f9ebe3","rid":1118567099}", "success",     Object { readyState=4, responseText="{"jid":"test@localhost","sid":"fd0fe18485f98bc31b2d8afdb838882de3f9ebe3","rid":1118567099}", status=200, más...}]])converse.js (línea 3532)
    jQuery.Callbacks/self.fireWith(context=Object { url="http://localhost/educalm...-php-master/prebind.php", type="GET", isLocal=false, más...}, args=[Object { url="http://localhost/educalm...-php-master/prebind.php", type="GET", isLocal=false, más...}, ["{"jid":"test@localhost","sid":"fd0fe18485f98bc31b2d8afdb838882de3f9ebe3","rid":1118567099}", "success", Object { readyState=4, responseText="{"{"jid":"test@localhost","sid":"fd0fe18485f98bc31b2d8afdb838882de3f9ebe3","rid":1118567099}", status=200, más...}]])converse.js (línea 3644)
    done(status=200, nativeStatusText="OK", responses=Object { text="{"jid":"test@localhost","sid":"fd0fe18485f98bc31b2d8afdb838882de3f9ebe3","rid":1118567099}"}, headers="Date: Wed, 13 May 2015 0...t/html; charset=UTF-8\r\n")converse.js (línea 9743)
    .send/callback(_=readystatechange , isAbort=undefined)converse.js (línea 10153)

As far as I understand what's going on, the data arrives well, but it lost somewhere in the initialization :S 

Just in case, the code in the prebind.php is based on [the example code provided in the documentation](https://github.com/candy-chat/xmpp-prebind-php) and read as follows: 

    require_once "lib/XmppPrebind.php";

    $username = "test";
    $password = "test";

    $xmppPrebind = new XmppPrebind('78.46.168.120', 'http://78.46.168.120:5280/http-bind/', null, false, true);
    $xmppPrebind->connect($username, $password);
    $xmppPrebind->auth();
    $sessionInfo = $xmppPrebind->getSessionInfo(); // array containing sid, rid and jid
    echo json_encode($sessionInfo);

**Comment by jcbrand** [comment]
Put a breakpoint at line 40085 in converse.js (in the browser's developer console) and then see what the `response` variable looks like. Also check `response.jid` and `response.sid`.

That will show you what is returned by your prebind script and whether it's correct.

I link to that PHP script in the documentation and I know other people are using it successfully with converse.js, but I have never used it myself.

If you find your problem it might provide us with more information which we can add to the documentation.

**Comment by xDaizu** [comment]
![debug-prebind](https://cloud.githubusercontent.com/assets/7584835/7610604/64e23e76-f97e-11e4-8b64-e65b8eb2f344.png)

It appears to be a string. Maybe the JSON string is not being decoded?

**Comment by jcbrand** [comment]
Yes, so the script is not returning JSON.

Another thing, I think we can replace `$.ajax` with `$.getJSON`.

**Comment by xDaizu** [comment]
Solved it, the problem was a little "gotchá" called:

Add:
 
    header('Content-Type: application/json');
to the server code.

**Comment by jcbrand** [comment]
@xDaizu Should I add something about it to the documentation?

**Comment by xDaizu** [comment]
Maybe there should be a note indicating that the JSON response MUST come with a JSON header (which is something always recommended but not always necessary and people tend to forget it). A little note can't hurt, can it?

That being said, if I'm the first one to fall there, maybe I'm just specially thick or careless about headers, haha....

**Comment by jcbrand** [comment]
Thanks, I added a note.
