### ISSUE TITLE
Unhandled exception on app shutdown

### ISSUE THREAD

**Issue by ChristinaElaine** [jcbrand/converse.js#398]
When closing the window that has a converse.js chat window, there is an unhandled exception in clearSession() because this.roster is undefined. It's the first line of this method:

```javascript
this.clearSession = function () {
    this.roster.browserStorage._clear();
    this.session.browserStorage._clear();
    var controlbox = converse.chatboxes.get('controlbox');
    controlbox.save({'connected': false});
};
```

I haven't seen this issue during normal running, only on shutdown.

**Comment by jcbrand** [comment]
Thanks. This should already be fixed with this commit: https://github.com/jcbrand/converse.js/commit/71ea60e44ad884d146eac699f7367bf0eda7d49e
