### ISSUE TITLE
chatBoxClosed event isn't triggered when minimized box is closed

### ISSUE THREAD

**Issue by fpytloun** [jcbrand/converse.js#402]
I am trying to implement auto-join into MUC rooms in my application. I am using this code to remove auto-join when user closes the chat box:
```
		converse.listen.on('chatBoxClosed', function(event, chatbox) {
			// Remove room from auto join rooms
			var jid = chatbox.getRoomJIDAndNick().split("/")[0];
			$.post("/xmpp/xhr/autojoin/", {'action': 'remove', 'jid': jid});
		});
```

It works fine when maximized chatbox is closed but does nothing when I close minimized chatbox.

Also I don't understand why there is `chatRoomOpened` event but no `chatRoomClosed`, anyway `chatBoxClosed` event seems to be working fine for any chat box so it doesn't matter.

And it would be good to enhance documentation to make finding existence of object's attributes easier, eg. undocumented `getRoomJIDAndNick` :-)

**Comment by jcbrand** [comment]
Not sure why you don't see the event being fired.
Looking at the code, it should be fired for minimized chats, see here:
https://github.com/jcbrand/converse.js/blob/3cbb93479ff84924fdc46d6aafd977912d7c355a/converse.js#L3355

I agree it would make sense to add a `chatRoomClosed` event.

If you can think of ways to make the documentation better, please do so and make a pull request. I'll be happy to merge.

**Comment by fpytloun** [comment]
I have wrapped getRoomJIDAndNick function into `try/catch` to handle exceptions. It seems that `chatBoxClosed` event is fired even when roster window is closed.

I have found that the event is correctly triggered when minimized window is closed but given chatbox object has no getRoomJIDAndNick function. When the same box is maximized, it works fine.
```chatbox.getRoomJIDAndNick is not a function```

**Comment by jcbrand** [comment]
> It seems that chatBoxClosed event is fired even when roster window is closed (which is probably also a bug).

No this is on purpose and not a bug.

> I have found that the event is correctly triggered when minimized window is closed but given chatbox object has no getRoomJIDAndNick function. When the same box is maximized, 

The `getRoomJIDAndNick` function is internal and not really meant for public consumption. Also, this is because minimized chat boxes and normal chat boxes are represented with two different view objects.

To get the JID you can simply call `this.model.get('jid')` if it's a chat room.
