### ISSUE TITLE
Roster not updating when new contact is added

### ISSUE THREAD

**Issue by teseo** [jcbrand/converse.js#403]
I'm logged in and have my converse roster list in an prebind session, when a new contact is added to the roster list and both are subscribed to each other, I need to refresh in order to see this new contact in my roster list.

I can see that if the other user changes presence or send messages, those are delivered to the browser but are not displayed due to is not appearing in the roster list. I need to refresh the page and then all works perfectly.

Is this the normal behaviour or a bug?

Thanks!!

**Comment by jcbrand** [comment]
Are you using the master branch? The roster code has been refactored extensively after the last release, so it might be a bug that was introduced.

**Comment by teseo** [comment]
Hello Jc,

We're using the version 0.9.3 installed through bower. This is something I have been experiencing since version 0.8.3 back in summer last year.

**Comment by jcbrand** [comment]
There must be something peculiar about your setup. Just yesterday someone subscribed to me through converse.js and didn't have to reload the page to see me in their roster list.

Have you modified converse.js? What XMPP server do you use?

**Comment by teseo** [comment]
Hello,

No, we're not modifying the code. We have custom templates but the whole installation comes from bower out of the box.

We're using Mongooseim 1.5.1 and converse.js 0.9.3

**Comment by jcbrand** [comment]
Do you have a running setup somewhere I can look at? If you need to send sensitive details you can contact me personally here: https://opkode.com/contact.html

**Comment by jcbrand** [comment]
> when a new contact is added to the roster list and both are subscribed to each other

How is a new contact added to the roster list?

**Comment by teseo** [comment]
The new contact is added directly on mysql. I enter two rows relationing the jid and nick columns with the column subscription set to B, ask to N, server to N, subscribe empty and type item.

**Comment by jcbrand** [comment]
Yeah, please mention details like that, it's important otherwise I don't know what you're talking about.

Probably what's happening is that your XMPP server is not pushing a new roster update notification after you make that change.

Set debug=true, and then check the stanzas being sent back and forth when you make such a change. You'll likely see that converse.js doesn't receive a stanza from the XMPP server after you make such a change.

If converse.js *does* receive a stanza and ignores it, then you can paste it here and I'll fix the problem. But currently it doesn't look like the problem lies in converse.js.

**Comment by teseo** [comment]
Hello Jc,

Sorry for the delay, When the new user is logged in all the stanzas related to this user are received from the inviter, the one whose roster is not updating. 

The composing stanza, the change status stanza and even the messages are received, just not rendered.

**Comment by jcbrand** [comment]
The server needs to send a **roster push** notification when the roster gets updated via MySQL.

From the [spec](https://xmpp.org/rfcs/rfc3921.html):

> This "roster push" consists of an IQ stanza of type "set" from the server to the client and enables all    available resources to remain in sync with the server-based roster information.

If it doesn't do that then converse.js has no way of knowing that there is a new user in the roster and therefore doesn't show that user. It will then also ignore message and presence stanzas from that user.

**Comment by teseo** [comment]
You are very right, that stanza is not sent by the server, it makes sense though. As I'm registering users on the chat server after they got registered in the site and by default both are subscribed to each other and for product decision, I can only have on session I'll stick to what I have and I'll work on something to refresh the roster automatically after user is generated. 

You can set this ticket as closed.
