### ISSUE TITLE
converse.logOut() with auto_reconnect = true causes reconnection retries

### ISSUE THREAD

**Issue by nevcos** [jcbrand/converse.js#418]
Calling converse.logOut() with auto_reconnect option with ```true``` value, causes reconnection retries.

Logout is calling disconnect:

```
        this.logOut = function () {
            converse.chatboxviews.closeAllChatBoxes(false);
            converse.clearSession();
            converse.connection.disconnect();
        };
```

And the DISCONNECTED status is manager by the onConnect callback, that tries to reconnect:

```
            } else if (status === Strophe.Status.DISCONNECTED) {
                if (converse.auto_reconnect) {
                    converse.reconnect();
                } else {
                    converse.renderLoginPanel();
                }
             }
```

Maybe conversejs could have a special "LOGING_OUT" state, where there's no reconnection attempts.

I'm using converse 0.9.3 (converse-no-locales-no-otr.js file) with Chrome 43 on Windows 7.

Thanks

**Comment by jcbrand** [comment]
This seems to be fixed in master. I just did a quick test and cannot replicate the problem anymore.
