### ISSUE TITLE
ConverseJS OTR Related Issue

### ISSUE THREAD

**Issue by gauripadbidri** [jcbrand/converse.js#423]
Hi JC,
I am using ConverseJS in my site and want to ENABLE the OTR feature. To do this, I open a Personal Chat Window and click the UNLOCKED Icon to initiate the OTR...However, I only see these messages : http://screencast.com/t/FVKTeYYwbgyh

I tried it on the conersejs site and it happens to work the same way. I think it is taking a lot of time. Can you please let me know what might have gone wrong ? OR it is a bug ? Thanks !

**Comment by jcbrand** [comment]
Does it hang there or does it eventually finish generating the key?

**Comment by gauripadbidri** [comment]
Hi JC,

 

It just hangs and nothing happens ! No key is generated.

 

Best Regards,

Gauri Padbidri

**Comment by jcbrand** [comment]
I can't help you without more information. What browser are you using? Do you see any debug output in the console?

**Comment by jcbrand** [comment]
I'm not getting any feedback here, so I'm closing the ticket.
