### ISSUE TITLE
Continue calling prebind_url until a connection is established (if auto_reconnect=true)

### ISSUE THREAD

**Issue by gauripadbidri** [jcbrand/converse.js#430]
When auto_reconnect is enabled, converse queries the "prebind_url" and our code gets the JID, SID and RID...Assuming the xmpp takes a while to restart and meanwhile the prebind_url fails to fetch JID, SID and RID from XMPP Server, int hat case converse fails to retry.

**Comment by jcbrand** [comment]
The auto reconnection code has been refactored extensively recently. This should now be fixed.
