### ISSUE TITLE
Make build failed on Windows

### ISSUE THREAD

**Issue by infernaler** [jcbrand/converse.js#432]
After installing git, grunt, bower, nodejs, typing "npm install" and "bower update" (i tried with "make dev" and "make -f Makefile.win dev" but it failed) i tried with "make build" in the directory of converse js but it failed giving me the following error:

touch stamp-npm
process_begin: CreateProcess(NULL, touch stamp-npm, ...) failed.
make (e=2): The system cannot find the file specified.
Makefile:85: recipe for target 'stamp-npm' failed
make: *** [stamp-npm] Error 2

I have Makefile.win in the directory of converse js
Please help

**Comment by jcbrand** [comment]
I'm sorry, but I don't use Windows and don't provide any support for building on Windows.
Windows support was added mostly by @gbonvehi, perhaps he is willing to take a look at your problem.

I suggest you write to the mailing list, conversejs@librelist.com, perhaps there's someone with Windows knowledge who can help.

This issue tracker is only used for bug reports and feature requests.

**Comment by gbonvehi** [comment]
@infernaler I'll try the Makefile again and let you know, I created it when I needed to keep developing converse and I only had a Windows machine for it.
You shouldn't be getting that error since one of the things I did was to remove the usage of touch in favor of a grunt module which does the same thing (because Windows doesn't include a touch binary).
Maybe you have an older version of the Makefile?

**Comment by gbonvehi** [comment]
@infernaler @jcbrand 

Here are some quick instructions to set this up and compile at least the javascript part of the project, note that Makefile.win should be reviewed as it may be missing some functions that I think were added to Makefile.

- Install Chocolatey: https://chocolatey.org/

Now using Chocolatey (open a cmd console as Administrator)

- Install NodeJS:
```
chocolatey install nodejs.install
```
- Install Git: 
```
chocolatey install git.install
```
- Install make (GNU):
```
chocolatey install make
```

- Clone the repository:
```
git clone https://github.com/jcbrand/converse.js.git
```
- Get all the requirements
```
make -f Makefile.win
```
- IMPORTANT NOTE: make was throwing an error when testing this, it seems to be something "known", you've to insert
```
SHELL=C:/Windows/System32/cmd.exe
````
as the first line of Makefile.win  as described here: http://superuser.com/questions/375029/make-interrupt-exception-caught

- Build the library
```
make -f Makefile.win build
```

**Comment by jcbrand** [comment]
Thanks @gbonvehi, I'll put this info in the docs sometime. Reopening this ticket as reminder.

**Comment by gbonvehi** [comment]
You're welcome, actually I included it in the docs (see https://github.com/jcbrand/converse.js/blob/master/docs/source/development.rst Windows environment:)
I think the best info would be changing the reference there to a mail and point it to this ticket ;)

**Comment by infernaler** [comment]
Thanks @gbonvehi it is working

**Comment by jcbrand** [comment]
@infernaler Please make a pull request! :)

**Comment by gbonvehi** [comment]
@infernaler you're right! it's pretty visible now that you mention it https://github.com/jcbrand/converse.js/blob/master/Makefile.win#L31 As jcbrand said, make a pull request so this can be fixed upstream.
Thanks!
