### ISSUE TITLE
How to make occupants in a room - links to a private chat

### ISSUE THREAD

**Issue by infernaler** [jcbrand/converse.js#433]
I tried with editing occupant.html in src/templates and after that building it with the following html:

<li class="{{role}}"
    {[ if (role === "moderator") { ]}
       title="{{desc_moderator}}"
    {[ } ]}
    {[ if (role === "participant") { ]}
       title="{{desc_participant}}"
    {[ } ]}
    {[ if (role === "visitor") { ]}
       title="{{desc_visitor}}"
    {[ } ]}
>
`<a class="open-chat" title="{{title_fullname}}: {{fullname}} JID: {{jid}} {{desc_chat}}" href="#">{{nick}}</a></li>`

But then the occupants list is empty only showing 
`<ul class="participant-list"></ul>`

The problem is the title attribute of the link, if it is empty everything works fine.

Please help

**Comment by jcbrand** [comment]
@infernaler I'm very strict about not accepting support requests in the issue tracker. Please write this to the mailing list and I'll try to help you there.
