### ISSUE TITLE
How to make occupants in a room - links to a private chat

### ISSUE THREAD

**Issue by infernaler** [jcbrand/converse.js#435]
I apologize for writing here again but since I haven't heard back from conversejs@librelist.com and I really need your urgent attention. Could you please take a look at it ?

**Comment by jcbrand** [comment]
You must have made a mistake, because I never received an email from you in the mailing list. The first time you send an email to the list, you need to send it twice, but you should have received a message from the list which explains that.

**Comment by jcbrand** [comment]
I looked again at the original ticket, and I honestly don't understand what the problem is or what you're trying to do. You need to provide more detail, what you're trying to do, what error messages you get and so forth.

And write it to the mailing list.
