### ISSUE TITLE
No restorable session error when using keepalive

### ISSUE THREAD

**Issue by fpytloun** [jcbrand/converse.js#438]
I am getting following error when using `keepalive: true`:

```Could not restore sessions. Error message: _restore: no restoreable session.```

It's happening here: https://github.com/jcbrand/converse.js/blob/master/converse.js#L5743
Initialize function:
```
require(['converse'], function (converse) {
    converse.initialize({
        "message_carbons": true,
        "xhr_user_search_url": "/xmpp/xhr/search/user/",
        "hide_muc_server": true,
        "allow_logout": false,
        "play_sounds": true,
        "allow_otr": false,
        "sounds_path": "/static/sounds/",
        "animate": true,
        "allow_registration": false,
        "xhr_user_search": true,
        "bosh_service_url": "https://xmpp.routebacker.com:5280/http-bind",
        "keepalive": true,
        "domain_placeholder": "develop.routebacker.com",
        "allow_muc": true,
        "jid": "filip@develop.routebacker.com",
        "password": "xxxxxxx",
        "allow_contact_requests": true,
        "auto_login": true,
        "visible_toolbar_buttons": {"clear": false, "call": false, "emoticons": true, "toggle_participants": false},
        "authentication": "login",
        "allow_chat_pending_contacts": true,
        "allow_contact_removal": false,
        "debug": true,
        "use_vcards": true,
        "auto_subscribe": true
    });
});
```

**Comment by jcbrand** [comment]
I you're making your own builds, make sure to use the master branch and not the 0.9.4 tag. I forgot to bump the strophe.js version required. That might be the issue here.

**Comment by jcbrand** [comment]
@fpytloun Can I close this ticket?

**Comment by fpytloun** [comment]
I have just taken `build/converse.min.js`.
Now I have also tried to create up-to-date build from master and it's still the same:
```Could not restore sessions. Error message: _restore: no restoreable session.```

**Comment by jcbrand** [comment]
Did you do a git pull just now? Perhaps you might have run into the same bug as in #439?

**Comment by fpytloun** [comment]
Hah, this version works! :-)
Thank you.
