### ISSUE TITLE
Issue related to Presence (Offline)  because of "null" resource added.

### ISSUE THREAD

**Issue by arung-ideas2it** [jcbrand/converse.js#440]
I am facing issue when logout. The reason behind is that "null" resource has been added to the roster object. I found while debugging, when rosters are initialized objects added with "null" resources because of bare jid. 

FYR,

https://github.com/jcbrand/converse.js/commit/cd759a7174d1377346bce966c0586ab72164730b#diff-e38d61021845f10696a85cfbe447c212R3490

**Comment by jcbrand** [comment]
Thanks @arung-ideas2it, this should be fixed now in the referenced commit.
