### ISSUE TITLE
Configuration option 'i18n' doesn't work

### ISSUE THREAD

**Issue by skope** [jcbrand/converse.js#445]
When I clone fresh repo and try to initialize converse with i18n: 'pl' for example, initialization fails and console spits out following in Chrome 44.0.2403.125 (64-bit):

`
Uncaught SyntaxError: Unexpected token p
`

In Firefox 38.0.1 output is:

`
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
`

Same happens with another languages as well.

**Comment by alexmoreno** [comment]
Same problem here. What did you do?

**Comment by skope** [comment]
IIRC instead of doing i18n: 'en' in config, I had to do i18n: locales['en']
