### ISSUE TITLE
Unable to install via Bower

### ISSUE THREAD

**Issue by turalsprofile** [jcbrand/converse.js#450]
Trying to install via bower: 
 
bower install converse

or

bower install converse.js

Installs only 0.4 version of converse. What am I doing wrong?

**Comment by jcbrand** [comment]
I don't know. Check that it's not restricted by a bower.json file in the directory in which you're installing it.

`bower info converse.js` shows that versions up until 0.9.4 are available.

This issue tracker is only for bugs or feature requests, so I'm closing this.
