### ISSUE TITLE
Instant MUC never fully completes

### ISSUE THREAD

**Issue by chrisolin** [jcbrand/converse.js#451]
As per http://xmpp.org/extensions/xep-0045.html#createroom
10.1.1: "After receiving notification that the room has been created, the room owner needs to decide whether to accept the default room configuration (i.e., create an "instant room") or configure the room to use something other than the default room configuration (i.e., create a "reserved room")."

Converse doesn't look for the room creation status codes in order to know if it needs to complete the instant room procedure. (10.1.2)

**Comment by jcbrand** [comment]
True. You can however configure a room to make it a reserved room by clicking on the gear icon at the top right of the room window.

**Comment by jcbrand** [comment]
This is now configurable via the [muc_instant_rooms](https://conversejs.org/docs/html/configuration.html#muc-instant-rooms)  setting.
