### ISSUE TITLE
converse.min.js, 行238 字符577305

### ISSUE THREAD

**Issue by zhengxiujiang** [jcbrand/converse.js#452]
ie7,ie8 has this isure

ie9 hasn't this isure

SCRIPT438: 对象不支持“bind”属性或方法 
converse.min.js, 行238 字符577305
SCRIPT5022: undefined missing converse 
converse.min.js, 行238 字符2150

**Comment by jcbrand** [comment]
Converse.js used to work in IE7 and IE8.  However, I haven't checked recently whether it still works.

I'm not interested in supporting IE7 and IE8. If someone is willing to fund the work to make converse.js work in IE7/IE8 again, I might work on it, but I'm not going to donate my time for this.
