### ISSUE TITLE
Official Dockerfile

### ISSUE THREAD

**Issue by sammcj** [jcbrand/converse.js#453]
It would be great if there was an official, lightweight Dockerfile for converse.js so that you could quickly and easily deploy a basic instance of it.

I'd suggest:

- Keep it as lightweight as possible - use alpine Linux as the base and Nginx for the web server.
- Take configuration as environment variables passed into the container.
- Make the default theme pretty like the demo page, with an option to mount external storage for custom static assets.

**Comment by fpytloun** [comment]
I was thinking about something similar for django-xmpp.
Container that would deploy latest ejabberd (including mod_mam) with authentication against simple Django application with ConverseJS.
I have also started to work on that, but still need to solve a few things, I'll keep you updated :-)

**Comment by sammcj** [comment]
@fpytloun yeah? key thing would be to make sure if it's the XMPP server that it can be easily clustered / federated to ensure reliability. Currently we use Openfire which is an unreliable, slow POS but I wasn't going to switch us to prosody / kaiwa-server until I had time to make a less heavy docker container for them.

**Comment by fpytloun** [comment]
@sammcj Ejabberd is pretty lightweight Erlang app, not difficult to setup up and easy to cluster.
Never tried Prosody to be able to compare. Openfire looks cute and is easy to setup but it's so.. Java :-)
BTW I have described way to setup this for testing in Docker container some time ago - https://github.com/fpytloun/django-xmpp/issues/3#issuecomment-117201255

**Comment by sammcj** [comment]
@fpytloun nice, I'll check out your docorisation. Openfire is very, very Java. It core dumps all the time, upgrades fail, randomly slows down, is super heavy etc...

Anyway, probably digressing about the issue at hand here. [PM me on twitter](https://twitter.com/s_mcleod) if you want to talk XMPP servers though I'm so keen to replace ours.

**Comment by jcbrand** [comment]
@sammcj, @fpytloun: For what it's worth, I use and recommend Prosody XMPP server. The code is in Lua, so it's very readable (similar to Python) and it's easy to set up. In my experience it also has better support for newer XEPs than ejabberd.

About a Dockerfile, I think it might be a good idea, but I don't personally use docker and I'm not interested in setting up (and maintaining and constantly fielding support requests) for a Dockerffile, it'll take too much of my time.

However, if you want to contribute one, we can include it in the repo (if it's not too big) and I'll be happy to mention it on the https://conversejs.org website and in the README.

**Comment by sammcj** [comment]
Thanks for the info.

I've found someone who had a decent enough basic Dockerfile, forked it, updated the version and reduced it's size a bit, I have a PR open with them: https://github.com/nsg/conversejs-docker/pull/1

A few things in it could be better such as not hard coding the version at all etc... but it's a start.
