### ISSUE TITLE
template code in form

### ISSUE THREAD

**Issue by Menzorg** [jcbrand/converse.js#454]
Where should i find a problem?
![image](https://cloud.githubusercontent.com/assets/10159888/9488386/c82bba3e-4bea-11e5-9b74-cdc9151b2172.png)

**Comment by jcbrand** [comment]
Honestly, I don't know. Besides that, this issue tracker is for bug reports and feature requests, not for support. For support, you can write to the mailing list, conversejs@librelist.org, but you'll have to provide much more information on what you're doing and how it came to be that templating doesn't work.

**Comment by ivansglazunov** [comment]
We wrote the post, and described in detail the problem :)

**Comment by jcbrand** [comment]
Sorry, I gave the wrong email address, it's conversejs@librelist.com, not .org.

http://librelist.com/browser/conversejs/

**Comment by ivansglazunov** [comment]
The problem is solved by attentive copying https://github.com/jcbrand/converse.js/blob/master/main.js :)
