### ISSUE TITLE
require is not defined and templates is not defined for conversejs

### ISSUE THREAD

**Issue by samism91** [jcbrand/converse.js#455]
I am facing this issue while doing set up for my web app.
Code is already put below the Body completion tag
and I have also added respective converse.js and converse.min.css files in my html.
Code is below:

	$(window).bind("load", function() {
	    require(['converse'], function (converse) {  
	        converse.initialize({  
	             bosh_service_url: 'http://127.0.0.1:7070/http-bind/', // 'https://conversejs.org/http-bind/' // Please use this connection manager only for testing purposes   
	             i18n: locales['en'], // Refer to ./locale/locales.js to see which locales are supported  
	             keepalive: true,  
	             message_carbons: true,  
	             play_sounds: true, 
	             roster_groups: true,  
	             show_controlbox_by_default: true,  
	             xhr_user_search: false,  
	   allow_muc: false,  
	   auto_reconnect: true,  
	   allow_registration: false,  
	   debug: false,  
	   use_otr_by_default: true,  
	   visible_toolbar_buttons:   
	   {  
	   call: false,  
	   clear: true,  
	   emoticons: true,  
	   toggle_participants: false   
	   }  
	         });  
	     }); 
	});

**Comment by jcbrand** [comment]
This issue tracker is only used for bug reports and feature requests, not for support.
You can try the mailing list: conversejs@librelist.com

The index.html file in the repo shows how to properly load and initialize converse.js.
