### ISSUE TITLE
Stanza ID assignment

### ISSUE THREAD

**Issue by hobblegobber** [jcbrand/converse.js#456]
Hello,

I am using converse.js to connect to a self hosted Ejabberd server. I came across a behavior where messages were being randomly dropped when I messaged in a group(MUC) from two different instances of conversejs browser with two different accounts.

I believe there is an issue with the Stanza ID assignment. Right now, the stanza ids are being assigned through the `getUniqueId()` function of the strophe library which returns a counter based ID with an optional suffix. This is a problem if there are two instances of conversejs browser sessions. 

Scenario:

The following scenario reproduces the bug:

Browser1 sends a message - Message ID 1
Browser2 sends a message - Message ID 2
Browser1 sends a message - Message ID 2

Now, since the message ids are the same for the last two messages, due to this line -

https://github.com/jcbrand/converse.js/blob/master/converse.js#L3372

The last message is not shown/emitted and is ignored.

I have cross checked the issue by connecting through a different XMPP client(Empathy) and the issue does not persist since Empathy uses UUID to id messages. A simple fix would be to move from counter based id that Strophe provides to UUID. The practice is recommended by XMPP RFC too - http://xmpp.org/rfcs/rfc6120.html#streams-attr-id

I have temporarily patched my code to replace the getUniqueId function with a UUID generator from this thread - http://stackoverflow.com/a/2117523 and can verify that the fix is working fine.

Please let me know if there is a better way to handle this issue/if I am missing something.

Also, would you be willing to accept a pull request for the fix by moving all ID assignments from Strophe's getUniqueId function to a utility function defined in converse.js?

**Comment by jcbrand** [comment]
Thanks for a good bug report and for figuring out the underlying cause. Makes perfect sense what you're saying and I agree with the proposed solution. However, I think this change needs to go into Strophe.js, not converse.js.

See here: https://github.com/strophe/strophejs/blob/master/src/core.js#L1681

Could you please make a pull request for this against Strophe.js? I'll make the merge there.

Tip, once you've made the change in `src/core.js`, you can run `make` to regenerate the single strophe.js file.

**Comment by hobblegobber** [comment]
Thanks for the help. I'll be checking if I can provide a pull request to the Strophe library.

**Comment by jcbrand** [comment]
This should now be fixed in the newest release.
