### ISSUE TITLE
Wrong datatype passed to converse.chatboxes.getChatBox

### ISSUE THREAD

**Issue by hobblegobber** [jcbrand/converse.js#459]
Hello,

In this line - https://github.com/jcbrand/converse.js/blob/master/converse.js#L6399

A chatroom object is passed to converse.chatboxes.getChatBox function. The getChatBox function always expects a jid string as the first argument as defined here - https://github.com/jcbrand/converse.js/blob/master/converse.js#L3548

This leads to 'Uncaught TypeError: undefined is not a function' error. I have patched the code locally to pass the jid instead of the chatroom and it looks fine. Can this be fixed?

Thanks.

**Comment by jcbrand** [comment]
Thanks, should be fixed now in master branch.
