### ISSUE TITLE
Keepalive and prebind

### ISSUE THREAD

**Issue by alb1183** [jcbrand/converse.js#460]
I have the same problem as the #438 and #439, but i use the new version 0.9.5.
When i use "**keepalive: true**" and "**prebind: true**" i get the error "**Could not restore session for jid: xxxx Error message: _restore: no restoreable session.**"
My configuration:
>		require(['converse'], function(converse) {
>				$.getJSON(urlweb+'php/prebind.php', function (data) {
>					converse.initialize({
>						debug: true,
>						i18n: locales.es,
>						bosh_service_url: 'http://servermurcia.com/http-bind/', // Please use this connection manager only for testing purposes
>						keepalive: true,
>						prebind: true,
>						jid: data.jid,
>						sid: data.sid,
>						rid: data.rid,
>						authentication: 'prebind',
>						message_carbons: true,
>						auto_subscribe: true,
>						allow_logout: false,
>						allow_muc: false,
>						allow_registration: false,
>						allow_contact_removal: false,
>						allow_contact_requests: false,
>						message_archiving: 'always',
>						use_vcards: true,
>						play_sounds: true,
>						hide_offline_users: false,
>						show_controlbox_by_default: true,
>						visible_toolbar_buttons: {"clear": false, "call": false, "emoticons": true, "toggle_participants": false}
>					});
>				});
>			});

I made my own build(version 0.9.5) and i use converse.nojquery.min.js

**Comment by jcbrand** [comment]
You're supposed to catch that error and then get new RID, SID and JID tokens which you pass to converse.initialize.

Alternatively, you can use [prebind_url](https://conversejs.org/docs/html/configuration.html#prebind-url) and let converse.js automatically call a URL for you to fetch the RID, JID and SID tokens (read the linked documentation).

For further support, please write to the mailing list: conversejs@librelist.com
