### ISSUE TITLE
MUC room names with spaces / multiple escaping

### ISSUE THREAD

**Issue by 1st8** [jcbrand/converse.js#461]
Hi,

I'm trying to resolve an issue that prevents rooms with names containing spaces (and probably other characters) from working.
Is this a known issue?

It seems, that the room jid is escaped more than once, at least when fetching the room list. ("foo bar@rooms.server.local" is escaped to "foo\20bar..." and then again to "foo\5c20bar...")
Upon room creation it is escaped correctly once.
Any ideas/hints? I'll let you know if I was able to make it work.

Cheers!

**Comment by 1st8** [comment]
Ok nevermind, I have found the extra escape (in `getRoomJIDAndNick`).
PR with some other improvements will be ready later today or tomorrow.

**Comment by jcbrand** [comment]
Pull request with improvements very welcome, thanks.
