### ISSUE TITLE
XEP-0363: HTTP File Upload

### ISSUE THREAD

**Issue by kruks23** [jcbrand/converse.js#466]
Hi,

It would be nice if converse.js implements XEP-0363: HTTP File Upload to share files:
http://xmpp.org/extensions/xep-0363.html

Sharing files in this way is very easy because you upload a file to your server and then you share the url. 

Conversations and gajim implement this XEP.

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/26496343-xep-0363-http-file-upload?utm_campaign=plugin&utm_content=tracker%2F194169&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F194169&utm_medium=issues&utm_source=github).

**Comment by Mrfuyu** [comment]
This [XEP-0363](http://xmpp.org/extensions/xep-0363.html) is so useful for todays communication. Would be fantastic great to use this with converse.js!

**Comment by jcbrand** [comment]
Yes, but it will probably still take a while. I expect to be able to implement this in the coming months.

**Comment by jcbrand** [comment]
Duplicate of #161

**Comment by shravanteegala** [comment]
How i Can implement the my IOSXMPPClient This XEP-0363 Module.
Please give me sample example.
in objective-c or swift.

**Comment by RafalxM** [comment]
Hi  @jcbrand 
I would like to ask about  image send / file upload. 
Are there any chances that this was implemented?
Thank you.

**Comment by jcbrand** [comment]
@RafalxM It's on the roadmap, but not yet done.

**Comment by Agostin** [comment]
Hello there!  Excuse me @jcbrand what about _file sharing feature_ into chat? Has been added to Converse.js? Thanks

**Comment by jcbrand** [comment]
@Agostin See #161
