### ISSUE TITLE
MAM not working : Openfire + converse.js

### ISSUE THREAD

**Issue by mrunalpittalia** [jcbrand/converse.js#470]
Hi,
I got issue with MAM while integrating XMPP to a portal build in PHP,MySQL.
 
**Tools I have used:**
* Xubuntu 14.04 server, 
* Openfire 3.10.2 latest release, setup using MySQL database type, 
* Converse.js v0.9.5 latest version
 
The converse.js & openfire both works very well.
But, getting archived messages using MAM is not working.
 
I have installed **Monitoring Service v 1.4.6** plugin in openfire and enabled archive of conversations.
As the plugin states that the MAM is used in this version, the mam calls should work.
But, I am getting "feature-not-implemented" in response of mam.
 
Here below is stanza used to get he mam pref. from openfire server:

`<body rid="550948740" xmlns="http://jabber.org/protocol/httpbind" sid="9c644adb">
	<iq id="1:sendIQ" type="get" xmlns="jabber:client">
		<prefs xmlns="urn:xmpp:mam:0"></prefs>
	</iq>
</body>`

and this is what i got in response from openfire:

`<body xmlns="http://jabber.org/protocol/httpbind" ack="550948740">
	<iq id="1:sendIQ" xmlns="jabber:client" type="error" to="796@192.168.5.43/null">
		<error code="501" type="cancel">
			<feature-not-implemented xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"></feature-not-implemented>
		</error>
	</iq>
</body>`

Am I missing anything in config or in openfire?

**Comment by jcbrand** [comment]
If you're getting "feature-not-implemented" then obviously your XMPP server doesn't support it or is not configured correctly.

Check your OpenFire configuration. Unfortunately I can't help you with that.
