### ISSUE TITLE
Cannot read property 'splitOnce' of undefined

### ISSUE THREAD

**Issue by bill2004158** [jcbrand/converse.js#472]
just find this error when trying send message "/clear" in group chat:
Uncaught TypeError: Cannot read property 'splitOnce' of undefined
d.initialize.v.ChatRoomView.m.ChatBoxView.extend.onChatRoomMessageSubmitted
d.initialize.v.ChatBoxView.Backbone.View.extend.keyPressed
p.event.dispatch
p.event.add.g.handle

**Comment by jcbrand** [comment]
Thanks. I've committed a fix and a new release is coming soon.
