### ISSUE TITLE
User is not online on messenger startup

### ISSUE THREAD

**Issue by turalsprofile** [jcbrand/converse.js#476]
After page load, it shows user as online. But it doesn't get any incoming message. However, I see status as online. 

Only after setting user offline and online again it starts to work properly and gets incoming messages

Btw, in config below https://domain.com/en/user/xmpp-auth url returns jid, sid, rid in json format. So everything ok with that. 

```
require(['converse'], function (converse) {
    converse.initialize({
        bosh_service_url: 'https://domain.com/http-bind',
        prebind_url: "https://domain.com/en/user/xmpp-auth",
        authentication: "prebind",
        xhr_user_search: false,
        i18n: locales.en,
        allow_chat_pending_contacts: true,
        show_controlbox_by_default: false,
        debug:true,
        auto_login: true,
        roster_groups: true,
        auto_list_rooms: true,
        message_archiving: "always",
        message_carbons: true,
        ping_interval:150,
        sounds_path: "/plugins/converse/sounds/",
        play_sounds:true
    });
});
```

**Comment by jcbrand** [comment]
Sounds like the server thinks that the user has gone offline when the page unloads (during a page load).

Did you modify converse.js in any way?

Could be something with the config of your XMPP server. What server are you using?

**Comment by turalsprofile** [comment]
@jcbrand Server is openfire. The latest. No I didn't modify anything
