### ISSUE TITLE
User status: object

### ISSUE THREAD

**Issue by turalsprofile** [jcbrand/converse.js#477]
Using latest version from github for 21 september.

Please take a look at this screenshot. 
http://screencast.com/t/cc87Sndir6ID

Here is what happens when I try to change the status. I can't figure out when exactly it goes like this. But it's like in 80% works well, only in 10-20% situations works like this. I think it's related with issue #476 . And it usually happens after page load. And here is how debug window looks like

http://screencast.com/t/cc87Sndir6ID

**Comment by turalsprofile** [comment]
@jcbrand please take a look

**Comment by jcbrand** [comment]
You posted the same screencast twice instead of posting info about the debug window.

**Comment by jcbrand** [comment]
Make sure you have this fix in your code: https://github.com/jcbrand/converse.js/commit/12da915ef8e057e2f0b28c388da231df5e2f30ff

To debug this you can put a `debugger` statement in that area of the code and then inspect the values when it gets called.

**Comment by turalsprofile** [comment]
Seems it was related with previous problem. In any case I will inform you. Thank you
