### ISSUE TITLE
An error occured while trying to set archiving preferences.

### ISSUE THREAD

**Issue by turalsprofile** [jcbrand/converse.js#478]
Using latest version for september 22. Also, as backend using Openfire latest.

Getting error message "An error occured while trying to set archiving preferences." in logs. http://joxi.ru/8AnNMyWTK4ZJAO

Here is config

require(['converse'], function (converse) {
    converse.initialize({
        bosh_service_url: 'https://domain.com/http-bind',
        prebind_url: "https://domain.com/en/user/xmpp-auth",
        authentication: "prebind",
        xhr_user_search: false,
        i18n: locales.en,
        allow_chat_pending_contacts: true,
        show_controlbox_by_default: false,
        debug:true,
        auto_login: true,
        roster_groups: true,
        auto_list_rooms: true,
        message_archiving: "always",
        message_carbons: true,
        ping_interval:150,
        sounds_path: "/plugins/converse/sounds/",
        play_sounds:true
    });
});

**Comment by jcbrand** [comment]
You're getting a **feature-not-implemented** message from the XMPP server, which means it doesn't support MAM.

Check your server configuration.

**Comment by turalsprofile** [comment]
@jcbrand using openfire server. As far as I know it supports.

**Comment by jcbrand** [comment]
Yes, but then you need to configure it correctly.

**Comment by turalsprofile** [comment]
@jcbrand also I don't know if it's related to archiving or not, for example if I'm offline and someone sends me message, I don't get this message and notification when I get online. Is it related to archiving or it's bug?

**Comment by turalsprofile** [comment]
@jcbrand I created chatroom for converse  js in gitter. https://gitter.im/turalsprofile/converse-js?utm_source=share-link&utm_medium=link&utm_campaign=share-link 

It'd be great if you join. Thank you in advance

**Comment by jcbrand** [comment]
I don't know, there could be multiple reasons for that behavior.

**Comment by turalsprofile** [comment]
@jcbrand I created chatroom for converse  js in gitter. https://gitter.im/turalsprofile/converse-js?utm_source=share-link&utm_medium=link&utm_campaign=share-link 

It'd be great if you join. Thank you in advance

**Comment by jcbrand** [comment]
Yeah, sorry but I'm not going to join. I use XMPP. You can join the room at discuss@conference.conversejs.org
