### ISSUE TITLE
"Ignore incoming message intended for a different resource"

### ISSUE THREAD

**Issue by turalsprofile** [jcbrand/converse.js#479]
Using latest version from github for 22 september.

Scenario looks like this:

Using web client, I'm signing in using prebind. I start to send from another account on another client (Trillian) messages to myself. Everything works well (receives messages) until I answer to second account. Problem starts from this point. I don't receive any messages after answering to account. I monitor firebug window while second account writes. I see that when second account sends message and even types log changes. But, I see something unusual:

Ignore incoming message intended for a different resource: account@domain.com/d0d09ed9

It looks like this:

http://joxi.ru/BA0b7DOCqYGBmy

I don't know if It's somehow related with prebind or not, but I can publish prebind backend script also

Config looks like this:

```
require(['converse'], function (converse) {
    converse.initialize({
        bosh_service_url: 'https://domain.com/http-bind',
        prebind_url: "https://domain.com/en/user/xmpp-auth",
        authentication: "prebind",
        xhr_user_search: false,
        i18n: locales.en,
        allow_chat_pending_contacts: true,
        show_controlbox_by_default: false,
        debug:true,
        auto_login: true,
        roster_groups: true,
        auto_list_rooms: true,
        message_archiving: "always",
        message_carbons: true,
        ping_interval:150,
        sounds_path: "/plugins/converse/sounds/",
        play_sounds:true
    });
});
```

**Comment by turalsprofile** [comment]
I tested in, https://conversejs.org/ it works well, without any error. I'm pasting here my prebind code in any case:

```
<?php
namespace common\extensions;

class XmppBosh
{
    protected $sid;
    protected $rid;
    protected $jid;
    protected $boshUrl;
    protected $user;
    protected $tld;
    protected $password;

    public function __construct($params)
    {
        foreach ($params as $key => $value)
            $this->{$key} = $value;
    }


    public function getRid()
    {
        return $this->rid;
    }

    public function getSid()
    {
        return $this->sid;
    }

    public function getJid()
    {
        return $this->jid;
    }

    public function connect()
    {
        $hash = base64_encode("$this->user@$this->tld\0$this->user\0$this->password") . "\n";
        $rid = rand();
        $jid = "$this->user@$this->tld";

        $body = "<body rid='$rid'
                    xmlns='http://jabber.org/protocol/httpbind'
                    to='4pro.co' xml:lang='en' wait='60' hold='1'
                    window='5' content='text/xml; charset=utf-8'
                    ver='1.6' xmpp:version='1.0' xmlns:xmpp='urn:xmpp:xbosh'/>";

        $return = $this->__sendBody($body);
        $xml = new \SimpleXMLElement($return);

        $sid = $xml['sid'];
        $rid++;
        $body = "<body rid='$rid' xmlns='http://jabber.org/protocol/httpbind' sid='$sid'>
                    <auth xmlns='urn:ietf:params:xml:ns:xmpp-sasl' mechanism='PLAIN'>$hash</auth>
                </body>";
        $this->__sendBody($body);

        $rid++;
        $body = "<body rid='$rid' xmlns='http://jabber.org/protocol/httpbind' sid='$sid' to='$this->tld' xml:lang='en' xmpp:restart='true' xmlns:xmpp='urn:xmpp:xbosh'/>";
        $this->__sendBody($body);

        $rid++;
        $body = "<body rid='$rid' xmlns='http://jabber.org/protocol/httpbind' sid='$sid'>
                        <iq type='set' id='_bind_auth_2' xmlns='jabber:client'>
                            <bind xmlns='urn:ietf:params:xml:ns:xmpp-bind'/>
                        </iq>
                </body>";

        $this->__sendBody($body);
        $rid++;
        $body = "<body rid='$rid' xmlns='http://jabber.org/protocol/httpbind' sid='$sid'>
            <iq type='set' id='_session_auth_2' xmlns='jabber:client'>
                <session xmlns='urn:ietf:params:xml:ns:xmpp-session'/>
            </iq>
        </body>";
        $this->__sendBody($body);
        $rid++;

        $sid = (array)$sid;
        return [
            "rid" => $rid,
            "sid" => $sid[0],
            "jid" => "$jid/messenger"
        ];
    }

    private function __sendBody($body)
    {
        $ch = curl_init($this->boshUrl);
        curl_setopt($ch, CURLOPT_HEADER, 0);
        curl_setopt($ch, CURLOPT_POST, 1);
        curl_setopt($ch, CURLOPT_POSTFIELDS, $body);
        curl_setopt($ch, CURLOPT_FOLLOWLOCATION, true);
        $header = array('Content-Type: text/xml; charset=utf-8');
        curl_setopt($ch, CURLOPT_HTTPHEADER, $header);
        curl_setopt($ch, CURLOPT_VERBOSE, 0);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        $output = curl_exec($ch);
        curl_close($ch);
        return ($output);
    }
}
```

**Comment by turalsprofile** [comment]
@jcbrand I've sent to you detailed information via mail (to jc@opkode.com )

**Comment by jcbrand** [comment]
@turalsprofile I don't want to be emailed privately for free support questions. In future, please write to the mailing list: conversejs@librelist.com

**Comment by turalsprofile** [comment]
@jcbrand I didn't know this email. no problem

**Comment by turalsprofile** [comment]
I sent message to your xmpp account. Do you know why this issue happens?

**Comment by jcbrand** [comment]
I didn't get an XMPP message. I don't know why this happens and I don't have the time right now to study it.

**Comment by jcbrand** [comment]
Some weird shit is going on here.

Look at the output you pasted here: http://joxi.ru/BA0b7DOCqYGBmy
**d0d09ed9**, which is the resource returned, is the SID in the stanza that you had sent out.

I'm not sure how that's happening. Is tural@4pro.co using Trillian?

Concerning your prebind code, don't hardcode the resource to `messenger`. Instead, rather don't return a resource at all (then converse.js will generate a resource), or otherwise make sure that you generate a unique resource every time a BOSH session is established.

Concerning the bug, I don't know where it is, but I'm pretty sure it's not in converse.js. Could be in the BOSH connection manager your using. Could be that the stanza's your prebind script.

I see you're not sending out a "resource binding request". You can try that...
See here: http://xmpp.org/extensions/xep-0206.html#preconditions-sasl

**Comment by turalsprofile** [comment]
@jcbrand I'm very thankful for your help. Please, edit your last comment and remove actual domain name from JID (as it's part of project and I don't want it to be indexed by google) I will remove all logs from here also, as I resolve this issue.

I removed messenger from my prebind code. But nothing changed. 

tural@domain.com is always in converse js side. sarkhan@domain.com is always using trillian. 

Scenario looks like that:

I open the page. sarkhan@domain.com sends me messages using trillian. I get them all, until I answer to him. He gets all answers from me. But after my first message I get this ignore problem in all following messages. I see activity in debug log. It actually receives message but doesn't show.

**Comment by turalsprofile** [comment]
I created fully working PHP handler. It works like a charm now:
https://github.com/turalsprofile/XMPP-Prebind-for-PHP
