### ISSUE TITLE
Anyway to disable "Add a contact" feature?

### ISSUE THREAD

**Issue by turalsprofile** [jcbrand/converse.js#480]
In my application user's friend added by api calls.  So there is no need to keep "Add a contact" in messenger.
I don't want to do it manually by modifying HTML files, because when update will be available I'll have to keep old, modified files and then update. 

Is there any inbuilt JS option to disable this feature? 

![screen shot 2015-09-22 at 15 13 20](https://cloud.githubusercontent.com/assets/724507/10015899/8c68f25c-613c-11e5-81bb-13b2547c73a6.png)

**Comment by jcbrand** [comment]
There is an option [allow-contact-requests](https://conversejs.org/docs/html/configuration.html#allow-contact-requests).

Please check all the configuration variables in the documentation before asking.

Also, the issue tracker here is only for bug reports and feature requests. If you have questions on how to do something (and you have read and search the documentation and didn't find anything), then you can write to the mailing list: conversejs@librelist.com
