### ISSUE TITLE
Keep only available rooms list in Rooms tab

### ISSUE THREAD

**Issue by turalsprofile** [jcbrand/converse.js#481]
In my application, all operations with rooms are going through API. What I want to achieve is, disable this form and keep only available rooms list. And if there is no room that user participiated in to hide rooms tab.

Is there anyway to achieve this?

![screen shot 2015-09-22 at 15 19 21](https://cloud.githubusercontent.com/assets/724507/10016015/64f0755a-613d-11e5-80c2-19b5a1d73acb.png)

**Comment by jcbrand** [comment]
You can use the [auto_list_rooms](https://conversejs.org/docs/html/configuration.html#auto-list-rooms) configuration setting.

There's no config setting for hiding the form. I'll mark this ticket as an enhancement to keep track of this as a feature request.

For now, you can hide it by overriding the HTML or hiding it in CSS. Or you can add that config option and make a pull request ;)

To auto-hide the tab if there aren't any chat rooms, you'll have to customize the code.
Converse.js will only query for rooms once the user clicks on the "Rooms" tab. So you'll have to change that somehow.

Once rooms are queried for, the `informNoRoomsFound` method gets called. You can probably hide the tab in there.

**Comment by turalsprofile** [comment]
Ok, I managed it. Just using css set hidden. But it'd be good to see it as config option
