### ISSUE TITLE
Strange issue with  bosh_service_url

### ISSUE THREAD

**Issue by turalsprofile** [jcbrand/converse.js#485]
My domain is: 
```
https://domain.com (w/ SSL)
```
My XMPP server's FQDN is: 
```
http://messenger.domain.com:7070/http-bind/ (w/o SSL)
```

Server is Openfire.

During development I redirected `https://domain.com/http-bind/` into `http://messenger.domain.com:7070/http-bind/` using NGinX. Set  `bosh_service_url: "https://domain.com/http-bind/"` . For now it works perfect
But I can't load main server with BOSH requests in production mode after development. 
That's why I tried to set direct url (`http://messenger.domain.com:7070/http-bind/`). Script stopped on page load. I saw loads of `XHR Failed` messages in debug window.

What's problem? Why it's not possible to set direct url?

**Comment by jcbrand** [comment]
AFAIK you're not allowed to call HTTP URLs via XHR when the page itself is loaded via HTTPS.
