### ISSUE TITLE
Honor existing mam user configuration

### ISSUE THREAD

**Issue by mt403** [jcbrand/converse.js#486]
Steps to reproduce:
- Server default policy is set to false (no archiving).
- User enables archiving with an ad-hoc command to his needs.
- Converse overwrites the user configured policy with it's defaults (false).

The following workaround is possible:
- Let the default be false
- Configure the jids you want to archive manually.

Software used:
- Server: prosody 0.10 hg:d5b416070f70
- Modules: mod_mam, mod_mam_adoc, mod_storage_xmlarchive

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/26996887-honor-existing-mam-user-configuration?utm_campaign=plugin&utm_content=tracker%2F194169&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F194169&utm_medium=issues&utm_source=github).

**Comment by devurandom** [comment]
Can't the current MAM settings be fetched on connect? Assuming that whenever MAM is enabled on the server, some preference will already be set, converse.js should only change those preferences if explicitly requested by the user.

**Comment by dl8bh** [comment]
I think, this is still a big issue which needs attention. I, as a XMPP server administrator, don't want to decide for all users, if they want their private conversations to be stored on the server or not. It should be really up to them, just honoring the existing decision should be enough, an interface for configuration is not needed in converse.js imho.

**Comment by weiss** [comment]
> an interface for configuration is not needed in converse.js imho.

If you assume Converse.js users will also use another client that provides such an interface, yes.  I'm not sure how safe that assumption is.

**Comment by darix** [comment]
any status update about this issue?

**Comment by throwaway42** [comment]
#780

**Comment by dl8bh** [comment]
Thanks for providing a solution for this! Will test in the next days!

**Comment by jcbrand** [comment]
Thanks, but it was @throwaway42 who provided a pull request (which I merged and updated a bit).
