### ISSUE TITLE
Users Chat State is not reflected to other clients

### ISSUE THREAD

**Issue by gpadbidri** [jcbrand/converse.js#492]
Hi JC,

Assuming a JID "priyagmcs@conversejs.org" is logged on from the Converse Site and PSI Web Client (meaning 2 resources)...Now setting the users chat state from <b>Online to BUSY </b> via PSI Client will reflect the Chat State for that user on Converse Site. However, setting the users chat state via Converse Site will NOT reflect it to other Chat Clients like PSI, which should not be the case...Can you tell me how we can broadcast / send presence to those JID resources ?

Can you point me to where in the code do we need to make changes to invoke the sendPresence() call ? Thanks !

Best Regards,
Gauri Padbidri

**Comment by jcbrand** [comment]
Sorry Gauri, this sounds like this is an issue with PSI. I'm not aware of anything that can be done about it in converse.js.

**Comment by gpadbidri** [comment]
@jcbrand  Sure, Thanks ! I thought so. Just wanted to confirm the same.
