### ISSUE TITLE
Problem with onRosterPush function when receiving a push from server

### ISSUE THREAD

**Issue by teseo** [jcbrand/converse.js#493]
Hello,

I am experimenting that when receiving a roster push from the server the roster list is not updated. Debugging I found this piece of code in the RosterContacts collection within converse.js file:
```javascript
            onRosterPush: function (iq) {
                /* Handle roster updates from the XMPP server.
                 * See: https://xmpp.org/rfcs/rfc6121.html#roster-syntax-actions-push
                 *
                 * Parameters:
                 *    (XMLElement) IQ - The IQ stanza received from the XMPP server.
                 */
                var id = iq.getAttribute('id');
                var from = iq.getAttribute('from');
                if (from && from !== "" && from != converse.bare_jid) {
                    // Receiving client MUST ignore stanza unless it has no from or from = user's bare JID.
                    converse.connection.send(
                        $iq({type: 'error', id: id, from: converse.connection.jid})
                            .c('error', {'type': 'cancel'})
                            .c('service-unavailable', {'xmlns': Strophe.NS.ROSTER })
                    );
                    return true;
                }
                converse.connection.send($iq({type: 'result', id: id, from: converse.connection.jid}));
                $(iq).children('query').find('item').each(function (idx, item) {
                    this.updateContact(item);
                }.bind(this));
                return true;
            },
```
My stanza contains in the ```from``` attribute actually the value of ```converse.connection.jid``` ```(user@host/resource)``` which is what it is used when sending the error stanza as well as when sending the result stanza back to server in this very function. ```converse.bare_jid``` is actually not used within that function at all other than in that if statement. If I manually change ```converse.bare_jid``` for ```converse.connection.jid``` in the if statement the roster list gets updated perfectly for both removing and adding. 

Is ```converse.bare_jid``` supposed to be in that if ? if so, is there a clean way to make it work ?

Many Thanks!

**Comment by jcbrand** [comment]
Hi @teseo, thanks for the report and explanation. Please see the fix I pushed 2 minutes ago.

**Comment by teseo** [comment]
@jcbrand lekker, dankie!

**Comment by jcbrand** [comment]
:D

**Comment by teseo** [comment]
Hello Jc,

I just updated to the last version and I am afraid the fix you pushed is not working as expected. I take my blame as I trusted it without testing it. I'm sorry for that.

Your fix is actually always allowing to enter in the mentioned if.

This is the code that actually works for me and I think it should be the fix:

```javascript```
                if (from && from !== "" && from != converse.connection.jid) {
                    // Receiving client MUST ignore stanza unless it has no from or from = user's bare JID.
                    converse.connection.send(
                        $iq({type: 'error', id: id, from: converse.connection.jid})
                            .c('error', {'type': 'cancel'})
                            .c('service-unavailable', {'xmlns': Strophe.NS.ROSTER })
                    );
                    return true;
                }
```
Again sorry for assuming instead of proper testing. If you give me green light, I'll push a pull request with this fix.

Dankie!

**Comment by jcbrand** [comment]
Hi @teseo, don't worry about it. Please make a pull request with the new fix.

**Comment by theMok** [comment]
Hi! rosterPush is working as expected? Im using punjab, but on roster update push function goes on but not update..

**Comment by jcbrand** [comment]
Yes, I tested roster push before releasing 0.10.0
