### ISSUE TITLE
Ask user to add Converse.js as an application for XMPP links

### ISSUE THREAD

**Issue by GreenLunar** [jcbrand/converse.js#494]
Use this code
```
<script type="text/javascript">
	navigator.registerProtocolHandler("xmpp", "https://hostname/%s", "Converse.js");
</script>
```

**Comment by jcbrand** [comment]
That's a cool trick, but I don't what there is to do on the converse.js side.

**Comment by GreenLunar** [comment]
I have posted this issue, in case it would be relevant in future.

I think we can have this issue closed.

**Comment by jcbrand** [comment]
OK, thanks.
