### ISSUE TITLE
bug in ping interval?

### ISSUE THREAD

**Issue by teseo** [jcbrand/converse.js#496]
Hello JC,

I'm having some zombie sessions in my backend and I wanted to try out the ping interval feature of converse.js. 

Having a look at the code I can see this piece of code within the ```converse``` object in ```converse.js``` file:
```javascript```
this.registerPingHandler = function () {
            this.registerPongHandler();
            if (this.ping_interval > 0) {
                this.connection.addHandler(function () {
                    /* Handler on each stanza, saves the received date
                     * in order to ping only when needed.
                     */
                    this.lastStanzaDate = new Date();
                    return true;
                }.bind(converse));
                this.connection.addTimedHandler(1000, function () {
                    var now = new Date();
                    if (!this.lastStanzaDate) {
                        this.lastStanzaDate = now;
                    }
                    if ((now - this.lastStanzaDate)/1000 > this.ping_interval) {
                        return this.ping();
                    }
                    return true;
                });
            }
        };
```
Noticed that I actually never got inside of the if statement where ping the server. I believe the code is missing some binding of the ```converse``` object so ```this``` inside of the callback actually has the expected ```converse``` values like ```lastStanzaDate``` or the ```ping()``` function itself, like you do on ```addHandler``` just a few lines above.

Dakie!

**Comment by jcbrand** [comment]
Thanks @teseo, you're right. I've committed a fix, can you please check that it's working now for you?

**Comment by teseo** [comment]
Looks Perfect. Lekker @jcbrand dankie!
