### ISSUE TITLE
Unreceived message in chat rooms

### ISSUE THREAD

**Issue by BenJaziaSadok** [jcbrand/converse.js#499]
Hello, i set up an openfire server and converse js for client side and i get this problem.
I'm connecting user and guests in chatrooms.
The problem is sometimes, messages are not received by members.
In spite i have a message '77' received in converse debug, i don't see this message appearing in the chat interface.

1 _dataRecv called
converse.min.js:236 <-body xmlns="http://jabber.org/protocol/httpbind" ack="570051797"><-message xmlns="jabber:client" to="3ed88d8a@chat.server.com/3ed88d8a" from="66@conference.chat.server.com/loggued user" type="groupchat" id="24"><-body>77</-body><-x xmlns="jabber:x:event"><-composing/></-x></-message><-/body>
converse.min.js:236 1 no requests during idle cycle, sending blank request
converse.min.js:236 0 _throttledRequestHandler called with 1 requests
converse.min.js:236 0 request id 94.0 posting
converse.min.js:236 0 request id 94.0 state changed to 1

**Comment by jcbrand** [comment]
Should be fixed by making a new release which depends on Strophe.js 1.2.3.

For reference: https://github.com/strophe/strophejs/commit/a3964eda751c5ced5fb83c2549b6c3de6b7be741

**Comment by jcbrand** [comment]
New release made.

**Comment by BenJaziaSadok** [comment]
not solved with latest version

**Comment by jcbrand** [comment]
On https://conversejs.org? Make sure you've cleared the cache in your browser.
