### ISSUE TITLE
Chat room is not opening in Non AMD

### ISSUE THREAD

**Issue by rrjanbiah** [jcbrand/converse.js#502]
https://conversejs.org/non_amd.html

Clicking the room link doesn't open the room dialog window.

Any suggestion is welcome. Thanks

**Comment by jcbrand** [comment]
Works fine for me, just tested now with Chrome. Which browser are you using?

**Comment by rrjanbiah** [comment]
@jcbrand Chrome/Windows. Please find screenshot:

![conversejs-room-open-bug](https://cloud.githubusercontent.com/assets/4907427/10432165/1545fa6c-7127-11e5-905e-0cfbd8a70d45.png)

Failing with:

    Uncaught TypeError: Expecting a function in instanceof check, but got undefined

**Comment by jcbrand** [comment]
What version of converse.js are you using? Can you perhaps find that line of code at line 6351?

**Comment by rrjanbiah** [comment]
> What version of converse.js are you using? 

@jcbrand I'm talking exactly about the online demo version https://conversejs.org/non_amd.html It doesn't work in (demo) https://conversejs.org/non_amd.html too.

> Can you perhaps find that line of code at line 6351?

```javascript
if (options instanceof Strophe.RSM) {
```

https://github.com/jcbrand/converse.js/blob/master/converse.js#L6400

Thanks for any help.

**Comment by rrjanbiah** [comment]
@jcbrand Further to our analysis, the above error doesn't seems to block the room opening. But, it seems that the control doesn't come to show method:

*  https://github.com/jcbrand/converse.js/blob/master/converse.js#L1212 - Event bind for show
*  https://github.com/jcbrand/converse.js/blob/master/converse.js#L3764 - Trigger show event
*  https://github.com/jcbrand/converse.js/blob/master/converse.js#L2026 - Show method -- not coming to this function when we click on room

Do you know why this is happening? TIA
