### ISSUE TITLE
KeepAlive doesn't works

### ISSUE THREAD

**Issue by YoMismo4** [jcbrand/converse.js#504]
when i configure these code
<script>
    require(['converse'], function (converse) {
        (function () {
            /* XXX: This function initializes jquery.easing for the https://conversejs.org
            * website. This code is only useful in the context of the converse.js
            * website and converse.js itself is NOT dependent on it.
            */
            var $ = converse.env.jQuery;
            $.extend( $.easing, {
                easeInOutExpo: function (x, t, b, c, d) {
                    if (t==0) return b;
                    if (t==d) return b+c;
                    if ((t/=d/2) < 1) return c/2 * Math.pow(2, 10 * (t - 1)) + b;
                    return c/2 * (-Math.pow(2, -10 * --t) + 2) + b;
                },
            });
            $(window).scroll(function() {
                if ($(".navbar").offset().top > 50) {
                    $(".navbar-fixed-top").addClass("top-nav-collapse");
                } else {
                    $(".navbar-fixed-top").removeClass("top-nav-collapse");
                }
            });
            //jQuery for page scrolling feature - requires jQuery Easing plugin
            $('.page-scroll a').bind('click', function(event) {
                var $anchor = $(this);
                $('html, body').stop().animate({
                    scrollTop: $($anchor.attr('href')).offset().top
                }, 700, 'easeInOutExpo');
                event.preventDefault();
            });
        })();
        converse.initialize({
            bosh_service_url: 'https://conversejs.org/http-bind/', // Please use this connection manager only for testing purposes
            keepalive: true,
            message_carbons: true,
            play_sounds: true,
            roster_groups: true,
            show_controlbox_by_default: true,
            xhr_user_search: false
        });
    });
</script>
and i put my bosh url it doesnt keeps alive the session, and when i move to another tab is the same thing it disconnects from openfire and in converse it shows me the login view of converse.
The thing that i am doing is i want to  use converse.js for my web application. I am uising xampp, and openfire and i have like this http://localhost:8080/converse.js-0.9.6/. I have it like this configure, or maybe i am not doing something correct. I would like to know if there something that i can do for keeping the session alive for more time.
![converse](https://cloud.githubusercontent.com/assets/15218345/10616553/424e866e-772b-11e5-85b5-d695508819d0.png)

**Comment by YoMismo4** [comment]
It onlive wors fine in converse.js-0.8.6 the session stays alive

**Comment by jcbrand** [comment]
Sorry, the issue tracker is only for bug reports and feature requests. You can ask for help in the discuss@conference.conversejs.org XMPP chat room or in the converse.js mailing list.

Just a mention on tabs, you need to establish a new BOSH session for each tab.
