### ISSUE TITLE
"Is typing" doesn't automatically disappear

### ISSUE THREAD

**Issue by turalsprofile** [jcbrand/converse.js#508]
When someone types message the "is typing" appears on chat window. But when he stops typing "is typing" doesn't disappear. I'm using 0.9.6.

**Comment by gpgform** [comment]
alitafra@hotmail.it afra.binelli@hotmail.it alitapiaf@gmail.com


On 27 October 2015 11:01:47 CET, Tural Aliyev <notifications@github.com> wrote:
>When someone types message the "is typing" appears on chat window. But
>when he stops typing "is typing" doesn't disappear. I'm using 0.9.6. 
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/jcbrand/converse.js/issues/508

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
