### ISSUE TITLE
An option to minimize the converse window by default

### ISSUE THREAD

**Issue by ser** [jcbrand/converse.js#511]
I use auto-login and it would be cool if there is an option to minimize the converse window when the web page is opened for the first time by default. Yes, if the user manually closes it, it keeps minimized, but it is necessary to close it one time. My users would prefer to open chat only when it is needed for them.

**Comment by jcbrand** [comment]
There already is such an option: https://conversejs.org/docs/html/configuration.html#show-controlbox-by-default

**Comment by ser** [comment]
OK, I have this option "show_controlbox_by_default: false" and converse shows up expanded every time page is accessed the first time. 

All my options:
```
       bosh_service_url: '/jabber/',
        i18n: locales.pl,
        show_controlbox_by_default: false,
        roster_groups: false,
        allow_muc: false,
        allow_otr: false,
        cache_otr_key: true,
        keepalive: true,
        allow_logout: false,
        allow_registration: false,
        auto_list_rooms: true,
        auto_away: 299,
        auto_xa: 1800,
        domain_placeholder: 'xxx.com',
        message_archiving: 'roster',
        message_carbons: true,
        hide_muc_server: true,
        play_sounds: true,
        fullname: '{S_USERNAME}',
        authentication: 'prebind',
        prebind_url: '/xmpp/prebind',
        jid: 'xxxx@xxxxx',
```

**Comment by ser** [comment]
Ok, I read again the manual, and I can understand now.

Show means no show. OK.

**Comment by jcbrand** [comment]
If the control box was open upon previous page load, then it will be opened on the next page load, regardless of the value of `show_controlbox_by_default`.

To double check, make sure to clear the browser's `sessionStorage` and then try again.

**Comment by ser** [comment]
I have cleared sessionStorage, it shows up.

I have accessed the website from a freshly installed web browser, a newly created account, it shows up.

**Comment by jcbrand** [comment]
I just double checked. If I set `show_controlbox_by_default` to `false`, it doesn't appear by default, whether the user is logged in or not. I don't know what else to say about it.

**Comment by jcbrand** [comment]
Are you using `prebind`? This might be related: https://github.com/jcbrand/converse.js/issues/261

However, I never reproduced that bug, which is why it's still not fixed.

**Comment by jcbrand** [comment]
What you can do is add a `debugger;` line in the `showControlBox()` method. Then look at the call stack to see what calls it. That will probably show the bug relatively quickly.

**Comment by ser** [comment]
Yup, it's exactly that but, sorry I have missed it before, I do not know why, as I have checked all bugs before reporting a new one. I will try to debug it and post the results in the  #261. Thanks :)

**Comment by jcbrand** [comment]
No worries. Would be great if you found the bug. Could it be that you have requesting contacts in your roster? Looking at the code, in that case the controlbox would be opened.

**Comment by ser** [comment]
Unfortunately no, I've changed to ```message_archiving: 'never'``` and it still pops up. I will try debugging, though I am not a javascript expert.

**Comment by jcbrand** [comment]
If you expose the website to me I can take a look. You can send me the details privately: https://opkode.com/contact.hml

I won't be able to look tonight still, but probably tomorrow.

**Comment by ser** [comment]
Hi JC, as I said before, I have changed to ```message_archiving: 'never'```, and now the popup/popdown behaviour gets unpredictable, sometimes it is up, sometimes down, as my users report. On my account it is nearly always up after login, but it might be because it is the prosody server administrative account. 

I will try to consult users to find out how to eventually reproduce the bug. 

But I am sending you privately the login/password to my site, as maybe you will have time to spot the reason for #510 ?

**Comment by rszabo** [comment]
I can verify that this is still an issue and will report back if I solve it in an elegant way. 

Might be related to delay in response from prebind_url. Either way, new chat windows shouldn't popup and that should imho be a separate setting. 

I believe that finding all instances of where the main window is being shown will reveal the bug. In one of those cases the window shouldn't be shown if show_controlbox_by_default is disabled.

**Comment by jcbrand** [comment]
> Either way, new chat windows shouldn't popup and that should imho be a separate setting. 

Agreed, but that would be a new (feature-request) ticket.
