### ISSUE TITLE
“make css” fails: File to import not found or unreadable: bourbon.

### ISSUE THREAD

**Issue by CyrilBrulebois** [jcbrand/converse.js#513]
Hi,

Trying to get rid of the strange “200px wide by default” settings for chat boxes, and to work around the fact one cannot maximize them (skimming over the code, maximize seems to actually be un-minimize), I tried to run “make css” but it failed with some missing bourbon:

> kibi@arya:~/hack/converse.js.git$ make css
> mkdir -p .bundle
> gem install --user bundler --bindir .bundle/bin
> WARNING:  You don't have /home/kibi/hack/converse.js.git/.bundle/bin in your PATH,
> 	  gem executables will not run.
> Successfully installed bundler-1.10.6
> Parsing documentation for bundler-1.10.6
> Done installing documentation for bundler after 3 seconds
> 1 gem installed
> ./.bundle/bin/bundle install --path .bundle --binstubs .bundle/bin
> Fetching gem metadata from https://rubygems.org/.............
> Fetching version metadata from https://rubygems.org/...
> Fetching dependency metadata from https://rubygems.org/..
> Installing sass 3.4.14
> Using bundler 1.10.6
> Bundle complete! 1 Gemfile dependency, 2 gems now installed.
> Bundled gems are installed into ./.bundle.
> touch stamp-bundler
> ./.bundle/bin/sass -I ./components/bourbon/app/assets/stylesheets/ sass/converse.scss css/converse.css
> Error: File to import not found or unreadable: bourbon.
>        Load path: /home/kibi/hack/converse.js.git/components/bourbon/app/assets/stylesheets
>         on line 9 of sass/converse.scss
>   Use --trace for backtrace.
> Makefile:127: recipe for target 'converse.css' failed
> make: *** [converse.css] Error 65

Maybe some missing dependency in the “css” target, since I see bourbon being mentioned in some manifest (bower.json)?

**Comment by jcbrand** [comment]
You need the development dependencies. I've updated the `Makefile` accordingly. You can either do a `git pull` and try again or first run `make dev` before running `make css`.

**Comment by jcbrand** [comment]
Chat boxes can be resized by dragging them horizontally, vertically or diagonally. There's no button to maximize a chat box to viewport size. It's something I've been considering for a new feature.

**Comment by CyrilBrulebois** [comment]
Yep, looks better with 6946c96a93, thanks!

And yeah, I notice one can resize them; but the current UI doesn't look like reasonable enough for me to throw a customer at a ConverseJS instance right away.
