### ISSUE TITLE
[Prebind] Safari is losing connection (?) after page reload

### ISSUE THREAD

**Issue by Zerebokep** [jcbrand/converse.js#516]
I've setup converse using the single session guide. Everything works fine so far using the following code:

http://pastebin.com/xe4vrRFb

Logging, adding each other as buddy and chatting works perfectly until one of both chatters are issuing a page reload. After that, the person who hasn't reloaded isn't able to receive messages from the other one anymore until he changes his status (weird), but the reloading person is still able to receive messages, even if he's shown offline.

This is how it looks it looks like when accessing the prebind url:
{"jid":"username@url.com/resource","sid":"677a4daa-bdf8-41ca-99ef-167701bbf6e4","rid":2246159011}

sid and rid gets updated after each reload.
No errors are thrown in the js console.

Any idea what's wrong here?

p.s. I've also posted this in the mailing list, but it doesn't seem to show up there.

**Comment by jcbrand** [comment]
Not sure if it's a problem, but the RID that is returned is not a double quoted string.

`{"jid":"username@url.com/resource","sid":"677a4daa-bdf8-41ca-99ef-167701bbf6e4","rid":2246159011}`

**Comment by Zerebokep** [comment]
Nope, same behaviour with rid forced as string.

I've found out that this problem only occurs when chatting with an user which is using Safari. Firefox <-> Firefox works perfectly.
