### ISSUE TITLE
Integrate with PHPBB Forum

### ISSUE THREAD

**Issue by shibdib** [jcbrand/converse.js#518]
Having trouble getting this to work in a PHPBB forum. Put the required lines in the simple_header.php and the simple_footer.php files and cleared all caches but nothing seems to show up. When using the chrome view code feature the code I added doesn't even appear to be present.

Works everywhere else on my website fine just not on the forum.

**Comment by jcbrand** [comment]
Sounds more like an issue with PHPBB than converse.js. If you can show that there is an issue with converse.js I can try to fix it. Otherwise it's not applicable to this issue tracker.
