### ISSUE TITLE
make dev failed on Windwos

### ISSUE THREAD

**Issue by kgmyathtet** [jcbrand/converse.js#519]
Hi, 

I am trying to run "make -f Makefile.win dev" on Windows. Everything look find but I got the following error in the end. 

bundler install --path=.
process_begin: CreateProcess(NULL, bundler install --path=., ...) failed.
make (e=2): The system cannot find the file specified.
make: *** [dev] Error 2

Can I know the cause of the problem and how to fix it? 

Thanks

**Comment by jcbrand** [comment]
The `Makefile.win` file for Windows is out of date. Windows support was added by people from the community. I personally don't support Windows.

That said, looks like you don't have [Bundler](http://bundler.io) installed. The *nix `Makefile` installs it for you in the `stamp-bundler` step. I'm not sure how to fix it for Windows, but you can try to install bundler separately.
