### ISSUE TITLE
Set specific server/domain

### ISSUE THREAD

**Issue by lbischof** [jcbrand/converse.js#520]
How do I set a specific server? I would like to use Conversejs in our company and want to set a specific server so it just always adds the domain after the username. Is this possible?

**Comment by lbischof** [comment]
I edited converse.js Is there a better way? maybe a configuration option?

**Comment by jcbrand** [comment]
No there's no config option for this but it's something that we could add. How did you edit converse.js for this? Do you want the domain to be visible or just implicit?

**Comment by lbischof** [comment]
I simply added the domain: jid = $jid_input.val() + '@domain.com' inside the authenticate method. Implicit would be perfect. Since I don't want to lock people in, they should still able to use a custom domain. So it would basically be a default domain if you don't specify one...

**Comment by jcbrand** [comment]
Ok, it's in the queue ;)

**Comment by lbischof** [comment]
Cool, thanks.

**Comment by nodiscc** [comment]
I just ran into the same issue. Thanks for reporting it and thanks again jc for improving conversejs

**Comment by jcbrand** [comment]
I could make two options, `locked_domain` and `'default_domain`, each taking the string value of the domain i.e. `example.org`.

If `locked_domain` is used, then JIDs from other domains cannot be used. If `default_domain` is used, then it's just a default but other domains can  be used.

Thoughts?

**Comment by nodiscc** [comment]
> Thoughts?

Sounds great.

**Comment by lbischof** [comment]
That sounds perfect, thanks

**Comment by jcbrand** [comment]
Done. I'd appreciate it if you guys could try it out and let me know whether it works as expected. Thanks.

**Comment by nodiscc** [comment]
Hi, logging in without a domain name does not work for me. I am running the current `master`, XMPP server is hosted on the same subdomain/machine as the web server running conversejs.

I have tried setting `locked_domain: 'my.own.subdomain',`, `default_domain: 'my.own.subdomain'`, and a combination of both.

Logging in with `user@my.own.subdomain` still works, logging in with only `user` never connects and keeps displaying `Attempting to reconnect in 5 seconds`.

There are no errors in the browser console, webserver logs, and XMPP server logs. Any idea on how to investigate is welcome.

**Comment by jcbrand** [comment]
@nodiscc That's strange. Are you 100% sure you had the newest code loaded in your browser? Perhaps the old code was still cached?

**Comment by nodiscc** [comment]
Indeed strange. I cleared all caches with the same result. I examined the BOSH server response for the XHR requests:

    <body xmlns:stream='http://etherx.jabber.org/streams' type='terminate' condition='host-unknown' xmlns='http://jabber.org/protocol/httpbind'/>

I think something is not passed correctly to the server. The BOSH server is `prosody 0.9.7-2+debu8u2`. This is my conversejs config:

```javascript
  <script>
  require(['converse'], function (converse) {
      converse.initialize({
          roster_groups: true,
          authentication: 'login',
          allow_chat_pending_contacts: false,
          allow_contact_removal: true,
          allow_contact_requests: true,
          allow_dragresize: true,
          allow_muc: true,
          allow_otr: true,
          allow_registration: true,
          animate: true,
          archived_messages_page_size: 20,
          auto_list_rooms: false,
          auto_login: false,
          auto_away: 0,
          auto_xa: 0,
          auto_reconnect: true,
          auto_subscribe: false,
          bosh_service_url: 'https://my.own.subdomain/bosh',
          cache_otr_key: false,
          csi_waiting_time: 0,
          debug: false,
          domain_placeholder: 'my.own.subdomain',
          keepalive: true,
          message_archiving: 'never',
          message_carbons: true,
          forward_messages: false,
          hide_muc_server: true,
          hide_offline_users: false,
          locked_domain: 'my.own.subdomain',
          play_sounds: false,
          providers_link: 'https://xmpp.net/directory.php',
          show_controlbox_by_default: true,
          show_only_online_users: false,
          storage: 'local',
          use_otr_by_default: false,
          use_vcards: true,
          visible_toolbar_buttons: {
              call: false,
              clear: true,
              emoticons: true,
              toggle_occupants: true
          }

      });
  });
  </script>
```

**Comment by jcbrand** [comment]
If you can figure out what the actual domain is that's sent to the XMPP server then it would probably show exactly what's going on here.

You'll see the JID with the domain in one of the first stanza sent out to the XMPP server during the session creation request. See for example here: http://xmpp.org/extensions/xep-0206.html#initiate

You'll have to set `debug` to `true` to see the stanzas in your browser console.

**Comment by nodiscc** [comment]
Thanks for pointing me to the debug option. The debug log when entering the username alone:

    Status changed to: CONNECTING converse.min.js:237:805246
    0 _throttledRequestHandler called with 1 requests converse.min.js:237:805246
    0 request id 11.0 posting converse.min.js:237:805246
    0 request id 11.0 state changed to 1 converse.min.js:237:805246
    <body rid="3535613660" xmlns="http://jabber.org/protocol/httpbind" to="mytestuser" xml:lang="en" wait="60" hold="1" content="text/xml; charset=utf-8" ver="1.6" xmpp:version="1.0" xmlns:xmpp="urn:xmpp:xbosh"> converse.min.js:237:805246
    POST 
    XHR 
    https://my.own.subdomain/bosh [HTTP/1.1 200 OK 530 ms]
    0 request id 11.1 state changed to 2 converse.min.js:237:805246
    0 request id 11.1 state changed to 3 converse.min.js:237:805246
    0 request id 11.1 state changed to 4 converse.min.js:237:805246
    0 removing request converse.min.js:237:805246
    0 _throttledRequestHandler called with 0 requests converse.min.js:237:805246
    0 request id 11 should now be removed converse.min.js:237:805246
    0 request id 11.1 got 200 converse.min.js:237:805246
    1 _connect_cb was called converse.min.js:237:805246
    <body xmlns:stream="http://etherx.jabber.org/streams" type="terminate" condition="host-unknown" xmlns="http://jabber.org/protocol/httpbind"> converse.min.js:237:805246
    ERROR: BOSH-Connection failed: host-unknown converse.min.js:237:805227
    Status changed to: CONNFAIL converse.min.js:237:805246
    1 _doDisconnect was called converse.min.js:237:805246
    Status changed to: DISCONNECTED converse.min.js:237:805246
    Attempting to reconnect in 5 seconds

When using full JID mytestuser@my.ownsubdomain:


    Status changed to: CONNECTING converse.min.js:237:805246
    0 _throttledRequestHandler called with 1 requests converse.min.js:237:805246
    0 request id 1.0 posting converse.min.js:237:805246
    0 request id 1.0 state changed to 1 converse.min.js:237:805246
    <body rid="610583366" xmlns="http://jabber.org/protocol/httpbind" to="my.own.subdomain" xml:lang="en" wait="60" hold="1" content="text/xml; charset=utf-8" ver="1.6" xmpp:version="1.0" xmlns:xmpp="urn:xmpp:xbosh"> converse.min.js:237:805246
    POST 
    XHR 
    https://my.own.subdomain/bosh [HTTP/1.1 200 OK 25 ms]
    0 request id 1.1 state changed to 2 converse.min.js:237:805246
    0 request id 1.1 state changed to 3 converse.min.js:237:805246
    0 request id 1.1 state changed to 4 converse.min.js:237:805246
    0 removing request converse.min.js:237:805246
    0 _throttledRequestHandler called with 0 requests converse.min.js:237:805246
    0 request id 1 should now be removed converse.min.js:237:805246
    0 request id 1.1 got 200 converse.min.js:237:805246
    1 _connect_cb was called converse.min.js:237:805246
    <body xmlns:stream="http://etherx.jabber.org/streams" xmpp:version="1.0" xmlns:xmpp="urn:xmpp:xbosh" ver="1.6" inactivity="60" requests="2" polling="5" secure="true" hold="1" from="my.own.subdomain"> converse.min.js:237:805246
    0 _throttledRequestHandler called with 0 requests converse.min.js:237:805246
    [...]
    Status changed to: CONNECTED converse.min.js:237:805246
    [...]

In the first case, it sends `to="mytestuser"`, where as in the second (working) it sends `to="my.own.subdomain"`

Firefox/Iceweasel 44.0b6

**Comment by jcbrand** [comment]
@nodiscc I think you simply have the old code, you're not yet using the new code. You didn't run `make build` to create a new `converse.min.js` file, did you?

Don't worry about it, I'm pretty sure this feature is working fine and I'll make a new release soon, then you can use the `converse.min.js` file that comes with it.

**Comment by nodiscc** [comment]
I followed [these setup instructions](https://conversejs.org/docs/html/quickstart.html) (with a few tweaks). No problem, I will have a try when the new release comes out. Thanks again for your help!

**Comment by nodiscc** [comment]
Works prefectly after upgrading to latest master.

**Comment by nandinibhaduri** [comment]
Can "Add Contact" be locked to a domain?

**Comment by jcbrand** [comment]
@nandinibhaduri It should probably be restricted when `locked_domain` is set to true. Please create a new ticket for that.
