### ISSUE TITLE
Typeahead versions conflict

### ISSUE THREAD

**Issue by cmorgia** [jcbrand/converse.js#523]
I'm trying to use Converse.js on a page where I need to use a specific version of Typeahead (0.11.1) where Converse.js seems to require 0.10.5.

When debugging in Safari, this is what I get:
<img width="1125" alt="error" src="https://cloud.githubusercontent.com/assets/214524/11484234/38f9b1f4-97ad-11e5-9c59-8f159eede0d3.png">

Any idea?

Thanks much!
Claudio

**Comment by jcbrand** [comment]
Just update the bower.json file to pin typeahead to 0.11.1, then run `make clean && make dev` the make sure you have that version downloaded. Then you can make a new converse.js bundle with `make build`.

Then you have the newest version of typeahead in converse.js. I suspect that everything will still work fine. If you don't encounter any issues, then please let me know and I'll update the version of typehead for converse.js.
