### ISSUE TITLE
Close controlbox on mobile

### ISSUE THREAD

**Issue by camaran** [jcbrand/converse.js#527]
Please set mobile height to 50% or minus beacuse now all screen is for converseJS and is not possible to close it

see the attached screenshot of iphone6s plus
![img_0677](https://cloud.githubusercontent.com/assets/1564974/11534012/f0971dd2-990c-11e5-84c6-af75d28751f2.PNG)

**Comment by jcbrand** [comment]
Should be fixed now with mobile build.
