### ISSUE TITLE
cannot minimize controlbox on mobile

### ISSUE THREAD

**Issue by christopherlynnsmith** [jcbrand/converse.js#529]
Team,

I add the following code to minimize the controlbox.  On mobile it stays open consistently and dominates the mobile users screen.

 con.chats.get('controlbox').close();

It does not work.  I am using xmpp prebind.

I have seen other issues related to this and I did not see a conclusive fix for this.

**Comment by nitmir** [comment]
this may be related to #527

**Comment by jcbrand** [comment]
Yes, I'll close this ticket in favor of #527
