### ISSUE TITLE
Support entering new lines in messages using Shift+Enter or similar

### ISSUE THREAD

**Issue by Nepoxx** [jcbrand/converse.js#530]
Most messaging applications allow you to insert a new line within your message without sending the message (usually shift+enter). It would be nice if Converse.js supported that.

**Comment by jcbrand** [comment]
I think in order to do this, converse.js needs to support HTML messages which is a whole can of worms because we then need a sanitizer for HTML.

I started work on that some months ago and then left it again because it appeared to be a lot of work which adds a lot more code (i.e. bloat).

The branch for that work is still here: https://github.com/jcbrand/converse.js/tree/xhtml_im

**Comment by Nepoxx** [comment]
Wouldn't using `\n` work?

**Comment by jcbrand** [comment]
@Nepoxx actually yeah, that would work fine I guess :-P

**Comment by wendymungovan** [comment]
Did you try this out?  We are sending messages with \n in them but they are not being displayed when they are received in the client chat room window. I'm  wondering if this is on my side or not.

Thank you

**Comment by jcbrand** [comment]
No I didn't try it out. Depends on the client I guess. Desktop clients like Pidgin would probably render `\n` as line breaks. However in HTML `\n` is ignored and markup should be used to create line breaks.

**Comment by wendymungovan** [comment]
Thanks, for the fast response.  We are injecting messages from another source and visualizing them in converse.js.  It does not look like converse.js is rendering \n in the message received window.  You probably already assume this but I also tried injecting message with <br/> but that did not work either. It rendered "<br/>" as text.

**Comment by jcbrand** [comment]
Yes. This is explained by my sentence above:

> I think in order to do this, converse.js needs to support HTML messages which is a whole can of worms because we then need a sanitizer for HTML.

Converse.js currently doesn't support HTML-enabled messages, which is why `<br/>` renders as text. To support HTML we would need to sanitize all input to avoid JS-injection and XSS attacks.

**Comment by jcbrand** [comment]
I probably have added to the confusion by saying `\n` should work. I was being stupid. `\n` would only work on Desktop apps, not in a webbrowser (HTML), since HTML rendering ignores them.

**Comment by wendymungovan** [comment]
ok thanks!

**Comment by jcbrand** [comment]
Duplicate of #667
