### ISSUE TITLE
Messages not shown when Chatroom JID contains mixed case

### ISSUE THREAD

**Issue by MRYingLEE** [jcbrand/converse.js#535]
When I tried Converse on Converjs.org with the MUC of "Demo@conference.bizchat.us", all sent messages are not shown, but they are sent successfully. Maybe messages are received successfully also, but I am not sure for I didn't trace into source code.

At the same time, other XMPP clients (Jappix.com, Mini.Jappix.com and Jitisi on PC) worked smoothly with this MUC.

The MUC of "Demo@conference.bizchat.us" was created before Converse accessed. If I create a new MUC in Converse, everything works normally.

So I guess maybe the problem comes from this MUC. But other XMPP clients work.

BTW, I am using Chrome 47 on Windows 8.1 and the XMPP server is Prosody. If you want, I may give you admin password.

Please check.

**Comment by MRYingLEE** [comment]
I highly think this is a bug.

In another test, I use 
converse.rooms.open() to open a chat room. In the chat room, no any occupants are listed. If I send a message, another chat box will be shown, which has the same JID and works normally. BTW, I set forward_messages to true.

Attached please find the screenshot.
![exception](https://cloud.githubusercontent.com/assets/11193534/12065866/b72809fc-b019-11e5-8973-96cf2632f230.JPG)

I am using Chrome 47 on Windows 10.

Please check.

Ying

**Comment by MRYingLEE** [comment]
After days struggle, I traced into the source code and confirmed this is a bug. The bug is in the function of converse.rooms.get(), which compares an JID with upper case characters (such as "PrivateChatxxx") with its lowercased name (such as "privatechatxxx") . 

The lowercased JID was stored at the first time when the JID was used. Later when I call converse.rooms.open(), converse didn't realize the room had been created due to the bug.

The bug in converse.rooms.get() is easy to be fixed. But in case similar bugs, I try not using uppercase characters in JID. Now JIDs with lowercase characters only work smoothly.

Ying

**Comment by jcbrand** [comment]
Where exactly in the code is this bug? Could you please make a pull request with a fix? Or at least just point me to the location.

**Comment by MRYingLEE** [comment]
Sorry. Let me clarify.
In the function to open a chatbox (line:6608 in converse.js, if I didn't happen to change something)
                    var chatroom = converse.chatboxes.get(jid);
which should be
                    var chatroom = converse.chatboxes.get(jid.toLowerCase());

It is because you store jid in lowercase internally. Actually when comparing in backbone.js
    get: function(obj) {
      if (obj == null) return void 0;
      return this._byId[obj] || this._byId[obj.id] || this._byId[obj.cid];
    },
 
you compare jids directly without case conversion.

I guess you may need to check other places just in case similar problems.

Thank you for your hard working.

Ying

**Comment by jcbrand** [comment]
Related: #431 #234

**Comment by jcbrand** [comment]
Thanks, should be fixed now.
