### ISSUE TITLE
required initialize function for plugins in 0.10

### ISSUE THREAD

**Issue by pmkaboo** [jcbrand/converse.js#540]
converse plugins require `initialize` function in order to work, at least in 0.10, dont know if they worked without it before. the function doesnt need to do anything, it just has to be there, otherwise javascript will crash on error `bind is not a function` located here https://github.com/jcbrand/converse.js/blob/master/converse.js#L6336. the plugin example in documentation should be updated to include this information.

example of working plugin:
```javascript
converse.plugins.add('myplugin', {
    initialize: function () {}, // wont work without this
    overrides: {
        enableCarbons: function () {
            this._super.enableCarbons();
        }
    }
});
```

**Comment by jcbrand** [comment]
Thanks, I think a better alternative might be to fix the code to not crash if there isn't an `initialize` method.
