### ISSUE TITLE
No jQuery build

### ISSUE THREAD

**Issue by camaran** [jcbrand/converse.js#542]
It's possible to have a no jQuery build?

**Comment by jcbrand** [comment]
Yes, when you run `make build` a number of different builds are generated, including one without jquery.

**Comment by camaran** [comment]
it's possible to have in github?

**Comment by jcbrand** [comment]
I originally had those builds in Github, but they are large so the bloat the repository. Also, because they're minified, their diffs are just as large as the files themselves and they make the repo even bigger.
