### ISSUE TITLE
Basic CSS?

### ISSUE THREAD

**Issue by tablampa** [jcbrand/converse.js#543]
Would it be possible to have a release with only the barest of bare-bones CSS? I mean, with the control pane, and chatrooms in plain divs down the page, and no interactive UI?

I'd like to restyle converse.js to make the chatrooms the centerpiece of the page - maybe tile the chatrooms in 2x2 to fill the page, or tab them with jQueryUI with the control pane as a menu along the top - but looking at the source .css files gave me the vapours and I had to have a little lie down.

Pretty please? In return, I shall rename my firstborn 'Conversedotjs'!

I'll sure she'll be fine with it.

**Comment by jcbrand** [comment]
Take a look at the Sass files in the `./sass` directory. That's the real source, not the .css files.

Your offer to rename your firstborn is compelling, but I have to respectfully decline.

The current UI/UX is embedded quite deeply into the code and its assumptions. So, to change the UI/UX is really not an easy task. It would require more than just changing the CSS.
