### ISSUE TITLE
Chat appear fa-spinner icon when active box

### ISSUE THREAD

**Issue by mustafaevcil** [jcbrand/converse.js#549]
User login system and converse js gets rosters successfully. If user clicks roster for chat, chat box opens and spinner shown permanent. I look debug mode console and see invalid response received message. I share screen chat and user clicking on roster logs. I use latest converse js 0.10.0 and latest strophe.js and openfire 4.0.0 release.

![fa-spinner](https://cloud.githubusercontent.com/assets/6851252/12319343/6d9b26fc-baaa-11e5-8643-edbdb9037dd1.png)
![consolespinner](https://cloud.githubusercontent.com/assets/6851252/12319347/714bc72a-baaa-11e5-9c85-3fd269399a8e.png)

**Comment by jcbrand** [comment]
This is an error related to MAM (message archive management) which you apparently have enabled.

The errors appears the be thrown here: https://github.com/strophe/strophejs/blob/77bbb38d345e059fd1d4c1b8f9a63e5cd74576e0/strophe.js#L4170

Looks like the response is not valid XML? Which XMPP server are you using?

**Comment by mustafaevcil** [comment]
I'm using openfire latest version , I removed monitoring service plugin for message archive feature and problem is fixed. Thanks.
