### ISSUE TITLE
[Q] Example libraries/implementations for the "call" button?

### ISSUE THREAD

**Issue by nodiscc** [jcbrand/converse.js#551]
https://github.com/jcbrand/converse.js/blob/master/docs/source/configuration.rst#visible-toolbar-buttons

>    // ... Third-party library code ...

Are there any examples of how to use conversejs along with a VoIP service to make use of the call button?

**Comment by jcbrand** [comment]
Nope, there aren't any examples. That would depend on the VoIP service.
