### ISSUE TITLE
Not showing contact's request

### ISSUE THREAD

**Issue by nikksbagul** [jcbrand/converse.js#556]
Hi all,
I have setup consersejs ver 0.10 together with openfire 3.9.3.
Currently, user can login to chat server. However, when a user try to add a contact, the target user didn't receive any request message to accept or decline. The sending site alway show "Pending Contacts"
Could you please tell me what are the additional steps to fix this issue?
Thank!

**Comment by jcbrand** [comment]
This functionality is well tested and should work.

Make sure that you didn't misspell the JID of the user you added. Set `debug: true` when calling `converse.initialize` and check that the appropriate stanza is actually received on the receiving end (by looking at the log output in the dev console of your browser).

Also, make sure whether you can reliably reproduce the issue and if can explain how to reproduce it.

If you've done those things, you can reopen this ticket and provide all the information you've gathered.

Good luck.

**Comment by nikksbagul** [comment]
This is working fine on consersejs ver 0.9.6 with openfire 3.9.3.
I am doing this for converse.initialize
     converse.initialize({
         show_controlbox_by_default: true,
         bosh_service_url: '{{ CONVERSEJS_BOSH_SERVICE_URL }}',
         show_only_online_users: true,
         allow_contact_requests: true,
         auto_list_rooms: false,
         auto_subscribe: false,
         hide_muc_server: {{ CONVERSEJS_HIDE_MUC_SERVER }},
         debug: true,
         prebind: true,
         jid: '{{ jid }}',
         sid: '{{ sid }}',
         rid: '{{ rid }}',
         prebind_url: {
     	    "jid": '{{ jid }}',
     	    "sid": '{{ sid }}',
     	    "rid": '{{ rid }}'
     	},
     });

Getting this error on sender side,
<error code="404" type="cancel"><remote-server-not-found xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"/></error>

Please help me how to resolved this issue.

**Comment by jcbrand** [comment]
That error appears to indicate that you gave the wrong domain for the JID you tried to add.

**Comment by Dharmik8478** [comment]
I am facing same issue in consersejs ver 0.10.
I debugged it and i found that issues is when i am going to search contact it returns data like 'null@jid' instead of 'jid@domain'.
