### ISSUE TITLE
Session offline problem with prebind on multiple browser tab 

### ISSUE THREAD

**Issue by mustafaevcil** [jcbrand/converse.js#557]
I'm using latest converse.js (source codes in repository) ,strophe.js. and openfire 4.0.0 server. My app uses prebind in single session. When the user opens 5 browser tabs, user have different session resource and correctly working, but the system is not working for more than 5 browser tabs(exp. 7-8). The session doesn't initialize as online , the user contacts are not getting and empty chat box is appeared. Also the online sessions is closed by openfire and disconnected chat box. I think closed sessions may be idle session. When I look console for debug info, http-bind response invalid session id because session is closed. I share openfire's session table.

![prebindproblems](https://cloud.githubusercontent.com/assets/6851252/12505565/b875a8ea-c0f0-11e5-9668-439403411b18.png)

After almost one minute sessions closed automatically.

![closed](https://cloud.githubusercontent.com/assets/6851252/12505637/6b662de4-c0f1-11e5-9cd9-7689014c9e29.png)

Another example with 11 tab and 30-45 seconds after all sessions are closed by openfire

![offlinesessions](https://cloud.githubusercontent.com/assets/6851252/12505992/42f1e6fc-c0f4-11e5-8496-03336b00ec04.png)

**Comment by jcbrand** [comment]
Could it be that OpenFire only accepts 5 concurrent sessions?

Perhaps it's also a browser issue, whereby the browser stops firing XMLHttpRequests in older tabs if more than `x` newer tabs are opened. However, I couldn't find any info that this is the case when googling for it.

Looking at the active sessions info you pasted, it looks like the sessions that go offline are random, i.e. it's not the oldest sessions that go offline first, right?

**Comment by mustafaevcil** [comment]
The sessions go offline are random as you said.

**Comment by jcbrand** [comment]
Doesn't look like there's anything to be done here for converse.js, so I'm closing this issue.
