### ISSUE TITLE
Performance issue with server side Shared Roster

### ISSUE THREAD

**Issue by irek-zaripov** [jcbrand/converse.js#560]
With 1000 or more contacts in roster we over-watch that the method fetch() in the string https://github.com/jcbrand/converse.js/blob/master/converse.js#L2603
converse.rosterview.render().**fetch()**.update();
is executed a long time(more than 15 seconds) and this is inadmissible for production systems.
Further investigation shows the dependency of this issue from the https://github.com/jashkenas/backbone project. 
It seems to be related to the issue https://github.com/jashkenas/backbone/issues/3242 `Poor "add" performance on sorted collections`.
@jcbrand what do you think, what options are exist for performance optimization on fetch() method for converse.rosterview?

**Comment by irek-zaripov** [comment]
@jcbrand What do you think about using "Nested Roster Groups" http://www.xmpp.org/extensions/xep-0083.html?
It would be very nice feature and may be will a workaround for large roster contacts.

**Comment by jcbrand** [comment]
>  what do you think, what options are exist for performance optimization on fetch() method for converse.rosterview?

Looking at the ticket, I think what is happening is that roster items are fetched one by one from sessionStorage and then sorting happens every time after such a fetch.

So a good optimization would be to fetch the roster items in a batch. If this is the case, then the change would most likely have to be made in Backbone.sessionStorage.

> What do you think about using "Nested Roster Groups"

This was already requested in #265. This feature is not planned for the near future, but I'm available for contracting for any new features to converse.js.

**Comment by jcbrand** [comment]
> Looking at the ticket, I think what is happening is that roster items are fetched one by one from sessionStorage and then sorting happens every time after such a fetch.

This isn't the case anymore. Closing.
