### ISSUE TITLE
Issues on IOS9

### ISSUE THREAD

**Issue by felipefda** [jcbrand/converse.js#562]
Hello there,

Someone is testing conversejs using safari on IOS9 (Ipad and Iphone)?
I was trying to run but contacts is not showing and in ejabberd user is not connected.

Someone have similar issues?

**Comment by m0cs** [comment]
I tested on an ipad, but conversejs not rendering and the problem was this two lines:
https://github.com/jcbrand/converse.js/pull/558/files#r50553489

**Comment by felipefda** [comment]
I try this two lines and nothing change.

In my case, conversejs load in screen but on Ipad not show any contact.
