### ISSUE TITLE
Converse doesn't accepts accents in plain message?

### ISSUE THREAD

**Issue by YoMismo4** [jcbrand/converse.js#563]
When I type a message with an accent or "ñ" the other user doesn't received the accent and the "ñ". Is there any config that I can do for accepting Latin letter and accents?

**Comment by jcbrand** [comment]
Works fine for me. I suspect that it might be an issue with your XMPP server and how it is configured, and not converse.js.

**Comment by YoMismo4** [comment]
ok I'm using OpenFire, i thought that it was from converse.js chat.
