### ISSUE TITLE
Cannot get controlbox with converse.chats.get() method

### ISSUE THREAD

**Issue by mustafaevcil** [jcbrand/converse.js#565]
I have latest converse.js with prebind. I try to get chat objects with converse.chats.get() method with 'controlbox', but converse.chatboxviews.get(chatbox.get('jid')); method return undefined. This method is working with user JID for open chat box. I want to get control box.

![getchats](https://cloud.githubusercontent.com/assets/6851252/12783933/eb5f9360-ca8c-11e5-955c-c4360f08d432.png)

**Comment by jcbrand** [comment]
Appears to be fixed in latest release.
