### ISSUE TITLE
How can I disable focusing latest opening chat box 

### ISSUE THREAD

**Issue by mustafaevcil** [jcbrand/converse.js#566]
My problem is that converse focus on latest opening chat box (when user gets new message). If the user get new message from other roster when is typing with rosters, chat box opens and focus. Therefore the user send wrong messages instead of active typing roster. I think default behaviour may be for new chat box open the left and send notification for this case or chat box minimized automatically.

**Comment by jcbrand** [comment]
Fixed in master.
