### ISSUE TITLE
Offline Message Problem with Pending Contact

### ISSUE THREAD

**Issue by manumklm** [jcbrand/converse.js#568]
Hi I having  offline message getting problem with the Pending contacts.Means the message is not getting  when the user who is in my roaster is as pending contact (I send subscription request to him) .I can get his offline message on my very first login, but my reply he is not getting when he login to his account

**Comment by rszabo** [comment]
This is related to the server software. I know that Prosody shows this behavior during extensive XMPP development. Maybe it's part of the XMPP protocol to prevent message flooding for non-friends, but don't quote me on this.

**Comment by manumklm** [comment]
Sir,

      Is any method available for block a user to prevent message me. I am
looking forward to your kind reply.

Thanks

Manuprasad

**Comment by jcbrand** [comment]
Converses.js doesn't send messages to users who are not yet in your roster. Pending contacts are not yet in the roster.
