### ISSUE TITLE
Feature request: Visibility of -all- windows.

### ISSUE THREAD

**Issue by rszabo** [jcbrand/converse.js#569]
Hello!

`show_controlbox_by_default` is today the only setting for whether or not the Contactlist and associated windows should be visible on launch. It does not control the behaviour of incoming messages.

I suggest the implementation of the following:
- `gui_show_new_chats` : `boolean`.   This would prevent new chat windows from revealing messages.
- `gui_show_minimized_chats_button`: `boolean`. Minimized windows does not always require a toggle button for their collective visibility. (IMHO: Unnecessary button)

Sidenote: `show_controlbox_by_default` is as of writing not working properly with some prebind setups,   so setting this to either boolean value is not a solution, quite irrelevant and outside the scope of this feature request.

Thank you

**Comment by jcbrand** [comment]
>  gui_show_new_chats : boolean. This would prevent new chat windows from revealing messages.

That would require some other way of informing the user that a message was received.

> gui_show_minimized_chats_button: boolean. Minimized windows does not always require a toggle button for their collective visibility.

I'm not sure what button you're referring to. There's a toggle button for the controlbox, which is necessary otherwise you can't open it at all.

**Comment by rszabo** [comment]
Yes, but `gui_show_new_chats` would still show the chat, but in a minimized state.  It's receiving a new message in your face that's the problem. :) One should still be able to actually restore a view, just that incoming requests to chat etc are altered.

The toggle-button `#conversejs #minimized-chats #toggle-minimized-chats` imho very unnecessary. We've hidden it using `#conversejs #minimized-chats #toggle-minimized-chats { display: none }`. This way we still get all the minimized chats but without a button which hides/shows the minimized entries.

**Comment by jcbrand** [comment]
> The toggle-button #conversejs #minimized-chats #toggle-minimized-chats imho very unnecessary. We've hidden it using #conversejs #minimized-chats #toggle-minimized-chats { display: none }. This way we still get all the minimized chats but without a button which hides/shows the minimized entries. 

What if you have so many minimized chats stack upon one another that they obscure something in the page you want to look at?

**Comment by rszabo** [comment]
It is true that stacking is a good option, however it should also be up for customisation. Sure, we did it using CSS and that might be enough. In our case we'll show the minimised windows in rows at the bottom of the page.
