### ISSUE TITLE
Session Storage bug prevents successful relogin (login disconnected)

### ISSUE THREAD

**Issue by rszabo** [jcbrand/converse.js#570]
Hello!

I'm using prebind to connect CJS to an existing platform, and both play very well together. There is however a rather annoying bug which prevents relogin in the same tab. My findings show that logging out of the platform (and sending BOSH logout obv.) and then logging on again, will fail for CJS.  

![screen shot 2016-02-06 at 05 41 39](https://cloud.githubusercontent.com/assets/253990/12864744/2cd5f3d8-cc96-11e5-9af9-d99fcb1511aa.png)

![screen shot 2016-02-06 at 05 41 56](https://cloud.githubusercontent.com/assets/253990/12864742/25f475f8-cc96-11e5-9f0f-84554687e03f.png)

CJS believes that it is offline due to previously stored values in the Session storage.

It is therefore my suggestion that any storage mechanism of CJS be exposed publicly, to allow methods such as (but not limited to):

* Clear Message History (priv/muc)
* Clear Connection Details
* Clear All Cache

**Comment by jcbrand** [comment]
> My findings show that logging out of the platform (and sending BOSH logout obv.) and then logging on again, will fail for CJS. 

What exactly happens when you log out of the platform? Does the page reload?

It's not clear to me the sequence of events here, especially what happens in converse.js when you log out of your app. If it's a single-page app, then it's not obvious to me that converse.js will also log out when you log out of your app, unless you explicitly tell it to somehow.

It appears to me that the problem is that stale BOSH tokens stay in sessionStorage after logout and that this prevents reconnection, but I'm not exactly sure how this might be happening and need more info on what exactly is going on.

**Comment by rszabo** [comment]
On logout, the page is not reloaded but navigated from /index to /logout. At the moment we do not disconnect XMPP properly, so CJS has no idea about the logout.

However, at our /login a new BOSH connection is setup and I have verified that "re-login" works, but after /login comes /index which gives us the "Disconnected." message. 

Doing the same thing but removing all sessionStorage-data or changing tab, will not result in the above. 

Either way, but off-topic, I'd love to have more control on what CJS stores and what it does not (separate ticket in the same project).

Thank you

**Comment by jcbrand** [comment]
Sounds like the solution then is to log out the user in converse.js as well.

There is an API for it: https://conversejs.org/docs/html/development.html#logout

**Comment by rszabo** [comment]
Sure, that's implemented now and unfortunately the sessionStorage is only cleared once until it is repopulated again. 

Clicking logout in the platform does:
* js: converse.user.logout()
* js: other stuff
* js: go to /logout (no gui)

However, even if the platform didn't logout properly using converse.user.logout(), CJS should be able to ignore cached data if the BOSH session is valid.
