### ISSUE TITLE
Help humbly asked on callbacks and extending CJS

### ISSUE THREAD

**Issue by rszabo** [jcbrand/converse.js#571]
Hello.

I've been working with CJS for the last couple of days and find it to be the best JS XMPP-client out there. There are some minor things I would like to change, and I'd happily push these changes back. 

Does anybody have an idea how to do any of the following:

* Intercept click on online/offline contacts: to start chatting per default is not an option when OTR is always on and the recipient is offline.
* **Never store** message history
* Clearing Session storage at will. Due to a previously reported bug, control of Session storage is essential, clearing one or all values. I.e. connection status, message history etc. 

Thank you kindly for all help

PS: I have been through https://conversejs.org/docs/html/development.html#writing-a-converse-js-plugin and some related pages.

**Comment by jcbrand** [comment]
You mention multiple things here. Please make a separate ticket for each. It's no fun trying to manage different things in one ticket and it gets more difficult to close such a ticket because often people pile on with more unrelated things.

**Comment by rszabo** [comment]
Making separate entries.
