### ISSUE TITLE
Changing archiving preferences automatically

### ISSUE THREAD

**Issue by kruks23** [jcbrand/converse.js#572]
Hello,

When I log with my account in conversejs.org, the archiving preferences on my account changes automatically to disable mam.

In ejabberd.dat I can see this configuration:

{<<"xxx">>,<<"xxx">>},never,[],[]}

This way mam is disabled in this account and messages are not stored until I change it manually.

**Comment by jcbrand** [comment]
The default settings is to never archive:
https://conversejs.org/docs/html/configuration.html#message-archiving

**Comment by weiss** [comment]
Wouldn't it be better to not fiddle with the user's archiving preferences if that option isn't specified?

**Comment by jcbrand** [comment]
@weiss Yes, there already is an open ticket for that: #486

**Comment by weiss** [comment]
Ah, thanks :-)
