### ISSUE TITLE
Build error in the release 10.1: `javascript' unknown

### ISSUE THREAD

**Issue by irek-zaripov** [jcbrand/converse.js#573]
xgettext --keyword=__ --keyword=___ --from-code=UTF-8 --output=locale/converse.pot converse.js --package-name=Converse.js --copyright-holder="Jan-Carel Brand" --package-version=0.10.1 -c --language="javascript";
xgettext: language `javascript' unknown
make[1]: *** [pot] Error 1

**Comment by jcbrand** [comment]
Works fine for me with gettext version 0.19.5.1

**Comment by irek-zaripov** [comment]
But for Centos 6 & 7 the default version of gettext is 0.18 :-(

**Comment by jcbrand** [comment]
I added a fallback.

**Comment by irek-zaripov** [comment]
Thanks! :)
