### ISSUE TITLE
Logging out from converse.js doesn't clear the connection status from the sessionStorage

### ISSUE THREAD

**Issue by irek-zaripov** [jcbrand/converse.js#575]
Key= `GsrE7Lf40t0YhTtB00rzlIkzgB4=`  Value =  `controlbox`
Key = `GsrE7Lf40t0YhTtB00rzlIkzgB4=-controlbox` Value = `{"id":"controlbox","box_id":"controlbox","height":450,"width":200,"num_unread":0,"time_opened":0,"default_height":450,"default_width":200,"min_width":200,"min_height":225,"connected":true}`
I guess that the commit https://github.com/jcbrand/converse.js/commit/26b45be9e0a98e61b5ef8215e18c7ff1cb7b278e  is not enough for clearing the sessionStorage.

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/30640831-logging-out-from-converse-js-doesn-t-clear-the-connection-status-from-the-sessionstorage?utm_campaign=plugin&utm_content=tracker%2F194169&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F194169&utm_medium=issues&utm_source=github).
</bountysource-plugin>

**Comment by jcbrand** [comment]
Thanks, I'll have a look.

**Comment by rszabo** [comment]
I can verify that `converse.user.logout()` and `converse.account.logout()` manages to clear the sessionStorage but is later repopulated when the converse object is destroyed. Checked in last two versions of CJS.

**Comment by jcbrand** [comment]
> but is later repopulated when the converse object is destroyed.

I'm not sure that that means.

**Comment by rszabo** [comment]
I didn't debug using break-points but can clearly see that when I call either `logout()` the sessionStorage is indeed cleared, but as soon as I navigate away from the page (/index to /logout to /login) will repopulate sessionStorage.

Because /logout doesn't have a gui and /login has no access to `converse`, the issue remains at the same page: /index.

**Comment by jcbrand** [comment]
I guess this is Backbone that repopulates the sessionStorage.

**Comment by rszabo** [comment]
Great findings! 
Which Backbone release do you use? I'd love to dive into the documentation and see when I can solve this issue.

**Comment by jcbrand** [comment]
@rszabo Check in bower.json
