### ISSUE TITLE
0.10.1 - contactStatusChanged broken?

### ISSUE THREAD

**Issue by rszabo** [jcbrand/converse.js#578]
Hello.

Is `contactStatusChanged` and `contactStatusMessageChanged` on version 0.10.1?

![screen shot 2016-02-08 at 20 32 05](https://cloud.githubusercontent.com/assets/253990/12897003/4c0c7630-cea5-11e5-9726-5335f2ba083d.png)

After `converse.initialize({ debug: true...` I setup a listener:
```converse.listen.on('contactStatusChanged', function(event, buddy, status) { console.log("*** X ***"); });```

Updating status is received by all clients but the event is never triggered.

I hard-coded a `console.log` into `onStatusChanged: function(` then I rebuilt conversejs with
`make dev` 
`make build`
...but no change.

**Comment by jcbrand** [comment]
Nothing there has changed AFAIK.

**Comment by rszabo** [comment]
OK. Any idea what could hinder a `.emit()`? 

I get updates on `statusChanged` and `statusMessageChanged` but not `contactStatusChanged` or `contactStatusMessageChanged`.

**Comment by jcbrand** [comment]
No. Best approach is to put a breakpoint in the relevant area in the code and step through it with the debugger to see exactly what happens.

**Comment by rszabo** [comment]
This is why I want more insight into CJS so that I can debug on a lower level. :)

```<body xmlns:stream="http://etherx.jabber.org/streams" xmlns="http://jabber.org/protocol/httpbind" sid="2d73e649-db4b-4e57-b700-6452ed1fbd1b"><presence xmlns="jabber:client" to="richard@specimen.me" from="rks@specimen.me/www"><status>happ</status></presence></body>```

I can clearly see that all XMPP messages are delivered and returned, but only a few of them will actually be handled using `converse.listen.on`.

**Comment by jcbrand** [comment]
The "chat status" in `onChatStatusChanged` is not the same `status` as you have in your stanza above. It's one of `online`, `offline`, `busy`, `away` etc.

`onChatStatusChanged` will only be called if the chat status changes. So if a user is `busy` and another presence is received with type `busy`, then that event won't emit.

As far as I'm aware, there isn't an event for when the user's custom status message changes, which appears to be what you want.

**Comment by rszabo** [comment]
That's awkward as your documentation states otherwise. :)

https://conversejs.org/docs/html/development.html#event-types
![screen shot 2016-02-09 at 08 29 31](https://cloud.githubusercontent.com/assets/253990/12910050/44647e20-cf07-11e5-810f-be45703e44fe.png)

Also, my way of testing XMPP is always:

* Tail XMPP server log
* Two fresh web browsers with two different users (richard@chrome and rks@firefox)
* Enable Debug in XMPP client
* Enable Developer Tools

When I test stati/statuses, I always go from one state to another, so never busy -> busy etc.

The following listeners are setup after `converse.initialize({ debug: true...` and only a few of them will work (I'll create a separate entry for one of these):

```
  converse.listen.on('contactStatusChanged', function(event, buddy, status) {
    Specimen.log(event, buddy);
    Specimen.Gui.notify("(TEST) Ally changed status, see debug");
    Specimen.log("-- Converse statusChanged --", status);
  });

  converse.listen.on('contactStatusMessageChanged', function(event, buddy, messageText) {
    Specimen.log(event, buddy);
    Specimen.log("-- Converse statusMessageChanged --", buddy);
    Specimen.Gui.notify(buddy.fullname + " shouts " + buddy.status);
  });

  converse.listen.on('statusChanged', function(event, text) {
    Specimen.Gui.notify("Status changed to " + text);
  });

  converse.listen.on('statusMessageChanged', function(event, text) {
    Specimen.Gui.notify("Status changed to " + text);
  });

  converse.listen.on('reconnect', function (event) {
    Specimen.log("-- Converse reconnected --");
    Specimen.Gui.notify("Reconnected chat.");
  });

  converse.listen.on('initialized', function (event) {
    Specimen.log("-- Converse initialised --");
  });

  converse.listen.on('ready', function(event) {
    Specimen.log("-- Converse ready --");
  });

  converse.listen.on('rosterPush', function(event, items) {
    Specimen.log("-- Converse rosterPush --", event, items);
  });

  converse.listen.on('noResumeableSession', function(event) {
    Specimen.Gui.notify("SESSION ERROR: Lost connection to chat.", "error");
  });
```

**Comment by jcbrand** [comment]
> That's awkward as your documentation states otherwise. :)

I don't see how it refutes anything I said previously, it's consistent with what I said. I simply had the wrong name, it's `onContactStatusChanged` and not `onChatStatusChanged`.

"chat status" is not the same thing as the `<status>` element in a stanza. The `<status>` element in the stanza is the "status message", which will trigger `onContactStatusMessageChanged` (which I couldn't remember whether such an event exists or not, but evidently it does).

In any case, all that stuff around presence status, custom status messages etc. is *really* confusing, also in the XMPP spec :(

**Comment by rszabo** [comment]
Sure, but I think this is related to something underlying as I clearly follow the documentation and I haven't modified the source code. Perhaps `emit()` (inaccessible outside converse) is not functioning properly? 

AFAIK the following file is used during `make build`: `libs/3rd/conversejs/converse.js-0.10.1/converse.js``
Correct?

That means that I could test how `listen.on` behaves and push back whatever I find, correct?

I agree, the specifications are indeed a handful to grasp, and I wasn't trying to see who was right or not, I only want CJS to work as good as it can.

**Comment by jcbrand** [comment]
> Sure, but I think this is related to something underlying as I clearly follow the documentation and I haven't modified the source code. Perhaps emit() (inaccessible outside converse) is not functioning properly?

Lots of people listen for emitted events in their own code. If it wasn't working I'd expect to hear much more about it.

> AFAIK the following file is used during make build: libs/3rd/conversejs/converse.js-0.10.1/converse.js
Correct? (or in this releases view: converse.js-0.10.1/converse.js)

When you run `make build`, the built files are in `./builds`, that first path of yours is totally foreign and the 2nd one appears to point to a non-build file.

> That means that I could test how listen.on behaves and push back whatever I find, correct?

I don't really understand what you're asking here.
