### ISSUE TITLE
Help: Intercept click on any contact in the roster

### ISSUE THREAD

**Issue by rszabo** [jcbrand/converse.js#579]
Hello there

I'd like to have more control on the visual roster because in our platform we wish to show a menu of sorts when clicking a user. 

Is there a neat way using plugins to achieve this? 

Thank you

**Comment by jcbrand** [comment]
You can override any component by using "overrides" in a plugin.

The documentation on writing a plugin is here: https://conversejs.org/docs/html/development.html#writing-a-converse-js-plugin

The component you want to override is probably the `RosterContactView` which is a Backbone View that renders for each contact in the roster. The example in the docs overrides `XMPPStatus` which is a Backbone Model.

Take a look at `openChat` in `RosterContactView`, I think you'll probably want to override that.
https://github.com/jcbrand/converse.js/blob/master/converse.js#L4327

**Comment by rszabo** [comment]
Thank you very much! I'll dive into this. :)

**Comment by rszabo** [comment]
Hm. Didn't work that well.. Here's what I tried after `converse.initialize({ debug: true`: 
```
  var plugin_name = "contact_click";

  (function (root, factory) {
    if (typeof define === 'function' && define.amd) {
      define(plugin_name, ["jquery", "strophe", "utils", "converse"], factory);
    }
  }(this, function ($, strophe, utils, converse_api) {
    // Wrap your UI strings with the __ function for translation support.
    var __ = $.proxy(utils.__, this);

    // Strophe methods for building stanzas
    var Strophe = strophe.Strophe;
    $iq         = strophe.$iq;
    $msg        = strophe.$msg;
    $build      = strophe.$build;

    console.log("*** HELLO THERE ***");

    // The following line registers your plugin.
    converse_api.plugins.add(plugin_name, {
      myFunction: function () {
        var converse = this.converse;
      },
      overrides: {
        onConnected: function () {
          var converse = this._super.converse;
          console.log("*** onConnected ***");
          this._super.onConnected();
        },
        RosterContactView: {
          openChat: function(ev) {
            console.log("*** openChat ***");
            this._super.openChat(ev);
          }

```

I don't get an `console.log` to exec. Also, `alert` didn't work either.

Thank you

**Comment by jcbrand** [comment]
Make sure it's loaded before `converse.initialize` is called.

**Comment by rszabo** [comment]
Unfortunately that didn't work either...
The complete function (~100 rows during debug) with listeners, plugin and initialize: http://pastebin.com/0TwXgtRK

**Comment by jcbrand** [comment]
That URL you pasted is now empty/expired. The problem appears to be that your script doesn't get loaded, perhaps because you're not using require.js? If you're not using require.js, then the script needs to be changed slightly. Take a look at this UMD example: https://github.com/umdjs/umd/blob/master/templates/amdWeb.js

**Comment by rszabo** [comment]
Ah, http://pastebin.com/vXbHJfaS 
The function loadconverse() is ran because I see the logs, and require.js is loaded before conversejs. :/
Thank you for your help

**Comment by jcbrand** [comment]
Ok, so you are using require.js? How familiar are you with it? You need to `require` this module, otherwise it won't get loaded, and by loaded, I mean the factory function, in which you have this code: ``console.log("*** HELLO THERE ***");``

**Comment by rszabo** [comment]
I am not familiar with require.js more than what I read on the converse.js website about dependencies. Then I assumed that I could use require.js by simply loading it before converse.js.

This is the head of require.js: http://pastebin.com/LdYTUXng (I figured that info is sufficient?)

Thank you

**Comment by jcbrand** [comment]
I'm not going to go into the particulars of require.js. You'll have to read its documentation and familiarize yourself with it. I think it'll be worth your time since many projects use it.

To not rely on require.js, you can change the script to look like the UMD example I linked to and then load the script manually in your HTML (after converse.js). Then it should be called.

I'll also update the example in the docs to use the UMD declaration.

**Comment by jcbrand** [comment]
Ok, I've updated the plugin example a bit. See here: https://conversejs.org/docs/html/development.html#writing-a-converse-js-plugin

Make sure to do a hard refresh to bypass your browser's cache.

I think the example as it stands now should be usable when loaded via a `<script>` tag.

Good luck

**Comment by rszabo** [comment]
Hello.

Are you saying that the only way to extend ConverseJS is to use RequireJS? The latter is a very unwelcomed addition to this project, primarily because it uses a module-to-filename lookup. Old news but, TCP overhead is not welcome. 

I counted the amount of instances using RequireJS in the platform and got a total of 15 files. This means that RequireJS wish to load all of these. No, that's bad.

**Comment by jcbrand** [comment]
You're not forced to use require.js in your own project, but if you want to create custom builds of converse.js (to then include in your project) then that is done with require.js's optimizer `r.js`. And since we use require.js internally in converse.js it makes sense to understand how it works if you want to extend/contribute.

**Comment by rszabo** [comment]
That's true, and I intend to learn more RequireJS once I get to contributing to your project. 
Thanks, I'll first have to see why I can't seem to initialize conversejs properly with whatever RequireJS-settings I have at this time. :)
