### ISSUE TITLE
0.10.0+ roster updates not handled

### ISSUE THREAD

**Issue by rszabo** [jcbrand/converse.js#580]
Hello

In our platform we require a users roster for other social functions, so we intend to listen for the initial roster update after login. The following listeners are setup, but aren't triggered:

```
  converse.listen.on('roster', function(event, items) {
    Specimen.log("-- Converse roster --", event, items);
  });

  converse.listen.on('rosterPush', function(event, items) {
    Specimen.log("-- Converse rosterPush --", event, items);
  });

```

Any idea what might be the problem?

**Comment by jcbrand** [comment]
Considering previous issues with the script not being loaded at all (#579), I suspect something similar is happening here. I'll therefore close this ticket unless you can provide more proof that this is not the case.
