### ISSUE TITLE
MUC server is not saved between page loads

### ISSUE THREAD

**Issue by rlanvin** [jcbrand/converse.js#581]
To reproduce:

- Open a page with Converse.js and check the "Rooms" tab. The MUC server is populated from what the XMPP server sends.
- Refresh the page (or go to another page), and check the "Rooms" tab. The MUC server is gone, and the field is empty.

A collateral bug is that the option `auto_list_rooms` only works when the user just signs in, but doesn't work after a page refresh.

**Comment by rlanvin** [comment]
After a couple of hours investigating this bug, it turns out that this was caused by my custom build. Bower had installed Backbone 1.2 (due to a mistake on my part), instead of Backbone 1.1.2 version (required in the project).

So I'm closing this, but I guess you should be careful when upgrading to Backbone 1.2 (if ever). From what I understood, the bug was that the Model was no properly created (?) and was some kind of array of models.

**Comment by jcbrand** [comment]
Yes, I'm aware that converse.js is not compatible with newer Backbone versions. I'm not yet sure what the cause is.
