### ISSUE TITLE
Duplicate contacts - case sensivity

### ISSUE THREAD

**Issue by Zerebokep** [jcbrand/converse.js#585]
It's possible to add the same contact multiple times by writing the JID different.

e.g. Test@test.com and test@test.com.

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/30734802-duplicate-contacts-case-sensivity?utm_campaign=plugin&utm_content=tracker%2F194169&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F194169&utm_medium=issues&utm_source=github).

<bountysource-plugin>

**Comment by saganshul** [comment]
@jcbrand You can close this issue now. :)
