### ISSUE TITLE
Not able to add contact in converjsejs

### ISSUE THREAD

**Issue by ashwinthakre91** [jcbrand/converse.js#588]
I am able to login in conversejs in all browsers
I am able to add contact in conversejs in firefox but not in other browsers.
Not able to see add contact dialog after clicking on add a contact button in browsers except firefox.
What can be the reason?

**Comment by ajinkyac** [comment]
Add a debug: true to your converse.initialize and paste your log here. One guess is the converse object throws error on firefox sometimes but better you post the logs.

**Comment by ashwinthakre91** [comment]
converse.initialize({
            bosh_service_url: 'http://localhost:5280/http-bind/', // Please use this connection manager only for testing purposes
            keepalive: true,
            message_carbons: true,
            play_sounds: true,
            roster_groups: true,
            show_controlbox_by_default: true,
        });

**Comment by ajinkyac** [comment]
Ashwin, this is the initialize code. You'll find the debug log on your console while adding the user. Please check the documentation for debugging and logs.

**Comment by ashwinthakre91** [comment]
ARIA: Attribute " aria-label ", required for accessibility, is missing on node: <button class=​"md-icon-button md-button md-ink-ripple hide-gt-sm" type=​"button" ng-transclude ng-click=​"toggleSidenav('left')​" hide-gt-sm>​…​</button>​
ARIA: Attribute " aria-label ", required for accessibility, is missing on node: <button class=​"md-icon-button md-button md-ink-ripple" type=​"button" ng-transclude ng-click=​"showSearchBarDiv = false">​…​</button>​
Markup '<md-button flex></md-button>' may not work as expected in IE Browsers. Consult 'https://github.com/philipwalton/flexbugs#9-some-html-elements-cant-be-flex-containers' for details.
Could not restore sessions. Error message: _restore: no restoreable session.
Failed to load resource: the server responded with a status of 404 (Not Found)
Failed to load resource: the server responded with a status of 404 (Not Found)
Status changed to: CONNECTING
0 _throttledRequestHandler called with 1 requests
0 request id 1.0 posting
0 request id 1.0 state changed to 1
<body rid=​"2913796491" xmlns=​"http:​/​/​jabber.org/​protocol/​httpbind" to=​"ashwin" xml:lang=​"en" wait=​"60" hold=​"1" content=​"text/​xml;​ charset=utf-8" ver=​"1.6" xmpp:version=​"1.0" xmlns:xmpp=​"urn:​xmpp:​xbosh">​</body>​
0 request id 1.1 state changed to 2
0 request id 1.1 state changed to 3
0 request id 1.1 state changed to 4
0 removing request
0 _throttledRequestHandler called with 0 requests
0 request id 1 should now be removed
0 request id 1.1 got 200
1 _connect_cb was called
<body xmlns=​"http:​/​/​jabber.org/​protocol/​httpbind" xmlns:xmpp=​"urn:​xmpp:​xbosh" xmlns:stream=​"http:​/​/​etherx.jabber.org/​streams" sid=​"551f1f18f6e8ac04c8ef32ae9b3c69d804f0b2bc" wait=​"60" requests=​"2" inactivity=​"30" maxpause=​"120" polling=​"2" ver=​"1.8" from=​"ashwin" secure=​"true" authid=​"15450717180062707997" xmpp:version=​"1.0">​<stream:features xmlns:stream=​"http:​/​/​etherx.jabber.org/​streams">​…​</stream:features>​</body>​
0 _throttledRequestHandler called with 0 requests
0 _throttledRequestHandler called with 1 requests
0 request id 2.0 posting
0 request id 2.0 state changed to 1
<body rid=​"2913796492" xmlns=​"http:​/​/​jabber.org/​protocol/​httpbind" sid=​"551f1f18f6e8ac04c8ef32ae9b3c69d804f0b2bc">​…​</body>​
0 request id 2.1 state changed to 2
0 request id 2.1 state changed to 3
0 request id 2.1 state changed to 4
0 removing request
0 _throttledRequestHandler called with 0 requests
0 request id 2 should now be removed
0 request id 2.1 got 200
1 _dataRecv called
<body xmlns=​"http:​/​/​jabber.org/​protocol/​httpbind">​<challenge xmlns=​"urn:​ietf:​params:​xml:​ns:​xmpp-sasl">​…​</challenge>​</body>​
0 _throttledRequestHandler called with 0 requests
0 _throttledRequestHandler called with 1 requests
0 request id 3.0 posting
0 request id 3.0 state changed to 1
<body rid=​"2913796493" xmlns=​"http:​/​/​jabber.org/​protocol/​httpbind" sid=​"551f1f18f6e8ac04c8ef32ae9b3c69d804f0b2bc">​…​</body>​
0 request id 3.1 state changed to 2
0 request id 3.1 state changed to 3
0 request id 3.1 state changed to 4
0 removing request
0 _throttledRequestHandler called with 0 requests
0 request id 3 should now be removed
0 request id 3.1 got 200
1 _dataRecv called
<body xmlns=​"http:​/​/​jabber.org/​protocol/​httpbind">​<success xmlns=​"urn:​ietf:​params:​xml:​ns:​xmpp-sasl">​dj1NbG5GSzVUOWFadTZ4YkFoUm9sMUpPbnhjNTQ9​</success>​</body>​
1 SASL authentication succeeded.
0 _throttledRequestHandler called with 0 requests
0 _throttledRequestHandler called with 1 requests
0 request id 4.0 posting
0 request id 4.0 state changed to 1
<body rid=​"2913796494" xmlns=​"http:​/​/​jabber.org/​protocol/​httpbind" sid=​"551f1f18f6e8ac04c8ef32ae9b3c69d804f0b2bc" to=​"ashwin" xml:lang=​"en" xmpp:restart=​"true" xmlns:xmpp=​"urn:​xmpp:​xbosh">​</body>​
0 request id 4.1 state changed to 2
0 request id 4.1 state changed to 3
0 request id 4.1 state changed to 4
0 removing request
0 _throttledRequestHandler called with 0 requests
0 request id 4 should now be removed
0 request id 4.1 got 200
1 _dataRecv called
<body xmlns=​"http:​/​/​jabber.org/​protocol/​httpbind" xmlns:xmpp=​"urn:​xmpp:​xbosh" xmlns:stream=​"http:​/​/​etherx.jabber.org/​streams" sid=​"551f1f18f6e8ac04c8ef32ae9b3c69d804f0b2bc" wait=​"60" requests=​"2" inactivity=​"30" maxpause=​"120" polling=​"2" ver=​"1.8" from=​"ashwin" secure=​"true" authid=​"8343320251530718921" xmpp:version=​"1.0">​<stream:features xmlns:stream=​"http:​/​/​etherx.jabber.org/​streams">​…​</stream:features>​</body>​
0 _throttledRequestHandler called with 0 requests
0 _throttledRequestHandler called with 1 requests
0 request id 5.0 posting
0 request id 5.0 state changed to 1
<body rid=​"2913796495" xmlns=​"http:​/​/​jabber.org/​protocol/​httpbind" sid=​"551f1f18f6e8ac04c8ef32ae9b3c69d804f0b2bc">​…​</body>​
0 request id 5.1 state changed to 2
0 request id 5.1 state changed to 3
0 request id 5.1 state changed to 4
0 removing request
0 _throttledRequestHandler called with 0 requests
0 request id 5 should now be removed
0 request id 5.1 got 200
1 _dataRecv called
<body xmlns=​"http:​/​/​jabber.org/​protocol/​httpbind">​<iq xmlns=​"jabber:​client" id=​"_bind_auth_2" type=​"result">​…​</iq>​</body>​
0 _throttledRequestHandler called with 0 requests
0 _throttledRequestHandler called with 1 requests
0 request id 6.0 posting
0 request id 6.0 state changed to 1
<body rid=​"2913796496" xmlns=​"http:​/​/​jabber.org/​protocol/​httpbind" sid=​"551f1f18f6e8ac04c8ef32ae9b3c69d804f0b2bc">​…​</body>​
0 request id 6.1 state changed to 2
0 request id 6.1 state changed to 3
0 request id 6.1 state changed to 4
0 removing request
0 _throttledRequestHandler called with 0 requests
0 request id 6 should now be removed
0 request id 6.1 got 200
1 _dataRecv called
<body xmlns=​"http:​/​/​jabber.org/​protocol/​httpbind">​<iq xmlns=​"jabber:​client" type=​"result" id=​"_session_auth_2">​</iq>​</body>​
Status changed to: CONNECTED
Connected
0 _throttledRequestHandler called with 0 requests
0 _throttledRequestHandler called with 1 requests
0 request id 7.0 posting
0 request id 7.0 state changed to 1
<body rid=​"2913796497" xmlns=​"http:​/​/​jabber.org/​protocol/​httpbind" sid=​"551f1f18f6e8ac04c8ef32ae9b3c69d804f0b2bc">​…​</body>​
0 request id 7.1 state changed to 2
0 request id 7.1 state changed to 3
0 request id 7.1 state changed to 4
0 removing request
0 _throttledRequestHandler called with 0 requests
0 request id 7 should now be removed
0 request id 7.1 got 200
1 _dataRecv called
<body xmlns=​"http:​/​/​jabber.org/​protocol/​httpbind">​<iq xmlns=​"jabber:​client" from=​"ashwin" to=​"admin@ashwin/​converse.js-27040382" id=​"d887bfec-20c7-4dc8-8e04-cfc0c7ae0197:​sendIQ" type=​"result">​…​</iq>​<iq xmlns=​"jabber:​client" from=​"ashwin" to=​"admin@ashwin/​converse.js-27040382" id=​"45df575e-16e1-4073-b2cd-15460767664c:​sendIQ" type=​"result">​…​</iq>​<iq xmlns=​"jabber:​client" from=​"admin@ashwin" to=​"admin@ashwin/​converse.js-27040382" id=​"enablecarbons" type=​"result">​</iq>​<iq xmlns=​"jabber:​client" from=​"admin@ashwin" to=​"admin@ashwin/​converse.js-27040382" id=​"3124297f-0e3d-4e3c-a220-bdae55f4a5c4:​roster" type=​"result">​…​</iq>​</body>​
0 _throttledRequestHandler called with 0 requests
Message carbons have been enabled.
0 _throttledRequestHandler called with 0 requests
0 _throttledRequestHandler called with 1 requests
0 request id 8.0 posting
0 request id 8.0 state changed to 1
<body rid=​"2913796498" xmlns=​"http:​/​/​jabber.org/​protocol/​httpbind" sid=​"551f1f18f6e8ac04c8ef32ae9b3c69d804f0b2bc">​…​</body>​
0 request id 8.1 state changed to 2
0 request id 8.1 state changed to 3
0 request id 8.1 state changed to 4
0 removing request
0 _throttledRequestHandler called with 0 requests
0 request id 8 should now be removed
0 request id 8.1 got 200
1 _dataRecv called
<body xmlns=​"http:​/​/​jabber.org/​protocol/​httpbind">​<iq xmlns=​"jabber:​client" from=​"conference.ashwin" to=​"admin@ashwin/​converse.js-27040382" id=​"0818ca58-9719-449a-be62-5be5d853c2f8:​sendIQ" type=​"result">​…​</iq>​<iq xmlns=​"jabber:​client" from=​"pubsub.ashwin" to=​"admin@ashwin/​converse.js-27040382" id=​"585c2b1e-7b0a-49fe-a03c-ac49e51105ee:​sendIQ" type=​"result">​…​</iq>​<iq xmlns=​"jabber:​client" from=​"ashwin" to=​"admin@ashwin/​converse.js-27040382" id=​"83d794b4-d4aa-47d5-8e8d-e83a3c401a46:​sendIQ" type=​"result">​…​</iq>​<iq xmlns=​"jabber:​client" from=​"ashwin" to=​"admin@ashwin/​converse.js-27040382" id=​"fa6d7fe2-4f30-478e-9ac3-68bc56be83bc:​sendIQ" type=​"result">​…​</iq>​<iq xmlns=​"jabber:​client" from=​"ashwin" to=​"admin@ashwin/​converse.js-27040382" id=​"12513ba7-9c89-4132-b0ff-c203349afff5:​sendIQ" type=​"result">​…​</iq>​<iq xmlns=​"jabber:​client" from=​"ashwin" to=​"admin@ashwin/​converse.js-27040382" id=​"5deb7bb4-afd3-41e2-ab10-aaa23950efa6:​sendIQ" type=​"result">​…​</iq>​<iq xmlns=​"jabber:​client" from=​"ashwin" to=​"admin@ashwin/​converse.js-27040382" id=​"ddf74755-7ac7-4e2d-967c-01596ff396a4:​sendIQ" type=​"result">​…​</iq>​<iq xmlns=​"jabber:​client" from=​"ashwin" to=​"admin@ashwin/​converse.js-27040382" id=​"6136752e-c846-47ab-9d65-11cbf03e24e2:​sendIQ" type=​"result">​…​</iq>​<iq xmlns=​"jabber:​client" from=​"ashwin" to=​"admin@ashwin/​converse.js-27040382" id=​"051bf010-bf6f-4414-9e67-03b1b35a3c96:​sendIQ" type=​"result">​…​</iq>​<iq xmlns=​"jabber:​client" from=​"ashwin" to=​"admin@ashwin/​converse.js-27040382" id=​"e035c38a-d381-40de-8791-6fd97e32de28:​sendIQ" type=​"result">​…​</iq>​<presence xmlns=​"jabber:​client" from=​"admin@ashwin/​converse.js-54284235" to=​"admin@ashwin/​converse.js-27040382">​…​</presence>​<presence xmlns=​"jabber:​client" from=​"admin@ashwin/​converse.js-27040382" to=​"admin@ashwin/​converse.js-27040382">​</presence>​</body>​
1 no requests during idle cycle, sending blank request
0 _throttledRequestHandler called with 1 requests
0 request id 9.0 posting
0 request id 9.0 state changed to 1
<body rid=​"2913796499" xmlns=​"http:​/​/​jabber.org/​protocol/​httpbind" sid=​"551f1f18f6e8ac04c8ef32ae9b3c69d804f0b2bc">​</body>​
0 request id 9.1 state changed to 2
0 request id 9.1 state changed to 3
0 request id 9.1 state changed to 4
0 removing request
0 _throttledRequestHandler called with 0 requests
0 request id 9 should now be removed
0 request id 9.1 got 200
1 _dataRecv called
<body xmlns=​"http:​/​/​jabber.org/​protocol/​httpbind">​<iq xmlns=​"jabber:​client" from=​"raje" to=​"admin@ashwin/​converse.js-27040382" type=​"error" id=​"ae49afb8-1a0e-4fe3-98ab-99a8e1e8d8fc:​sendIQ">​…​</iq>​</body>​
1 no requests during idle cycle, sending blank request
0 _throttledRequestHandler called with 1 requests
0 request id 10.0 posting
0 request id 10.0 state changed to 1
<body rid=​"2913796500" xmlns=​"http:​/​/​jabber.org/​protocol/​httpbind" sid=​"551f1f18f6e8ac04c8ef32ae9b3c69d804f0b2bc">​</body>​
0 request id 10.1 state changed to 2
0 request id 10.1 state changed to 3
0 request id 10.1 state changed to 4
0 removing request
0 _throttledRequestHandler called with 0 requests
0 request id 10 should now be removed
0 request id 10.1 got 200
1 _dataRecv called
<body xmlns=​"http:​/​/​jabber.org/​protocol/​httpbind">​<iq xmlns=​"jabber:​client" from=​"ds" to=​"admin@ashwin/​converse.js-27040382" type=​"error" id=​"d05dfc6c-4668-42d3-84a6-ffaeb82aece7:​sendIQ">​…​</iq>​</body>​
1 no requests during idle cycle, sending blank request
0 _throttledRequestHandler called with 1 requests
0 request id 11.0 posting
0 request id 11.0 state changed to 1
<body rid=​"2913796501" xmlns=​"http:​/​/​jabber.org/​protocol/​httpbind" sid=​"551f1f18f6e8ac04c8ef32ae9b3c69d804f0b2bc">​</body>​
0 request id 11.1 state changed to 2
0 request id 11.1 state changed to 3
0 request id 11.1 state changed to 4
0 removing request
0 _throttledRequestHandler called with 0 requests
0 request id 11 should now be removed
0 request id 11.1 got 200
1 _dataRecv called
<body xmlns=​"http:​/​/​jabber.org/​protocol/​httpbind">​</body>​
1 no requests during idle cycle, sending blank request
0 _throttledRequestHandler called with 1 requests
0 request id 12.0 posting
0 request id 12.0 state changed to 1
<body rid=​"2913796502" xmlns=​"http:​/​/​jabber.org/​protocol/​httpbind" sid=​"551f1f18f6e8ac04c8ef32ae9b3c69d804f0b2bc">​</body>​
0 request id 12.1 state changed to 2
0 request id 12.1 state changed to 3
0 request id 12.1 state changed to 4
0 removing request
0 _throttledRequestHandler called with 0 requests
0 request id 12 should now be removed
0 request id 12.1 got 200
1 _dataRecv called
<body xmlns=​"http:​/​/​jabber.org/​protocol/​httpbind">​</body>​
1 no requests during idle cycle, sending blank request
0 _throttledRequestHandler called with 1 requests
0 request id 13.0 posting
0 request id 13.0 state changed to 1
<body rid=​"2913796503" xmlns=​"http:​/​/​jabber.org/​protocol/​httpbind" sid=​"551f1f18f6e8ac04c8ef32ae9b3c69d804f0b2bc">​</body>​
0 request id 13.1 state changed to 2
0 request id 13.1 state changed to 3
0 request id 13.1 state changed to 4
0 removing request
0 _throttledRequestHandler called with 0 requests
0 request id 13 should now be removed
0 request id 13.1 got 200
1 _dataRecv called
<body xmlns=​"http:​/​/​jabber.org/​protocol/​httpbind">​<presence xmlns=​"jabber:​client" from=​"admin@ashwin/​converse.js-54284235" to=​"admin@ashwin/​converse.js-27040382" type=​"unavailable">​</presence>​</body>​
1 no requests during idle cycle, sending blank request
0 _throttledRequestHandler called with 1 requests
0 request id 14.0 posting
0 request id 14.0 state changed to 1
<body rid=​"2913796504" xmlns=​"http:​/​/​jabber.org/​protocol/​httpbind" sid=​"551f1f18f6e8ac04c8ef32ae9b3c69d804f0b2bc">​</body>​

**Comment by ashwinthakre91** [comment]
getting the same log in firefox and other browsers however in firefox i can see the add contact
![image](https://cloud.githubusercontent.com/assets/17229061/13033847/d8861d42-d34a-11e5-8625-04b7ca5ee17e.png)
Where as in other browsers not able to see
![image](https://cloud.githubusercontent.com/assets/17229061/13033849/03f60230-d34b-11e5-9aee-6aed3e2f3130.png)

**Comment by ashwinthakre91** [comment]
ARIA: Attribute " aria-label ", required for accessibility, is missing on node: <button class=​"md-icon-button md-button md-ink-ripple hide-gt-sm" type=​"button" ng-transclude ng-click=​"toggleSidenav('left')​" hide-gt-sm>​…​</button>​
ARIA: Attribute " aria-label ", required for accessibility, is missing on node: <button class=​"md-icon-button md-button md-ink-ripple" type=​"button" ng-transclude ng-click=​"showSearchBarDiv = false">​…​</button>​
Markup '<md-button flex></md-button>' may not work as expected in IE Browsers. Consult 'https://github.com/philipwalton/flexbugs#9-some-html-elements-cant-be-flex-containers' for details.
Could not restore sessions. Error message: _restore: no restoreable session.
Failed to load resource: the server responded with a status of 404 (Not Found)
Failed to load resource: the server responded with a status of 404 (Not Found)
Status changed to: CONNECTING
0 _throttledRequestHandler called with 1 requests
0 request id 1.0 posting
0 request id 1.0 state changed to 1
<body rid=​"2913796491" xmlns=​"http:​/​/​jabber.org/​protocol/​httpbind" to=​"ashwin" xml:lang=​"en" wait=​"60" hold=​"1" content=​"text/​xml;​ charset=utf-8" ver=​"1.6" xmpp:version=​"1.0" xmlns:xmpp=​"urn:​xmpp:​xbosh">​</body>​
0 request id 1.1 state changed to 2
0 request id 1.1 state changed to 3
0 request id 1.1 state changed to 4
0 removing request
0 _throttledRequestHandler called with 0 requests
0 request id 1 should now be removed
0 request id 1.1 got 200
1 _connect_cb was called
<body xmlns=​"http:​/​/​jabber.org/​protocol/​httpbind" xmlns:xmpp=​"urn:​xmpp:​xbosh" xmlns:stream=​"http:​/​/​etherx.jabber.org/​streams" sid=​"551f1f18f6e8ac04c8ef32ae9b3c69d804f0b2bc" wait=​"60" requests=​"2" inactivity=​"30" maxpause=​"120" polling=​"2" ver=​"1.8" from=​"ashwin" secure=​"true" authid=​"15450717180062707997" xmpp:version=​"1.0">​<stream:features xmlns:stream=​"http:​/​/​etherx.jabber.org/​streams">​…​</stream:features>​</body>​
0 _throttledRequestHandler called with 0 requests
0 _throttledRequestHandler called with 1 requests
0 request id 2.0 posting
0 request id 2.0 state changed to 1
<body rid=​"2913796492" xmlns=​"http:​/​/​jabber.org/​protocol/​httpbind" sid=​"551f1f18f6e8ac04c8ef32ae9b3c69d804f0b2bc">​…​</body>​
0 request id 2.1 state changed to 2
0 request id 2.1 state changed to 3
0 request id 2.1 state changed to 4
0 removing request
0 _throttledRequestHandler called with 0 requests
0 request id 2 should now be removed
0 request id 2.1 got 200
1 _dataRecv called
<body xmlns=​"http:​/​/​jabber.org/​protocol/​httpbind">​<challenge xmlns=​"urn:​ietf:​params:​xml:​ns:​xmpp-sasl">​…​</challenge>​</body>​
0 _throttledRequestHandler called with 0 requests
0 _throttledRequestHandler called with 1 requests
0 request id 3.0 posting
0 request id 3.0 state changed to 1
<body rid=​"2913796493" xmlns=​"http:​/​/​jabber.org/​protocol/​httpbind" sid=​"551f1f18f6e8ac04c8ef32ae9b3c69d804f0b2bc">​…​</body>​
0 request id 3.1 state changed to 2
0 request id 3.1 state changed to 3
0 request id 3.1 state changed to 4
0 removing request
0 _throttledRequestHandler called with 0 requests
0 request id 3 should now be removed
0 request id 3.1 got 200
1 _dataRecv called
<body xmlns=​"http:​/​/​jabber.org/​protocol/​httpbind">​<success xmlns=​"urn:​ietf:​params:​xml:​ns:​xmpp-sasl">​dj1NbG5GSzVUOWFadTZ4YkFoUm9sMUpPbnhjNTQ9​</success>​</body>​
1 SASL authentication succeeded.
0 _throttledRequestHandler called with 0 requests
0 _throttledRequestHandler called with 1 requests
0 request id 4.0 posting
0 request id 4.0 state changed to 1
<body rid=​"2913796494" xmlns=​"http:​/​/​jabber.org/​protocol/​httpbind" sid=​"551f1f18f6e8ac04c8ef32ae9b3c69d804f0b2bc" to=​"ashwin" xml:lang=​"en" xmpp:restart=​"true" xmlns:xmpp=​"urn:​xmpp:​xbosh">​</body>​
0 request id 4.1 state changed to 2
0 request id 4.1 state changed to 3
0 request id 4.1 state changed to 4
0 removing request
0 _throttledRequestHandler called with 0 requests
0 request id 4 should now be removed
0 request id 4.1 got 200
1 _dataRecv called
<body xmlns=​"http:​/​/​jabber.org/​protocol/​httpbind" xmlns:xmpp=​"urn:​xmpp:​xbosh" xmlns:stream=​"http:​/​/​etherx.jabber.org/​streams" sid=​"551f1f18f6e8ac04c8ef32ae9b3c69d804f0b2bc" wait=​"60" requests=​"2" inactivity=​"30" maxpause=​"120" polling=​"2" ver=​"1.8" from=​"ashwin" secure=​"true" authid=​"8343320251530718921" xmpp:version=​"1.0">​<stream:features xmlns:stream=​"http:​/​/​etherx.jabber.org/​streams">​…​</stream:features>​</body>​
0 _throttledRequestHandler called with 0 requests
0 _throttledRequestHandler called with 1 requests
0 request id 5.0 posting
0 request id 5.0 state changed to 1
<body rid=​"2913796495" xmlns=​"http:​/​/​jabber.org/​protocol/​httpbind" sid=​"551f1f18f6e8ac04c8ef32ae9b3c69d804f0b2bc">​…​</body>​
0 request id 5.1 state changed to 2
0 request id 5.1 state changed to 3
0 request id 5.1 state changed to 4
0 removing request
0 _throttledRequestHandler called with 0 requests
0 request id 5 should now be removed
0 request id 5.1 got 200
1 _dataRecv called
<body xmlns=​"http:​/​/​jabber.org/​protocol/​httpbind">​<iq xmlns=​"jabber:​client" id=​"_bind_auth_2" type=​"result">​…​</iq>​</body>​
0 _throttledRequestHandler called with 0 requests
0 _throttledRequestHandler called with 1 requests
0 request id 6.0 posting
0 request id 6.0 state changed to 1
<body rid=​"2913796496" xmlns=​"http:​/​/​jabber.org/​protocol/​httpbind" sid=​"551f1f18f6e8ac04c8ef32ae9b3c69d804f0b2bc">​…​</body>​
0 request id 6.1 state changed to 2
0 request id 6.1 state changed to 3
0 request id 6.1 state changed to 4
0 removing request
0 _throttledRequestHandler called with 0 requests
0 request id 6 should now be removed
0 request id 6.1 got 200
1 _dataRecv called
<body xmlns=​"http:​/​/​jabber.org/​protocol/​httpbind">​<iq xmlns=​"jabber:​client" type=​"result" id=​"_session_auth_2">​</iq>​</body>​
Status changed to: CONNECTED
Connected
0 _throttledRequestHandler called with 0 requests
0 _throttledRequestHandler called with 1 requests
0 request id 7.0 posting
0 request id 7.0 state changed to 1
<body rid=​"2913796497" xmlns=​"http:​/​/​jabber.org/​protocol/​httpbind" sid=​"551f1f18f6e8ac04c8ef32ae9b3c69d804f0b2bc">​…​</body>​
0 request id 7.1 state changed to 2
0 request id 7.1 state changed to 3
0 request id 7.1 state changed to 4
0 removing request
0 _throttledRequestHandler called with 0 requests
0 request id 7 should now be removed
0 request id 7.1 got 200
1 _dataRecv called
<body xmlns=​"http:​/​/​jabber.org/​protocol/​httpbind">​<iq xmlns=​"jabber:​client" from=​"ashwin" to=​"admin@ashwin/​converse.js-27040382" id=​"d887bfec-20c7-4dc8-8e04-cfc0c7ae0197:​sendIQ" type=​"result">​…​</iq>​<iq xmlns=​"jabber:​client" from=​"ashwin" to=​"admin@ashwin/​converse.js-27040382" id=​"45df575e-16e1-4073-b2cd-15460767664c:​sendIQ" type=​"result">​…​</iq>​<iq xmlns=​"jabber:​client" from=​"admin@ashwin" to=​"admin@ashwin/​converse.js-27040382" id=​"enablecarbons" type=​"result">​</iq>​<iq xmlns=​"jabber:​client" from=​"admin@ashwin" to=​"admin@ashwin/​converse.js-27040382" id=​"3124297f-0e3d-4e3c-a220-bdae55f4a5c4:​roster" type=​"result">​…​</iq>​</body>​
0 _throttledRequestHandler called with 0 requests
Message carbons have been enabled.
0 _throttledRequestHandler called with 0 requests
0 _throttledRequestHandler called with 1 requests
0 request id 8.0 posting
0 request id 8.0 state changed to 1
<body rid=​"2913796498" xmlns=​"http:​/​/​jabber.org/​protocol/​httpbind" sid=​"551f1f18f6e8ac04c8ef32ae9b3c69d804f0b2bc">​…​</body>​
0 request id 8.1 state changed to 2
0 request id 8.1 state changed to 3
0 request id 8.1 state changed to 4
0 removing request
0 _throttledRequestHandler called with 0 requests
0 request id 8 should now be removed
0 request id 8.1 got 200
1 _dataRecv called
<body xmlns=​"http:​/​/​jabber.org/​protocol/​httpbind">​<iq xmlns=​"jabber:​client" from=​"conference.ashwin" to=​"admin@ashwin/​converse.js-27040382" id=​"0818ca58-9719-449a-be62-5be5d853c2f8:​sendIQ" type=​"result">​…​</iq>​<iq xmlns=​"jabber:​client" from=​"pubsub.ashwin" to=​"admin@ashwin/​converse.js-27040382" id=​"585c2b1e-7b0a-49fe-a03c-ac49e51105ee:​sendIQ" type=​"result">​…​</iq>​<iq xmlns=​"jabber:​client" from=​"ashwin" to=​"admin@ashwin/​converse.js-27040382" id=​"83d794b4-d4aa-47d5-8e8d-e83a3c401a46:​sendIQ" type=​"result">​…​</iq>​<iq xmlns=​"jabber:​client" from=​"ashwin" to=​"admin@ashwin/​converse.js-27040382" id=​"fa6d7fe2-4f30-478e-9ac3-68bc56be83bc:​sendIQ" type=​"result">​…​</iq>​<iq xmlns=​"jabber:​client" from=​"ashwin" to=​"admin@ashwin/​converse.js-27040382" id=​"12513ba7-9c89-4132-b0ff-c203349afff5:​sendIQ" type=​"result">​…​</iq>​<iq xmlns=​"jabber:​client" from=​"ashwin" to=​"admin@ashwin/​converse.js-27040382" id=​"5deb7bb4-afd3-41e2-ab10-aaa23950efa6:​sendIQ" type=​"result">​…​</iq>​<iq xmlns=​"jabber:​client" from=​"ashwin" to=​"admin@ashwin/​converse.js-27040382" id=​"ddf74755-7ac7-4e2d-967c-01596ff396a4:​sendIQ" type=​"result">​…​</iq>​<iq xmlns=​"jabber:​client" from=​"ashwin" to=​"admin@ashwin/​converse.js-27040382" id=​"6136752e-c846-47ab-9d65-11cbf03e24e2:​sendIQ" type=​"result">​…​</iq>​<iq xmlns=​"jabber:​client" from=​"ashwin" to=​"admin@ashwin/​converse.js-27040382" id=​"051bf010-bf6f-4414-9e67-03b1b35a3c96:​sendIQ" type=​"result">​…​</iq>​<iq xmlns=​"jabber:​client" from=​"ashwin" to=​"admin@ashwin/​converse.js-27040382" id=​"e035c38a-d381-40de-8791-6fd97e32de28:​sendIQ" type=​"result">​…​</iq>​<presence xmlns=​"jabber:​client" from=​"admin@ashwin/​converse.js-54284235" to=​"admin@ashwin/​converse.js-27040382">​…​</presence>​<presence xmlns=​"jabber:​client" from=​"admin@ashwin/​converse.js-27040382" to=​"admin@ashwin/​converse.js-27040382">​</presence>​</body>​
1 no requests during idle cycle, sending blank request
0 _throttledRequestHandler called with 1 requests
0 request id 9.0 posting
0 request id 9.0 state changed to 1
<body rid=​"2913796499" xmlns=​"http:​/​/​jabber.org/​protocol/​httpbind" sid=​"551f1f18f6e8ac04c8ef32ae9b3c69d804f0b2bc">​</body>​
0 request id 9.1 state changed to 2
0 request id 9.1 state changed to 3
0 request id 9.1 state changed to 4
0 removing request
0 _throttledRequestHandler called with 0 requests
0 request id 9 should now be removed
0 request id 9.1 got 200
1 _dataRecv called
<body xmlns=​"http:​/​/​jabber.org/​protocol/​httpbind">​<iq xmlns=​"jabber:​client" from=​"raje" to=​"admin@ashwin/​converse.js-27040382" type=​"error" id=​"ae49afb8-1a0e-4fe3-98ab-99a8e1e8d8fc:​sendIQ">​…​</iq>​</body>​
1 no requests during idle cycle, sending blank request
0 _throttledRequestHandler called with 1 requests
0 request id 10.0 posting
0 request id 10.0 state changed to 1
<body rid=​"2913796500" xmlns=​"http:​/​/​jabber.org/​protocol/​httpbind" sid=​"551f1f18f6e8ac04c8ef32ae9b3c69d804f0b2bc">​</body>​
0 request id 10.1 state changed to 2
0 request id 10.1 state changed to 3
0 request id 10.1 state changed to 4
0 removing request
0 _throttledRequestHandler called with 0 requests
0 request id 10 should now be removed
0 request id 10.1 got 200
1 _dataRecv called
<body xmlns=​"http:​/​/​jabber.org/​protocol/​httpbind">​<iq xmlns=​"jabber:​client" from=​"ds" to=​"admin@ashwin/​converse.js-27040382" type=​"error" id=​"d05dfc6c-4668-42d3-84a6-ffaeb82aece7:​sendIQ">​…​</iq>​</body>​
1 no requests during idle cycle, sending blank request
0 _throttledRequestHandler called with 1 requests
0 request id 11.0 posting
0 request id 11.0 state changed to 1
<body rid=​"2913796501" xmlns=​"http:​/​/​jabber.org/​protocol/​httpbind" sid=​"551f1f18f6e8ac04c8ef32ae9b3c69d804f0b2bc">​</body>​
0 request id 11.1 state changed to 2
0 request id 11.1 state changed to 3
0 request id 11.1 state changed to 4
0 removing request
0 _throttledRequestHandler called with 0 requests
0 request id 11 should now be removed
0 request id 11.1 got 200
1 _dataRecv called
<body xmlns=​"http:​/​/​jabber.org/​protocol/​httpbind">​</body>​
1 no requests during idle cycle, sending blank request
0 _throttledRequestHandler called with 1 requests
0 request id 12.0 posting
0 request id 12.0 state changed to 1
<body rid=​"2913796502" xmlns=​"http:​/​/​jabber.org/​protocol/​httpbind" sid=​"551f1f18f6e8ac04c8ef32ae9b3c69d804f0b2bc">​</body>​
0 request id 12.1 state changed to 2
0 request id 12.1 state changed to 3
0 request id 12.1 state changed to 4
0 removing request
0 _throttledRequestHandler called with 0 requests
0 request id 12 should now be removed
0 request id 12.1 got 200
1 _dataRecv called
<body xmlns=​"http:​/​/​jabber.org/​protocol/​httpbind">​</body>​
1 no requests during idle cycle, sending blank request
0 _throttledRequestHandler called with 1 requests
0 request id 13.0 posting
0 request id 13.0 state changed to 1
<body rid=​"2913796503" xmlns=​"http:​/​/​jabber.org/​protocol/​httpbind" sid=​"551f1f18f6e8ac04c8ef32ae9b3c69d804f0b2bc">​</body>​
0 request id 13.1 state changed to 2
0 request id 13.1 state changed to 3
0 request id 13.1 state changed to 4
0 removing request
0 _throttledRequestHandler called with 0 requests
0 request id 13 should now be removed
0 request id 13.1 got 200
1 _dataRecv called
<body xmlns=​"http:​/​/​jabber.org/​protocol/​httpbind">​<presence xmlns=​"jabber:​client" from=​"admin@ashwin/​converse.js-54284235" to=​"admin@ashwin/​converse.js-27040382" type=​"unavailable">​</presence>​</body>​
1 no requests during idle cycle, sending blank request
0 _throttledRequestHandler called with 1 requests
0 request id 14.0 posting
0 request id 14.0 state changed to 1
<body rid=​"2913796504" xmlns=​"http:​/​/​jabber.org/​protocol/​httpbind" sid=​"551f1f18f6e8ac04c8ef32ae9b3c69d804f0b2bc">​</body>​

**Comment by ashwinthakre91** [comment]
got the issue thanks a lot ajinkya
