### ISSUE TITLE
Pull requests were lost when splitting into multiple files

### ISSUE THREAD

**Issue by rlanvin** [jcbrand/converse.js#596]
@jcbrand  It seems my fixes (in pull request #589 and #590) are not in converse-core.js anymore. I suspect they have been lost during the commit 576efc4815709aca0645c08f1478b4f5023ae3bc. Could you apply them again?

It is possible that some other pull requests have been lost as well, so you should check (maybe #587). Or maybe I'm just very unlucky...

**Comment by jcbrand** [comment]
Sorry about that!
