### ISSUE TITLE
Add new option to synchronize presence with other own client resources

### ISSUE THREAD

**Issue by davec82** [jcbrand/converse.js#597]
Hi!

do you think that it could be useful to add an option (default setting) that let (or not)  to synchronize  presence status in converse.js client when another one client (with different resource), with the same account, changes his presence status?

Now, by default, if you log in with another client (with the same account) and you change presence status  also converse.js client will change his presence status.

**Comment by jcbrand** [comment]
Yes, such an option could be added.

**Comment by davec82** [comment]
Could 'synchronize_presence' be a good name for this option?

**Comment by jcbrand** [comment]
Sure. It could take three values, `true`, `false`, or the resource name of the particular client that it should synchronize with.

**Comment by jcbrand** [comment]
Refs #598
