### ISSUE TITLE
onRoomsFound, informNoRoomsFound do not respect hide_muc_server setting.

### ISSUE THREAD

**Issue by sww314** [jcbrand/converse.js#601]
The hide_muc_server hides the server name on the "Rooms" tab. 
However, after you select "Show Rooms", the response does respect this setting an displays the MUC server. 
Suggest modifying the messages from: 
in onRoomsFound:
"Rooms on <muc_domain>" -> "Rooms available:"

in informNoRoomsFound:
"No rooms on <muc_domain>" -> "No rooms available."

Alternatively can add setting check and if/else the message. 

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/31495753-onroomsfound-informnoroomsfound-do-not-respect-hide_muc_server-setting?utm_campaign=plugin&utm_content=tracker%2F194169&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F194169&utm_medium=issues&utm_source=github).

<bountysource-plugin>

**Comment by jcbrand** [comment]
This seems to have been fixed in the meantime.
