### ISSUE TITLE
'show_desktop_notifications: true' breaks message delivery to js client

### ISSUE THREAD

**Issue by badfiles** [jcbrand/converse.js#603]
If one sends a message to js client while on another tab, the message is not delivered and all further messages are also lost. 
Js --> nonjs messages pass OK.

**Comment by badfiles** [comment]
This feature is still broken.
It shows notification about status change, but only after refreshing the page.
It does not show notification about new message, and all further incoming messages are lost.
Outgoing messages are sent OK.

**Comment by badfiles** [comment]
Now it works OK, but somehow notifications are displayed even if the page with client is active.

**Comment by jcbrand** [comment]
It checks whether the page is "blurred". So the page might still be visible, but if it's not in focus, it will show the notifications.

**Comment by badfiles** [comment]
I see, I had to use clients on separate computers.
