### ISSUE TITLE
Buddies' status in roster is not updated (online -- offline)

### ISSUE THREAD

**Issue by badfiles** [jcbrand/converse.js#604]

**Comment by jcbrand** [comment]
Can you please double-check whether this is still a problem? Also, check whether it's not related to this: https://github.com/jcbrand/converse.js/issues/547

**Comment by badfiles** [comment]
Just checked, still a problem.

**Comment by jcbrand** [comment]
Please give more info on what exactly is happening.

**Comment by badfiles** [comment]
It look like status update is totally broken. I cant't even determine how bad it is. 
I used two test cases -- a buddy changes his status while js client is online and offline.
When js client is online, status changes are not picked up at all.
When js client connects, it shows some statuses correctly, and some are wrong.
But it seems like correct status pickup depends on the previous status, and I am not sure how exactly.

**Comment by jcbrand** [comment]
The master branch is currently under heavy refactoring and development and things may break in the process. If you want something stable to work with, then branch off the latest release tag.

**Comment by badfiles** [comment]
Unfortunately I need converse to connect with random resource, which is available only in latest git.

**Comment by jcbrand** [comment]
Should be working now again.

**Comment by badfiles** [comment]
But status are is not being updated still (550f7827bfc9).
I found another problem, maybe it is connected.
While using `local` storage I noticed local records are not updated if contact's data has been changed (I used nickname for testing). 
I switched to `session` storage and found the same problem.

**Comment by jcbrand** [comment]
I tested it with various accounts and it worked well for me.

I would not recommend using `local` storage. There might be weird unanticipated side-effects if you do.

About contact data, that doesn't get updated in real-time, it only gets updated when there is a new session (when the session data in the browser storage has been cleared).

**Comment by badfiles** [comment]
I agree, if session storage is used, it is updated on the next session, but it is pretty hard to initiate next session, the user should close the page containing js client and open it again, page refresh does not work.
As for the local storage, it is impossible to update once created record at all. 
It works only if I refresh the page, unlit the page is refreshed old status is displayed.
I tried with clients libpurple 2.10.11, xabber beta, jTalk, in ff 44.0.2 and chrome  50.0.2661.11 dev (64-bit)

**Comment by jcbrand** [comment]
>  but it is pretty hard to initiate next session, the user should close the page containing js client and open it again, page refresh does not work.

True, but that's out of scope for this ticket. You can create a feature request for that if you want (although there's no guarantee that I or someone else will work on it).

> Status updates work only if I refresh the page

I'm not able to reproduce this (like I mentioned, it works for me since the last commits today). You can try to debug this and gather more information on what the cause might be.

Set `debug` to `true` in `converse.initialize` and then check the debug output in your browser's dev console (Chrome works best IMHO). See if you find any errors and check whether you receive the presence stanzas from the other users.

**Comment by badfiles** [comment]
Thank you anyway, will to my best to determine what is wrong with this one.
It could also be xmpp server, I use openfire 4.0.1

**Comment by badfiles** [comment]
I think I understand what is happening here. I assume you use `bosh_service_url` with `auto_reconnect`?
If so, your client just reconnects after timeout and gets updated statuses.
I use `websocket_url`, and with persistent connection reconnect just does not happen.

Having tested with `bosh_service_url` and default nginx' `proxy_read_timeout` of 60s I found statuses update on timeout, changing `proxy_read_timeout` to 300s (over default ping_interval 180) has 'broken' status updates.

**Comment by jcbrand** [comment]
No, I use BOSH but nwithout `auto_reconnect` and when a user changes their status, it's reflected immediately, not after multiple seconds.

**Comment by badfiles** [comment]
I briefly ran through protocol with wireshark and it looks like there are no messages informing js client about status change.
Then I made libpurple work over httpbind and found out that server actually emits presence notifications.
For both clients (libpurple and js) feature `var="http://jabber.org/protocol/pubsub#presence-notifications"` was declared in handshake, but the same server emits presence notifications for libpurple client and does not emit such notifications for converse.js, so for me it looks like converse does not inform server to emit presence notifications.

**Comment by badfiles** [comment]
There is one packet with error, maybe is is connected somehow
`<body rid='21323' xmlns='http://jabber.org/protocol/httpbind' sid='88by8j2f7b'><iq type='set' xmlns='jabber:client' id='9e319c69-5d7a-4593-a9b3-e7bee79cbe58:sendIQ'><query xmlns='urn:xmpp:mam:0' queryid='89fda3ce-4575-4304-8528-0030a491caca'><x xmlns='jabber:x:data' type='submit'><field var='FORM_TYPE' type='hidden'><value>urn:xmpp:mam:0</value></field><field var='with'><value>alex@server.ru</value></field></x><set xmlns='http://jabber.org/protocol/rsm'><max>20</max><before></before></set></query></iq></body>`

`<body xmlns='http://jabber.org/protocol/httpbind' ack='21323'><iq xmlns="jabber:client" type="error" id="9e319c69-5d7a-4593-a9b3-e7bee79cbe58:sendIQ" to="www@server.ru/converse.js-136000131"><error code="501" type="cancel"><feature-not-implemented xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"/></error></iq></body>`

**Comment by jcbrand** [comment]
Congratulations on solving it.

Why was the user not in the roster however? In converse.js, a user should be added to the roster as soon as the subscription request is accepted (if I remember correctly).

**Comment by badfiles** [comment]
Three test users were in converse.js roster, but none of them had converse.js user. All four had mutual subscription. 
When js user is not in roster I can see it's jid and resource marker in IM-window of libpurple client, otherwise I can only see the jid.
