### ISSUE TITLE
Can't load javascript With AMD and require.js 

### ISSUE THREAD

**Issue by docaohuynh** [jcbrand/converse.js#606]
Dear jcbrand!
I just started with conversejs I have problem with development when use requirejs.
I added this to the <head> session but when load index.html its not work

```
<link rel="stylesheet" type="text/css" media="screen" href="converse.css">
<script data-main="main" src="components/requirejs/require.js"></script>
```

Error

```

Error: Script error for "converse-api", needed by: converse
http://requirejs.org/docs/errors.html#scripterror
var e = new Error(msg + '\nhttp://requirejs.org/docs/errors.html#' + id);

	
require.js (line 165, col 17)
Error: Script error for "locales"
http://requirejs.org/docs/errors.html#scripterror
var e = new Error(msg + '\nhttp://requirejs.org/docs/errors.html#' + id);

	
require.js (line 165, col 17)
Error: Script error for "converse-muc"
http://requirejs.org/docs/errors.html#scripterror
var e = new Error(msg + '\nhttp://requirejs.org/docs/errors.html#' + id);
```

Tks!

**Comment by jcbrand** [comment]
Use the file `dev.html` in the converse.js repo. That should work (after you have run `make dev`).

**Comment by docaohuynh** [comment]
Tks Jcbrand!
I have one more question. What IDE are you used to develop project
I use Eclipse and add Tern plugin but It can't hyperlink  

Example:
I'm in file **converse-no-dependencies.js ** in line
```
'initialize': function (settings, callback) {
            converse.initialize(settings, callback);
        },
```
I want link to file to know what file is called when click on initialize

Hope you understand!
Tks

**Comment by jcbrand** [comment]
Sorry @docaohuynh, but I can't help you there. I use VIM with exuberant-ctags.
