### ISSUE TITLE
no-jquery.js is broken

### ISSUE THREAD

**Issue by badfiles** [jcbrand/converse.js#608]
Now it wants `jquery-private` trowing `Error: converse-api missing jquery-private`

**Comment by jcbrand** [comment]
Please give more info. It's not clear what you're referring to.

**Comment by badfiles** [comment]
converse.nojquery.js built on efa4a9ff
is broken and wants `jquery-private` although it should be excluded.

**Comment by jcbrand** [comment]
Should be working now again.
