### ISSUE TITLE
Offline message is not showing when the person is not added in roster contact

### ISSUE THREAD

**Issue by Pbalu87** [jcbrand/converse.js#615]
I have implemented converse framework for a chat application and modified some functionality.I am creating a temp user each time when a visitor of the site wish to chat with admin of my site and login with that temp user and adding admin user to the roster contact of the temp user created. Problem is if temp user sends message to admin and admin is offline, the message is not showing to admin user when he becomes online, the reason that i found out was since the temp user is not added to admin's roster contact, it will not show the offline message.If again the admin goes offline and again the temp user sends offline message second time (that is after the temp user is added to admin's roster contact when he log in for first time by setting auto_subscribe property to true), then the offline message pop up is showing. Please tell me the solution for this. My requirement is even if the admin user is offline and temp user sends a message, the admin user must receive that offline message once he accepts the temp user's request. Please help.

**Comment by jcbrand** [comment]
Converse.js doesn't show messages from people not on your roster.

See here:
https://github.com/jcbrand/converse.js/blob/9a449e3615e9877fef5c365b037e22727d8e57b1/src/converse-core.js#L1375

You can write a plugin to override that functionality.
https://conversejs.org/docs/html/development.html#writing-a-converse-js-plugin
