### ISSUE TITLE
Error when open index.html

### ISSUE THREAD

**Issue by docaohuynh** [jcbrand/converse.js#616]
Dear Jcbrand!

I open index.html file but have error

```
TypeError: obj is undefined
if (!obj.prototype._super) {
```
In file 	
**converse.js** (line 28760, col 17)

**Comment by lixmal** [comment]
It seems the value for key "MinimizedChatBoxView" is undefined in this line:

`                         this._extendObject(converse[key], override);`

**converse-core.js**, line 1840

**Comment by jcbrand** [comment]
Thanks @lixmal, that helped me know what the problem is.

I've pushed a fix for this. Please update and check again.

**Comment by lixmal** [comment]
Works for me, error is gone.
Thanks a lot.
