### ISSUE TITLE
unable to login with websockets after a wrong password has been specified initially

### ISSUE THREAD

**Issue by mt7479** [jcbrand/converse.js#618]
**software**

prosody-trunk (62d533535334)
converse.js (0.10.1)

**steps to reproduce**
- issue a wrong password for your account
- issue the correct password for your account

**problem**

converse.js shows the spinning dots and does not continue to login until you refresh
the page with F5 and enter your credentials again.

**browsers**

Firefox 45.0.1
Chrome 48.0.2564.109

**else**
- when using bosh the same procedure works
- all tests conducted directly against the bosh/websocket endpoints (no proxying)

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/32249262-unable-to-login-with-websockets-after-a-wrong-password-has-been-specified-initially?utm_campaign=plugin&utm_content=tracker%2F194169&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F194169&utm_medium=issues&utm_source=github).

<bountysource-plugin>

**Comment by saganshul** [comment]
@jcbrand I think you can close this issue now. This bug does not exist in new release of converse.js

**Comment by jcbrand** [comment]
Thanks @saganshul

**Comment by mt403** [comment]
@saganshul How did you test this ? The issue still persists for me.

**Comment by saganshul** [comment]
@mt403 which version of converse.js you are working on?

**Comment by mt403** [comment]
@saganshul 3.0.0

**Comment by jcbrand** [comment]
I tested this now and can confirm the problem. However it's not clear to me that this is a problem with converse.js (or more strictly speaking with strophe.js).

In the case where logging in hangs... the log output says that converse.js sent this stanza:

```
<iq type="set" id="_bind_auth_2" xmlns="jabber:client"><bind xmlns="urn:ietfarams:xml:ns:xmpp-bind"><resource>converse.js-20611459</resource></bind></iq>
```

to bind the resource.

It then waits for a reply IQ which it apparently never receives.

In the debug log output of Prosody, I don't see any mention of that stanza being received. However in the case where login works, I **do** see that stanza being mentioned in the log output.

**Comment by mt403** [comment]
Created a prosody issue:

https://prosody.im/issues/issue/843

**Comment by mt7479** [comment]
I think the issue can be closed for good since I'm not able the reproduce the error with a clean lab setup. The original instance is not available any more.

I've updated the prosody issues as well. Sorry for any inconvenience.

**Comment by jcbrand** [comment]
Ok, thanks for reporting back.
