### ISSUE TITLE
Faulty access to the local converse.min.css file on WordPress installations

### ISSUE THREAD

**Issue by zane901267** [jcbrand/converse.js#619]
Hey there everyone,

I think there's something wrong with your code in some WordPress installations. In case if you have to change the colors of the converse.js client, the plugin doesn't use the internal converse.min.css, located under /core/css/converse.min.css. Instead, it relies on a different converse.min.css which is located on an web server somewhere in the internet. After some searching, I've found the problem in the conversejs.php file. 

        	switch ($this->default['cdn']) {
			case 0:
				wp_register_style( 'ConverseJS', plugins_url( '/core/css/converse.min.css', __FILE__ ), array(), $this->default['conver'] );
				wp_enqueue_style( 'ConverseJS' );
				wp_register_script( 'ConverseJS', plugins_url( '/core/converse.min.js', __FILE__ ), array(), $this->default['conver'], false );
				wp_enqueue_script( 'ConverseJS' );
			case 1:
				wp_register_style( 'ConverseJS', 'https://wordpress.chatme.im/chat/conversejs/css/converse.min.css', array(), $this->default['conver'] );
				wp_enqueue_style( 'ConverseJS' );
				wp_register_script( 'ConverseJS', 'https://wordpress.chatme.im/chat/conversejs/converse.min.js', array(), 'cdn', false );
				wp_enqueue_script( 'ConverseJS' );

After changing case 1 to the same like case 0, the client used the right CSS file. Is that behavior intended like this or is it possible to correct the code? Maybe removing case 1 or something like that, otherwise any local converse.min.css might be very unnecessary. Or is there any possibility to tell the plugin which css file it should use?

Currently I use the following workaround to tell my client what css file it has to use:

		switch ($this->default['cdn']) {
			case 0:
				wp_register_style( 'ConverseJS', plugins_url( '/core/css/converse.min.css', __FILE__ ), array(), $this->default['conver'] );
				wp_enqueue_style( 'ConverseJS' );
				wp_register_script( 'ConverseJS', plugins_url( '/core/converse.min.js', __FILE__ ), array(), $this->default['conver'], false );
				wp_enqueue_script( 'ConverseJS' );
			case 1:
				wp_register_style( 'ConverseJS', plugins_url( '/core/css/converse.min.css', __FILE__ ), array(), $this->default['conver'] );
				wp_enqueue_style( 'ConverseJS' );
				wp_register_script( 'ConverseJS', plugins_url( '/core/converse.min.js', __FILE__ ), array(), $this->default['conver'], false );
				wp_enqueue_script( 'ConverseJS' );

Thanks and have a nice evening!

**Comment by jcbrand** [comment]
Hi @zane901267 

Thanks for the bug report. This repo and issue tracker is however only about the core, "vanilla" converse.js code and doesn't cover it's integration into any other frameworks or platforms.

For the Wordpress plugin, you should contact its author: @camaran 

I'm not sure where he hosts the software for the Wordpress plugin.

**Comment by camaran** [comment]
Hi, I fix the problem tomorrow 

Inviato da iPhone

**Comment by camaran** [comment]
Fixed in 2.5.17 removed use of cdn now work with local copy of conversejs files :-)

**Comment by jcbrand** [comment]
Thanks @camaran. Where do you host the code for the wordpress plugin?

**Comment by camaran** [comment]
@jcbrand the plugin code is hosted in wordpress plugin repository, but the conversejs.min,js first i use a CDN but now i localy installed in every wordpress that install plugin
