### ISSUE TITLE
Unread message count on minimised windows doesn't match

### ISSUE THREAD

**Issue by edwh** [jcbrand/converse.js#624]
I see an issue where the "Minimised" box has a count on it indicating new messages,. but none of the groups shown when you click on it do. Any ideas?

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/32563277-unread-message-count-on-minimised-windows-doesn-t-match?utm_campaign=plugin&utm_content=tracker%2F194169&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F194169&utm_medium=issues&utm_source=github).

<bountysource-plugin>

**Comment by jcbrand** [comment]
Not sure. It might be a bug where notifications (X *is typing*) are wrongly counted as messages. There should be code to check for this though.
