### ISSUE TITLE
Open chat minimised

### ISSUE THREAD

**Issue by edwh** [jcbrand/converse.js#626]
When a chat is opened using the API, it opens the full window.  It would be nice if you could open a chat window minimised.

At present I set a timer to do this once it has fully opened, so there's a bit of screen clutter.

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/32564157-open-chat-minimised?utm_campaign=plugin&utm_content=tracker%2F194169&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F194169&utm_medium=issues&utm_source=github).

<bountysource-plugin>

**Comment by swift11** [comment]
agreed, a minimized chat window would also be more mobile browser friendly

**Comment by FlipperDev** [comment]
Hey there, I want to do it also. I use auto_join_rooms and I want that chatbox open minimised. How do you do that for now ? 

thanks

**Comment by saganshul** [comment]
@jcbrand @edwh 
I didn't actually get what is supposed to be done here. 
Should I create a **new configuration variable** say
```javascript
open_chat_minimised: true
```
then on joining the group, chat box will open in minimized state? or something different?

**Comment by jcbrand** [comment]
@saganshul I think the way to go is to make the API configurable, so that a user can call `chats.open` in such a way as to prevent the chat from opening.

So the fix would likely have to do with the API here:
https://github.com/jcbrand/converse.js/blob/06668d8733a463ff621ae82a7c05270fb98d7d2e/src/converse-core.js#L2159

**Comment by novokrest** [comment]
Can I work on this issue?

**Comment by jcbrand** [comment]
@novokrest Sure!

**Comment by jcbrand** [comment]
Done by @novokrest and merged.
