### ISSUE TITLE
webp support for vcard avatars

### ISSUE THREAD

**Issue by mt403** [jcbrand/converse.js#629]
Conversations seems to publish images in webp format regardless of what the source file is.

Webp support for vcards would enable interop between conversations, converse.js and possibly gajim, 
in conjunction with [mod_pep_vcard_avatar](https://modules.prosody.im/mod_pep_vcard_avatar.html).

siacs/Conversations#1744

Edit: Chrome displays the webp images, Firefox does not.
https://bugzilla.mozilla.org/show_bug.cgi?id=856375

**Comment by jcbrand** [comment]
Doens't look like this is a converse.js issue then. I'll close it.
