### ISSUE TITLE
Invalid SID value

### ISSUE THREAD

**Issue by py-samsung** [jcbrand/converse.js#630]
when i log in and log out frequently.an error will occur.below is my code

function logout(){
	converse.user.logout();
}

converse.initialize({
        bosh_service_url:, // Please use this connection manager only for testing purposes
        show_controlbox_by_default: false,
        roster_groups: false,
		keepalive: true,
        message_carbons: true,
        play_sounds: true,
        roster_groups: true,
        show_controlbox_by_default: true,
	    auto_login:true,
		jid:,
		password:,
		debug:true,
		visible_toolbar_buttons:{
              call: true,
              clear: true,
              emoticons: true,
              toggle_occupants: true,
			allow_registration:false,
			allow_chat_pending_contacts:true,
			show_controlbox_by_default:true
             }
         });

})

**Comment by jcbrand** [comment]
What version of converse.js are you using, and what exactly is the error you are receiving?

**Comment by py-samsung** [comment]
my converse.js version is 0.10.1,blow is my picture.
<img width="1220" alt="2016-04-13 5 17 09" src="https://cloud.githubusercontent.com/assets/3212780/14488664/e704407c-019b-11e6-9bfd-ab3d758516d4.png">

**Comment by py-samsung** [comment]
if i do not set auto login =false ,everything will be ok.but i have to set auto login=true,

**Comment by jcbrand** [comment]
Can you try the unreleased version in the master branch and see if the problem still persists?

**Comment by py-samsung** [comment]
i find  how above problem occurs ,when i login same account in two different exporlor ,if i login this explorer's account ,another will occur above problem

**Comment by py-samsung** [comment]
the lastest master branch is ok .

**Comment by jcbrand** [comment]
Good to know, thanks.

**Comment by umpirsky** [comment]
@jcbrand I get this error often with converse 2.0.4, openfire 4.0.4 returns:

```<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/>
<title>Error 404 </title>
</head>
<body>
<h2>HTTP ERROR: 404</h2>
<p>Problem accessing /http-bind/. Reason:
<pre>    Invalid SID value.</pre></p>
<hr /><i><small>Powered by Jetty://</small></i>
</body>
</html>
```

**Comment by Hanmanth95** [comment]
getting invalid sid error, can anyone help me out with this issue.
