### ISSUE TITLE
The spinner never removes when we try to get into a room with password

### ISSUE THREAD

**Issue by JoseMariaRubioMoral** [jcbrand/converse.js#635]
Hi!

I'm using the version 0.10.1 and i have the following issue.
- I search from room inside a domain
- I click on one room with password
- I complete the form with the right password
- A spinner show up and never removes. I can not see the room.

I solve this problem adding the next code inside of  `this.ChatRoomView = converse.ChatBoxView.extend`            

`hidePasswordSpinner: function(){
  this.$('.chat-area').show();
  this.$('.occupants').show();
  this.$('span.centered.spinner').remove();
},`

and in the class `this.ChatRoomOccupantsView` I also added:

`
            onOccupantAdded: function (item) {
                var view = this.get(item.get('id'));
               ...
                if (item.get('id') == converse.bare_jid){
                    this.chatroomview.hidePasswordSpinner();
                };
                ...
            },
`

Because the refactoring of all the classes I'm affraid to send a pull request of this.

Thanks in advance

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/32941142-the-spinner-never-removes-when-we-try-to-get-into-a-room-with-password?utm_campaign=plugin&utm_content=tracker%2F194169&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F194169&utm_medium=issues&utm_source=github).

**Comment by jcbrand** [comment]
Thanks. I think a pull request with changes made to 0.10.1 won't help much in any case, since the code in the master branch has been heavily refactored.
