### ISSUE TITLE
converse in Samsung browser

### ISSUE THREAD

**Issue by swift11** [jcbrand/converse.js#637]
I've tested Converse on a Samsung Z3 phone (Tizen OS) with the Samsung browser and posted some screenshots on Dropbox: would it be possible to comment the screenshots please ? :)
https://www.dropbox.com/sh/vm017xwe2yx87rb/AAClaiLlXCUXvV6I3Fk8FLXxa?dl=0

**Comment by jcbrand** [comment]
@swift11 I've made various mobile improvements a while ago, as part of this ticket: [622](https://github.com/jcbrand/converse.js/issues/622)

They are not released yet, but you can try out the builds in the master branch and see how well they work for you. They should fix a lot of the problems you've identified. If you still see problems you can mention them in a new ticket.
