### ISSUE TITLE
issue with OTR activation on Release 1.0.0

### ISSUE THREAD

**Issue by cemalgultekin** [jcbrand/converse.js#640]
When activating OTR from a chatbox on Firefox Developer Edition to an xmpp server, we receive an error with 
**this.connection is undefined**

the current fix as far as I could find is replacing 

**pass_check = window.sessionStorage[b64_sha1(this.connection.jid+'pass_check')];**

with

**pass_check = window.sessionStorage[b64_sha1(converse.connection.jid+'pass_check')];**

in **converse-otr.js** at line **152**

**Comment by jcbrand** [comment]
Hi @cemalgultekin, could very well be, since some large refactoring was done in the previous release. Please make a pull request with your change and I'll review.
