### ISSUE TITLE
Enable base-64 encoding and decoding of messages.

### ISSUE THREAD

**Issue by Anubh** [jcbrand/converse.js#643]
I am unable to find any configuration related to encoding and decoding of messages. Is there any configuration there.
Thanks

**Comment by jcbrand** [comment]
What's your usecase?

**Comment by Anubh** [comment]
Hi @jcbrand 

So, I want to encode message in base64 before sending to ejabber and decrypt message after receiving from server.

**Comment by jcbrand** [comment]
Why would you want to do that?

This is not a usecase that converse.js supports.

Modern browsers have the methods [atob and btoa](https://developer.mozilla.org/en-US/docs/Web/API/WindowBase64/Base64_encoding_and_decoding) which you can use to encode/decode Base64, but you'll have to do it yourself.

You can create a [converse.js plugin](https://conversejs.org/docs/html/development.html#writing-a-converse-js-plugin) that encodes messages before they're sent and decodes them once they are received.

You can look at the [converse-otr.js](https://github.com/jcbrand/converse.js/blob/master/src/converse-otr.js) plugin for some inspiration.
