### ISSUE TITLE
Receive chatroom message without opening it.

### ISSUE THREAD

**Issue by hendry91** [jcbrand/converse.js#644]
Hi,
Is it possible to make it receive all the room message without opening/minimize the room?

**Comment by jcbrand** [comment]
Give more info please. What are you currently doing that's not working for you?

**Comment by hendry91** [comment]
@jcbrand I would like to receive chat room message without open/join, but they are room member.
example: user A send "hi" to room xxx, user B didn't open/join the room, but receive the notification room xxx has a new message.
is it possible to do that?

**Comment by jcbrand** [comment]
No, it's not possible to do that, users need to join the room to be able to receive messages sent to it.
