### ISSUE TITLE
message receive issue on 1.0.2 release

### ISSUE THREAD

**Issue by cemalgultekin** [jcbrand/converse.js#647]
Hi there,

using 1.0.2 release and bosh, when I log in I(m) can send a message to a user (x) on my roster and m can receive as well, but after m replies , something happens and whenever x replies the http-bind receives the message but doesn't show on the user chat pane. m can send messages and they will be sent but although the messages sent from x are received by the browser, it's not shown.

Using Openfire 3.9.3 and http-bind with the config below.

```javascript
require(['converse'], function (converse) {
        converse.initialize({
            bosh_service_url: 'https://foo.com/http-bind/',
            show_controlbox_by_default: true,
            allow_chat_pending_contacts: false,
            roster_groups: true,
            play_sounds: true,
            auto_login: true,
            authentication: 'prebind',
            jid: 'session_jid',
            sid: 'session_sid',
            rid: 'session_rid',
            allow_muc: false,
            allow_registration: false,
            allow_logout : true,
            auto_away: 600,
            auto_xa: 1800,
            hide_offline_users: true,
            use_otr_by_default: false,
            cache_otr_key: false,
            allow_contact_requests: false,
            allow_contact_removal: false,
            archived_messages_page_size: 0,
            forward_messages: true,
            message_carbons: true,
            hide_muc_server: true,
            include_offline_state: false,
            storage: 'session',
            message_archiving: 'never',
            synchronize_availability: true,
            keepalive: true,
            sticky_controlbox: false,
            prebind: false,
            debug: false,
            sounds_path: '/audio/',
            notification_icon: '../img/converse_logo.png'
        });
    });

```

**Comment by jcbrand** [comment]
Set `debug` to `true` and then open the browser's developer console. Then reproduce the issue and look for errors. In Chrome/Chromium you can even save the log out output and send it to me, otherwise if you see an error you can paste it here.

**Comment by demetriusofpharos** [comment]
@jcbrand - I'm seeing a similar issue. It seems to only happen once I minimize a chat, then open it again, then send a message from converse, then try to send back. 

I think this is the relevant bit from the console:
`<body xmlns="http://jabber.org/protocol/httpbind"><message xmlns="jabber:client" from="mike@xmpp.taalocal.local/Ebethron" to="1@xmpp.taalocal.local/89788678850734190681516" type="chat" id="purple643736ea"><active xmlns="http://jabber.org/protocol/chatstates"/></message></body>
converse.js?l:28595 onMessage: Ignoring incoming message intended for a different resource: 1@xmpp.taalocal.local/89788678850734190681516
converse.js?l:28595 1 no requests during idle cycle, sending blank request
converse.js?l:28595 0 _throttledRequestHandler called with 1 requests
converse.js?l:28595 0 request id 14.0 posting
converse.js?l:28595 0 request id 14.0 state changed to 1
converse.js?l:28595 <body rid="1389864779" xmlns="http://jabber.org/protocol/httpbind" sid="157ed12f0e0d01caab568a1b8e8889b294cc43b5"/>`

Converse 1.0.2
Ejabberd 16.03
Adium 1.5.10.2

**Comment by jcbrand** [comment]
@demetriusofpharos When the chat box gets minimized, converse.js sends out a stanza `<inactive>`.  If you have more than one client connected, then Ejabberd will decide to route messages to the other client, which has a difference "resource" associated with it. That's why you then see the message: `Ignoring incoming message intended for a different resource`.

That's all assuming you have a different client connected as well with a different resource. If that's not the case, then there is likely a bug somewhere. Do you know what the resource is of that instance of converse.js? 

You can check it in the browser console with: `converse.user.jid()`

**Comment by demetriusofpharos** [comment]
"If you have more than one client connected..."
ConverseJS itself acts as multiple clients if it's opened in multiple tabs, doesn't it? I do have `message_carbons: true` in the initialize. If you're referring to Adium; I'm logged into Adium with a different user over the same Ejabberd instance for testing purposes. For what it's worth, it seems to only happen with `authentication: 'prebind'`, as I changed it to `login` and it didn't happen. It also didn't happen with 1.0 at all.

Hopefully that clarifies.

**Comment by jcbrand** [comment]
>  it seems to only happen with authentication: 'prebind'

Then I think what might have happened is that you reloaded the page and the user received a new resource from the prebind values. Could that be it?

**Comment by jcbrand** [comment]
@demetriusofpharos I've now turned off the filtering by resource by default. I don't think it's strictly necessary, and creates confusion such as in your case.

**Comment by demetriusofpharos** [comment]
Ok, great. 

For what it's worth, I tested this morning and even with only one window open it was still happening. I'll apply the patch for now. Thanks.

**Comment by cemalgultekin** [comment]
Hi,

sorry for the late reply but my issue was resolved upon following your instructions. It seems the message wasn't received because it was for another resource. The fact behind it was, I was using a jid as "test@localhost/ConverseJs" however the other party's reply was intended for "test@localhost/conversejs", and converse was simply ignoring it due to case difference in resource.

**Comment by jcbrand** [comment]
Ok, good to know.
