### ISSUE TITLE
Not always firing disconnected event

### ISSUE THREAD

**Issue by kamranzafar** [jcbrand/converse.js#648]
Conversejs only seems to be firing the disconnected event when **auto_reconnect** is set to **true** 

The problem seems to be in the onDisconnected method, where it just returns if auto_reconnect is false.

       this.onDisconnected = function (condition) {
            if (!converse.auto_reconnect) { return; }
            if (converse.disconnection_cause === Strophe.Status.CONNFAIL) {
                converse.reconnect(condition);
                return 'reconnecting';
            } else {
                converse.emit('disconnected');
                return 'disconnected';
            }
        };

Can we change this to something like:

        this.onDisconnected = function (condition) {
            if (converse.disconnection_cause === Strophe.Status.CONNFAIL &&
                                                  converse.auto_reconnect) {
                converse.reconnect(condition);
                return 'reconnecting';
            } else {
                converse.emit('disconnected');
                return 'disconnected';
            }
        };

That's how the disconnected event is always fired even when **auto_reconnect** is set to **false**

I can submit a pull request if you want.

**Comment by jcbrand** [comment]
Looks good, please submit a pull request and I'll merge.
