### ISSUE TITLE
Mobile issue with infinite scroll

### ISSUE THREAD

**Issue by julian-d** [jcbrand/converse.js#651]
Hi, i am using infinite scroll on my website and when I use converse.js on my mobile phone and try to type something the browser jumps down, the infinite scroll is executed and the chat box moves down.
When i scroll down to the checkbox the infinite scroll is executed and so on.

**Comment by jcbrand** [comment]
It's not clear that this is a converse.js bug.

> When i scroll down to the checkbox the infinite scroll is executed and so on.

What checkbox?

**Comment by julian-d** [comment]
Sorry "Chatbox" not "Checkbox"

**Comment by jcbrand** [comment]
Sorry, but there's not anything I can do about this at the moment. You can reopen the issue if you have concrete information on what the problem is and how converse.js is responsible.
