### ISSUE TITLE
Mobile no Jquery build

### ISSUE THREAD

**Issue by julian-d** [jcbrand/converse.js#652]
For my app I need a nojquery mobile build of converse.js.

I created a fork and changed it there -> https://github.com/julian-d/converse.js/commit/621e8a2d74d6c3c5a8b9fd7f12f038b23fdb10cd

The make check throws an error i can't fix, so I think some small fixes are needed

```
src/build-mobile-no-jquery.js: line 16, col 2, Expected an assignment or function call and instead saw an expression.

1 error
make: *** [jshint] Error 2
```

**Comment by jcbrand** [comment]
Add `src/build-mobile-no-jquery.js` to JSHINTEXCEPTIONS in line 20 of `Makefile`.

**Comment by julian-d** [comment]
That worked, thanks!
Do you merge the mobile no jquery build into master?

**Comment by jcbrand** [comment]
No, I didn't merge it.
