### ISSUE TITLE
Desktop Notification focus window

### ISSUE THREAD

**Issue by julian-d** [jcbrand/converse.js#653]
Hi,
it would be great if the notifications where linked to the chat window. It can be done with notification.onclick

http://stackoverflow.com/questions/27324996/how-can-i-add-simple-link-in-html5-desktop-notification

**Comment by jcbrand** [comment]
When I click on a notification, then it takes me to the browser in which converse.js is running. I'm not sure what exactly else you're looking for. Chat windows are not linkable, so it's not clear to me what else could be done here.

If you have an idea, you're welcome to mention it here or to make a pull request.

**Comment by julian-d** [comment]
On Chrome Mac OS nothing happens if i click on the notification. (Also tested on conversejs.org)

**Comment by jcbrand** [comment]
Sorry, but I'm not aware of anything specifically I can do about it.
