### ISSUE TITLE
online users count

### ISSUE THREAD

**Issue by amanzur** [jcbrand/converse.js#656]
Converse does not show the online user count in minimized view on first page load. 

![contacts](https://cloud.githubusercontent.com/assets/5274197/15856482/8f6ee50a-2cad-11e6-8d9f-8da7bec01e09.png)

However it starts to show the correct number of online users, if we start to use the chat client and them minimize it. 

![contacts2](https://cloud.githubusercontent.com/assets/5274197/15856552/0edc5f20-2cae-11e6-9f37-aab76652cf61.png)

I am not sure if it is the intended behavior or have been overlooked. 

If we change the following code , we can get the intended behavior. 

```javascript
initialize: function () {
                    this.render();
                    converse.on('initialized', function () {
                        converse.roster.on("add", this.updateOnlineCount, this);
                        converse.roster.on('change', this.updateOnlineCount, this);
                        converse.roster.on("destroy", this.updateOnlineCount, this);
                        converse.roster.on("remove", this.updateOnlineCount, this);
                    }.bind(this));
                },
```

We will have to call updatedOlineCount() function from our initialization function. 

```javascript
initialize: function () {
                    this.render();
                    this.updateOnlineCount(); 
                    converse.on('initialized', function () {
                        converse.roster.on("add", this.updateOnlineCount, this);
                        converse.roster.on('change', this.updateOnlineCount, this);
                        converse.roster.on("destroy", this.updateOnlineCount, this);
                        converse.roster.on("remove", this.updateOnlineCount, this);
                    }.bind(this));
                },
```

If you would like to make the change I can submit a pull request.

**Comment by jcbrand** [comment]
Thanks for the bug report @amanzur, please make a pull request with your change and I'll merge it.
