### ISSUE TITLE
WebSocket prebind ?

### ISSUE THREAD

**Issue by jayesbe** [jcbrand/converse.js#659]
Im trying to use WebSockets rather than BOSH.  I also want to totally control the users ability to login.  Based on the examples I can easily create a BOSH session on the server and pass the JID, RID, and SID into the response OR I can use the prebind_url to return the same info.  However for WebSockets I can't use the CandyChat XMPP prebind example.  

Is it possible to create a WebSocket client (server side), fetch the SID, JID, RID from the client and pass that into the response similar to the CandyChat BOSH example ?

**Comment by jcbrand** [comment]
You can't prebind with websocket connections. BOSH allows prebinding because it uses tokens for authentication, but BOSH is HTTP-specific, it doesn't work over websockets.

**Comment by jayesbe** [comment]
So at the moment its not feasible to control a users connection. Users must login manually?

**Comment by jcbrand** [comment]
It depends. You could develop your own token system, but you'd need to develop a custom authentication module for your XMPP server and you would need something like the [prebind_url](https://conversejs.org/docs/html/configuration.html#prebind-url) setting, but which returns your own tokens and for establishing a websocket connection, not a BOSH connection.

**Comment by jayesbe** [comment]
Couldn't I establish a web socket connection on the server ( say when a user logs in on my site ) to the openfire server and return the tokens embedded in the response so they are available for the Converse initialization?

**Comment by jcbrand** [comment]
What tokens? Prebind tokens are BOSH-based and don't work with websocket.

**Comment by jayesbe** [comment]
Ah ok. Aside from that though. Is there a possibility of initiating a web socket connection from the server then transferring that connection to the browser in some way?

**Comment by jcbrand** [comment]
> You could develop your own token system, but you'd need to develop a custom authentication module for your XMPP server and you would need something like the prebind_url setting, but which returns your own tokens and for establishing a websocket connection, not a BOSH connection.
