### ISSUE TITLE
Add avatar support before user names in user list

### ISSUE THREAD

**Issue by rubytastic** [jcbrand/converse.js#66]
It would be nice if the user list would have an option ( userlist_avater = true ) for adding avatar images in the user list.
Image source could be easy set like /users/get_avatar/1 for easy integration into existing app

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/17920781-add-avatar-support-before-user-names-in-user-list?utm_campaign=plugin&utm_content=tracker%2F194169&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F194169&utm_medium=issues&utm_source=github).

<bountysource-plugin>

**Comment by jcbrand** [comment]
This won't be done. If anybody would like this, they can do it in a 3rd party plugin.
