### ISSUE TITLE
No report of connection problems, small timeouts

### ISSUE THREAD

**Issue by avic-ufmg** [jcbrand/converse.js#661]
jabme.eu is a server that stayed with connection problems or unavailable for almost 48 hours. During this period users of their account were mostly getting "connection refused" erros or long timeouts for operations.

There are two issues here:
1. conversejs did not report any error as (for example) Pidgin did. What happened in conversejs was: open site; fill login form; see "connecting" image; after a few seconds the form was reset, without apparent reasons. Users could try again, but it would never show them the server problem.
2. conversejs seems to have too small timeouts for login related operations. This was discovered by using another client (Pidgin) to use jabme.eu accounts. While, at the same time, Pidgin gave either connection refused errors (password errors with correct passwords being sent) or a unavailable error (which happened faster than the connection refused ones). When Pidgin waited for longer periods to give the wrong password errors, conversejs did not wait. This looks like a problem of small than needed timeouts.

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/35252283-no-report-of-connection-problems-small-timeouts?utm_campaign=plugin&utm_content=tracker%2F194169&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F194169&utm_medium=issues&utm_source=github).
</bountysource-plugin>

**Comment by jcbrand** [comment]
This code has recently been reworked.
