### ISSUE TITLE
report more info between clients and server, specially ip client

### ISSUE THREAD

**Issue by mckaygerhard** [jcbrand/converse.js#662]
the chat its great, i have it integrated in roundcube..

could be possible t (or if i have someting worng) that the client report more info (mostly the ip lient) to the server and others?

**I mean: in pidgin, using right click over some contact, i used "show contact information" and if the contac are using converse , the info are very limited to name id, client name id and domain, as contrary if the user contact are using pidgin or something other xmpp chat client, the info its more complete!**

**Comment by jcbrand** [comment]
I'm not sure where Pidgin looks for that information, so I don't know where it would have to be set.

**Comment by mckaygerhard** [comment]
not only pidgin, also spark and others, well its a great idea, i'll
seach for the xmpp number of standart if there any!

if report the priority and id, also can report the ip client! a great
idea for chat support!

2016-06-17 10:51 GMT-04:00, JC Brand <notifications@github.com>:
> I'm not sure where Pidgin looks for that information, so I don't know where
> it would have to be set.
>
> ---
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/jcbrand/converse.js/issues/662#issuecomment-226790223


-- 
Lenz McKAY Gerardo (PICCORO)
http://qgqlochekone.blogspot.com
