### ISSUE TITLE
room persistence issue

### ISSUE THREAD

**Issue by hamdijmii1992** [jcbrand/converse.js#663]
I successfuly create a new room with converse js , but when I reloaded the page my room doesn't exist yet.
There are 2 screenshots which describe my issue
![img1](https://cloud.githubusercontent.com/assets/13905213/16155705/ecca350a-34b0-11e6-8239-886d2fb648f0.png)
![img2](https://cloud.githubusercontent.com/assets/13905213/16155706/eccbb574-34b0-11e6-9bc7-be01c21e888e.png)

**Comment by jcbrand** [comment]
Click on the wrench icon of the room, then the room's configuration form will appear. In there you can set the room to be permanent.

**Comment by hamdijmii1992** [comment]
thanks :+1:

**Comment by hamdijmii1992** [comment]
sorry @jcbrand can I add a users when I create a new room ??

**Comment by jcbrand** [comment]
No, but you can invite users to a room. Look at the top right of the room, there is an input where you can type their JIDs.

**Comment by hamdijmii1992** [comment]
@jcbrand , But when I write w JID for some users the app don't trigger the invit message.
It didn't trigger anything !!
