### ISSUE TITLE
Offline status is not getting reflected on logout

### ISSUE THREAD

**Issue by rajeebta** [jcbrand/converse.js#665]
Offline status is not getting reflected on logout when both users chat windows are open and one user logs out without closing the chat window.

Setup:
using prebind connection using bosh url with below converse settings.

```
        bosh_service_url: 'https://domain.com/http-bind/', 
        keepalive: true,
        message_carbons: true,
        play_sounds: true,
        roster_groups: true,
        show_controlbox_by_default: true,
```

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/35453575-offline-status-is-not-getting-reflected-on-logout?utm_campaign=plugin&utm_content=tracker%2F194169&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F194169&utm_medium=issues&utm_source=github).

<bountysource-plugin>

**Comment by jcbrand** [comment]
If the one user is still logged in somewhere else (in another tab, or another chat client), then they are still online, and won't be shown as offline in converse.js.

**Comment by rajeebta** [comment]
When one user clicks on the logout, all his chat windows gets closed and gets logged off. Openfire status also shows online. I guess offline status is not getting send to other users when clicks on logout when the users chat window is open. Otherwise users status is getting changed to offline immediately and is reflected to other user.

**Comment by mckaygerhard** [comment]
same behabiour with ejabeerd 2.1.13 and converse.js into the rouncube
plugin using php prebind from candy chat

2016-06-24 5:52 GMT-04:00, rajeebta <notifications@github.com>:
> When one user clicks on the logout, all his chat windows gets closed and
> gets logged off. Openfire status also shows online. I guess offline status
> is not getting send to other users when clicks on logout when the users chat
> window is open. Otherwise users status is getting changed to offline
> immediately and is reflected to other user.
>
> ---
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/jcbrand/converse.js/issues/665#issuecomment-228305465


-- 
Lenz McKAY Gerardo (PICCORO)
http://qgqlochekone.blogspot.com

**Comment by saganshul** [comment]
@rajeebta @mckaygerhard @jcbrand I am not able to reproduce the bug. Can you help me out here?
