### ISSUE TITLE
requirejs-tpl-jcbrand CDN template loading issues

### ISSUE THREAD

**Issue by joe-liquid** [jcbrand/converse.js#666]
I am trying to load the converse HTML templates through a CDN instead of a local directory. I have tried CloudFront and CacheFly and get the same errors with Underscore. All my other Underscore templates in my application load fine with these CDNs, so it is making me think this is an issue around requirejs-tpl-jcbrand. Has anybody else successfully loaded the Converse templates through a CDN? Is there anything I need to change in Converse config to allow me to do this? I am getting 200s on all the Converse templates so it seems to me like it is an issue with requirejs-tpl-jcbrand and Underscore. All the other Converse static files load fine from a CDN. I am using require to load the Converse dependencies. 

<img width="860" alt="screen shot 2016-06-27 at 13 47 31" src="https://cloud.githubusercontent.com/assets/6525914/16380320/4e0fe3f4-3c6e-11e6-8554-ea971b84068a.png">

**Comment by joe-liquid** [comment]
When the Underscore lib is not uglified as in the screenshot I uploaded before I am getting text is undefined. 

<img width="873" alt="screen shot 2016-06-27 at 14 07 17" src="https://cloud.githubusercontent.com/assets/6525914/16380755/c90bb09a-3c70-11e6-930d-9e85a734834a.png">

**Comment by jcbrand** [comment]
Did you come right? Sorry, no idea what the problem is here...

**Comment by joe-liquid** [comment]
As I described. This is happening when i try to load try to load the converse HTML templates through a CDN instead of a local directory. All the information is in the top comment. I believe this is an issue with requirejs-tpl-jcbrand.

**Comment by jcbrand** [comment]
I read everything you wrote, however it doesn't give me a clue as to what the issue might be.

**Comment by joe-liquid** [comment]
I would like to load the templates via a CDN like my other Underscore templates. I am unable to load the Converse templates like my others in my Backbone application. This is the issue. Have you loaded the templates through a CDN before?

**Comment by jcbrand** [comment]
The templates have variables in them, are you aware of that?

You should be loading `dist/templates.js`, not the individual templates, are you doing that?

Since recently there's a CDN for converse.js, but I haven't been using it much personally.

Here's the file you need: https://cdn.conversejs.org/1.0.4/dist/templates.js

**Comment by joe-liquid** [comment]
We are using version 0.10.1 as we have a custom integration and need to do more work to before we can update to the latest version. I can see templates.js in the builds directory for this so I will look at loading this instead of the templates individually. Thanks for the tip!
