### ISSUE TITLE
User as member role is not connected to chatroom

### ISSUE THREAD

**Issue by nikksbagul** [jcbrand/converse.js#668]
Hello, i set up an openfire 3.9.3 server and converse js 1.0.3 for client side and i get this problem.
User has room member permission in openfire room. 
I'm not connecting to chat room. I'm getting this issue.
`<body xmlns="http://jabber.org/protocol/httpbind"><presence xmlns="jabber:client" from="test_nikhil@test.droanatest/rahul" to="rahul@droanatest/db51a9f4" type="error"><x xmlns="http://jabber.org/protocol/muc"><history/></x><error code="404" type="wait"><recipient-unavailable xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"/></error></presence></body>`

If user has room owner permission in openfire room then user can be connected to chat room. Please give me any solution.

**Comment by jcbrand** [comment]
Sorry, I don't know what the problem is here. Seems to be an OpenFire configuration issue, perhaps your room is members-only and the user you're trying to enter with is not in the members' list?

**Comment by nikksbagul** [comment]
Please check my OpenFire configuration

![room_setting](https://cloud.githubusercontent.com/assets/16437505/18903917/3a31c4a2-8579-11e6-9b7b-c34864b6f8d5.png)
![roompermission](https://cloud.githubusercontent.com/assets/16437505/18903921/3fda31aa-8579-11e6-9be8-beabbfd0849e.png)

I'm not connecting to chat room. I'm getting this issue.

```
<body xmlns='http://jabber.org/protocol/httpbind' ack='8173648'><presence from="room01@chm.droanatest
/chm_cmp_02" to="chm_cmp_02@droanatest/azw11rg6v6" type="error" xmlns="jabber:client"><x xmlns="http
://jabber.org/protocol/muc"><history/></x><error code="404" type="cancel"><item-not-found xmlns="urn
:ietf:params:xml:ns:xmpp-stanzas"/></error></presence></body>
```
If user has room owner permission in openfire room then user can be connected to chat room.

**Comment by jcbrand** [comment]
I think the JID for your room is incorrect. You tried to join `room01@chm.droanatest`.  It should probably be `room01@conference.chm.droanatest`. Check the MUC domain setting in OpenFire.

**Comment by nikksbagul** [comment]
My MUC domain setting is correct. I'm creating new service as 'chm' in OpenFire.
