### ISSUE TITLE
Not able to load old data.

### ISSUE THREAD

**Issue by Anubh** [jcbrand/converse.js#670]
Currently I am not able to load old data for my chat, I have 500+ connection in my channel, I am able to see current chat data but as I am doing re-login, I am not able to see my old data. Is there any limit of connections in channel should I limit or any limit of local storage should I focus on.
I am able to see my data in database but It is not visible in chatbox, Can you give me any clue how can I ignore local storage and just load data from server.

**Comment by jcbrand** [comment]
You need to enable [XEP-313 MAM](https://xmpp.org/extensions/xep-0313.html) for your XMPP server and then properly configure converse.js, see the [message_archving](https://conversejs.org/docs/html/configuration.html#message-archiving) configuration option.
