### ISSUE TITLE
No way to assign affiliations to users

### ISSUE THREAD

**Issue by rblin081** [jcbrand/converse.js#671]
XMPP supports different affiliations for chat users (Owner; Admin; Member; Outcast; None). There currently isn't a way to assign affiliations when joining a room, or change that of a current room member.

**Comment by jcbrand** [comment]
There are ways, you can type `/help` inside a chat room to see the available commands.

https://github.com/jcbrand/converse.js/blob/0c393cf286ff9afed4e3369bb7d0a52d4f2b406a/src/converse-muc.js#L408

No doubt it could still be improved upon, and there's no UI yet.
