### ISSUE TITLE
UI config options

### ISSUE THREAD

**Issue by mikemarsian** [jcbrand/converse.js#672]
I would love to be able to configure some basic UI aspects of how the chat window looks and behaves, instead of relying on CSS (which may break in future versions). Specifically, I would like to be able to:

1) change the height, width and title of the chat window
2) turn on/off the following elements: occupants column, server announcements window, invite functionality, control window

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/36243751-ui-config-options?utm_campaign=plugin&utm_content=tracker%2F194169&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F194169&utm_medium=issues&utm_source=github).
</bountysource-plugin>

**Comment by jcbrand** [comment]
Looking at this again, I think this is out of scope for how I see converse.js evolving.

That said, I'd be willing to review a pull request if anyone wants to implement UI configuration.
