### ISSUE TITLE
Apply template changes into release

### ISSUE THREAD

**Issue by michaeljohneduave** [jcbrand/converse.js#673]
I'm sorry if I missed this on the documentation. Whenever I `make dist` and include the converse.min.js file, the changes don't seem to apply. But I can see the changes on the dev.html.

I also included the templates.js from the dist folder and It still didn't work.

How do you apply changes into release? :)

**Comment by jcbrand** [comment]
If I understand correctly, your problem is that converse.min.js is not being included in your git repo?

The converse.min.js file is ignored by git because it's in the `.gitignore` file. Just remove it from that file, then you can add it to your git repo.
