### ISSUE TITLE
Allow configuration of time format (24h/12h)

### ISSUE THREAD

**Issue by dl8bh** [jcbrand/converse.js#675]
it would be great to be able to configure converse.js to use 24h time format instead of 12h format.

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/36600616-allow-configuration-of-time-format-24h-12h?utm_campaign=plugin&utm_content=tracker%2F194169&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F194169&utm_medium=issues&utm_source=github).

**Comment by t0kieu** [comment]
Or make that functionality more complex, for example time format can be defined per language.
