### ISSUE TITLE
What function is called when loss internet connection or disconnect to XMPP?

### ISSUE THREAD

**Issue by docaohuynh** [jcbrand/converse.js#676]
Dear Jcbrand!
Would you show me what function is called when disconnected to XMPP.
When disconnect I see my log is:

```
POST https://mideasvn.com:3280/http-bind net::ERR_CONNECTION_REFUSED
request id 10.1 state changed to 4
ERROR: request id 10.1 error 0 happened
request errored, status: 0, number of errors: 1
_throttledRequestHandler called with 1 requests
request id 11.1 posting
request id 11.1 state changed to 1
```
thanks!

**Comment by jcbrand** [comment]
You can set [auto_reconnect](https://conversejs.org/docs/html/configuration.html#auto-reconnect) to `true`, then converse.js will automatically reconnect when the connection drops.

Alternatively you can call `converse.reconnect()` yourself, but this is on the protected "closured" `converse` object, so you can only do this inside a converse.js plugin.

For exemple, it gets called here: https://github.com/jcbrand/converse.js/blob/88d21425018332b3351f0958ee6bc684514cf56d/src/converse-core.js#L416

Here's more info on writing a plugin: https://conversejs.org/docs/html/development.html#writing-a-converse-js-plugin
