### ISSUE TITLE
Auto open chat with buddy

### ISSUE THREAD

**Issue by beherit** [jcbrand/converse.js#679]
It's possible to automatic open chat with some JID? I try to use this code but it doesn't work:

```
converse.listen.on('connected', function (event) {
    var chatbox = converse.chats.open('buddy@domain.com')
    chatbox.open();
});
```

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/37216406-auto-open-chat-with-buddy?utm_campaign=plugin&utm_content=tracker%2F194169&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F194169&utm_medium=issues&utm_source=github).

<bountysource-plugin>

**Comment by jcbrand** [comment]
I think that should work, is `buddy@domain.com` in your roster? You don't have to call `chatbox.open()`, `converse.chats.open` should open the chat box already.

**Comment by beherit** [comment]
I don't have this contact on roster but after I added it I still have the same problem.

**Comment by jcbrand** [comment]
What version of converse.js are you using? What object gets returned when you call `converse.chats.open`?

**Comment by beherit** [comment]
I use CDN  so I think is the latest version. After call ``converse.chats.open`` returned object is empty. I enabled debug and in Chrome console I see:
```
ERROR: Could not get roster item for JID buddy@domain.com
```
I have this contact on roster (but it should work even I don't have it on roster).

**Comment by jcbrand** [comment]
> but it should work even I don't have it on roster

Converse.js doesn't let you chat with people not on your roster.

**Comment by beherit** [comment]
Okey, I understand but it doesn't matter that I have contact on roster or not - calling ``converse.chats.open`` not open chat box.

**Comment by jcbrand** [comment]
If you still see the error `ERROR: Could not get roster item for JID buddy@domain.com`, then the contact is not in your roster.

**Comment by beherit** [comment]
Still doesn't work, in console logs I see that event "roster" and "roster Cached" is not called.

**Comment by jcbrand** [comment]
What is the CDN URL that you're using?

**Comment by beherit** [comment]
I use https://cdn.conversejs.org/dist/converse.nojquery.min.js

**Comment by jcbrand** [comment]
ok, I don't know what the problem is, I'll have to investigate some time.

**Comment by jcbrand** [comment]
@beherit can you please try with Converse.js 3.0.0?

**Comment by beherit** [comment]
Amazing, now its works :) Thank You!
