### ISSUE TITLE
Clearing the session fails randomly because of invalid regex

### ISSUE THREAD

**Issue by Martinique** [jcbrand/converse.js#681]
I had random problems logging out of my ejabberd server and finally traced the problem to improper use of regular expressions. The issue seems to be here:
```javascript
  // Clear browserStorage for specific collection.
  _clear: function() {
    var local = this.store, itemRe;

    if (typeof this.name.startsWith === "function" && this.name.startsWith('+')) {
      itemRe = new RegExp("^\\" + this.name + "-");
    } else {
      itemRe = new RegExp("^" + this.name + "-");
    }
```
Both cases fail completely when **this.name** contains special regex characters such as "++" in the middle of the string. The whole string should be escaped properly for use in a regex, something like this:
```javascript
  // Clear browserStorage for specific collection.
  _clear: function() {
    var local = this.store, itemRe;

    itemRe = new RegExp("^" + this.name.replace(/[\-\[\]\/\{\}\(\)\*\+\?\.\\\^\$\|]/g, "\\$&") + "-");
```

**Comment by jcbrand** [comment]
This doesn't look like converse.js code. I guess it's from one of its dependencies.

**Comment by Martinique** [comment]
OK, I found it in your Backbone.browserStorage: https://github.com/jcbrand/Backbone.browserStorage/blob/master/backbone.browserStorage.js

**Comment by jcbrand** [comment]
Thanks @Martinique, would you mind making a pull request in backbone.browserStorage?

**Comment by Martinique** [comment]
Done.
