### ISSUE TITLE
Add "Send" button to input box in chat dialog window

### ISSUE THREAD

**Issue by MurzNN** [jcbrand/converse.js#682]
Will be good to see visible "Send" button to input box in dialog window, for activate send message operation via mouse, without keyboard. Sometimes on Google Chrome when I press "Enter" (without Alt, Ctrl, Shift pressed) - it goes to new line instead of sending message, so there are no way to send message.

**Comment by MayankPratap** [comment]
@jcbrand  I want to work on this issue.

**Comment by jcbrand** [comment]
There's already someone working on it in #796

**Comment by novokrest** [comment]
@jcbrand Hi! I think this issue can be closed
