### ISSUE TITLE
Show messages number

### ISSUE THREAD

**Issue by PegasusGo** [jcbrand/converse.js#686]
Hello,

Is it possible to show how many messages did we receive for each friend on the chat?

Thanks

**Comment by jcbrand** [comment]
Do you mean all messages or only unread messages?

**Comment by PegasusGo** [comment]
All messages yes, like in Facebook or twitter

**Comment by jcbrand** [comment]
AFAIK Twitter only shows unread messages.

So you'd like to see ALL messages that were ever received from a user?

 That would mean making a MAM query to the XMPP server to return all archived messages (assuming that all exchanged messages were archived). More info here: http://xmpp.org/extensions/xep-0059.html#count

Not something that can be done out of the box.
