### ISSUE TITLE
change JID to website nickname

### ISSUE THREAD

**Issue by PegasusGo** [jcbrand/converse.js#687]
Hello,

On the chat of my website, friends have this username : "nickname@mydomainname.com"
but I want to remove "@mydomaine.com" to leave just "nickname" 

How can I do it ?

Thanks

**Comment by jcbrand** [comment]
Add the following line here: https://github.com/jcbrand/converse.js/blob/600f98afcbd2a23c5506f916f1a61a4378c19fcf/src/converse-rosterview.js#L614

```'fullname': Strophe.getNodeFromJid(item.get('jid')),```

**Comment by PegasusGo** [comment]
But Im using Conversejs's CDN, I dont have any scripts about Conversejs. Just the PHP prebind and conversejs footer configuration

**Comment by jcbrand** [comment]
You can write a [converse.js plugin](https://conversejs.org/docs/html/development.html#writing-a-converse-js-plugin) which overrides the `render` method of  `RosterContactView`. Put the plugin code in a separate JS file and then load it after the CDN file.
