### ISSUE TITLE
Build a friend roster

### ISSUE THREAD

**Issue by PegasusGo** [jcbrand/converse.js#692]
Hello

Im using Conversejs with Ejabberd
but how can I create a SQL query with PHP (im using Mysql database) to create a friend system for my social network? I don't know where I can write it because Im using the CDN of Conversejs , so there is no scripts on my server, just the php prebind and conversejs configuration scripts

Thanks

**Comment by jcbrand** [comment]
I don't know of any way you can do this with Ejabberd, but for Prosody there is an add-on module [mod_http_roster_admin](https://modules.prosody.im/mod_http_roster_admin.html) which lets you delegate the roster management to an external service (such as your own website).

This will however require more work than just a few SQL queries (which would in any case not be sufficient).
