### ISSUE TITLE
Change JID to nickname

### ISSUE THREAD

**Issue by PegasusGo** [jcbrand/converse.js#693]
Hello,

On the chat of my website, friends have this username : "nickname@mydomainname.com"
but I want to remove "@mydomaine.com" to leave just "nickname"

How can I do it ? Because Im using CDN of conversejs and I don't have any conversejs files.
I have the contact request function but if I remove "@mydomainname.com" , can I add a contact with his nickname?

Thanks

**Comment by jcbrand** [comment]
You know full well this is a duplicate of #687
