### ISSUE TITLE
The option - "notification_icon" 

### ISSUE THREAD

**Issue by sashad** [jcbrand/converse.js#694]
The option "notification_icon" has to be used in all "var n = new Notification ... " !

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/38041879-the-option-notification_icon?utm_campaign=plugin&utm_content=tracker%2F194169&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F194169&utm_medium=issues&utm_source=github).
</bountysource-plugin>

**Comment by marncz** [comment]
I'd like to work on that issue

**Comment by jcbrand** [comment]
@marncz Ok, this should be very easy. It's simply a matter of replacing `logo/conversejs.png` with `_converse.notification_icon` in [src/converse-notification.js](https://github.com/jcbrand/converse.js/blob/master/src/converse-notification.js).

It's a good idea to do `make dev` before you start, to install all development libraries. Then you can serve and load the `dev.html` file to test any changes you make.

**Comment by marncz** [comment]
@jcbrand it's more a matter of getting familiar with the project, running my instance and the development process :)

thanks for the info!
