### ISSUE TITLE
Limit number of displayed conversations

### ISSUE THREAD

**Issue by Darkman75ful** [jcbrand/converse.js#699]
Hello, I would like to limit the number of displayed conversations on conversejs to 1, chatrooms included. And I would like to keep focus on this conversation even if another user is talking to me.
So I would like to disable auto-opening conversations and display the number of unread messages next to the contact name.

I tried some stuff in jQuery but it didn't work.

Thanks.

**Comment by jcbrand** [comment]
You're not going to get far with jQuery.

Converse.js uses Backbone Models and Views, and these are the things you'll need to concern yourself with, not jQuery. You'll have to write a plugin for converse.js which overrides the current functionality. Totally doable, but not simple.
