### ISSUE TITLE
Cannot read property 'get' of undefined

### ISSUE THREAD

**Issue by magnetik** [jcbrand/converse.js#702]
Hi,

When refreshing my site where converse is installed too quickly, my XMPP server answers 403 when doing the POST request (the OPTIONS request works). 

It's failing at the line 33295 of converse.js : `if (group.get('state') === converse.CLOSED) {`

So the plugin stays with the text "Disconnected", even when `auto_reconnect` is on

Thanks

**Comment by jcbrand** [comment]
This seems familiar with a bug I fixed some time ago. What version are you using?

**Comment by magnetik** [comment]
2.0.0

**Comment by jcbrand** [comment]
Check your XMPP server's logs, perhaps they give some indication why the server returns 403. Make sure to turn on DEBUG-level logging for your server.

**Comment by magnetik** [comment]
Yep I have to check if something is wrong with my server. It seems that it's happening when I refresh quickly after a connection. 

But I would expect converse to acknowledge the error, and try to reconnect (maybe ?)

**Comment by jcbrand** [comment]
Unfortunately the reconnection code is difficult to get right and therefore buggy. Use at own risk.
