### ISSUE TITLE
Show list of rooms user is currently in

### ISSUE THREAD

**Issue by TheRolfFR** [jcbrand/converse.js#705]
Hello, I would like to know if there's a way to display only rooms where e are participant ? because on my conversejs chat, in the "room" tab, I can can see all rooms

**Comment by jcbrand** [comment]
No, it such a thing doesn't exist, however I want to add such functionality for [inverse.js](https://github.com/jcbrand/inverse.js) in the coming weeks, could then also be used in converse.js.

**Comment by vishnu-sreenivasan** [comment]
Hi, any update on this feature?

**Comment by smitbose** [comment]
@jcbrand I can't understand this feature exactly. If I'm not wrong, we close a room means we're leaving the room. That means all opened tabs are rooms of which we are currently occupants. I don't seem to understand the use case right here.

**Comment by jcbrand** [comment]
@smitbose The goal is to show a list of chatrooms the user is currently participating in, in the "Rooms" tab of the ControlBoxView.

**Comment by jcbrand** [comment]
This is included in the inVerse release.
