### ISSUE TITLE
white content after submited password on chatrooms 

### ISSUE THREAD

**Issue by Darkman75ful** [jcbrand/converse.js#706]
I have a white content when joining a protected room (with password), is it normal? They are lacking a function that would display the content when password is entered correctly.

**Comment by jcbrand** [comment]
No this is normal. Please provide debug information from your browser console or something else for me to work with, otherwise I can't help.

**Comment by sander85** [comment]
Hi!

How is this normal? When the correct password is entered then divs with classes .chat-area and .occupants both have style="display: none" - successful login should remove this style but currently it doesn't. I'm using Firefox.

**Comment by jcbrand** [comment]
Sorry, I meant to say it's NOT normal. I edited my previous post.
