### ISSUE TITLE
CSS issues? when trying to add new contact

### ISSUE THREAD

**Issue by hinesmr** [jcbrand/converse.js#709]
Good afternoon,

I'm having an issue in the attached screenshot:

![chat](https://cloud.githubusercontent.com/assets/966394/19748994/132fb45c-9bab-11e6-8036-1df47e426cbb.png)

I use the latest git master (as of a few days ago). I do have some other bootstrap/jquery mobile components in my web application that might be conflicting with Converse's styling.

Can you point me in the right direction?

**Comment by jcbrand** [comment]
Look in the relevant Sass files. Most of the relevant styles are probably in [_controlbox.scss](https://github.com/jcbrand/converse.js/blob/master/sass/_controlbox.scss).

Read also the theming documentation: https://conversejs.org/docs/html/theming.html

If you find a bug or something that can be improved, please make a pull request, and I'll merge.

**Comment by hinesmr** [comment]
@jcbrand I'm finding that this works in Chrome, but not in Firefox. (It also works on mobile).
