### ISSUE TITLE
controlbox clicks stop responding after auto_reconnect

### ISSUE THREAD

**Issue by hinesmr** [jcbrand/converse.js#712]
The following sequence of events is very reproducible. I'm happy to set a breakpoint somewhere in Firebug if you can tell me what to look for.
1. Initialize converse.js with auto_reconnect = true
2. Force an auto-reconnect by stopping the network or the jabber server and then bring it back.
3. Wait for the browser notification that the reconnect occured (the controlbox will refresh too).
4. Now, attempt to click on someone and chat with them -- no chat box opens

If you logout manually, and then log back in, opening the chat does start working again, but that wouldn't not be ideal....

Ideas?

**Comment by jcbrand** [comment]
Sounds like the event subscribers are no longer registered or the DOM elements on which they were registered were replaced. Something like that.

Perhaps the fix is as simple as calling `delegateEvents` on the RosterView at the right time/place.

While using converse.js myself day-to-day I also identified problems with reconnection (which is why I mentioned recently that reconnection is buggy and not yet ready for prime-time):

- MUC chat room messages are no longer received
- All users in the roster are shown offline

I haven't seen what you reported, but that might just be because I didn't try to open a new chat.

Working on reconnection has so far proven to be difficult and time-consuming, which means it constantly gets neglected because I don't find the time for it (and nobody's paid me so far to work on it).

**Comment by hinesmr** [comment]
Acknowledged. =) (I also had the same experience of all roster users appearing offline).

Thanks for the hard work so far. Like many others, I'm looking towards converse.js to become an integral part of my business.

In the meantime, I'll go forth and login()/logout() manually to get a stable, working solution and then later come back and look at contributing some PRs when I get spare time.

**Comment by jcbrand** [comment]
Thanks @hinesmr. Pull requests are always welcome.

**Comment by hinesmr** [comment]
@jcbrand So, I have a long list of PRs that I would love to make, but the problem I'm having (and this issue is a good example) is that for people like me, there are multiple levels of indirection going on here that are buried in your head but not easy to unwrap. 

What I really need is one or more detailed architecture diagrams that map out the relationships between backbone.js, converse.js, strophe.js, moment.js, underscore.js, and jquery.

All of these levels of indirection are extremely hard to debug for someone like me that's new to the project. I have no idea where to set breakpoints and there's no obvious way to reinitialize the DOM in such a way that I could only re-initialize converse from scratch within the same window to begin debugging the problems that I am experiencing when an exception is thrown or what have you.

Is there any chance you could either
1) Provide a way to COMPLETELY re-initialize converse.js (and thus strophe by dependency) without reloading the page?
2) Come up with a set of documentation that clearly lays out the relationships between all of the above metioned javascript libraries?

**Comment by hinesmr** [comment]
For example, for 1) above, I have this awful heavy-handed approach (which does work, thanks to prebind being so fast) which completely destroys the converse.js DOM objects and javascript objects and re-creates them all from scratch. That MIGHT allow me to debug converse.js and fix bugs, but without a number of architecture diagrams, I'm really just shooting in the dark. All of the javascript libraries are just way too asynchronous to be able to know where to start.

**Comment by jcbrand** [comment]
I made some commits. Should be fixed now.

> 1) Provide a way to COMPLETELY re-initialize converse.js (and thus strophe by dependency) without reloading the page?

There are API methods for logging out and logging in (I think you do this already?).

> 2) Come up with a set of documentation that clearly lays out the relationships between all of the above metioned javascript libraries?

JQuery is for DOM manipulation.
moment.js provides a better interface for handling dates and times.
Underscore is a utility library providing all kinds of utility methods.
Backbone.js is used to model the data as Models and Collections and to render Views for this data.
Strophe.js maintains the XMPP session, is used to build XMPP stanzas, to send them and to register handlers for received stanzas.

And then converse.js is an application that uses the above. Specifically it uses Backbone to model the data and to create views that render the UI and it uses Strophe to manage the XMPP session and to send and receive stanzas.

That's as much as I can say for now. I'll see whether I can update the developer docs a bit more with this info.

**Comment by hinesmr** [comment]
@jcbrand Thank you, sir. I'll give your commit a try.

In the meantime: logout/login via prebind is unstable. By setting a listener on the "disconnected" event and then logging out and subsequently logging back in, the controlbox ends up different states of disarray. I'll open another issue for that if the commits you just made don't solve the problem.

Before the commit you pushed today, I ended up heavy-handedly solving this by destroying the DOM objects and reloading the converse.js javascript itself from scratch.
