### ISSUE TITLE
offline user group

### ISSUE THREAD

**Issue by camaran** [jcbrand/converse.js#719]
Add an option for group offline user to a simbolic group: offline Users where all offline users are.
When the user go online go in the correct group

**Comment by jcbrand** [comment]
The chat filter can be used to filter users by chat state (online, busy, away, offline).

The groups code is relatively complex and depends on the roster groups that are received from the XMPP server. Mixing in to this the idea of chat states is not really feasible. So, sorry but not going to do this.
