### ISSUE TITLE
not open room

### ISSUE THREAD

**Issue by camaran** [jcbrand/converse.js#723]
i use this code
````    
<script>
        require(['converse'], function (converse) {

        converse.plugins.add('chatme', { 
       initialize: function () { 
           converse.listen.on('logout', function (ev) { 
               window.location.href = "https://chatme.im"; 
               }); 
           } 
       }); 

        converse.initialize({
        allow_muc_invitations: false, 
       allow_contact_requests: false, 
       muc_nickname_from_jid: false, 
       authentication: 'anonymous', 
       auto_login: true, 
       auto_join_rooms: [{'jid': 'piazza@conference.chatme.im', 'nick': ''}], 
       notify_all_room_messages: ['piazza@conference.chatme.im'], 
       jid: 'anonymous.chatme.im', 
 bosh_service_url: 'https://bind.chatme.im/', 
       keepalive: true, 
       sounds_path: 'core/sounds/', 
       play_sounds: true, 
       strict_plugin_dependencies: false, 
       notification_icon: 'background/icon.png', 
show_controlbox_by_default: true, 
          
            });
        });
    </script>
```` 
but not open the room, it's a bug of last version, 2.0.0 work.
You can try here https://chatme.im/chat/conversejs/?r=piazza@conference.chatme.im

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/39122289-not-open-room?utm_campaign=plugin&utm_content=tracker%2F194169&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F194169&utm_medium=issues&utm_source=github).

**Comment by camaran** [comment]
you can see the difference:
- https://chatme.im/chat/conversejs/?cdn=1&version=2.0.0&r=piazza (work)
- https://chatme.im/chat/conversejs/?cdn=1&version=2.0.1&r=piazza (not work)

**Comment by camaran** [comment]
i think depends from bookmarks function that is not available for anonymous but conversejs try to

**Comment by jcbrand** [comment]
This problem should now be fixed in the master branch.

**Comment by camaran** [comment]
https://chatme.im/chat/conversejs/?version=2.0.1&r=piazza not work

**Comment by jcbrand** [comment]
I checked the link and the room *does* open for me.
