### ISSUE TITLE
XMPP server terminates session due to overactivity (too many requests)

### ISSUE THREAD

**Issue by kevinfaguiar** [jcbrand/converse.js#726]
Hi, 

I'm trying to set up Converse JS with keepalive option to be true, but after 3/4 refreshes or going to other pages in the same domain, it loses the connection.

The Google Chrome log:

> Warning: The "initialized" event has been deprecated and will be removed, please use "connected".
converse.js:17558 Warning: The "initialized" event has been deprecated and will be removed, please use "connected".
converse.js:17558 Status changed to: ATTACHED
converse.js:17558 Attached
converse.js:17558 no requests during idle cycle, sending blank request
converse.js:17558 _throttledRequestHandler called with 1 requests
converse.js:17558 request id 1.0 posting
converse.js:17558 request id 1.0 state changed to 1
converse.js:17558 <body rid="365186429" xmlns="http://jabber.org/protocol/httpbind" sid="5jrim538aw"/>
converse.js:17558 _throttledRequestHandler called with 1 requests
converse.js:17558 _processRequest: first request has readyState of 1
(index):857 sid 5jrim538aw
converse.js:17558 request id 1.1 state changed to 2
converse.js:17558 request id 1.1 state changed to 3
converse.js:12624 XHR finished loading: POST "http://10.22.50.178:7070/http-bind/".sendFunc @ converse.js:12624_processRequest @ converse.js:12639_throttledRequestHandler @ converse.js:12785_onIdle @ converse.js:12423_onIdle @ converse.js:11466flush @ converse.js:10351onConnected @ converse.js:18135onConnectStatusChanged @ converse.js:17883_changeConnectStatus @ converse.js:10708_attach @ converse.js:12169_restore @ converse.js:12201restore @ converse.js:10184attemptNonPreboundSession @ converse.js:19284logIn @ converse.js:19317_initialize @ converse.js:19364_initialize @ converse.js:35968wrappedOverride @ converse.js:14699executeBound @ converse.js:1138bound @ converse.js:1170_initialize @ converse.js:37593wrappedOverride @ converse.js:14699executeBound @ converse.js:1138bound @ converse.js:1170converse.initialize @ converse.js:19396initialize @ converse.js:19430(anonymous function) @ (index):840main @ converse.js:318(anonymous function) @ converse.js:392
converse.js:17558 request id 1.1 state changed to 4
converse.js:17558 removing request
converse.js:17558 _throttledRequestHandler called with 0 requests
converse.js:17558 request id 1 should now be removed
converse.js:17558 request id 1.1 got 200
converse.js:17558 _dataRecv called
converse.js:17558 <body xmlns="http://jabber.org/protocol/httpbind" type="terminate" condition="policy-violation"/>
converse.js:17558 Status changed to: CONNFAIL
converse.js:17558 _doDisconnect was called
converse.js:17558 Status changed to: DISCONNECTED
converse.js:17558 DISCONNECTED

The defs of the plugin on the script:

> require(['converse'], function (converse) {
	    converse.initialize({
	    	debug: true,
	    	bosh_service_url: 'http://10.22.50.178:7070/http-bind/', 
			allow_otr: false,
			allow_registration: false,
			keepalive: true,
			expose_rid_and_sid: true,
			default_domain: '10.22.50.178',
			jid: converse.tokens.get('jid'),
	        i18n: locales['pt-br'], 
	        show_controlbox_by_default: true,
	        roster_groups: false,
			allow_logout: true,
			allow_muc: false,
			allow_contact_requests: false,
			allow_contact_removal: false
	    });
	});

EDIT: It seems the disconnect occurs only if I stay in the page for less than 5 seconds and then go to other page or refresh.

**Comment by jcbrand** [comment]
This is the key piece of information:
` <body xmlns="http://jabber.org/protocol/httpbind" type="terminate" condition="policy-violation"/>`

Apparently the server terminates the connection due to overactivity. See here: https://xmpp.org/extensions/xep-0124.html#overactive

When the BOSH session is set up, check whether a "requests" attribute is specified by your XMPP-Server (or connection manager, if its separate).

If not, then your server is not behaving properly:

> Note: If the connection manager did not specify a 'requests' attribute in the session creation response, then it MUST allow the client to send as many simultaneous requests as it chooses.

Otherwise, if it's specified, then it might be a bug in strophe.js or converse.js

**Comment by kevinfaguiar** [comment]
It was overactivity. Setting XMPP server to ignore overactivity solved the problem, thanks.
