### ISSUE TITLE
Message not being send on Enter press

### ISSUE THREAD

**Issue by kevinfaguiar** [jcbrand/converse.js#728]
Hi,

When I type some text and then press Enter, the message isn't being send. Also, there isn't any error on Chrome console.

**Comment by jcbrand** [comment]
Not enough information in this ticket. Set `debug` to `true` when calling `converse.initialize` and then check for errors.

You can reopen the ticket if you have more debug data to paste here.

**Comment by kevinfaguiar** [comment]
Here is the Chrome console log: 

> converse.js:12624 XHR finished loading: POST "http://10.22.50.178:7070/http-bind/".sendFunc @ converse.js:12624_processRequest @ converse.js:12639_throttledRequestHandler @ converse.js:12791_onIdle @ converse.js:12423_onIdle @ converse.js:11466(anonymous function) @ converse.js:12751
converse.js:17558 request id 2.1 state changed to 4
converse.js:17558 removing request
converse.js:17558 _throttledRequestHandler called with 0 requests
converse.js:17558 request id 2 should now be removed
converse.js:17558 request id 2.1 got 200
converse.js:17558 _dataRecv called
converse.js:17558 <body xmlns="http://jabber.org/protocol/httpbind" ack="388200460"><iq xmlns="jabber:client" type="error" id="8de42e3d-19bc-4c10-800b-899c2d9d4d69:sendIQ" to="kevin.aguiar@10.22.50.178/converse.js-75587971"><error code="501" type="cancel"><feature-not-implemented xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"/></error></iq></body>
converse.js:17558 An error occured while trying to set archiving preferences.
converse.js:17558 B…e.Model {cid: "c14", attributes: Object, collection: child, _changing: false, _previousAttributes: Object…}
converse.js:17558 no requests during idle cycle, sending blank request
converse.js:17558 _throttledRequestHandler called with 1 requests
converse.js:17558 request id 3.0 posting
converse.js:17558 request id 3.0 state changed to 1
converse.js:17558 <body rid="388200461" xmlns="http://jabber.org/protocol/httpbind" sid="8s7ojc5fx3"/>
converse.js:17558 _throttledRequestHandler called with 1 requests
converse.js:17558 _processRequest: first request has readyState of 1
converse.js:17558 _throttledRequestHandler called with 2 requests
converse.js:17558 _processRequest: first request has readyState of 1
converse.js:17558 request id 4.0 posting
converse.js:17558 request id 4.0 state changed to 1
converse.js:17558 <body rid="388200462" xmlns="http://jabber.org/protocol/httpbind" sid="8s7ojc5fx3"><message to="alberto.rocha@10.22.50.178" type="chat" xmlns="jabber:client"><composing xmlns="http://jabber.org/protocol/chatstates"/><no-store xmlns="urn:xmpp:hints"/><no-permanent-store xmlns="urn:xmpp:hints"/></message></body>
converse.js:17558 request id 3.1 state changed to 2
converse.js:17558 request id 3.1 state changed to 3
converse.js:12624 XHR finished loading: POST "http://10.22.50.178:7070/http-bind/".sendFunc @ converse.js:12624_processRequest @ converse.js:12639_throttledRequestHandler @ converse.js:12785_onIdle @ converse.js:12423_onIdle @ converse.js:11466(anonymous function) @ converse.js:11472
converse.js:17558 request id 3.1 state changed to 4
converse.js:17558 removing request
converse.js:17558 _throttledRequestHandler called with 1 requests
converse.js:17558 _processRequest: first request has readyState of 1
converse.js:17558 request id 3 should now be removed
converse.js:17558 request id 3.1 got 200
converse.js:17558 _dataRecv called
converse.js:17558 <body xmlns="http://jabber.org/protocol/httpbind" ack="388200462"/>
converse.js:17558 _throttledRequestHandler called with 1 requests
converse.js:17558 _processRequest: first request has readyState of 1
converse.js:17558 _throttledRequestHandler called with 2 requests
converse.js:17558 _processRequest: first request has readyState of 1
converse.js:17558 request id 5.0 posting
converse.js:17558 request id 5.0 state changed to 1
converse.js:17558 <body rid="388200463" xmlns="http://jabber.org/protocol/httpbind" sid="8s7ojc5fx3"><message to="alberto.rocha@10.22.50.178" type="chat" xmlns="jabber:client"><paused xmlns="http://jabber.org/protocol/chatstates"/><no-store xmlns="urn:xmpp:hints"/><no-permanent-store xmlns="urn:xmpp:hints"/></message></body>
converse.js:17558 request id 4.1 state changed to 2
converse.js:17558 request id 4.1 state changed to 3
converse.js:12624 XHR finished loading: POST "http://10.22.50.178:7070/http-bind/".sendFunc @ converse.js:12624_processRequest @ converse.js:12639_throttledRequestHandler @ converse.js:12791_onIdle @ converse.js:12423_onIdle @ converse.js:11466(anonymous function) @ converse.js:12751
converse.js:17558 request id 4.1 state changed to 4
converse.js:17558 removing request
converse.js:17558 _throttledRequestHandler called with 1 requests
converse.js:17558 _processRequest: first request has readyState of 1
converse.js:17558 request id 4 should now be removed
converse.js:17558 request id 4.1 got 200
converse.js:17558 _dataRecv called
converse.js:17558 <body xmlns="http://jabber.org/protocol/httpbind" ack="388200463"/>

This "bug" occurs after sending many messages in sequence, then refreshing the page. After the refresh, it doesn't send messages anymore.

**Comment by kevinfaguiar** [comment]
Nevermind... After some usage tests, its actually random. Sometimes it just doesn't send the <form> on "Enter" press.

**Comment by jcbrand** [comment]
I never have this problem and use converse.js every day.

**Comment by kevinfaguiar** [comment]
Since nothing is displayed on console even with debug=true, I'm thinking it can be relative to html atribute "type" of textarea. I will do some tests.
