### ISSUE TITLE
Chat Boxes who are minimized, on page reload, appears open

### ISSUE THREAD

**Issue by kevinfaguiar** [jcbrand/converse.js#729]
Hi, 

I'm having the problem in specified in the title. On page reload, the minimized chat boxes appears open. (I'm using keep alive = true)

**Comment by jcbrand** [comment]
What other Javascript do you have loaded in your site?

**Comment by jcbrand** [comment]
I did a quick test myself, indeed looks to be buggy ATM.

**Comment by kevinfaguiar** [comment]
Okay, I will be waiting for a fix, thank you!

**Comment by jcbrand** [comment]
This is now fixed in master.
