### ISSUE TITLE
Controlbox toggle not showing with anonymous login

### ISSUE THREAD

**Issue by camaran** [jcbrand/converse.js#734]
after fix of https://github.com/jcbrand/converse.js/issues/723 you can try

- https://chatme.im/chat/conversejs/?version=2.0.1&r=piazza not ask me the nickname (and for this not show occupants in rrom)
- https://chatme.im/chat/conversejs/?version=2.0.1&r=piazza if i close the room panel i cannot open again
- https://chatme.im/chat/conversejs/?version=2.0.1 not show me the conversejs login panel

if you compare with ?version=2.0.0 you can see that work

**Comment by jcbrand** [comment]
Looking at the configuration of #723, I think the problem might be this: ```auto_join_rooms: [{'jid': 'piazza@conference.chatme.im', 'nick': ''}], ```

You are giving an empty JID. Instead of making it an array of objects, just make it an array of strings and see if that works:

```auto_join_rooms: ['piazza@conference.chatme.im']````

**Comment by camaran** [comment]
ok with https://webchat.chatme.im/?version=2.0.1&r=piazza&n=Thomas work, i must change auto_join_rooms: ['piazza@conference.chatme.im'] for work with and without nickname.

But now if i close room panel how i can see the login panel again?
Try first go https://webchat.chatme.im/?version=2.0.1&r=piazza&n=Thomas and after https://webchat.chatme.im/?version=2.0.1 i must see the login and subscription tab but not

**Comment by jcbrand** [comment]
Try making nick `undefined` or `null` instead of an empty string, if that's easier.

The controlbox toggle seems disappearing seems to be a bug

**Comment by camaran** [comment]
ok for nickname, but for my php script it's easy to change, but i try :-) ok for controlbox bug

**Comment by camaran** [comment]
i try with https://webchat.chatme.im/index2.php?version=2.0.1&r=support but not work and now it's correct

**Comment by jcbrand** [comment]
I took a look at this, and I think one problem is simply that you haven't updated the CSS.

The CSS files also need to be updated, then the controlbox and its toggle will appear.

Secondly, I found a bug concerning the nickname, which caused the user to not get one.

Please try again.

**Comment by camaran** [comment]
when i try make cssmin i have error: no cssmin rule found, can you check?

**Comment by camaran** [comment]
now i think work
