### ISSUE TITLE
Room configuration button not visible

### ISSUE THREAD

**Issue by camaran** [jcbrand/converse.js#735]
with new version i cannot see the room setting icon in my muc room

**Comment by jcbrand** [comment]
You'll only see that icon if you are the owner of the room. If you are logging in anonymously, then you're definitely not the owner of the room (it it's been created previously already).

**Comment by camaran** [comment]
but i'm logged with my username and password

**Comment by jcbrand** [comment]
Create a completely new room and check if you see the settings button.
