### ISSUE TITLE
Translation bug with new release

### ISSUE THREAD

**Issue by PegasusGo** [jcbrand/converse.js#737]
Hello ,

with the new release, my chat is english , before it wasn't 
Is it normal ?

thanks

**Comment by jcbrand** [comment]
Are you using the same browser as always? There is some code to detect the browser language and then sets converse.js's language to that. This code hasn't changed AFAIK.

You can also try setting the language explicitly when you call `converse.initialize` to see what happens then.

**Comment by jcbrand** [comment]
I found the bug. It's fixed in master.

**Comment by PegasusGo** [comment]
Please can you update it on a new release ? thanks :)
