### ISSUE TITLE
 A "url" property or function must be specified Error

### ISSUE THREAD

**Issue by hariks789** [jcbrand/converse.js#739]
Hi,

Still facing  "A "url" property or function must be specified" error when switching back to chats page from another page. Using version 2.0.2

Thanks

**Comment by jcbrand** [comment]
There isn't enough information here for me to do anything.

You'll need to in the least past a full traceback of the error. Also, turn on debug mode and look for any other errors earlier up in the developer console of your browser. Paste them here if you find them.

You'll also need to explain in greater detail what exactly you are doing and whether you have a modified version of converse.js.

**Comment by hariks789** [comment]
Hi, 
What I have is a multi page site with the standard converse.js CDN(https://cdn.conversejs.org/2.0.3/dist/converse.min.js) 
initialized in one of the pages, rendered in a div with id="conversejs"
When I navigate to another tab/page and comes back to the chat page this error occurs.

Warning: The "initialized" event has been deprecated and will be removed, please use "connected".
converse.min.js:244 Warning: The "initialized" event has been deprecated and will be removed, please use "connected".
angular.js:13236 Error: A "url" property or function must be specified
    at q (converse.min.js:244)
    at L.i.url (converse.min.js:244)
    at Function.v.result (converse.min.js:239)
    at L.i.e.sync (converse.min.js:244)
    at L.i.n.sync (converse.min.js:244)
    at L.i.sync (converse.min.js:244)
    at L.i.save (converse.min.js:244)
    at L.i.renderContactsPanel (converse.min.js:257)
    at L.i.renderContactsPanel (converse.min.js:258)
    at L.i.wrappedOverride (converse.min.js:243)

**Comment by jcbrand** [comment]
Please use the unminified version of the code, without the `.min.` part, so it's just `2.03./dist/converse.js`.

Then paste the traceback for that. I can't do much with a traceback for minified code, since all the code is then squashed.

Did you also turn on debug mode?

**Comment by hariks789** [comment]
Same error occurs with unminified version too.
angular.js:13236 Error: A "url" property or function must be specified
    at urlError (converse.js:26890)
    at child.url (converse.js:25677)
    at Function._.result (converse.js:11654)
    at child.Backbone.sync (converse.js:26385)
    at child.Backbone.sync (converse.js:27176)
    at child.sync (converse.js:25420)
    at child.save (converse.js:25631)
    at child.renderContactsPanel (converse.js:33162)
    at child.renderContactsPanel (converse.js:35365)
    at child.wrappedOverride (converse.js:24544)

Yes debug mode is on and there are no prior warnings. Chat works without errors the first time, error occurs when we navigate to another page and comes back to the chats page.

**Comment by jcbrand** [comment]
> Same error occurs with unminified version too.

Yes, as it should. The point why I wanted the unminified version is to have proper line numbers.

> error occurs when we navigate to another page and comes back to the chats page.

When you navigate to the other page, is converse.js loaded and active on that page as well?

Please paste your `converse.initialize` call, so that I can see how you are configuring it.

**Comment by hariks789** [comment]
converse.waitUntilLoaded().done(function () {
         converse.initialize({
              allow_otr: true,
              keepalive: true,
             // authentication:"login",
             // auto_list_rooms: true,
             // bosh_service_url: 'http://ilabs.qburst.com:7070/http-bind/',
             // auto_subscribe: true,
             // muc_nickname_from_jid: true,
             // auto_login:true,
             // jid:'sony@ilabs.qburst.com',
             // password:'qburst'
             // allow_otr: true,
             // keepalive: true,
             // authentication:"login",
             auto_join_rooms: ["abc@servicedesk.ilabs.qburst.com"],
             auto_join_on_invite: true,
             auto_list_rooms: true,
             bosh_service_url: 'http://ilabs.qburst.com:7070/http-bind/',
             // auto_subscribe: false,
             muc_nickname_from_jid: true,
             auto_login:true,
             jid:'sony@ilabs.qburst.com',
             password:'qburst'
         });
      // More custom code could come here...
     });

**Comment by jcbrand** [comment]
Thanks, however you didn't answer my question whether converse.js is loaded in the page when you navigate away from the chat, but it sounds from what you wrote as if this is not the case.

So what I think is happening, is that the keepalive tokens are kept in session storage. You navigate away from the chat and the tokens don't get refreshed because converse.js is no longer loaded.

When you navigate back to the chat page, converse.js tries to reattach to the older session, and then things go wrong. At least something along those lines.

It'll require some further digging to find the actual bug and a solution for it.

However, if you have chat only on one page, then you can try turning off `keepalive` as a workaround. I don't know if that will solve the problem, but it might.

**Comment by Sheharyar566** [comment]
I know this is an old issue but i'm getting the same error... i'm trying to persist the logged session across page loads or refreshes but the same error occurs (it doesn't matter whether i have keepalive to true or not).

Here's my initialize function 
```
            const user = AuthService.getUser();
            const jid: string = `${ user?.id }@av.taxis.plus`;
            const token = this.chatToken ? this.chatToken : this.getChatToken();
            console.log('Initialized chat service');
            if(user?.id && token) {
                // Registering the logout plugin
                this.client.plugins.add('logoutPlugin', {
                    initialize: (props: any) => {
                        console.log('Logout plugin initialized');
                        // Setting the event listener to listen to logout evetns
                        const _converse = props.properties._converse;
                        this.once('chat_logout', () => {
                            _converse.api.user.logout();
                        });
                    }, 
                });

                // Initializing the chat service
                this.client.initialize({
                    websocket_url: 'ws://av.taxis.plus:5443/ws',
                    jid: jid,
                    keepalive: true,
                    discover_connection_methods: false,
                    password: token,
                    auto_login: true,
                    allow_logout: false,
                    whitelisted_plugins: ['logoutPlugin'],
                });
            }
        } catch(e) {
            console.log('Error occured while starting the chat service');
            console.log(e);
        }
```

**Comment by jcbrand** [comment]
@Sheharyar566 See here for an explanation of that error: https://conversejs.org/docs/html/troubleshooting.html#error-a-url-property-or-function-must-be-specified
