### ISSUE TITLE
Show permanent room occupants/participants, like on Slack etc.

### ISSUE THREAD

**Issue by ghost** [jcbrand/converse.js#744]
Hello

Is it possible to have the list of all occupants on rooms and not only people who are connected on these rooms, and its better to see who is connected or not 

If there is no more update on conversejs, I will leave conversejs forever..

Thanks

**Comment by jcbrand** [comment]
> If there is no more update on conversejs, I will leave conversejs forever..

I'll ignore your attempt at blackmail and answer the question in the interest of other people who might be interested in an answer.


It would be possible to show all members of a chat room, and not only those people who are currently online, but it would most likely require server support.

The way to do this is to use affiliations and so-called member lists.
More info here: http://xmpp.org/extensions/xep-0045.html#example-131

There are 3 applicable affiliations ('member', 'owner', 'admin'), so there are 3 lists to be set.
The lists are mutually exclusive, so a user can't have more than one affiliation.

To have permanent room occupants (like in Slack), the XMPP client could show the the users on these list as the permanent members of the room.

There are however some complications with this approach. Mostly to do with whether all room occupants (and not only the owner) are allowed to modify member-lists ([relevant Prosody ticket](https://prosody.im/issues/issue/445)) and whether affiliation changes of users not currently online are broadcasted to current occupants of the room ([relevant Prosody ticket](https://prosody.im/issues/issue/682).

So, doing this well doesn't depend on just the client, but also on the server being used. Also, new room occupants need to be added to the member lists.

This is therefore a large change, requiring lots of changes and coordination with XMPP server development.

**Comment by PegasusGo** [comment]
Thanks for your answer, is it coming soon on conversejs?

**Comment by vcarro** [comment]
Perhaps you can add https://docs.ejabberd.im/developer/xmpp-clients-bots/proposed-extensions/muc-sub/ from ejabberd

**Comment by jcbrand** [comment]
IMO the solution here is to implement MIX, which solves this problem. There is a pending [GSOC proposal](https://wiki.xmpp.org/web/Summer_of_Code_2017#MIX_groupchat_support_in_Converse.js) for this.

**Comment by Majaspic** [comment]
I didnt got you, the problem is solved on the last version of conversejs?
