### ISSUE TITLE
Contact list not showing

### ISSUE THREAD

**Issue by merbin2012** [jcbrand/converse.js#748]
I am new to converse.js, and my new project is integrate this chat application to virtual mall, and we can chat with every one. I have tried two methods.

Methods 1:
   Manually I registered two account in different browser(same computer), so two users are there but no users shown in the contact list. So I tried to manually sent chat request, but no notification is came, always it show pending invitation.

Method 2:  (I want this methods only)
    Users no need to register, that's why we are automatically login to the chat application from our database username and password(successfully login).
I can not able to send request,
Every one can chat in group chat (open chat), but it will work only when I set the password for that group in my openfire server.

Note:
I am not installed any plugin, default plugin only available (search).

my code is shown below
```
            converse.initialize({
					bosh_service_url: 'http://ft-dev-2:7070/http-bind/',
					auto_login: true,
					authentication: 'login',
					jid: "actual_username",
					password: "mywebsiteloginpassword",
					auto_subscribe: true,
					allow_chat_pending_contacts:true,
				}
			);
```

**Comment by jcbrand** [comment]
Honestly, I don't really know what to do here. I don't really understand your issue.
There are many tests for contact requests, and the feature is pretty stable and untouched since a while, so I wonder whether you maybe just gave the wrong JID or something.

If this is still an issue for you, then turn on debugging by setting `debug: true` when calling `converse.initialize` and check the log output in your browser's console. You can paste the output in this ticket.

**Comment by mckaygerhard** [comment]
hi @merbin2012  i guest u are new to xmpp chat, any new user if are not in same group are not "automatically suscribed" to another, as gtalk/gmailchat does, if u not are **mutually** suscribed to another user, u cannot see or chat to this

the only proble i see some time ago in converse was that in some time in startup list does not show, this due the nature of the request, of course if u send so many request to the chat, one of that request will not have the right response..

this happened many times with the converse-plugin in the roundcube mail... so with this clarify, please provide more info based on those facts that i xposed here to u
