### ISSUE TITLE
Converse.js SASL Authentication - Unexpected Exeption

### ISSUE THREAD

**Issue by zane901267** [jcbrand/converse.js#751]
Hey there everyone,

at the moment, i can't connect my Converse.js client to my Openfire 4.1.1 server anymore. Everytime i try to login, Converse tries to connect to my server but disconnects after a few seconds. Here are the error logs from my Openfire server and the Debug logs from my web browser:

Error Log on Openfire:

```
2017.01.06 21:58:38 org.jivesoftware.openfire.net.SASLAuthentication - An unexpected exception occurred during SASL negotiation. Affected session: org.jivesoftware.openfire.http.HttpSession@48266f42 status: 1 address: agoshan.com/q0jo19cdn id: q0jo19cdn presence:
<presence type="unavailable"/>
java.lang.NullPointerException
at org.jivesoftware.openfire.sasl.ExternalClientSaslServer.evaluateResponse(ExternalClientSaslServer.java:60)
at org.jivesoftware.openfire.net.SASLAuthentication.handle(SASLAuthentication.java:324)
at org.jivesoftware.openfire.SessionPacketRouter.route(SessionPacketRouter.java:64)
at org.jivesoftware.openfire.http.HttpSession.sendPendingPackets(HttpSession.java:639)
at org.jivesoftware.openfire.http.HttpSession$HttpPacketSender.run(HttpSession.java:1271)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745) 
```

Debug Log on Browser Console:

```
Warning: The "initialized" event has been deprecated and will be removed, please use "connected". converse.nojquery.min.js:217:8116

Could not restore session. Error message: _restore: no restoreable session.  converse.nojquery.min.js:217:8116

Status changed to: CONNECTING  converse.nojquery.min.js:217:8116
_throttledRequestHandler called with 1 requests  converse.nojquery.min.js:217:8116

request id 1.0 posting  converse.nojquery.min.js:217:8116

request id 1.0 state changed to 1  converse.nojquery.min.js:217:8116

<body rid="899624935" to="agoshan.com" xml:lang="en" wait="60" hold="1" content="text/xml; charset=utf-8" ver="1.6" xmpp:version="1.0" xmlns:xmpp="urn:xmpp:xbosh"/>  converse.nojquery.min.js:217:8116

request id 1.1 state changed to 2  converse.nojquery.min.js:217:8116

request id 1.1 state changed to 3  converse.nojquery.min.js:217:8116

request id 1.1 state changed to 4  converse.nojquery.min.js:217:8116

removing request  converse.nojquery.min.js:217:8116

_throttledRequestHandler called with 0 requests  converse.nojquery.min.js:217:8116

request id 1 should now be removed  converse.nojquery.min.js:217:8116

request id 1.1 got 200  converse.nojquery.min.js:217:8116

_connect_cb was called  converse.nojquery.min.js:217:8116

<body xmlns="http://jabber.org/protocol/httpbind" xmlns:stream="http://etherx.jabber.org/streams" from="agoshan.com" authid="q0jo19cdn" sid="q0jo19cdn" secure="true" requests="2" inactivity="30" polling="5" wait="60" hold="1" ack="899624935" maxpause="300" ver="1.6"><stream:features><mechanisms xmlns="urn:ietf:params:xml:ns:xmpp-sasl"><mechanism>PLAIN</mechanism><mechanism>SCRAM-SHA-1</mechanism><mechanism>EXTERNAL</mechanism></mechanisms><register xmlns="http://jabber.org/features/iq-register"/><bind xmlns="urn:ietf:params:xml:ns:xmpp-bind"/><session xmlns="urn:ietf:params:xml:ns:xmpp-session"><optional/></session></stream:features></body>  converse.nojquery.min.js:217:8116

_throttledRequestHandler called with 0 requests  converse.nojquery.min.js:217:8116

_throttledRequestHandler called with 1 requests  converse.nojquery.min.js:217:8116

request id 2.0 posting  converse.nojquery.min.js:217:8116

request id 2.0 state changed to 1  converse.nojquery.min.js:217:8116

<body rid="899624936" sid="q0jo19cdn"><auth mechanism="EXTERNAL">YXNldGgxODEwMTJAYWdvc2hhbi5jb20=</auth></body>  converse.nojquery.min.js:217:8116

request id 2.1 state changed to 2  converse.nojquery.min.js:217:8116

request id 2.1 state changed to 3  converse.nojquery.min.js:217:8116

request id 2.1 state changed to 4  converse.nojquery.min.js:217:8116

removing request  converse.nojquery.min.js:217:8116
_throttledRequestHandler called with 0 requests  converse.nojquery.min.js:217:8116

request id 2 should now be removed  converse.nojquery.min.js:217:8116

request id 2.1 got 200  converse.nojquery.min.js:217:8116

_dataRecv called  converse.nojquery.min.js:217:8116

<body xmlns="http://jabber.org/protocol/httpbind" ack="899624936"><failure xmlns="urn:ietf:params:xml:ns:xmpp-sasl"><not-authorized/></failure></body>  converse.nojquery.min.js:217:8116

Status changed to: AUTHFAIL  converse.nojquery.min.js:217:8116

Status changed to: DISCONNECTING  converse.nojquery.min.js:217:8116

Disconnect was called because: Authentication Failed  converse.nojquery.min.js:217:8116

_sendTerminate was called  converse.nojquery.min.js:217:8116

_throttledRequestHandler called with 1 requests  converse.nojquery.min.js:217:8116

request id 3.0 posting  converse.nojquery.min.js:217:8116

request id 3.0 state changed to 1  converse.nojquery.min.js:217:8116

<body rid="899624937" sid="q0jo19cdn" type="terminate"/>  converse.nojquery.min.js:217:8116

request id 3.1 state changed to 2  converse.nojquery.min.js:217:8116

request id 3.1 state changed to 3  converse.nojquery.min.js:217:8116

request id 3.1 state changed to 4  converse.nojquery.min.js:217:8116

removing request  converse.nojquery.min.js:217:8116

_throttledRequestHandler called with 0 requests  converse.nojquery.min.js:217:8116

request id 3 should now be removed  converse.nojquery.min.js:217:8116

request id 3.1 got 200  converse.nojquery.min.js:217:8116

_dataRecv called  converse.nojquery.min.js:217:8116

<body xmlns="http://jabber.org/protocol/httpbind" type="terminate" ack="899624937"/>  converse.nojquery.min.js:217:8116

_doDisconnect was called  converse.nojquery.min.js:217:8116

Status changed to: DISCONNECTED  converse.nojquery.min.js:217:8116

DISCONNECTED  converse.nojquery.min.js:217:8116
```

I'm quite sure that i've entered my credentials correctly. This problem occurs since i've upgraded my Openfire server from 4.0.4 to 4.1.1.

Could someone check this out ASAP?

Thanks,

Lucas

**Comment by jcbrand** [comment]
What version of converse.js are you using?

Please set `debug` to `true` when calling `converse.initialize` and then paste the output in the browser console.

**Comment by zane901267** [comment]
I'm using v2.0.4.

My output in the browser console:
`
Warning: The "initialized" event has been deprecated and will be removed, please use "connected". converse.min.js:244:30161
Could not restore session. Error message: _restore: no restoreable session.  converse.min.js:244:30161
Status changed to: CONNECTING  converse.min.js:244:30161
_throttledRequestHandler called with 1 requests  converse.min.js:244:30161
request id 1.0 posting  converse.min.js:244:30161
request id 1.0 state changed to 1  converse.min.js:244:30161
<body rid="1064545105" to="agoshan.com" xml:lang="en" wait="60" hold="1" content="text/xml; charset=utf-8" ver="1.6" xmpp:version="1.0" xmlns:xmpp="urn:xmpp:xbosh"/>  converse.min.js:244:30161
request id 1.1 state changed to 2  converse.min.js:244:30161
request id 1.1 state changed to 3  converse.min.js:244:30161
request id 1.1 state changed to 4  converse.min.js:244:30161
removing request  converse.min.js:244:30161
_throttledRequestHandler called with 0 requests  converse.min.js:244:30161
request id 1 should now be removed  converse.min.js:244:30161
request id 1.1 got 200  converse.min.js:244:30161
_connect_cb was called  converse.min.js:244:30161
<body xmlns="http://jabber.org/protocol/httpbind" xmlns:stream="http://etherx.jabber.org/streams" from="agoshan.com" authid="28bv774taj" sid="28bv774taj" secure="true" requests="2" inactivity="30" polling="5" wait="60" hold="1" ack="1064545105" maxpause="300" ver="1.6"><stream:features><mechanisms xmlns="urn:ietf:params:xml:ns:xmpp-sasl"><mechanism>PLAIN</mechanism><mechanism>SCRAM-SHA-1</mechanism><mechanism>EXTERNAL</mechanism></mechanisms><register xmlns="http://jabber.org/features/iq-register"/><bind xmlns="urn:ietf:params:xml:ns:xmpp-bind"/><session xmlns="urn:ietf:params:xml:ns:xmpp-session"><optional/></session></stream:features></body>  converse.min.js:244:30161
_throttledRequestHandler called with 0 requests  converse.min.js:244:30161
_throttledRequestHandler called with 1 requests  converse.min.js:244:30161
request id 2.0 posting  converse.min.js:244:30161
request id 2.0 state changed to 1  converse.min.js:244:30161
<body rid="1064545106" sid="28bv774taj"><auth mechanism="EXTERNAL">YXNldGgxODEwMTJAYWdvc2hhbi5jb20=</auth></body>  converse.min.js:244:30161
request id 2.1 state changed to 2  converse.min.js:244:30161
request id 2.1 state changed to 3  converse.min.js:244:30161
request id 2.1 state changed to 4  converse.min.js:244:30161
removing request  converse.min.js:244:30161
_throttledRequestHandler called with 0 requests  converse.min.js:244:30161
request id 2 should now be removed  converse.min.js:244:30161
request id 2.1 got 200  converse.min.js:244:30161
_dataRecv called  converse.min.js:244:30161
<body xmlns="http://jabber.org/protocol/httpbind" ack="1064545106"><failure xmlns="urn:ietf:params:xml:ns:xmpp-sasl"><not-authorized/></failure></body>  converse.min.js:244:30161
Status changed to: AUTHFAIL  converse.min.js:244:30161
Status changed to: DISCONNECTING  converse.min.js:244:30161
Disconnect was called because: Authentifizierung gescheitert  converse.min.js:244:30161
_sendTerminate was called  converse.min.js:244:30161
_throttledRequestHandler called with 1 requests  converse.min.js:244:30161
request id 3.0 posting  converse.min.js:244:30161
request id 3.0 state changed to 1  converse.min.js:244:30161
<body rid="1064545107" sid="28bv774taj" type="terminate"/>  converse.min.js:244:30161
request id 3.1 state changed to 2  converse.min.js:244:30161
request id 3.1 state changed to 3  converse.min.js:244:30161
request id 3.1 state changed to 4  converse.min.js:244:30161
removing request  converse.min.js:244:30161
_throttledRequestHandler called with 0 requests  converse.min.js:244:30161
request id 3 should now be removed  converse.min.js:244:30161
request id 3.1 got 200  converse.min.js:244:30161
_dataRecv called  converse.min.js:244:30161
<body xmlns="http://jabber.org/protocol/httpbind" type="terminate" ack="1064545107"/>  converse.min.js:244:30161
_doDisconnect was called  converse.min.js:244:30161
Status changed to: DISCONNECTED  converse.min.js:244:30161
DISCONNECTED
`

**Comment by jcbrand** [comment]
Ok, so what's happening is that your XMPP server now advertises that it supports SASL EXTERNAL as an authentication mechanism.

SASL EXTERNAL is used to log in with a client x.509 SSL certificate and it has highest priority in Strophe.js.

Did you ever see a popup from your browser asking you to choose a certificate?

In any case, the EXTERNAL auth fails, which is why you get disconnected.

There are two things you can do to fix this. Either you can disable SASL EXTERNAL AUTH in your OpenFire settings or you can disable support for it in Converse.js.

I've written down how to change the SASL auth settings for OpenFire 3.10.3, I assume it's similar for for 4.1.1. You can read that here: https://opkode.com/blog/strophe_converse_sasl_external/#configure-openfire-s-system-properties

To whitelist which SASL mechanisms Converse.js supports, read the section "Whitelisting the supported SASL auth mechanisms" in this blog post: https://opkode.com/blog/strophe_custom_sasl_auth/#whitelisting-the-support-sasl-auth-mechanisms

You might as well read both blog posts in their entirety to get an understanding of what's involved.

**Comment by zane901267** [comment]
Hey there,

so, the thing is, i've never configured my server for authentication trough external sasl. I don't know why converse tries to connect this way. Must be some of the "new features" of Openfire 4.1.x.
I've changed my Openfire configuration, Converse works now. 

Thanks,
Lucas

**Comment by jcbrand** [comment]
In earlier versions of 4.x SASL EXTERNAL didn't work (and might have been disabled). I wrote the ticket on their bug tracker to inform them of this.

That's one side of the story, the other side is that Strophe.js/Converse.js added support for SASL EXTERNAL only relatively recently.

So it's these things coming together which caused this.

Perhaps Converse.js should be configured to disable SASL EXTERNAL by default, to avoid situations like this. I'll keep it in mind.

**Comment by proton5000** [comment]
@zane901267 , please help me
that you changed in openfire ???

**Comment by jcbrand** [comment]
All the information you need is in the linked to ticket #753 and the blog posts it links to.

**Comment by zane901267** [comment]
@proton5000 i've added the following string in my openfire configuration:

`sasl.mechs ANONYMOUS,PLAIN,DIGEST-MD5,CRAM-MD5,JIVE-SHAREDSECRET`

At the moment, it seems that only Plain Authentication is possible on my system, maybe i've to change some more settings on my openfire server.

**Comment by jcbrand** [comment]
@zane901267 You might want to check whether SASL SCRAM-SHA-1 can be turned on in OpenFire (I would expect so). That would be preferable to PLAIN.

**Comment by proton5000** [comment]
guys I have earned
I did the following:
in the admin panel openfire
1) [screen_1](http://i.piccy.info/i9/1ad890b5108f90a5f43cee7d559bf169/1484295317/324550/1108247/Screenshot_1.jpg)
2) [screen_2](http://i.piccy.info/i9/b56d34b645e6b08ea0c5ad70788f80a4/1484295436/314312/1108247/Screenshot_2.jpg)
3) [screen_3](http://i.piccy.info/i9/bb4abc4b9e74314423c72f9e6deda979/1484295498/368642/1108247/Screenshot_3.jpg)

and in converse 
converse.initialize({
            bosh_service_url: 'https://ec2-54-213-237-72.us-west-2.compute.amazonaws.com:7443/http-bind/',
            debug: true,
            keepalive: true,
            message_carbons: true,
            play_sounds: true,
            roster_groups: true,
            show_controlbox_by_default: true,
            connection_options: {
                'mechanisms': [
                    converse.env.Strophe.SASLMD5,
                    converse.env.Strophe.SASLPlain
                ]
            },
        });
    });
it helped me, and I hope this will help you

**Comment by jcbrand** [comment]
Thanks for sharing @proton5000
