### ISSUE TITLE
CDN is not up to date with 2.0.4

### ISSUE THREAD

**Issue by janmuennich** [jcbrand/converse.js#752]
The CDN files under /2.0.4 (e.g. https://cdn.conversejs.org/2.0.4/dist/converse.nojquery.min.js) are not up to date with version 2.0.4.

I noticed that locales are not working and found out that commit 5b944f9e5fed7f0b9ae451cbad8e838c473ac76e is not included in the /2.0.4/dist file.

The files under /dist seem to be version 2.0.4 although.

**Comment by jcbrand** [comment]
You're right, it was still pointing to the 2.0.3 tag, thanks for informing me.

I've now updated the tag and regenerated the files, so it should be fixed now.

Managing all the different versions for the CDN is turning out to be tricky, I'll try to think of ways to automate or at least streamline it.
