### ISSUE TITLE
Per-user or per-room unread messages indicator

### ISSUE THREAD

**Issue by OlegVoytuk** [jcbrand/converse.js#754]
For example: 
I have 2 friends in chat, Olga and Jon. Right now i chating with Jon, but Olga sent me two messages and i don't what to read they. Can i see number of unread messages from Olga after i update the page?
Or can i send some messages in "unread list"?
P.S. sorry for my english

**Comment by jcbrand** [comment]
Converse.js currently doesn't have a per-user or per-room unread messages indicator and doesn't keep track of unread messages.

I might be adding such a feature in the coming weeks/months since it's required for a project I'm working on.

**Comment by thatguyyoulove** [comment]
Just want to throw in my support for this. I'm also really interested in Inverse (which I assume is what you were referring to) for an enterprise application I currently support which uses Converse. I haven't gotten a chance to dive too deep into the source yet due to deadlines and the Windows Makefile being broken, but would be interested in contributing. I did eventually get the project to compile using the new Windows Subsystem for Linux so hopefully I'll have time soon to look into this.

**Comment by jcbrand** [comment]
I don't really understand why this is a desired feature in Converse.js. From what I can tell this isn't necessary.

You always have chat boxes for users so you either see the message appear or if the chat box is minimized then there is already an unread messages counter.

I *do* want to implement this for inverse, but that's handled as a different project with its own issue tracker.

**Comment by jcbrand** [comment]
I'm therefore closing this.

**Comment by Majaspic** [comment]
If i am offline and I send a message to an offline friend, he will never see my message. If he have received 10 messages from 10 persons its the same issue. 

We need unread messages counter :p

**Comment by jcbrand** [comment]
> If i am offline and I send a message to an offline friend, he will never see my message. If he have received 10 messages from 10 persons its the same issue.

How can you send a message if you're offline?

Also, my understanding is that whether or not a user sees a message sent while he was offline is dependent on the XMPP server and not on the client.

It's the XMPP server's job to keep the message until that user comes online and then to deliver that message.

See here: https://xmpp.org/extensions/xep-0160.html

**Comment by Majaspic** [comment]
Yes but unread messages counter is needed if there is multiple messages sent by multiple users to one offline user , rounded counter  notification I mean

**Comment by jcbrand** [comment]
Why? I still don't understand why. Once the messages are delivered, chat boxes will open to show them and if the chat boxes are minimized they will have unread messages notifications.

I don't know what a "rounded corner notification" is. Can you show an example or screenshot?

**Comment by Majaspic** [comment]
Like this : https://www.noelshack.com/2017-10-1488895583-screenshot-20170307-150440.png

**Comment by Majaspic** [comment]
And this : https://www.noelshack.com/2017-10-1488895739-screenshot-20170307-150832.png

**Comment by jcbrand** [comment]
That would only make sense when the chat boxes are minimized, right?

**Comment by Majaspic** [comment]
No, when no chatbox is open. Look at the chat list only :)

Its useful on responsive I swear

**Comment by jcbrand** [comment]
> No, when no chatbox is open

When new (and also old/delayed) messages are received a new chatbox is opened. So there is always a chatbox opened.

But ok, it might not be visible on mobile. I didn't really think people used converse.js on mobile. There are mobile XMPP clients which are better suited for mobile usage.

**Comment by Majaspic** [comment]
Yes right. Thanks for re opening the issue

I can provide you my responsive code for conversejs if you want

**Comment by jcbrand** [comment]
@Majaspic yes please

**Comment by Majaspic** [comment]
@jcbrand oh sorry I have only the responsive version of conversejs 2.0.0 version, it's an old one

**Comment by jcbrand** [comment]
You should upgrade to 3.0.0. There are known security holes in versions before 2.0.6.

**Comment by Majaspic** [comment]
@jcbrand  Oh ok I will do , thanks! You know, more than 700 users are using the responsive version of conversejs on my site :)

**Comment by Majaspic** [comment]
https://www.noelshack.com/2017-11-1489485758-20170314-110132.png

**Comment by jcbrand** [comment]
inVerse has been released already.

**Comment by fingertips-solutions** [comment]
i have similar problem. for example i have 4 chat groups i want to re order chat groups according to latest message. 
e.g if group 3 received latest message it should be on top... but converse order is alphabetic. can we change that so latest message group should be first one ?

**Comment by fingertips-solutions** [comment]
what if a user get chat messages from 10 people it will open 10 chat boxes ? i am taking about full screen mode ? it will open only one chat group then user will don't know about other 9 messages... i am taking about huge number of groups here say if we have 100 groups and only one will be opened user has to go to each one to check if there are new messages ? there should be and indicator where he can see in list that this group has 2 unread messages.
