### ISSUE TITLE
Add this package in packagist.org

### ISSUE THREAD

**Issue by fabiomontefuscolo** [jcbrand/converse.js#755]
Hello,

Have your package listed in packagist.org would be amazing. PHP developers will be able to install and follow your updates using *composer* (the PHP dependency manager). Do you think it is possible?

Thanks in advance,

**Comment by jcbrand** [comment]
I've accepted your pull request and done the steps you mentioned. Should be set up now. Thanks!

**Comment by marclaporte** [comment]
Already 920 installs!
https://packagist.org/packages/jcbrand/converse.js

Well done JC and Fabio!

**Comment by marclaporte** [comment]
50k installs! https://packagist.org/packages/jcbrand/converse.js

**Comment by marclaporte** [comment]
As a follow-up: https://github.com/conversejs/converse.js/issues/1685
