### ISSUE TITLE
Option to allow chatting with users not in roster

### ISSUE THREAD

**Issue by Ape** [jcbrand/converse.js#760]
I'd like to create a support chat widget using Converse.js. It already almost works for this, but there are some issues.

I can already automatically login with an anonymous account. However, I would like to completely hide the control box (perhaps add `disable_controlbox` configuration) and automatically open a chat window for a specific contact. Opening the chat would be already possible with `converse.chats.open("jid@server");`, but not if the contact is not in the roster. There is `allow_chat_pending_contacts`, but it is not enough. I don't want to add the contact to the roster at all. My XMPP server does allow this and it works with other clients.

**Comment by jcbrand** [comment]
You can hide the roster via CSS, or better yet, you can create a custom build of converse.js that doesn't include the roster at all.

You can create a custom build by modifying `src/converse.js` to remove those plugins you don't need (like `converse-controlbox`) and then running `make dist` to generate new build files in the `dist` directory.

**Comment by jcbrand** [comment]
I've renamed this ticket to make it clear that the enhancement of letting users chat with non-roster users is desired.
