### ISSUE TITLE
Google maps

### ISSUE THREAD

**Issue by OlegVoytuk** [jcbrand/converse.js#768]
On my web-site i use google-maps. This code for example:
require(['googlemaps!'], function() {...})      
It work good.
But when i include converse.j:
require(['converse'], function(converse) {...})
Maps go down and console show me next text:
Uncaught Error: No googlemaps
    at r (converse.min.js:236)
    at h (converse.min.js:236)
    at c (converse.min.js:236)
    at converse.min.js:236

What it can be?
And one thing, when i debugg code, require() it's function requirejs. But when i include converse, debug told me that require() it's function converse.min.js

**Comment by jcbrand** [comment]
Converse.js also uses require.js to load dependencies. In the build, `converse.min.js`, we include [almond.js](https://github.com/requirejs/almond), which is a small require.js API implementation for optimized builds.

What's happening now is that the `require` method from require.js is overloaded with the `require` method from almond.js in `converse.min.js`.

If you're already using require.js, then I would suggest that you don't use the build of converse.js, but instead that you load all the individual converse files and dependencies with your require.js implementation. You can then make your own custom build which contains converse.js and all your other javascript modules.

**Comment by OlegVoytuk** [comment]
Thanks)
