### ISSUE TITLE
My Content Security Policy does not permit eval

### ISSUE THREAD

**Issue by morrisonlevi** [jcbrand/converse.js#779]
We would like to use `converse.js`  but our Content Security Policy does not permit `eval` usage. Would you consider removing `eval`? Is there a particular reason to use `eval` instead of a regular closure?

**Comment by jcbrand** [comment]
Converse.js doesn't use `eval`. Why do you think that it does?

**Comment by morrisonlevi** [comment]
It definitely does; see `https://raw.githubusercontent.com/jcbrand/converse.js/6d2a38a7c12678582cb58c52600c6ae3f6d79039/dist/converse.js`

**Comment by jcbrand** [comment]
`grep -r "eval\>" src/` returns nothing, so converse.js itself doesn't use eval, but perhaps a dependency does.

Looking at `dist/converse.js`, I see `eval` in this function from jQuery:
```
	// Evaluates a script in a global context
	globalEval: function( code ) {
		var script,
			indirect = eval;
		code = jQuery.trim( code );
		if ( code ) {
			// If the code includes a valid, prologue position
			// strict mode pragma, execute code by injecting a
			// script tag into the document.
			if ( code.indexOf( "use strict" ) === 1 ) {
				script = document.createElement( "script" );
				script.text = code;
				document.head.appendChild( script ).parentNode.removeChild( script );
			} else {
				// Otherwise, avoid the DOM node creation, insertion
				// and removal by using an indirect global eval
				indirect( code );
			}
		}
	},```

That might be the culprit, although I don't know in which context it's used or required.
Perhaps you can investigate that further.

I've started work on removing jQuery altogether as a dependency. My initial goal is to have `converse-core.js` completely free of jQuery and then move on to the plugins. I don't expect this work to be done soon however.

**Comment by dbluhm** [comment]
Investigating this issue further, it is still unclear whether the above code is used or where it is being called. However there is at least one instance where `new Function` is definitely called. This call originates from the template system used by Underscore.js (https://github.com/jashkenas/underscore/blob/master/underscore.js#L1588). As Content Security reports `eval` and `new Function` as the same thing, we may have misdiagnosed where the issue was coming from initially.

**Comment by morrisonlevi** [comment]
> As Content Security reports eval and new Function as the same thing, we may have misdiagnosed where the issue was coming from initially.

@dbluhm This is because they have the same security implications; this should also be investigated.

@jcbrand Do you have plans to remove underscore.js usage?

**Comment by dbluhm** [comment]
I'm not sure if this is helpful but stepping through execution, the function `initInviteWidget()` is at least among the first of the functions called that gets blocked by CSP for using `new Function`.

**Comment by dbluhm** [comment]
Without having a complete understanding of what's going on behind the scenes, I simply commented out lines 2054-2056 and everything appears to work as expected without creating obvious problems with CSP.

**Comment by jcbrand** [comment]
@dbluhm That template is used by jquery-typeahead to render auto-complete suggestions when you want to invite someone to a chat room. So removing won't break anything except that feature.

@morrisonlevi In the current master branch underscore.js has been replaced with lodash. I don't think underscore.js is to blame here though, looks to me to be due to jquery-typeahead.

**Comment by jcbrand** [comment]
I've just committed a change which replaced jquery-typeahead with awesomplete, which is smaller and which doesn't rely on jQuery.

Perhaps you can test whether this fixes your issue. Please be aware though that the current master branch contains several breaking changes to the 2.0.x branch.

**Comment by dbluhm** [comment]
@jcbrand Ultimately I'm not perfectly sure where it was happening, but a `_.template` function was being pulled in somewhere that was making use of a `new Function`. With the removal of typeahead (commit d2227c8), however, there are no longer any `new Function`s in dist/converse.js (or elsewhere) and it works fine with the CSP `unsafe-eval` directive not specified as an acceptable script src. Thanks for your help and patience.

**Comment by jcbrand** [comment]
Ok great. Glad we got this sorted then.

**Comment by dbluhm** [comment]
Just for clarification, the most recent commit in master ends up giving this error:
![converse js-error](https://cloud.githubusercontent.com/assets/22032832/22990006/0b93bc44-f375-11e6-987f-548a1630d093.png)

I built using commit d2227c8 and am using that version.

**Comment by jcbrand** [comment]
thanks for the update @dbluhm. Should be fixed now
