### ISSUE TITLE
Some messages won't be received 

### ISSUE THREAD

**Issue by Majaspic** [jcbrand/converse.js#782]
Hello

I'm using ejabberd and conversejs with php prebinding. But sometimes, some messages are not receive from some people. On the database, all archive is there so I don't know what is lacking. Carbon messages are enabled..

We also need unread messages counter, it's very important

thanks for your help

**Comment by jcbrand** [comment]
Sorry, but I can't do anything with what you wrote. When submitting a bug report you need to provide concrete debuggable info or at least detailed steps on how to reproduce the problem.

**Comment by Majaspic** [comment]
Ok I will provide you
unread messages counter will be on next release?

**Comment by jcbrand** [comment]
Maybe.
