### ISSUE TITLE
Improoving MUC occupant list

### ISSUE THREAD

**Issue by Majaspic** [jcbrand/converse.js#783]
The MUC occupant list is not updating on real-time. Some bugs are there, and it could be better if we can see all people on the list and connected people/offline people

**Comment by jcbrand** [comment]
The occupant does update in realtime. If you are aware of cases where it doesn't, then please explain to me how I can reproduce them or see whether you can find debug output in the browser  console (set `debug: true` when calling `converse.initialize`).

Concerning showing offline people, this is only possible if you maintain member-lists for your rooms.

**Comment by Majaspic** [comment]
Hi, 

If I maintain the list then the room will be saved on room tab of my occupants right?

**Comment by jcbrand** [comment]
no, the member-list of the room has nothing to do with whether a room shows under the rooms tab. To do that you need to bookmark the room.

**Comment by Majaspic** [comment]
Oh ok thank you. If my occupants bookmark the rooms, I will see their username on occupant list but offline if they are disconnected , right?

**Comment by jcbrand** [comment]
No, you are still misunderstanding. Bookmarks and the members-list are two different things.

Converse.js doesn't show users not currently in the MUC room. But it could be changed to show users in the members list.
