### ISSUE TITLE
mam retrieval broken since 2.0.6

### ISSUE THREAD

**Issue by mt403** [jcbrand/converse.js#790]
MAM retrieval has always been a mixed thing for me (#545) but since the latest release it has stopped working completely. Reverting back to release 2.0.5 fixes the issue.

I can provide a test account on my server if required.

converse settings:
archived_messages_page_size: 50
websocket (tested bosh as well, same result)

prosody settings:
max_archive_query_results = 50; (default)

software:
Prosody 0.10 nightly build 348
Converse.js 2.0.6

**Comment by jcbrand** [comment]
Yes I also noticed that it's not working for me anymore. Good to know that the breakage was between 2.0.5 and 2.0.6, then I can do a diff.

Another problem is that Converse.js supports a very old version of MAM. I haven't had time to update it.

I'll try to get it fixed for the 3.0 release (which is already a week behind schedule) but I can't promise anything.

**Comment by mt403** [comment]
Thanks for the effort! Regarding the mam thing, are you aware of the fact
that conversations will switch to mam:1 in the near future ?

2017-02-23 10:07 GMT+01:00 JC Brand <notifications@github.com>:

**Comment by jcbrand** [comment]
mam:2 is already out though.

**Comment by mt403** [comment]
What version will Converse Support ?

Am 23.02.2017 3:30 nachm. schrieb "JC Brand" <notifications@github.com>:

**Comment by jcbrand** [comment]
Fixed. I'm not going to update MAM for this release, too much work. Currently converse.js supports mam:0.
