### ISSUE TITLE
Set a new language 

### ISSUE THREAD

**Issue by omerx** [jcbrand/converse.js#792]
I copied the "en" folder to the "tr" folder. I changed the file "converse.json". But it still seems English.

Only Turkish is enough for me. I tried to change "converse.json" in "En" folder. I could not be successful.

`        converse.initialize({
            bosh_service_url: 'http://192.168.0.205:7070/http-bind/', // Please use this connection manager only for testing purposes
			i18n: locales['tr'],
            keepalive: true,
            message_carbons: true,
            play_sounds: true,
            roster_groups: true,
            show_controlbox_by_default: true,
			auto_login:true,
			/*
			nick: 'omer',
			auto_join_rooms: [
                'duyuru@conference.webserver',
            ],
			*/
            notify_all_room_messages: [
                'duyuru@conference.webserver',
            ],
			room: false,
			jid:'omer@192.168.0.205',
			password:'1234'
        });`

**Comment by jcbrand** [comment]
Make a pull request with your turkish translations and I'll help you connect it properly.
