### ISSUE TITLE
Error on installing development environment with $make dev

### ISSUE THREAD

**Issue by saganshul** [jcbrand/converse.js#795]
https://gist.github.com/jcbrand/07878252c63bdf1e20dcf6e25d6099c3

**Comment by jcbrand** [comment]
What operating system are you using? What version of Node.js do you have?

**Comment by saganshul** [comment]
OS - linux(ubuntu)
node v7.5.0 (npm v4.1.2)

**Comment by jcbrand** [comment]
This looks to be just a problem installing an optional dependency `webworker-threads`.

Type `make serve` and then check if you can load converse.js by opening `localhost: 8000/dev.html`

**Comment by saganshul** [comment]
yeah! Its working thanx :)

**Comment by lkraav** [comment]
https://github.com/arlolra/otr/releases seems to be quite antiquated, and it requires an old version of webworker-threads, which doesn't seem to build on anything recent.

`npm install --no-optional` skips it.

**Comment by jcbrand** [comment]
@linkmauve I think this might be the cause of your troubles with building converse.js on Arch.

**Comment by JoeBoxr** [comment]
Hello.

There's still problems compiling on a Windows box with webworker-threads.    npm install --no-optional  doesn't skip it.  Would you have any suggestions?

**Comment by jcbrand** [comment]
I don't use Windows, so I'm waiting for someone to submit a pull request with a fix. See #641
