### ISSUE TITLE
Can not register successfully in ejabberd17.01

### ISSUE THREAD

**Issue by qyidc** [jcbrand/converse.js#800]
I have thought that my server is set up a problem, but the test of other public servers found that the use of converse.js can not be registered users on the ejabberd17.01 , but can be properly registered ejabberd16.09, the error message is: Missing attribute ' Id 'in tag <iq /> qualified by namespace' jabber: client '
Bad-request

**Comment by themaverik** [comment]
@qyidc Can you mention the version of converse js you are using?

**Comment by suchatorg** [comment]
To me it gives me that error in: https://conversejs.org/

**Comment by iamsayantan** [comment]
Hello, I am facing this same issue. I am using ejabberd 17.01 and converse version 3.0.2.

**Comment by jcbrand** [comment]
This is now fixed in master.
