### ISSUE TITLE
require is not defined

### ISSUE THREAD

**Issue by camaran** [jcbrand/converse.js#805]
require(['converse'], function (converse)

with 2.x work, with 3.0.0 i have error require is not defined

you can see here https://webchat.chatme.im/test.php
 the code is this https://conversejs.org/docs/html/quickstart.html#getting-a-demo-up-and-running

**Comment by jcbrand** [comment]
Remove the `require` statement, it's no longer available and it's not needed. Look at the `index.html` or `dev.html` files in the repo for examples.

**Comment by jcbrand** [comment]
I'll update the documentation.

**Comment by camaran** [comment]
hi, thank you now work, i have a problem with plugin 
`            converse.plugins.add('chatme', { 
                initialize: function () { 
                    converse.listen.on('logout', function (ev) { 
                        window.location.href = "//webchat.chatme.im"; 
                    }); 
                } 
            });`
how i must update it?

**Comment by jcbrand** [comment]
```
           converse.plugins.add('chatme', { 
                initialize: function () { 
                    var _converse = this.__super__._converse;
                    _converse.user.logout( function(ev) { 
                        window.location.href = "//webchat.chatme.im"; 
                    }); 
                } 
            });
```

**Comment by camaran** [comment]
not work see here https://webchat.chatme.im/test.php

**Comment by jcbrand** [comment]
I think it must be `_converse.api.user.logout`

**Comment by camaran** [comment]
```
           converse.plugins.add('chatme', { 
                initialize: function () { 
                    var _converse = this.__super__._converse;
                    _converse.api.user.logout( function(ev) { 
                        window.location.href = "//webchat.chatme.im"; 
                    }); 
                } 
            });
```
this?

**Comment by jcbrand** [comment]
You also need to whitelist the plugin, otherwise it won't load.

https://conversejs.org/docs/html/configuration.html#whitelisted-plugins

**Comment by camaran** [comment]
now i have TypeError: this.__super__ is undefined

**Comment by jcbrand** [comment]
Yes, looks like it must be `this._converse` not `this.__super__._converse` because the method being overridden is already on the `_converse` object.

That's a bit confusing. Probably pluggable.js could be updated to make the behavior more consistent.

**Comment by camaran** [comment]
now i have this error TypeError: f.chatboxviews is undefined ou can see https://webchat.chatme.im/test.php

**Comment by jcbrand** [comment]
```            converse.plugins.add('chatme', { 
                initialize: function () { 
                    this._converse.listen.on('logout', function (ev) { 
                        window.location.href = "//webchat.chatme.im"; 
                    }); 
                } 
            });
```
