### ISSUE TITLE
Event listeners registered via `_converse.listen` not being triggered

### ISSUE THREAD

**Issue by camaran** [jcbrand/converse.js#806]
I create e plugin for redirect user to a new page when logout with 2.x version work but not with 3.x

you can see the 2.x version here https://webchat.chatme.im/test2.php and 3.x version here https://webchat.chatme.im/test.php

**Comment by jcbrand** [comment]
Fixed in master. As a workaround for now you can use `_converse.on` instead of `_converse.listen.on`.

Actually the `_converse.listen` API is now no longer really needed and should get deprecated in favor of just using `on`, `off` etc. directly.
