### ISSUE TITLE
Update to Converse.js 3.0.0

### ISSUE THREAD

**Issue by MurzNN** [jcbrand/converse.js#809]
Converse.js release new major version https://github.com/jcbrand/converse.js/releases/tag/v3.0.0 with some bug fixes and new features.

Please update link to it in this plugin. Seems there are no changes in API, so we can only update link to CDN version of js file? And file name have new format:
https://cdn.conversejs.org/3.0.0/dist/converse-no-jquery.js

And maybe we can use some auto-updated url like https://cdn.conversejs.org/dist/converse-no-jquery.js for always use latest version?

Also will be good to have option for change sources from CDN to local downloaded file in roundcube plugin.

**Comment by jcbrand** [comment]
Looks like you made this ticket in the wrong tracker.

BTW, the API is updated. Most of the API is now private and only available to plugins and plugins need to be whitelisted before they can be used.

**Comment by MurzNN** [comment]
Yes, sorry, it is for Roundcube plugin: https://github.com/priyadi/roundcube-converse.js-xmpp-plugin
