### ISSUE TITLE
Update to Moment.js 2.17.1 

### ISSUE THREAD

**Issue by jcbrand** [jcbrand/converse.js#810]
We'd like to upgrade to the latest version of moment.js.

However currently the tests fail when we update to Moment.js 2.17.1 as can be seen here in this Greenkeeper pull request: https://github.com/jcbrand/converse.js/pull/741

**Comment by novokrest** [comment]
I think this issue can be closed because Moment.js 2.18,1 is used now

**Comment by jcbrand** [comment]
True, thanks.
