### ISSUE TITLE
Open only active group chat per page

### ISSUE THREAD

**Issue by umpirsky** [jcbrand/converse.js#813]
I use converse to allow users to chat around different topics, in this example topics are `Session1` and `Session2`, they reside on different urls, so I want each of this groups to open chat for it's own subject.

I initialize converse.js with:

```js
 converse.initialize({
        authentication: 'prebind',
        keepalive: true,
        hide_muc_server: true,
        bosh_service_url: 'http://localhost:7070/http-bind/',
        show_controlbox_by_default: false,
        jid: 'name2@openfire/foo',
        sid: '28gc8z6c31',
        rid: '5596002988',
        auto_join_rooms: [{jid: 'Session1@conference.openfire', nick: 'name2'}]
    });
```

On some other page I do it with same data, but `auto_join_rooms: [{jid: 'Session2@conference.openfire', nick: 'name2'}]`.

The problem is that on this page, I don't want chat for room `Session1` to be opened, just `Session2`. So only one chat window at a time, but they seem to be adding up as I browse the site, joining one by one. Can I limit joining to only one room? Or leave other rooms somehow once I join new group.

@jcbrand How can I control that?

**Comment by jcbrand** [comment]
Currently there isn't a configuration setting to do this.

**Comment by umpirsky** [comment]
I guess if I remove user from a chat room via Openfire API (https://www.igniterealtime.org/projects/openfire/plugins/restapi/readme.html#delete-a-user-from-a-chat-room), this chat windows will dissapear.

I'll try that, thanks.

**Comment by umpirsky** [comment]
@jcbrand It does not work. I wonder why with `auto_join_rooms: [{jid: 'Session2@conference.openfire', nick: 'name2'}]` user is joined as participant at first:

![screenshot from 2017-03-14 13-21-48](https://cloud.githubusercontent.com/assets/208957/23900377/42429c7a-08b9-11e7-8e6a-ae2820dba5d4.png)

 but after second page refresh, it's joined as moderator/owner:

![screenshot from 2017-03-14 13-15-02](https://cloud.githubusercontent.com/assets/208957/23900126/45108652-08b8-11e7-9077-003112f22f23.png)

And I cannot remove him via API afterwards.

Also, I tried to [add user with role to chat room](https://www.igniterealtime.org/projects/openfire/plugins/restapi/readme.html#add-user-with-role-to-chat-room) and remove `auto_join_rooms`, but chat windows are not showing. Is there a way to not join from javascript, but do it from API and have chat windows? Or, control user role when joining via `auto_join_rooms` from js?

**Comment by jcbrand** [comment]
A user will join as `owner` if the room didn't exist beforehand, and as `participant` if the room already exists.

**Comment by umpirsky** [comment]
Looks like you are right, and moderator cannot be removed from group chat.

For some weird reason, I create chat room via API on first page load, then converse joins correctly, but after a page refresh, room is recreated by converse and the old one is gone, maybe because I'm creating room with simple name `$roomName`, and I'm passing `$roomName.'@conference.'.$host` to converse. But again, strange that it does not do it after first load, but only after second.

Thanks for the fast responses.

**Comment by umpirsky** [comment]
@jcbrand I did deeper testing and I can confirm that converse.js is doing some unexpected actions.

What I do is:

- Create user, room and add user to room with role `members` via openfire API from PHP.
- Then, load converse as described above https://github.com/jcbrand/converse.js/issues/813#issue-213858897 with `auto_join_rooms: [{jid: 'collab33@conference.openfire', nick: 'name11'}]`

After first page load I see this in openfire admin:

![screenshot from 2017-03-15 17-57-48](https://cloud.githubusercontent.com/assets/208957/23960877/75336722-09a9-11e7-83b3-682adceb2bec.png)
![screenshot from 2017-03-15 17-58-03](https://cloud.githubusercontent.com/assets/208957/23960876/752ed734-09a9-11e7-8241-6ce68885b151.png)
![screenshot from 2017-03-15 17-58-15](https://cloud.githubusercontent.com/assets/208957/23960875/750448a2-09a9-11e7-8f63-e541c72de832.png)

Then, if I refresh the page, chat room is changed and user is promoted to moderator, this is done through converse.js, because when I remove js, it does not happen, here is how it looks:

![screenshot from 2017-03-15 17-58-33](https://cloud.githubusercontent.com/assets/208957/23960941/a76e7a1a-09a9-11e7-8e94-b029062f1649.png)
![screenshot from 2017-03-15 17-58-43](https://cloud.githubusercontent.com/assets/208957/23960939/a7434782-09a9-11e7-8544-fd202a07db83.png)
![screenshot from 2017-03-15 17-58-55](https://cloud.githubusercontent.com/assets/208957/23960940/a74573d6-09a9-11e7-86f8-f1f0810130c8.png)

What I want to do is to be able to control what chats will be active, and with ths behavior, I cannot remove moderator from room, and cannot deactivate rooms based on what page I am on.

Thanks in advance.

**Comment by jcbrand** [comment]
@umpirsky Take a look at the [converse-singleton.js](https://github.com/jcbrand/converse.js/blob/b07e6291ea4cc465c5160fe4565681a01b848267/src/converse-singleton.js) non-core plugin I added recently.

It makes sure that only one chat is visible at any one time. I use it for the [converse-mobile.js](https://github.com/jcbrand/converse.js/blob/b07e6291ea4cc465c5160fe4565681a01b848267/src/converse-mobile.js#L24) build and whitelist it in [mobile.html](https://github.com/jcbrand/converse.js/blob/b07e6291ea4cc465c5160fe4565681a01b848267/mobile.html#L130).
