### ISSUE TITLE
Images from URLs with query strings aren't being rendered.

### ISSUE THREAD

**Issue by jcbrand** [jcbrand/converse.js#814]
Converse.js renders images from pasted URLs.

However, if the URL contains a query string, then the image doesn't get rendered. This must be because the code that checks a URL to determine whether it points to an image doesn't recognize that this is an image URL.

The solution would be to update that code to take query strings into account.

An example of such an URL which should work, but doesn't:

https://cloud.opkode.com/index.php/apps/files_sharing/ajax/publicpreview.php?x=2872&y=850&a=true&file=screen_shot_2017-03-14_at_09.06.39_720.png&t=9szwpg220warFeY&scalingup=0

**Comment by novokrest** [comment]
Hello, can I take up this task?
If yes, are there any guidelines I have to follow beforehand?

**Comment by jcbrand** [comment]
Hi @novokrest, thanks for your interest, you're welcome to do so.

You can read the developer documentation to help you get started:
https://conversejs.org/docs/html/development.html

Please adhere to the software style guide as given in the dev docs.

**Comment by novokrest** [comment]
@jcbrand Thanks for the answer! Now I read documentation and ready to start looking the code. Could you tell me which folders/files/modules store the logic responsible for sending and displaying images?

**Comment by saganshul** [comment]
@novokrest  You will find a `isImage` funtion in src/utils.js . This function checks that given URL is image or not. 
@jcbrand right?

**Comment by novokrest** [comment]
@saganshul Thank you! That's what I was looking for.

**Comment by jcbrand** [comment]
@saganshul FYI, I updated the `isImage` method to not use jQuery.
