### ISSUE TITLE
font icons base64

### ISSUE THREAD

**Issue by camaran** [jcbrand/converse.js#818]
it's possible to include fontinconse in base64 to fix more and more problem

**Comment by jcbrand** [comment]
What kinds of problems?

**Comment by camaran** [comment]
for example url in css

**Comment by camaran** [comment]
and also bad URI or cross-site access not allowed source in more and more case with wordpress

**Comment by jcbrand** [comment]
I think the solution is for the icons to be hosted by the wordpress host.

**Comment by jcbrand** [comment]
Read here for reasons why it's not a good idea: https://github.com/FortAwesome/Font-Awesome/issues/294

**Comment by camaran** [comment]
yes but now i fixed this https://github.com/jcbrand/converse.js/issues/803 in wordpress plugin :-)

**Comment by jcbrand** [comment]
ok, so solved then?

**Comment by camaran** [comment]
yes yes now is ok but is not better solution :-)
