### ISSUE TITLE
Enabling custom builds (was: Converse without OTR)

### ISSUE THREAD

**Issue by p3drosola** [jcbrand/converse.js#82]
Hi, I noticed the latest version includes a lot of Crypto-js & OTR code.

I don't intend on using any encryption layer other than SSL, so this really bloats my build. Is it an optional dependancy? Can I use converse without OTR?

**Comment by rlanvin** [comment]
Regarding jQuery, I would suggest to permanently remove it from the build, and instead adopt a similar approach to what Boostrap does, which is to add these lines at the beginning of the file:

```
if (typeof jQuery ==  "undefined" ) {
    throw new Error("Bootstrap's JavaScript requires jQuery");
}
```

They have configured Grunt to add it automatically during the build (by using the option `banner`).

It's not unreasonable to assume that a vast majority of the websites will already have jQuery loaded. For those few who don't, it's extremely easy to add one line to load jQuery from a CDN (this can be explained in the doc). It's easier to do that than to have to install the full dev environment and make a custom build to get rid of jQuery.

**Comment by jcbrand** [comment]
That could be added, but right now, if you run `make build` it make various builds of converse.js, including one that doesn't include jQuery
