### ISSUE TITLE
Inconsistency in displaying room features

### ISSUE THREAD

**Issue by smitbose** [jcbrand/converse.js#820]
I was just trying out the use cases of room configuration by a moderator, and created my own chatroom where I changed the room setting from temporary to persistent. This should show in the room features only "persistent". It however shows "persistent" and "temporary" both. 
![screenshot from 2017-03-19 00-23-57](https://cloud.githubusercontent.com/assets/10517141/24075033/38bb73e6-0c3a-11e7-8f74-4599eedc5a14.png)

**Comment by jcbrand** [comment]
Should be fixed now. Could you please double check?

**Comment by smitbose** [comment]
@jcbrand working fine now
