### ISSUE TITLE
L10N - do not cut strings

### ISSUE THREAD

**Issue by Jibec** [jcbrand/converse.js#829]
Hi,

it is not easy to translate strings like this ones: https://github.com/jcbrand/converse.js/blob/master/src/converse-muc.js#L1714

because it gives us a part of string to translate, which may lead to bad translation because of missing context or typography. In french, we want to translate " " by « ». which is impossible as far as I know.
https://github.com/jcbrand/converse.js/blob/9214c81bbcbf7dfcb7868508977c043a9c83badd/locale/en/LC_MESSAGES/converse.po#L592

can we have something like {message}, %1 or at least %s with comment to translate correctly?

thanks for your help

**Comment by linkmauve** [comment]
I didn’t notice this issue when I wrote 561bdbba3515e85ae96d736f0810a0a3145cb3ad, it could probably be closed.

**Comment by jcbrand** [comment]
Thanks
