### ISSUE TITLE
Google Summer of Code: Backup mentor required for 24 to 14 August

### ISSUE THREAD

**Issue by jcbrand** [jcbrand/converse.js#833]
For the first time, I'd like to get Converse.js involved in the Google Summer of Code program. We've already received some pull requests from prospective students and we currently have 2 applications (the deadline is today).

I will be the mentor and will be available to assist the student for the duration of the program, except for a period of a bit less than 3 weeks (24 July to 14 August) during which I will be traveling and without internet connection.

I'm hoping that someone will be willing to volunteer a bit of their time to review pull requests made by the student during this time. Basically what we need is someone who is familiar with the architecture of Converse.js and the coding style, who is willing to look over the student's code and to make suggestions or to answer questions that the student might have.

During this period of 3 weeks where I'm not available, there will be about 2 days (around 7, 8 Aug.) where I will have internet again and during which I'll be able to help out and to respond to any questions from the student or the backup mentor.

Deep domain knowledge of the XMPP work being done for GSoC would be helpful, but not required, since I'll ask someone from the XMPP community to be available for XMPP-related questions. The feature being worked on will either be MIX ([XEP-0369](https://xmpp.org/extensions/xep-0369.html) or #497 OMEMO ([XEP-0384](https://xmpp.org/extensions/xep-0384.html)).

Any help would be greatly appreciated! Volunteers can respond here, or contact me privately (via email or my [contact form](http://opkode.com/contact.html)). **I'm willing to trade my time for yours**, so for someone who is willing to volunteer their time I will do any converse.js related work that matches the amount of time they spent reviewing pull requests.

Anyone who has contributed to converse.js before, or who can demonstrate understanding and proficiency with the code can respond here.

Also CC'ing some previous contributors: @thierrytiti, @floriancargoet, @ichim-david, @knixeur, @1st8

**Comment by 1st8** [comment]
Hey, sorry for the no-feedback situation. 
I didn't want to put anyone off by declining your request due to time constraints and not really doing any work related to XMPP for quite some time now.
Cheers!

**Comment by jcbrand** [comment]
No worries, it was a long shot.

**Comment by knixeur** [comment]
Hi @jcbrand, it's been a while! Sorry to add to 1st8, I'm currently unable to help. I've in my mind to upgrade to a newer version of converse.js on our site so I hope to be able to contribute later.
Congratulations and good luck with gsoc!
