### ISSUE TITLE
converse and converse-mobile

### ISSUE THREAD

**Issue by camaran** [jcbrand/converse.js#839]
It's possibile to have only one build for desktop and mobile and use a new variable setting: mobile: true/false for better manage ?

**Comment by jcbrand** [comment]
I don't think this is something worth pursuing. Part of the reason for making a separate mobile build is to also keep the build file as small as possible. To have one build file for both mobile and desktop will result in a larger file for mobile devices. Additionally it also adds complexity to that build file.

Instead you can simply load a different URL for mobile devices (like we do with m.conversejs.org) via Nginx or Apache.
