### ISSUE TITLE
Persistent muc room creation not working

### ISSUE THREAD

**Issue by notnow123** [jcbrand/converse.js#842]
I am trying to use the converse.js developer API to create a persistent multi-user chatroom.  The room is created, but in the UI under 'features', the room is listed as Temporary.

I am using converse.js from the conversejs.org CDN:

`<script src="https://cdn.conversejs.org/dist/converse.min.js"></script>`

My code is as follows:

```
<script>
converse.plugins.add('larc-join-room', {
    initialize: function () {
    	var _converse = this._converse;
    	console.log(_converse);
    	_converse.on('connected', function (event) { 
  			var nick = $('#username').val().replace(" ", "").toLowerCase() + $('#user_id').val();
        	var roomname = $('#selected-document').val().replace(" ", "").toLowerCase() + '@conference.servername.co.uk'
        	var create_if_not_found = true;
        	_converse.api.rooms.open(
            roomname,
            {'nick': nick, 'auto_configure': true, 'roomconfig': {'persistentroom': true}}, false);
		});
    }
});

converse.initialize({
  bosh_service_url: 'https://servername/http-bind/',
  keepalive: true,
  debug: true,
  authentication: 'prebind',
  jid: $('#jabber_id').val(),
  prebind_url: 'https://servername/larc/get_bosh_data',
  show_controlbox_by_default: true,
  whitelisted_plugins: ['larc-join-room'],
  blacklisted_plugins: [
                'converse-dragresize',
                'converse-minimize',
                'converse-vcard'
            ]
});
</script>
```

Can you help me to fix this issue?  Thanks.

**Comment by jcbrand** [comment]
Seems to work for me. I wonder whether this is server related. What XMPP server are you using?

Can you please check whether you can reproduce the problem with the `conversejs.org` XMPP server?

**Comment by notnow123** [comment]
Thanks for the reply.

I am using ejabberd as my XMPP server.  It is pretty much the default
install on an Ubuntu 16.04 server.

I'll try with the converse.js server as you suggest and report back.

Thanks again.


On 10 Apr 2017 18:27, "JC Brand" <notifications@github.com> wrote:

Seems to work for me. I wonder whether this is server related. What XMPP
server are you using?

Can you please check whether you can reproduce the problem with the
conversejs.org XMPP server?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/jcbrand/converse.js/issues/842#issuecomment-293020051>,
or mute the thread

**Comment by notnow123** [comment]
I meant to say that if I make the room persistent through the settings
dialog of the converse.js UI (by clicking the spanner icon, ticking the
relevant checkbox and then saving changes) the room becomes persistent and
the features text is updated as I would expect.

It just doesn't work through the rooms.open roomconfig route, so I had
discounted a server-side problem.  But I will check.

**Comment by notnow123** [comment]
I can't switch my code to use the conversejs.org server.  I get a certificate does not match error from my BOSH credentials controller when I try to generate tokens for the converse server.

How should I go about debugging this?

Thanks for your help.

**Comment by jcbrand** [comment]
Don't use `prebind`. Instead, register an account on that server via https://conversejs.org.

Then use [auto_login](https://conversejs.org/docs/html/configuration.html#auto-login) together with the `jid` and `password` to automatically log the user in.

Then you can check if a room automatically created is permanent or not.

**Comment by notnow123** [comment]
Having tested this, I can confirm that the same issue occurs with roomconfig not being respected on the conversejs.org server.

I changed my configuration to use the conversejs.org XMPP server after creating an account, and switched authentication to auto_login with my username and password, as advised.  The room that I need is automatically created and the correct nick is implemented as per the plugin code that I have written but the room is temporary and not persistent.

My complete code for initialising converse.js and for creating the MUC chatroom is now as follows:

```
<script>
converse.plugins.add('larc-join-room', {
    initialize: function () {
    	$._converse = this._converse;
    	$._converse.on('connected', function (event) { 
  			var nick = $('#username').val().replace(" ", "").toLowerCase() + $('#user_id').val();
        	var roomname = $('#selected-document').val().replace(" ", "").toLowerCase() + '@conference.conversejs.org'
        	var create_if_not_found = true;
        	$._converse.api.rooms.open(
            roomname,
            {'nick': nick, 'auto_configure': true, 'roomconfig': {'persistentroom': true}}, false);
		});
    }
});

converse.initialize({
  debug: true,
  auto_login: true,
  authentication: 'login',
  jid: 'evbuk@conversejs.org',
  password: 'Atherton1234',
  bosh_service_url: 'https://conversejs.org/http-bind/',
  hide_muc_server: true,
  auto_reconnect: true,
  show_controlbox_by_default: false,
  whitelisted_plugins: ['larc-join-room'],
  blacklisted_plugins: [
                'converse-dragresize',
                'converse-minimize',
                'converse-vcard'
            ]
});
</script>
```
Any advice on a fix for this would be gratefully received.

**Comment by jcbrand** [comment]
@notnow123 I've committed a fix. Please check if it now works for you.

**Comment by notnow123** [comment]
@jcbrand I can confirm that the fix works.  roomconfig is now respected in MUC rooms created through the API.
