### ISSUE TITLE
Open chat box

### ISSUE THREAD

**Issue by dopinder100** [jcbrand/converse.js#844]
I want to integrate XMPP chat into my website. Tried to create just a bare bone chat, where it should auto login and auto open a chat window. It just can auto login, but does nothing after that.

The whole code is as below. Why it does not auto open a chat window? I have white listed the plugin.

    converse.initialize({
        show_controlbox_by_default: true,
        allow_muc: false,
        auto_login: true,
        authentication: 'login',
        jid: 'kelvin@xmpp.mydomainhere.com',
        password: 'kelvin',
        websocket_url: 'wss://xmpp.mydomainhere.com:5280/websocket',
        whitelisted_plugins: ['myplugin']
    });

    console.log("JACKY 000");
	
    converse.plugins.add('myplugin', {
        initialize: function () {
        	   console.log("JACKY 111");
            this._converse.chats.open('jacky@xmpp.mydomainhere.com')

            var msg = converse.env.$msg({
                from: 'kelvin@xmpp.mydomainhere.com',
                to:'jacky@xmpp.mydomainhere.com',
                type:'chat'
            });
            this._converse.send(msg);
        }
    });

    console.log("JACKY ZZZ");

In the developer web console, I can see JACKY 000 and JACKY ZZZ only.

**Comment by jcbrand** [comment]
You're supposed to add the plugin before calling `converse.initialize`.

**Comment by dopinder100** [comment]
I switched the two code blocks.

	console.log("JACKY 000");

    converse.plugins.add('myplugin', {
        initialize: function () {
        	   console.log("JACKY 111");
            this._converse.chats.open('jacky@xmpp.mydomainhere.com');

            var msg = converse.env.$msg({
                from: 'kelvin@xmpp.mydomainhere.com',
                to:'jacky@xmpp.mydomainhere.com',
                type:'chat'
            });
            this._converse.send(msg);
        }
    });

    converse.initialize({
        show_controlbox_by_default: true,
        allow_muc: false,
        auto_login: true,
        authentication: 'login',
        jid: 'kelvin@xmpp.mydomainhere.com',
        password: 'kelvin',
        websocket_url: 'wss://xmpp.mydomainhere.com:5280/websocket',
        whitelisted_plugins: ['myplugin']
    });
	console.log("JACKY ZZZ");

Now, in the developer web console, I can see JACKY 000 and JACKY 111 only. Nothing else happens. I think converse.initialize does not even get run...

**Comment by dopinder100** [comment]
Hi, please... any help here? Thanks.

**Comment by jcbrand** [comment]
Sorry @dopinder100, looks like the API documentation is out of date.

The private API methods must be accessed via `_converse.api`. So you must use `this._converse.api.send` and `this._converse.api.chats.open`.

**Comment by jcbrand** [comment]
Besides that, you also need to wait until converse.js is connected before you can send a message.

So your code needs to look something like this:

```
converse.plugins.add('myplugin', {
    initialize: function () {
        var _converse = this._converse;
        this._converse.api.waitUntil('connected').then(function () {
            this._converse.api.chats.open('jacky@xmpp.mydomainhere.com');
            var msg = converse.env.$msg({
                from: 'kelvin@xmpp.mydomainhere.com',
                to:'jacky@xmpp.mydomainhere.com',
                type:'chat'
            }).c('body').t('hello world');
           _converse.api.send(msg);
        });
    }
});

converse.initialize({
    show_controlbox_by_default: true,
    allow_muc: false,
    auto_login: true,
    authentication: 'login',
    jid: 'kelvin@xmpp.mydomainhere.com',
    password: 'kelvin',
    websocket_url: 'wss://xmpp.mydomainhere.com:5280/websocket',
    whitelisted_plugins: ['myplugin']
});
```
