### ISSUE TITLE
Coverse.js chat on Mobile browser or Phone browser with mobile websites

### ISSUE THREAD

**Issue by hzzg6y** [jcbrand/converse.js#846]
Dear All,

     Please help whether we have any Mobile version of converse.js chat client. Reason being that I want to connect the Desktop  users to chat with users who are on Mobile/phone as well. So that 1-2-1 chat communication on website can increase. Please advice. 

I am already using Jappix chat with Mini version on Website however Mobile version on mobile browser is not work as seamless it is suppose to.. hence user experience is not good. Please advice. 

Thanks

**Comment by jcbrand** [comment]
You can use the mobile build:
https://cdn.conversejs.org/3.0.1/dist/converse-mobile.min.js
https://cdn.conversejs.org/3.0.1/css/converse.min.css
https://cdn.conversejs.org/3.0.1/css/mobile.min.css

See https://m.conversejs.org
