### ISSUE TITLE
Some CSS is broken in Firefox but fine in Chrome. Fix provided inside.

### ISSUE THREAD

**Issue by Semperverus** [jcbrand/converse.js#847]
I have been making some modifications using "Inspect Element" to fix these, and dropping them into a file called theme-fixes.css, then loading that after the converse.min.css and theme.min.css to correct for it. Basically, Firefox is either not inheriting styles properly, or chrome is doing weird stuff that @jcbrand is developing against. I've tested these fixes in both chrome and firefox, and chrome looks identical before and after.

Here are my fixes so far:
```
#conversejs #controlbox #fancy-xmpp-status-select a.change-xmpp-status-message {
    margin-right: 5px;
    margin-top: 5px;
}

#conversejs #controlbox .dropdown dd.search-xmpp {
    width: 100%;
}

.current-xmpp-contact {
    display: block !important;
}
```

This fixes the following:

- The pencil icon in the status change box floats far too much into the upper right corner

- The "Add Contact" box has a width of 0% and makes adding new contacts difficult

- Contact entries are set to "display: inline;" instead of "display: block;" sometimes, and break the list when this happens. Names will either overlap names below them or all names will be displayed side by side instead of in a vertical list.

There's one more I'm trying to fix right now with the ( i ) button next to room names not being aligned. One thing that works for Firefox but not Chrome is to set
```
#conversejs #controlbox #chatrooms dl.rooms-list dd.available-chatroom a.room-info::before {
    position: relative;
    top: 1px;
}
```

I hope this helps.

**Comment by jcbrand** [comment]
Thank you. Can you please make a pull request with the first two fixes?

Concerning the 3rd one, `!important` in CSS rules is harmful and shouldn't be used. Also, it works around the problem instead of finding the underlying cause. The proper solution will be to figure out why they get `display: inline` sometimes, which is admittedly more difficult to do.

**Comment by Semperverus** [comment]
I'd love to, but I unfortunately don't know all the necessary steps in Git
that I'd need to take. I know how to clone and pull, but that's about it.
If I "Git Push" will it clone it to my account here?

**Comment by jcbrand** [comment]
I disabled all non-converse CSS and then tested in Firefox and couldn't reproduce the errors you mentioned. Are you sure it's not your own CSS that's interfering here?

**Comment by Semperverus** [comment]
Correct.

So basically, what I've got set up is a really basic webpage. All I did was
clone your git repo, and then go to the default page and the CSS issues
start up in firefox. Everything is self-hosted, so I'm not linking to
anything off-site from your CDN. Going to conversejs.org doesn't seem to
have these issues somehow, but the instant it gets self-hosted is when it
acts up.

**Comment by Semperverus** [comment]
As a side note, I had to wget your minified scripts from your CDN to
actually get converse to run since I was struggling to get anything to
build (NPM kept eating itself). Without those, it wouldn't run at all. But
this has been an issue for me since way back in the early versions (I
believe I had something as far back as 1.x, and occasionally revisited to
do updates before I automated it last week)

**Comment by ignatdoc** [comment]
Using Firefox 52.0.1 on OS X and all seems fine.

**Comment by Semperverus** [comment]
[Here](http://i.imgur.com/Kar8pHc.png) is what it looks like without my CSS fixes, hosted on my splash page for my chat section on my site. The link on the left with Converse.js at the top of the list leads to the ultra-basic version of the chat client that has none of the navigation in the background or text or anything, just converse.js, and it looks the same. I'm also on the latest firefox if that matters, though this has been a persistent problem.

Here's the source code to the basic page:

```
<html lang="en">
<head>
    <title>Converse.js</title>
    <meta charset="utf-8">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content="Converse.js: An XMPP chat client" />
    <meta name="author" content="JC Brand" />
    <meta name="keywords" content="xmpp chat webchat converse.js" />
    <link type="text/css" rel="stylesheet" media="screen" href="node_modules/bootstrap/dist/css/bootstrap.min.css" />
    <link type="text/css" rel="stylesheet" media="screen" href="css/converse.min.css" />
    <link type="text/css" rel="stylesheet" media="screen" href="css/theme.min.css" />
    <link type="text/css" rel="stylesheet" media="screen" href="css/theme-custom.css" />
    <script src="dist/converse.min.js"></script>
</head>
<body style="background:url(../images/bg.png); background-color: #E8E8E8;">
</body>
<script>
        converse.initialize({
            bosh_service_url: "https://MYWEBSITE.COM/http-bind/",
            default_domain: "MYWEBSITE.COM",
            domain_placeholder: "MYWEBSITE.COM",
            show_controlbox_by_default: true,
            auto_list_rooms: true,
            cache_otr_key: true,
            message_carbons: true,
            play_sounds: true,
            show_send_button: true
        });
</script>
```

**Comment by Semperverus** [comment]
So I made a pull request. Took me a minute to figure out. I thought I was gonna have to go digging through the man pages for the git command, and was not looking forward to committing a few nights to that. Turns out it can all be done in-site here, and github even has a built-in text editor! Yay!

**Comment by jcbrand** [comment]
There's something weird going on here. That anchor tag already has a right margin of 0.3em, so why is it not showing in your screenshot?

**Comment by Semperverus** [comment]
The right margin is fine, it's floating upwards. Vertically. Since you had it in a rigid pixel by pixel defined box, I just changed it to 5px by 5px top and right. Keeps it in exactly the same spot horizontally but pushes it down to where it needs to be vertically. You could make it 0.3em by 0.3em if you like.

Also, it's not showing in the code itself because I have a roster thing selected.

I also have the "Add a contact" box showing as well, as that really bizarre vertical line with the half "add" button.

**Comment by Semperverus** [comment]
Here is what it looks like with my fixes enabled (including the !important one)

![untitled](https://cloud.githubusercontent.com/assets/613225/25231495/e9e8bd70-258c-11e7-8677-761bd8d52fc7.png)

**Comment by Semperverus** [comment]
I figure to repeat this, the easiest way is to clone your repo into a blank new box, start a new instance of apache, clone converse.min.js into the /var/www/converse/dist/ and converse.min.css into /var/www/converse/css/, then copy my basic page (get rid of the bootstrap css, it does nothing and I haven't removed it), and just go from there. It's completely self-contained and stripped down.

This is literally my monthly update script I'm running now, if you want an idea of what I'm doing:

```
#!/bin/sh

#  Base
git pull https://github.com/jcbrand/converse.js

#  Javascript
wget -N -q https://cdn.conversejs.org/dist/converse.min.js -P dist/
wget -N -q https://cdn.conversejs.org/dist/converse-mobile.min.js -P dist/

#  CSS
wget -N -q https://cdn.conversejs.org/css/converse.min.css -P css/
wget -N -q https://cdn.conversejs.org/css/theme.min.css -P css/
wget -N -q https://cdn.conversejs.org/css/mobile.min.css -P css/
wget -N -q https://cdn.conversejs.org/css/converse-muc-embedded.min.css -P css/
```
