### ISSUE TITLE
Auto_reconnect feature failure sometimes

### ISSUE THREAD

**Issue by ignatdoc** [jcbrand/converse.js#849]
How to reproduce:
1. bind credential address to conversejs config with login:pass
2. Load web page, auth will go fine.
3. On slow inet connections when uploading or downloading big file - jabber connection may fail
4. ConverseJS will try to reconnect and stall in this operation even when inet connection stabilizes.

Need to reload page manualy.

Thanks and sorry for my english ;)

**Comment by jcbrand** [comment]
Set `debug` to `true` when calling `converse.initialize` and see if you see any errors in the browser console when this happens. Report them here if you find any.

**Comment by ignatdoc** [comment]
Ok, will do that.
Why my topic about OTR was deleted? There was a report about error from debug mode set...

**Comment by jcbrand** [comment]
Not sure what you're referring to, I didn't delete anything.

**Comment by ignatdoc** [comment]
#848 
Seems you missread what I tried to tell

**Comment by ignatdoc** [comment]
Status changed to: DISCONNECTED  converse.js:46868:17
RECONNECTING  converse.js:46868:17
The connection has dropped, attempting to reconnect.  converse.js:46868:17
.initialize/_converse.showFeedbackNotification@https://someserver.com/_assets/conversejs/dist/converse.js:65966:29
.initialize/_converse.handleFeedback@https://someserver.com/_assets/conversejs/dist/converse.js:66005:21
triggerEvents@https://someserver.com/_assets/conversejs/dist/converse.js:44809:32
triggerApi@https://someserver.com/_assets/conversejs/dist/converse.js:44796:19
eventsApi@https://someserver.com/_assets/conversejs/dist/converse.js:44595:16
Events.trigger@https://someserver.com/_assets/conversejs/dist/converse.js:44786:5
_converse.emit@https://someserver.com/_assets/conversejs/dist/converse.js:46786:9
_converse.initialize/this.giveFeedback@https://someserver.com/_assets/conversejs/dist/converse.js:47125:13
_converse.initialize/this.reconnect<@https://someserver.com/_assets/conversejs/dist/converse.js:47148:13
invokeFunc@https://someserver.com/_assets/conversejs/dist/converse.js:22801:18
leadingEdge@https://someserver.com/_assets/conversejs/dist/converse.js:22811:26
debounced@https://someserver.com/_assets/conversejs/dist/converse.js:22876:20
_converse.initialize/this.onDisconnected@https://someserver.com/_assets/conversejs/dist/converse.js:47188:13
_converse.initialize/this.onConnectStatusChanged@https://someserver.com/_assets/conversejs/dist/converse.js:47228:17
Strophe.Connection.prototype._changeConnectStatus@https://someserver.com/_assets/conversejs/dist/converse.js:41245:17
Strophe.Connection.prototype._doDisconnect@https://someserver.com/_assets/conversejs/dist/converse.js:41287:9
Strophe.Connection.prototype._onDisconnectTimeout@https://someserver.com/_assets/conversejs/dist/converse.js:41954:9
Strophe.Bosh.prototype._hitError@https://someserver.com/_assets/conversejs/dist/converse.js:42882:13
Strophe.Bosh.prototype._onRequestStateChange@https://someserver.com/_assets/conversejs/dist/converse.js:43080:13
  converse.js:46868:17
"error: undefined https://someserver.com/_assets/conversejs/dist/converse.js:65966 - TypeError: _converse.i18n.locale_data is undefined"  converse.js:46868:17
ERROR: User connection callback caused an exception: TypeError: _converse.i18n.locale_data is undefined

**Comment by ignatdoc** [comment]
Then:

InvalidStateError: XMLHttpRequest state must be OPENED.  converse.js:43173
	Strophe.Bosh.prototype._processRequest/sendFunc https://someserver.com/_assets/conversejs/dist/converse.js:43173:17
	Strophe.Bosh.prototype._processRequest/< https://someserver.com/_assets/conversejs/dist/converse.js:43185:21

And when it tries to reconnect i will get this:

Status changed to: CONNFAIL  converse.js:46868:17
.initialize/_converse.showFeedbackNotification@https://someserver.com/_assets/conversejs/dist/converse.js:65966:29
.initialize/_converse.handleFeedback@https://someserver.com/_assets/conversejs/dist/converse.js:66005:21
triggerEvents@https://someserver.com/_assets/conversejs/dist/converse.js:44809:32
triggerApi@https://someserver.com/_assets/conversejs/dist/converse.js:44796:19
eventsApi@https://someserver.com/_assets/conversejs/dist/converse.js:44595:16
Events.trigger@https://someserver.com/_assets/conversejs/dist/converse.js:44786:5
_converse.emit@https://someserver.com/_assets/conversejs/dist/converse.js:46786:9
_converse.initialize/this.giveFeedback@https://someserver.com/_assets/conversejs/dist/converse.js:47125:13
_converse.initialize/this.onConnectStatusChanged@https://someserver.com/_assets/conversejs/dist/converse.js:47243:17
Strophe.Connection.prototype._changeConnectStatus@https://someserver.com/_assets/conversejs/dist/converse.js:41245:17
Strophe.Connection.prototype._dataRecv@https://someserver.com/_assets/conversejs/dist/converse.js:41359:17
Strophe.Bosh.prototype._onRequestStateChange@https://someserver.com/_assets/conversejs/dist/converse.js:43073:13
  converse.js:46868:17
"error: undefined https://someserver.com/_assets/conversejs/dist/converse.js:65966 - TypeError: _converse.i18n.locale_data is undefined"  converse.js:46868:17
ERROR: User connection callback caused an exception: TypeError: _converse.i18n.locale_data is undefined  converse.js:46866:17
_doDisconnect was called

And back to 
Status changed to: DISCONNECTED converse.js:46868:17
RECONNECTING converse.js:46868:17
The connection has dropped, attempting to reconnect. converse.js:46868:17
and etc...

**Comment by jcbrand** [comment]
How do you log in? Manually with username and password? In that case reconnecting will only work when you don't reload the page. If you reload the page, then the password is gone and converse.js cannot attempt to reconnect because it doesn't have your credentials anymore.

Reconnecting works best with something like [credentials_url](https://conversejs.org/docs/html/configuration.html#configuration-variables) or [auto_login](https://conversejs.org/docs/html/configuration.html#auto-login) where it can get the login credentials at any time.

**Comment by ignatdoc** [comment]
I am using credentials_url or auto_login already for that :)
Autoreconnect works fine when I reload page, it don't work when internet is gone for example for 20 sec and then back again.

**Comment by jcbrand** [comment]
I made some fixes. Can you make a new build of the latest code and check again?

**Comment by ignatdoc** [comment]
I don't know how to build and get all depencies... Can you please make a test build for me? Thanks

**Comment by jcbrand** [comment]
@ignatdoc Try this: https://cloud.opkode.com/index.php/s/j454pmurrGTLPxI

Link will expire in 3 days.

**Comment by ignatdoc** [comment]
1. Making disconnect of internet(at router, so wifi enabled) and after a few retries getting this:

request id 35.3 state changed to 2  converse.js:47344:17
request id 35.3 state changed to 4  converse.js:47344:17
ERROR: request id 35.3 error 0 happened  converse.js:47342:17
request errored, status: 0, number of errors: 5  converse.js:47344:17
_onDisconnectTimeout was called  converse.js:47344:17
Status changed to: undefined  converse.js:47344:17
_doDisconnect was called  converse.js:47344:17
Status changed to: DISCONNECTED  converse.js:47344:17
RECONNECTING  converse.js:47344:17
The connection has dropped, attempting to reconnect.  converse.js:47344:17
_throttledRequestHandler called with 0 requests

2. After 5-10 sec getting this and converse becomes quite and roster is "hidden" with green tab and Reconnecting:

InvalidStateError: XMLHttpRequest state must be OPENED.  converse.js:43650
	Strophe.Bosh.prototype._processRequest/sendFunc https://someserver.com/_assets/conversejs/dist/converse.js:43650:17
	Strophe.Bosh.prototype._processRequest/< https://someserver.com/_assets/conversejs/dist/converse.js:43662:21

3. Connecting internet back, roster is "hidden" with green tab and Reconnecting, chat tabs still open. Each time I click on green roster tab I get this:

TypeError: _converse.connection is undefined[Learn More] converse.js:52644:1
	.initialize/_converse.ControlBoxToggle<.showControlBox https://someserver.com/_assets/conversejs/dist/converse.js:52644:1
	.initialize/_converse.ControlBoxToggle<.onClick https://someserver.com/_assets/conversejs/dist/converse.js:52661:25
	wrapper https://someserver.com/_assets/conversejs/dist/converse.js:17419:16
	jQuery.event.dispatch https://someserver.com/_assets/conversejs/dist/converse.js:7339:16
	jQuery.event.add/elemData.handle https://someserver.com/_assets/conversejs/dist/converse.js:7152:6

So I need to reload page to get it loggen in back again.
Thanks.

**Comment by jcbrand** [comment]
I've made various auto_reconnection fixes.
