### ISSUE TITLE
Roster Not Loading

### ISSUE THREAD

**Issue by ovadbar** [jcbrand/converse.js#850]
When I login the roster is empty.
I have narrowed down the error to line 51221 and threw a try catch around it to get the following debug.

TypeError: Cannot read property 'get' of undefined
    at child.isGroupCollapsed (converse.js:51221)
    at child.<anonymous> (converse.js:51390)
    at arrayEach (converse.js:12988)
    at Function.forEach (converse.js:21810)
    at child.each (converse.js:44612)
    at child.filter (converse.js:51388)
    at converse.js:50941
    at converse.js:17395
    at baseForOwn (converse.js:15452)
    at converse.js:17364

**Comment by jcbrand** [comment]
What version of converse.js are you using? Did you modify it in any way?

**Comment by ovadbar** [comment]
I first noticed the issue on the converse js home page.
The converse I was using was the hosted converse that I downloaded and
modified only in order to debug this issue.
I looked at the code and couldn't figure out why the logic was working but
decided to replace it with something much simpler.

I did start to modify to use the following logic instead of the logic in
the isGroupCollapsed and this seems to work.


                isGroupCollapsed: function () {
                    /* Check whether the group in which this contact
appears is
                     * collapsed.
                     */
                    // XXX: this sucks and is fragile.
                    // It's because I tried to do the "right thing"
                    // and use definition lists to represent roster groups.
                    // If roster group items were inside the group
elements, we
                    // would simplify things by not having to check whether
the
                    // group is collapsed or not.
                    if
(this.$el.prevAll('dt:first').find('.icon-closed').size()) {
                        return true;
                    }
                    return false;
                },

Let me know if this helps

Thanks,
Baroukh Ovadia

**Comment by jcbrand** [comment]
Can you do me a favor please?

Set `debug` to `true`.
Use the chrome or chromium browser.
Open the developer console.
Log in with your account in chrome.
Reproduce the bug (i.e. with unmodified converse.js).

Then in the browser console, save the debug output as a file (see here for info how: https://developers.google.com/web/tools/chrome-devtools/console/#saving_the_history).

Then send me this file to jc <at> opkode <dot> com

Then I'll try to debug what the problem is.

**Comment by ovadbar** [comment]
Did you make a new build? I am not able to reproduce the error

**Comment by jcbrand** [comment]
No, I didn't change anything.

**Comment by ovadbar** [comment]
Ok I think the code used on the main site (
https://conversejs.org/dist/converse.min.js) has some problems because the
roster isn't showing up  but the  hosted code is now working.

Not sure why that is

**Comment by ovadbar** [comment]
You can test with the login 2019795351@ch1.dyl.com and
password 3YvPoKG6Mo9U7ehoEkwFWMFI7

**Comment by jcbrand** [comment]
I committed a fix for this. The problem is that your group name is a number and Backbone's `.where` function doesn't match numbers.
