### ISSUE TITLE
Autoreconnect + http_bind + fixed resource

### ISSUE THREAD

**Issue by ignatdoc** [jcbrand/converse.js#860]
Next bug found ) This is maybe not a bug, but.. emm:
Autoreconnect, http_bind, resouce name fixed in config. When opening more than 1 browser tab - ConverseJS start to go offline on one tab and going online in other. And this is in infinite loop :)

**Comment by jcbrand** [comment]
Using a fixed resource name across browser tabs won't work. Each connection per browser tab must have its own resource.

**Comment by magnetik** [comment]
I was about to open quite the same bug. Sharing the connection between multiple tab is not possible then?

**Comment by jcbrand** [comment]
No, it's not possible. Each tab needs its own connection.
