### ISSUE TITLE
Inconsistent unread messages count updating

### ISSUE THREAD

**Issue by novokrest** [jcbrand/converse.js#873]
There can be out-of-sync information about unread messages count in different parts of GUI in following scenario:
1. User opens chat
2. Users scrolls chat up so that new incoming messages wouldn't be visible
3. User receives messages that are not read, but unread messages count in roster view are not displayed.
4. User minimizes chat, but unread messages count in minimized mode are not displayed
5. While chat is minimized, user receives one more message and unread messages count appears in roster view and minimized chat's indicator and equals to 1 (but should be more than 1)
6. User clicks on roster view, then scrolled-up chatbox are opened and unread messages count disappears from roster view, but received messages are still unread.

**Comment by jcbrand** [comment]
How many of these usecases are now covered by your pull request?

**Comment by novokrest** [comment]
@jcbrand All of the above use cases are covered by these pull request

**Comment by jcbrand** [comment]
Great work, thanks.
