### ISSUE TITLE
symbols symbolizing smileys in links are converted to smileys leading to non-clickable links

### ISSUE THREAD

**Issue by Mrfuyu** [jcbrand/converse.js#879]
If you receive a link like e.g. `https://www.domain.tld/tas82nas1:Pt+a` the `:P` gets converted to an smiley so you can't click and follow the link. 

There should be an exception for smiley conversion inside of links.

Real example: Try sending https://de.wikipedia.org/wiki/Datei:Polaritaet_antisense.png

**Comment by jcbrand** [comment]
No longer relevant, since the emoticons have been replaced with emojis (in master).
