### ISSUE TITLE
Logout with link

### ISSUE THREAD

**Issue by alessandrolanghi** [jcbrand/converse.js#881]
How I can programmatically logout from chat?

**Comment by joshp23** [comment]
This would be handy for account switching.

**Comment by jcbrand** [comment]
Inside a plugin (where you have access to the private `_converse` object, you call `_converse.api.user.logout()`.

**Comment by xinthose** [comment]
Is there no public function I can call to logout?  I use the `auto_login: true` configuration so I use a custom login with a custom logout.

**Comment by jcbrand** [comment]
There is an API method for logging out:

https://conversejs.org/docs/html/developer_api.html#logout
