### ISSUE TITLE
add contact failure

### ISSUE THREAD

**Issue by joshp23** [jcbrand/converse.js#883]
When I try to add contact, the add contact form is malformed, however the contact still adds, I just can't see what I am typing.

The code I used was directly from the quickstart guide, and the page that it is loading on is quite basic.

![screenshot from 2017-05-12 10-57-09](https://cloud.githubusercontent.com/assets/7341917/26005071/eb05621e-3705-11e7-8442-61a60d432881.png)

**Comment by jcbrand** [comment]
Appears to be related to #847
