### ISSUE TITLE
Remove a plugin

### ISSUE THREAD

**Issue by reinodenoia** [jcbrand/converse.js#885]
I initialize conversejs depending on a action.
I created a plugin to access converse's private methods and then I disconnected. 
When I try to initialized a second time shows me an error:

Error: plugin with name "connect" has already been registered!

I see in the documentacion it describes a remove plugin method, but not works. 

Any idea? 

Ty

**Comment by jcbrand** [comment]
Try listening to the `disconnected` event inside your plugin's `initialize` method, then you don't need to register it twice.

The `remove` method has been removed because it's not needed, instead a plugin only has to be initialized once and then it can listen to events from thereon out.
