### ISSUE TITLE
Link image preview to full url of image

### ISSUE THREAD

**Issue by MurzNN** [jcbrand/converse.js#887]
At now converse.js displays preview of image if I receive url to image in message. But it displays only in chat window that have small width. I can copy image location and open it in new window for see full-sized image, but this is too hard way for not-improved users.

Please add `<a href="url" target="_blank">` link to image preview with for easily look full image.

**Comment by Mrfuyu** [comment]
Maybe you can also use what I do temporarily. Just add this:

```
<script type="text/javascript">
  $("body").on('mouseover', '.chat-image', function(e){
    $(this).css('cursor', 'pointer');
  });
  $("body").on('click', '.chat-image', function(e){
    var URL = $(this).attr("src");
    window.open(URL,'_blank','',''); 
  });
</script>
```
