### ISSUE TITLE
[QA] How i can implement multi rosters chat window?

### ISSUE THREAD

**Issue by liverbool** [jcbrand/converse.js#889]
I want to make a new help desk support. The system will have a lot of clients, these clients will send their message to admin for chatting. They are too many popup chat windows that make it difficult to manage for admin, so i want to re-design ui to be a list layout instead of the popup windows. Thus, admin could chat with clients easier.

like this

![screenshot-3-](https://cloud.githubusercontent.com/assets/206804/26761476/66f1a444-495a-11e7-807f-9e1a21f43c58.jpeg)

Thanks for advance.

**Comment by jcbrand** [comment]
It's not clear to me from your question what you actually want.

**Comment by liverbool** [comment]
@jcbrand i edit what actually i want ;)

#### So, i want to change this:

<img width="1307" alt="2560-06-04 18 14 09" src="https://cloud.githubusercontent.com/assets/206804/26761462/1f470238-495a-11e7-8ba1-d2ca89e49db1.png">

#### to something like this:

![screenshot-3-](https://cloud.githubusercontent.com/assets/206804/26761470/3c847b5a-495a-11e7-9107-7867230acd91.jpeg)

**Comment by mckaygerhard** [comment]
jajaaj now its clearly clear.. i have same behavior in my roundcube implementation.. screen are too chick for many chats window...

but due sure this will raise the requirements of web browsers i dont care .. due sure newer featured will dont work in older browsers

**Comment by jcbrand** [comment]
I'm working on a fullscreen version of converse.js called inVerse, currently in its own repo at https://github.com/jcbrand/inverse.js (but I might merge it back into the converse.js repo).

You could build on top of inVerse if you want a full screen version.

Note, there's no release yet for inVerse and no final Javascript distribution/build file.

**Comment by mckaygerhard** [comment]
inverse seems need lof of tools installed that does not ship with package vendors in servers!

also inverse works in any browser version, at least firefox 16?

**Comment by jcbrand** [comment]
FF 16 is ancient. I don't know whether it's supported.
