### ISSUE TITLE
Message carbons not sent out after reconnection

### ISSUE THREAD

**Issue by ignatdoc** [jcbrand/converse.js#890]
Hello.

I have two clients running, one of them is Converse.js . After some amount of time message carbons stop working, to restore it's operation I need to reload page with Converse.js . Checked server-side(Prosody 0.9) - all is fine. Checked with two desktop clients - all is fine. Catch this problem through debug console is almost impossible as it may take a few hours before it dies..

**Comment by jcbrand** [comment]
Without debug information there's not much I can do about this. Try using converse.js with the developer console open the entire time (for example, the whole day), then when the problem starts to happen, check the output around that time. In chrome/chromium you can also store the debug log as an XML file, to search through later.

**Comment by ignatdoc** [comment]
I am back again and without debug log, because it is clean with no errors, but one thing I have understood: carbons work good from start, but problem occurs after autoreconnect !(login/password are taken from URL). So as soon as I got my connection dead and back again Converse is trying to reconnect and (maybe) forget to send carbon xml stanza?

Thanks

**Comment by jcbrand** [comment]
Here you go: https://cloud.opkode.com/index.php/s/Gq9MAMwlgutDT0E

**Comment by ignatdoc** [comment]
Uploaded to test but got another problems with css i think? 
<img width="220" alt="screen shot 2017-06-15 at 1 01 18 pm" src="https://user-images.githubusercontent.com/27704345/27192861-deb27918-51ca-11e7-9c91-1c384002c7ee.png">

**Comment by jcbrand** [comment]
Ah, I forgot that you'll need new CSS as well: https://cloud.opkode.com/index.php/s/prAWr0u8o8SfIxr

**Comment by ignatdoc** [comment]
Somehow new converse.js breaking my site JS ) Trying to understand what is wrong now.

**Comment by ignatdoc** [comment]
Yep, seems newer jQuery version is not fully compatible with my site... So now or working site, or working Converse.js

**Comment by jcbrand** [comment]
OK, I think I'll just assume the bug is fixed for now. Thanks for trying.

**Comment by ignatdoc** [comment]
Nope, seems carbons stopped working at all on new version. I don't see my forwarded messages from other client.

**Comment by jcbrand** [comment]
Ah, there was one more bug. Thanks for checking

**Comment by ignatdoc** [comment]
Can you please compile for me with new bugfix? and maybe without jQuery please..

**Comment by jcbrand** [comment]
https://cloud.opkode.com/index.php/s/yxNpwagCekwbgh4
