### ISSUE TITLE
converse.js how to determine the change in the status of users in a chat

### ISSUE THREAD

**Issue by proton5000** [jcbrand/converse.js#891]
on frontend side i use listener

```
_converse.api.listen.on('contactStatusChanged', function(event, buddy) {
                    console.log("get status");
                    scope.chat.chatFriends = _converse.api.contacts.get();
                    scope.$applyAsync();
});
```

to chek users status

when user logout i set his status by

`_converse.api.user.status.set('offline');`

and then logout

`_converse.api.user.logout();`

but other users see when user is online by long time

please help me to solve this problem

**Comment by jcbrand** [comment]
What happens when you set to a different state, like 'dnd'?

**Comment by proton5000** [comment]
when i change status to `_converse.api.user.status.set('offline');` or `_converse.api.user.status.set('dnd'); ` nothing happens - listener not detect change status
i solved my problen - i send requets to logout to openfire chat server, and then listener detecht change status and start code inside function
```
console.log("get status");
scope.chat.chatFriends = _converse.api.contacts.get();
scope.$applyAsync();
```
