### ISSUE TITLE
otr in inverse

### ISSUE THREAD

**Issue by nrobinaubertin** [jcbrand/converse.js#898]
Hi !
I'm pretty new to xmpp (so I maybe missed something). 
I tried to use OTR with inverse.chat and it failed:
```
?OTRv23?I would like to start a private (OTR encrypted) conversation but your client doesn’t seem to support that
```
It works well on converjs.org ! So I wonder if it's not implemented on inverse or if it should work ?

**Comment by jcbrand** [comment]
For some inexplicable reason I blacklisted the `converse-otr` plugin when calling `converse.initialize` in `inverse.html` (must have been a typing mistake or something).

I removed the blacklist now.
