### ISSUE TITLE
How to logout

### ISSUE THREAD

**Issue by xinthose** [jcbrand/converse.js#905]
Hello.  I am confused how to call the private [logout](https://conversejs.org/docs/html/developer_api.html#logout) function.  Here is my code:
**Login**
```
converse.initialize({
	bosh_service_url: 'http://localhost:7070/http-bind/',
	show_controlbox_by_default: true,
	debug: true,
	auto_login: true,
	auto_reconnect: true,
	allow_logout: false,
	locked_domain: "elemechinc.com",
	jid: email_address,
	password: password,
	auto_join_rooms: [{
		"jid": "testing@conference.desktop-bn13agh",
		"nick": user_name
	}],
	message_archiving: "always",
	play_sounds: true,
	sounds_path: "/osrc/converse/sounds/",
	notification_icon: "/osrc/converse/logo/conversejs.png",
	use_emojione: true,
	emojione_image_path: "/osrc/converse/EmojiOne_3.1.1_128x128_png/"
});
```
**Logout**
```
converse.plugins.add('myplugin', {
	initialize: function () {
		this._converse.api.user.logout();
	}
});
```
When I call the logout code, it does not work.  What am I doing wrong?

**Comment by jcbrand** [comment]
Most likely what's happening is that you're trying to log out before the user has been logged in.

The `initialize` methods of the plugins are called near the end of the `initialize` method of `converse` itself which is before the user is logged in.

You should therefore wait for an event (or promise).

You could wait for [statusInitialized](https://conversejs.org/docs/html/events.html#statusinitialized) which is available as either an event or promise.

See here: https://conversejs.org/docs/html/events.html#statusinitialized

To wait for the promise, you can do the following in your `initialize` method:
```
_converse.api.waitUntil('statusInitialized').then(function () {
    // Your code here...
});
```

Or to listen for the event:
```
_converse.on('statusInitialized', function (status) { ... });
```

Alternatively you could listen for the `connected` event (which is not available as a promise currently, but might be in the future).

**Comment by xinthose** [comment]
OK.  Thank you sir.  The logout code is called when the user selects my logout button, so it will not execute before they are logged in.  It would not make sense to login then logout as soon as converse initializes.  I do not understand how I can call this logout function on demand and not after a converse event.

**Comment by jcbrand** [comment]
I was referring to the code snippet you pasted, in which the user is logged out immediately as soon as `initialize` is called.

Yes it doesn't make sense to immediately log out after being logged in, but I assumed you are first trying to get the API call to work and that you'll then refactor afterwards to use logout where its appropriate.

To call the function on demand, you can simply listen for an event from your own code.

**Comment by xinthose** [comment]
Thank you.  I copied the code from the logout example without understanding what I was doing.  I just realized that I can use 
`_converse.emit('logout');`
with
```
_converse.api.listen.on("logout", function () {
	this._converse.api.user.logout();
});
```
Does that look right to you?  I do not need to create my own plugin then, if I'm not mistaken.

**Comment by jcbrand** [comment]
The `_converse` object is only available in plugins, so if you want to listen for the `logout` event (like you show in your code snippet), then that code needs to be in a plugin.

**Comment by xinthose** [comment]
OK.  So after I call `converse.initialize(...)` I create my plugin with the logout method:
```
converse.plugins.add('wiki_chat_plugin', {
	logout: function () {
		this._converse.api.user.logout();
	},
});
```
But now how do I call this logout method in my plugin from outside it?  Would it look like this? `converse.plugins.get("wiki_chat_plugin").logout();`

Thank you for your patience with my ignorance.

**Comment by jcbrand** [comment]
Based on your code example it doesn't look like you read or understood the plugin documentation. Please make sure you read it carefully:
https://conversejs.org/docs/html/plugin_development.html

To further your understanding you can also read the [pluggable.js documentation](https://jcbrand.github.io/pluggable.js/) which is the plugin library used by converse.js.

Concerning making something accessible from the outside, the converse.js plugin infrastructure doesn't do anything for you there. The most obvious and easiest way is to simply add the public method to a global variable on the `window` object, like for example the `converse` object.

**Comment by xinthose** [comment]
> The most obvious and easiest way is to simply add the public method to a global variable on the window object, like for example the converse object.
OK.  Thank you.  What would the code look like?  I cannot figure it out.

**Comment by jcbrand** [comment]
Sorry @xinthose, but I don't have the time and capacity to help and coach you further through your code. This issue tracker is intended only for bug reports and feature requests and I've already made more of an effort than usual to support you.

**Comment by xinthose** [comment]
OK.  Thank you sir.

**Comment by fingertips-solutions** [comment]
Can anyone tell me how to logout and redirect to custom login page ?  i have custom login page and once that login is approved i am auto login xmpp users... this part is ok but when i try to logout it not redirecting me back to my custom login page...

**Comment by FaizanZahid** [comment]
@xinthose were you able to figure out how to log out using a JS function call after converse initialize? if yes, please share your working code example.

**Comment by jcbrand** [comment]
See here: https://conversejs.org/docs/html/api/-_converse.api.user.html#.logout

**Comment by xinthose** [comment]
@FaizanZahid I did not figure out how to use custom plugins.  I stopped my development on that project.
