### ISSUE TITLE
Problem with message history (XEP-0313) (prosody)

### ISSUE THREAD

**Issue by sneerix** [jcbrand/converse.js#906]
Hi,

I've problem with receiving/reading message history in converse.js. I log into own (simple, only for converse) page with Converse.js, open message window to anyone and history window is empty.

When I use Conversations (android app) I can clean client history and then fetch history from server.

Am I doing something wrong? For some time it was working ok, stopped working few months ago.

I'm using:
- current version of converse.js, today I've upgraded it to version from github repository.
- current version (from hg repo) prosody 0.10
- apache2
- centos 6

Converse config looks like:
```
<script>
    converse.initialize({
        bosh_service_url: 'https://im.domain.pl/http-bind/',
        allow_muc: false,
        auto_reconnect: true,
        keepalive: true,
        message_archiving: 'always',
        message_carbons: true,
        show_controlbox_by_default: true
    });
</script>
```

At prosody side, I use mod_mam and storage sql.

**Comment by jcbrand** [comment]
Just yesterday I fixed a bug related to MAM2, which is used by the latest Prosody.

The issue was that converse.js queried the wrong disco node to figure out whether MAM is supported. Probably this is also the issue that you're having.

**Comment by sneerix** [comment]
Is this fix included in https://github.com/jcbrand/converse.js/commit/4e491ac5d327eee0013dcf75e323b1a762b87a68?
I saw https://github.com/jcbrand/converse.js/commit/02a055d31d4a82a977a6921447901331a302ed17 commit.
Today I cloned repository and replaced files on my webpage from dist/ directory in converse repository.
Nothing changed so far :-(

**Comment by jcbrand** [comment]
Put some breakpoints in `./src/converse-mam.js` and see what happens when you open a chat.

Report back if you find anything useful. Otherwise I unfortunately can't help you.

**Comment by sneerix** [comment]
After upgrading to latest release (3.2.0 (2017-08-09)) history works again. Thank you :-)

**Comment by jcbrand** [comment]
Yay! :)
