### ISSUE TITLE
default_domain dont  active? a bug?

### ISSUE THREAD

**Issue by wenthywang** [jcbrand/converse.js#907]
converse.initialize({
	bosh_service_url: 'ws://127.0.0.1:7070/ws/', // Please use this connection manager only for testing purposes
    show_controlbox_by_default: true,
    //authentication:'anonymous',
    keepalive: true,
    allow_registration:false,
    auto_login:true,
    jid:'test',
    password:'test',
    default_domain:'wenthywang.com',
    locked_domain:true,
    time_format:'hh:mm a',
    allow_bookmarks:false,
    debug:false
});

初始化用这个，但是登陆的时候并没有调用插件的authenticate这个方法，是个bug吗？这个方法就是组装jid的用户名的，还是我的配置有问题，请指教。

**Comment by jcbrand** [comment]
`locked_domain` is not a Boolean (`true` or `false`) value. If you want to lock the domain, then you set `locked_domain` to your domain `wenthywang.com` and you then do not need to set `default_domain`.

**Comment by wenthywang** [comment]
@jcbrand it dont work..
converse.initialize({
	bosh_service_url: 'ws://127.0.0.1:7070/ws/', // Please use this connection manager only for testing purposes
    show_controlbox_by_default: true,
    //authentication:'anonymous',
    keepalive: true,
    allow_registration:false,
    auto_login:true,
    jid:'test',
    password:'test',
  //  default_domain:'wenthywang.com',
    locked_domain:'wenthywang.com',
    time_format:'hh:mm a',
    allow_bookmarks:false,
    debug:false
});

**Comment by guusdk** [comment]
I'm running into a similar issue, which did _not_ occur with Inverse 3.1.0. When logging in with just the node-part of the JID and default_domain set, there's not an explicit authentication error. Instead, the app appears to refuse to attempt, giving the text input a red border. This might be input validation that is looking for a proper JID.
