### ISSUE TITLE
L10N - please remove variables and pull translations

### ISSUE THREAD

**Issue by Jibec** [jcbrand/converse.js#909]
Hi there, I noticed new strings to translate and decided to help a little :)
I'm surprise to see we have to translate things like "$(command)" or "notification.reason".

In bonus, I would rather translate the content of these variables!

It looks like to come from this file:
https://github.com/jcbrand/converse.js/blob/master/src/converse-muc.js#L1761

It also looks like you didn't pull content from weblate since last march :(
https://github.com/jcbrand/converse.js/pulls?utf8=%E2%9C%93&q=is%3Apr%20is%3Aclosed%20weblate

What's going on?

**Comment by jcbrand** [comment]
Hi, thanks for your translations.

I recently updated some strings to ES2015 template literals and looks like gettext doesn't parse them properly, which is why there were strings like "$(command)".

That's fixed now.

Concerning Weblate, I was under the impression that Weblate automatically makes pull requests. Looks like this isn't the case. I merged the code now.

**Comment by Jibec** [comment]
Le 23 août 2017 13:03:36 UTC+03:00, JC Brand <notifications@github.com> a écrit :
>Hi, thanks for your translations.
>
>I recently updated some strings to ES2015 template literals and looks
>like gettext doesn't parse them properly, which is why there were
>strings like "$(command)".
>
>That's fixed now.
>
>Concerning Weblate, I was under the impression that Weblate
>automatically makes pull requests. Looks like this isn't the case. I
>merged the code now.

Thanks for your reactivity, I assume there a bug somewhere, can you please open a bug request in Weblate's github project? The whole objective of using Weblate is to make it as easy as possible for you as a maintainer and us as translator to have automatic push/pull mechanism. I assume it is minor misconfiguration somewhere.

Have a nice day!
-- 
Jean-Baptiste Holcroft
