### ISSUE TITLE
MAM not working on 3.2.1

### ISSUE THREAD

**Issue by milestogo77** [jcbrand/converse.js#914]
I have Converse.js 3.0.2 which retrieves archived messages successfully. However, the new release 3.2.1 shows the following error

`WARNING: Attempted to fetch archived messages but this user's server doesn't support XEP-0313`

I'm using the same options for both instances.

`    converse.initialize({
	bosh_service_url: 'http://localhost:7070/http-bind/',
	authentication: 'login',
        auto_login: false,
        registration_domain: 'pcechlt46.local',
        default_domain: 'pcechlt46.local',
        allow_muc: false,
        use_vcards: true,
        allow_contact_requests: false,
        allow_non_roster_messaging: true,
        allow_otr: false,
	play_sounds: true,
	sounds_path: '/converse/sounds/',
	notification_icon: '/converse/logo/conversejs.png',
	debug: true

    });`

**Comment by jcbrand** [comment]
The latest converse.js uses MAM2, the previous one you used, used MAM0.
