### ISSUE TITLE
Add chatBoxClosing event

### ISSUE THREAD

**Issue by mikemarsian** [jcbrand/converse.js#916]
Currently, when the user clicks on X icon on the chat box, the chat room is closed and the chatBoxClosed notification is fired only as a final step. I would like to display an alert box asking the user to confirm, before closing the chatBox.

In order to implement this, I suggest adding the chatBoxClosing event that is fired before the actual closing of the chat room. If the event function returns true, then proceed to closing the chat. Otherwise, stop and return without closing.

If you see a simpler way to add an alert box, please let me know. Otherwise, if the syntax of the new event makes sense to you, I would be glad to send a pull request.

**Comment by jcbrand** [comment]
Hi @mikemarsian, you're welcome to submit a pull request. I'd prefer that the event is called `beforeChatBoxCloses`, which makes more semantic sense to me.

However, I'm not sure that it'll work the way you expect. When an event is triggered, the handlers are called asynchronously and the code that triggered the event doesn't wait for return values from the handlers.

An alternative approach would be to override the method in which the chat box gets closed in a plugin and to add the `confirm` there. Events are preferable to overrides, but in this case I'm not sure whether it can be done with an event.

**Comment by mikemarsian** [comment]
Hi @jcbrand , I tried the approach you suggested - overriding the onChatBoxClosed, and it worked well, until I realized that it's being called not just by user click events, but also by internal events. So the user would suddenly receive an alert-box without any interaction from his side.

So I guess a better solution would be to introduce an event similar to callButtonClicked, smth like closeButtonClicked. Does that make sense to you?

**Comment by jcbrand** [comment]
I think I'd rather just include the original even when emitting `onChatBoxClosed`, that way the event handler can check whether it's because of a `click` event and what the target of the click was and we don't have to create yet another event.

**Comment by mikemarsian** [comment]
Sounds good. Do you have time to add this?

**Comment by jcbrand** [comment]
I thought you would do it, since you're already working on the code.

**Comment by mikemarsian** [comment]
OK, I will try to. I'll let you know if I have any questions. What kind of
source object did you have in mind? in case of user click that could a DOM
element, but in case of internal event, what would the source be?

2017-09-08 2:48 GMT-05:00 JC Brand <notifications@github.com>:

**Comment by jcbrand** [comment]
If it gets triggered internally, then the event can be `undefined` or `null`.

**Comment by jcbrand** [comment]
Hi @mikemarsian, any update on this?

**Comment by mikemarsian** [comment]
Hi, sorry, I got busy with other things. I'm not sure I'll get to this
anytime soon. I'll let you know, if I'll get back to this.

2017-09-29 3:06 GMT-05:00 JC Brand <notifications@github.com>:
