### ISSUE TITLE
Integrating Converse.js and Angular 2/4

### ISSUE THREAD

**Issue by Braste** [jcbrand/converse.js#926]
Is there any integration available or planned for angular 2/4? You can see this as feature request, if there isn't.

**Comment by jcbrand** [comment]
I integrated Converse.js into Angular2 for a client a while back and documented what I did here:
https://conversejs.org/docs/html/other_frameworks.html#angular-js

I think providing Angular integration is out of scope for this repo and if it was done should be made in a different project/repo.

The code from the above linked documentation could perhaps be used, at least as basis.

**Comment by Braste** [comment]
Not everyone is able to convert this to typescript, which is used by at least Angular 4.

**Comment by JinJinSu** [comment]
How to integrate converse.js to existing angularjs project?

**Comment by JinJinSu** [comment]
@jcbrand How to integrate converse.js to existing angularjs project?
Please help me.

**Comment by jcbrand** [comment]
@JinJinSu https://conversejs.org/docs/html/other_frameworks.html#angular-js

**Comment by JinJinSu** [comment]
@jcbrand 
I don't know every steps.
Could you explain about that more please?
Thanks.

**Comment by JinJinSu** [comment]
@jcbrand I have one question.
I am going to integrate the converse.js to angular.js project.
Already I read the doc. Now my question is...
Should I put the all converse.js source code to angular.js project?
Or only some part?

**Comment by JinJinSu** [comment]
Here is the URL
https://m.conversejs.org/docs/html/other_frameworks.html

**Comment by jcbrand** [comment]
No, because I haven't had to integrate Converse with Angular > 1 yet.

I expect the fundamentals to be the same however.

**Comment by DeborahK** [comment]
So is this a typo above:

> I integrated Converse.js into Angular2 for a client a while back and documented what I did here:

That should have been `AngularJS`?

**Comment by jcbrand** [comment]
Yes, thanks for pointing it out. Fixed.
