### ISSUE TITLE
single session support and prebinding problem

### ISSUE THREAD

**Issue by husen13** [jcbrand/converse.js#928]
i am trying to use single session support here,and what i know that i have to configure the converse.initialize with keepalive,prebind,and prebind_url,and i got the serverside code example from here **https://github.com/candy-chat/xmpp-prebind-php** and i try use it on my own,so here's my converse.initialize code : 

>     converse.initialize({
        prebind: true,
        prebind_url : "bind/bind.php",
        keepalive:true,
        debug: true,
        bosh_service_url: 'http://localhost:5280/http-bind/',
        auto_list_rooms: true,
        auto_subscribe: false,
        hide_muc_server: false,
        i18n: locales.id, // Refer to ./locale/locales.js to see which locales are supported
        show_controlbox_by_default: true,
        xhr_user_search: false,
        auto_reconnect: true,
        play_sounds: true,
        message_storage : 'local',
        message_archiving: 'always',
        jid: 'admin1@localhost',
    });

and my serverside code : 

>        require 'xmpp-prebind-php-master/lib/XmppPrebind.php';

            $user = "admin1";
            $password = "husen";
            $resource = 5280;
            $tld = "localhost";
            $boshUrl ="http://localhost:5280/http-bind/"; 
     
        $xmpp = new XmppPrebind($tld,$boshUrl,$resource,false,false);
        $xmpp->connect($user, $password);
        print_r($xmpp->connect()); //will return JID, SID, RID as JSON

i got internal server error in my serverside code : 
**
Fatal error: Uncaught XmppPrebindConnectionException: Child not found in response from server. in /var/www/html/converse.js/bind/xmpp-prebind-php-master/lib/XmppPrebind.php:170 Stack trace: #0 /var/www/html/converse.js/bind/bind.php(13): XmppPrebind->connect('adl@localte,xxxxxx') #1 {main} thrown in /var/www/html/converse.js/bind/xmpp-prebind-php-master/lib/XmppPrebind.php on line 170**

does anyone know something ?,sorry if this kinda foolish question,please help me,this is kinda urgent

**Comment by jcbrand** [comment]
This issue tracker is for bug reports and feature requests, not general support questions around setting up Converse.js.

You can try asking on [StackOverflow](http://stackoverflow.com/).
