### ISSUE TITLE
Locking to a Domain

### ISSUE THREAD

**Issue by nandinibhaduri** [jcbrand/converse.js#929]
There should be a way where the converse.js client can be locked to a domain. Like it would be a internal chat thing. They will be able to add contacts from a single domain only.

**Comment by jcbrand** [comment]
There is a [locked_domain](https://conversejs.org/docs/html/configuration.html#locked-domain) setting, however you're still able to add contacts from other domains (at least via the UI).

**Comment by nandinibhaduri** [comment]
Then I guess I would have to add the functionality. Do you want me to contribute the feature to the repository? And can you please provide me with some technical documentation.

**Comment by jcbrand** [comment]
Yes, a pull request would be welcome.

Here's the developer docs: https://conversejs.org/docs/html/development.html
