### ISSUE TITLE
Bosh Request - Server Side

### ISSUE THREAD

**Issue by Sammuel-Miranda** [jcbrand/converse.js#933]
Hello, i'm building my own XMPP server (using C#), and i based it on ["agsXMPP"](https://www.ag-software.net/agsxmpp-sdk/download/) library and TeamLab Jabber Server (for the Bosh Connections).

My problem is, on handling the requests coming from converse.js, it always send a request using "OPTIONS" HttpMethod with a NULL body. Shouldn't it request using a <body> tag? What i need to respond when converse.js sends an empty body, "OPTIONS" request?

I've read what i could find on Xmpp.org and it's XEP's, but didn't find any referecent to "OPTIONS" request.

**Comment by jcbrand** [comment]
The OPTIONS request is a so-called [preflight request](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#Functional_overview) to determine whether the domain being queried supports CORS.

IIRC this only happens when making cross-domain requests. If you intend to support CORS, then you'll need to respond appropriately to OPTIONS requests.

**Comment by Sammuel-Miranda** [comment]
I don't know what am i doing wrong, I took this few days to try and resolve this one, but i'm not getting there.

On server side i'm responding maybe the most generous (kinding here...) CORS response ever.
Something like this:

```
internal static void SendCORSResponse(HttpListenerContext ctx)
{
    ctx.Response.StatusCode = (int)HttpStatusCode.OK; //200
    ctx.Response.AddHeader("Access-Control-Allow-Origin", "*");
    ctx.Response.AddHeader("Access-Control-Allow-Methods", "GET,POST,HEAD,PUT,DELETE,OPTIONS");
    ctx.Response.AddHeader("Access-Control-Allow-Headers", "content-type");
    ctx.Response.AddHeader("Access-Control-Max-Age", "86400");
    ctx.Response.AddHeader("Accept-Encoding", "gzip");
    ctx.Response.AddHeader("Accept-Charset", "utf-8");
    ctx.Response.AddHeader("Accept-Language", "*");
    ctx.Response.AddHeader("Accept", "*");
    ctx.Response.Close(); //sends the response
}
```

**Comment by Sammuel-Miranda** [comment]
so, just to update this issue - my bad, really the CORS part was write, another function that would run, prior to that had an error. All good now.

**Comment by jcbrand** [comment]
Glad you got it working.

**Comment by Sammuel-Miranda** [comment]
Not really ... left it alone for now

**Comment by Sammuel-Miranda** [comment]
Google Chorme keeps asking for permission to show notifications, and the connection ends even if i press "permit" - very painful this browsers ...

**Comment by Sammuel-Miranda** [comment]
All good :)
