### ISSUE TITLE
Cant able to connect with prebind

### ISSUE THREAD

**Issue by kvinayak1991** [jcbrand/converse.js#934]
`<script>
            var connection;
            jQuery(document).ready(function () {
                connection = new Strophe.Connection("http://10.254.8.81:7979/http-bind/");
                connection.connect("http://10.254.8.81:7979/");
                console.log(connection);
            });
            jQuery(document).ready(function () {
                converse.initialize({
                    bosh_service_url: 'http://10.254.8.81:7979/http-bind/',
                    show_controlbox_by_default: true,
                    auto_reconnect: true,
                    keepalive: true,
                    debug: true,
                    jid: "yyy@data.com",
                    sid: connection._proto.sid,///got sid null in strophe connection object
                    rid: connection._proto.rid,
                    auto_login: true,
                    authentication: 'prebind',
                    prebind: true,
                    prebind_url: 'http://10.254.8.81:7979/api/prebind',
                    show_only_online_users:true
                });
            });

        </script>`

got Exceptions
INFO: Could not restore session for jid: yyy@data.com Error message: _restore: no restoreable session.

2converse.js:49450 GET http://10.254.8.81:7979/api/prebind 404 (Not Found)

startNewBOSHSession @ converse.js:49450 attemptPreboundSession @ converse.js:49487 logIn @ converse.js:49561 _converse.initialize @ converse.js:49635 initialize @ converse.js:49788 (anonymous) @ PrebindChat.html:26 fire @ jquery-1.12.4.js:3232 fireWith @ jquery-1.12.4.js:3362 ready @ jquery-1.12.4.js:3582 completed @ jquery-1.12.4.js:3617 PrebindChat.html:1 Failed to load http://10.254.8.81:7979/api/prebind: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://10.254.8.112:8080' is therefore not allowed access. The response had HTTP status code 404. converse.js:298

**Comment by jcbrand** [comment]
You are trying to load the prebind credentials from a different IP address which is not allowed due to cross-domain restrictions.

Read this: https://conversejs.org/docs/html/setup.html?highlight=cross%20domain#overcoming-cross-domain-request-restrictions

**Comment by kvinayak1991** [comment]
I tried with same ip but with different port then also showing same

**Comment by jcbrand** [comment]
That's because you're using a different port so it's still considered to be "cross domain".

**Comment by kvinayak1991** [comment]
So, u mean to say i hv to create a domain name for that IP Address then and then only it work.

**Comment by kvinayak1991** [comment]
<script>
            var connection;
            var connection = new Strophe.Connection("http://sample.com/http-bind/");
            connection.connect('vpkkk@sample.com');
            console.log(connection);
            connection.xmlOutput = function (e) {
                if (Strophe.Status.CONNECTED) {
                    converse.initialize({
                        bosh_service_url: 'http://sample.com/http-bind/',
                        show_controlbox_by_default: true,
						auto_reconnect: true,
                        //keepalive: true,
                        jid: "vpkkk@sample.com",
                        sid: $(e).attr('sid'),
                        rid: $(e).attr('rid'),
//						  rid: (parseInt($(e).attr('rid').toString()) + 1).toString(),
                        auto_login: true,
                        authentication: 'prebind',
                        prebind: true,
						debug:true,
                        prebind_url:'http://sample.com/api/prebind/'
                    });
                }
            };
        </script>

I created domain using fiddler its user showing logged in but cant able to add contact please look into it
