### ISSUE TITLE
Third-party library to initiate a call.

### ISSUE THREAD

**Issue by rheman** [jcbrand/converse.js#936]
Hi everyone.
I just discover conversejs and it is a great tools for chat in website. Moreove it is very easy ti integrate it. took less than 3 hours to integrate it within my website.
You did a great job.
I read on documentation that it way be possible to use a third-party library to initiate a call. Could someone help me about this issue. 
I would like to know what I should do to integrate call.
Best regard.

**Comment by jcbrand** [comment]
Thanks for your kind words @rheman.

Concerning a third-party library to initiate a call, I only know of proprietary solutions like Vidyo.
