### ISSUE TITLE
contacts list - how to update after vcard FN changed

### ISSUE THREAD

**Issue by RafalxM** [jcbrand/converse.js#937]
I'm using  converse 3.2.1 with ejabberd 17.8 (debian package)
I have a problem with change display in converse contact list afer friend (roster item) change vcard FN .

For example:
1. have registered  user 'test1@localhost' with vcard FN 'NICK test1'
2. register user 'test2@localhost' , set  his vcard FN  to  'NICK test2'
3. add_rosteritem  for both users together - then converse contact list display data from vcard FN  and everything is ok. user1@localhost  is shown as  'NICK test1'  on   test2@localhost  converse contact list.

Now I need to change for user test2@localhost  his   vcard FN  to  'NICK test2 NEW', so:
1. use command:   ejabberdctl set_vcard test2 localhost FN 'NICK test2 NEW'
2. with command:   ejabberdctl get_vcard test localhost FN       I get proper data:  'NICK test2 NEW'

And I have two cases:

case 1:  user test1@localhost , with authentication:login, is logged in and is online , has an open window with converse chat, he see 'NICK test2'  on his contact list.
After changed vcard FN for user2@localhost 
  - he not see these vcard change in real time in his contact list. 
  - he not see these vcard change after reload page
  - he WILL SEE these vcard change ONLY after he will manually log out, and again login to converse.

case 2. user test1@localhost, with authentication:prebind, is logged in and is online, has an open window with converse chat, he see 'NICK test2'  on his contact list. I have no idea how to refresh contact list for  user  test1@localhost  after  his friend  vcard FN  change.

Only way that I know, but it is unacceptable because it takes too much time is:
1. ejabberdctl delete_rosteritem  test1 localhost test2 localhost
2. ejabberdctl add_rosteritem  test1 localhost test2 localhost NICK GROUP both     - NICK is required here as argument, it is not visible in converse contact list

After use these 2 commands  user test1@localhost will  see in realtime 'change nick' of test@localhost user.

As I described it is possible, but if user test2@localhost  will have  40friends in his roster  it wil take about 50seconds on very strong i7 machine with 64gb ram memmory.
I think there is nome hook in method add_rosteritem  that  populate these data to logged in users (active sessions ). I'm looking for a method  to use it  manually after  vcard FN change.

My ejabberd config  have anabled mods:
 mod_vcard:
 mod_vcard_xupdate: {}

I thought that mod_vcard_xupdate will resolve this problem, but not - maybe there is some more configuration required , or maybe somebody knows other way do do this ?
Maybe some converse.js  plugin/event ?

**Comment by jcbrand** [comment]
Converse only fetches the VCards upon login and the XMPP server doesn't inform you when a roster contact's VCard changes.

That's why the user's name doesn't change in realtime.

Perhaps the XMPP server also changes the user's nickname as stored in your roster and then sends out updates for that. I don't know.

If you want to find out, you can set `debug: true` when calling `converse.initialize` and then check the XML stanzas in the log output once you've changed the vCard FN value.

If you see the new value in a "roster push" stanza, then we could update Converse.js to listen for this and to update the user's name.

More info on "roster push":
https://tools.ietf.org/html/rfc6121#section-2.1.6

**Comment by RafalxM** [comment]
Thank you @jcbrand  for fast answer.
Of course I have debug enabled , this is very helpfull.

I have an idea how to do it from converse, but I need you help.

I can send from ejabberd , using set_presence:
`ejabberdctl set_presence test1 localhost 73053624288038632436642 available chat statusMessageText 1`

Then I get this info in my converse plugin:
`
		converse.plugins.add('myplugin', {
			initialize: function () {
				console.log('myplugin  initialize!');
				this._converse.on('statusMessageChanged', function (data) {
					console.log(data);
					/*
					result (data) is  'statusMessageText'
					*/
                                        // var jid = data+'@localhost';
                                        // getVacd(jid);  here ???
				});
			}
		});
`

So in this field 'statusMessage' of set_presence method  I can send  JID  of user which changed his vcard FN, and I can send this info to his roster item (friend). 

Converse at initialize get al contacts vcards (if they have). 
Could someone show me a basic javascript call, that I can use , in 'myplugin' , with  known JID  to  get/refresh data on contact list    from his vcard?

**Comment by jcbrand** [comment]
Currently there's no vCard API. However, you can look at the file `src/converse-vcard.js`. There's a method `getVCard`, defined on the `_converse` object which you can use.

**Comment by RafalxM** [comment]
Thank you for help.
I resolved this issue whis way, maybe it will help somebody:

`converse.plugins.add('vcardPlugin', {`
`      initialize: function () {`
`                      var myconverse = this._converse;`
`			this._converse.on('contactStatusChanged', function (data) {`
`				var myContactJID = data.jid;`
`				myconverse.getVCard(myContactJID,`
`					function () {},`
`					function () {}`
`				);`
`			});`
`		}`
`	});`
