### ISSUE TITLE
Error when login at the same time from different location

### ISSUE THREAD

**Issue by rheman** [jcbrand/converse.js#942]
Hi everyone.
When I login in at same time from two locations(two different browser) with the same user account, I get the following errors. 

Reconnecting
esfam-test.auf.org
The connection has dropped, attempting to reconnect

Connection failed
esfam-test.auf.org
An error occured while reconnecting to the chat server: unknown

Reconnecting
esfam-test.auf.org
The connection has dropped, attempting to reconnect

As you can see in the following pictures.

**Picture 1**

![converjs_error1](https://user-images.githubusercontent.com/4598772/32267732-ee44acce-bef4-11e7-9467-d35cd54da8a8.png)

**Picture 2**

![converjs_error2](https://user-images.githubusercontent.com/4598772/32267740-f288900c-bef4-11e7-8fcf-7e94667062b8.png)

But everything works perfectly when I login from a single location.

My environment looks as followed:

ejabberd 16.09 with mod_mam support (mysql based) 
conversejs lastest release (v 3.0.2) // I cannot use conversejs lastest release because my server does not support mam:2 for message_archiving

My conversejs setting looks as followed.

var user_jid = elgg.data.pessek_chat.user_jid;    
    var bosh_service_url = test.data.pessek_chat.bosh_service_url;  
    var credentials_url = test.data.pessek_chat.credentials_url;     
    var prebind_url = test.data.pessek_chat.prebind_url;   
    var userxmppdomain = test.data.pessek_chat.userxmppdomain;
    var sounds_path = test.data.pessek_chat.sounds_path;
    //var emojione_image_path = test.data.pessek_chat.emojione_image_path;
    
    converse.initialize({
            
            prebind_url: prebind_url,
            //credentials_url: credentials_url,
            keepalive: true,
            jid: user_jid,
            authentication: 'prebind',
            //authentication: 'login',
            bosh_service_url: bosh_service_url,
            use_vcards: true,
            //allow_logout: true,
            allow_muc: false,
            //use_emojione: true,
            //emojione_image_path: emojione_image_path,
            allow_muc_invitations: false,
            allow_contact_requests: false, 
            auto_reconnect: true,
            auto_login: true,
            animate: true,
            message_archiving: 'always',
            archived_messages_page_size: 50,
            //message_archiving_timeout: 8000,
            //muc_history_max_stanzas: 12,
            message_carbons: true,
            default_domain : userxmppdomain,
            allow_contact_removal: false,
            allow_registration: false,
            debug: true,
            hide_muc_server: true,
            sounds_path: sounds_path,
            play_sounds: true,
            xhr_user_search: true,
            show_controlbox_by_default: true,
            strict_plugin_dependencies: false,
            visible_toolbar_buttons: {
                call: true,
                clear: true,
                emoji: true,
                toggle_occupants: true
            },
    });

Best regard.

**Comment by jcbrand** [comment]
I suspect you're trying to use the same [JID resource](https://xmpp.org/extensions/xep-0029.html#sect-idm139366643560976) in both cases, which won't work. Resources need to be unique.

First check whether that's the case.

Otherwise, set `debug` to `true` when calling `converse.initialize` and check the browser console for errors.

**Comment by rheman** [comment]
Thanks. I have the following errors in my firefox javascript console.

```
POST XHR https://ejabberd-esfam.auf.org:5280/http-bind/
XML Parsing Error: no root element found Location: https://ejabberd-esfam.auf.org:5280/http-bind/ Line Number 1, Column 1:
```
POST 

`<body rid='1883434096' xmlns='http://jabber.org/protocol/httpbind' sid='9fda04eae285645e1b04f96c3be7059d6558c27e'><iq from='irene@esfamchat.auf.org/resource' id='enablecarbons' type='set' xmlns='jabber:client'><enable xmlns='urn:xmpp:carbons:2'/></iq><presence xmlns='jabber:client'><priority>0</priority></presence><presence xmlns='jabber:client'><priority>0</priority></presence></body>`

Response
Nothing

**Comment by jcbrand** [comment]
I haven't seen that error before. I'm not sure what's causing it.

**Comment by rheman** [comment]
I have changes auto_reconnect from true to false.
When I am connected in one browser and when I try to use the same user from another browser and automatically deconnecter from the previous browser. 

I have the following in my firefox console
```
_doDisconnect was called
Status changed to: DISCONNECTED
DISCONNECTED

```
Could someone know what's wrong with my settings ??

Best regard.

**Comment by rheman** [comment]
You where right the probleme was due to JID resource  Thanks a lot.
