### ISSUE TITLE
Problem with allow_contact_requests and xhr_user_search

### ISSUE THREAD

**Issue by rheman** [jcbrand/converse.js#943]
Hi everyone I have a probleme with `allow_contact_requests: true` and `xhr_user_search: true`

When I try to add a contact a search box appears but the search is not working. My users are well registered and in their vcard I have a fullname a nickname.
I dont no why the search is not working. Moreove I have enable debug mode (debug: true) but nothing appear in my firefox console.

I also want to know if it is possible to set a room is such a way that user can only acces room and cannot create room ? I have set `muc_instant_rooms` but user can still create rooms.

My environment looks as followed:

**ejabberd 16.09 with mod_mam support (mysql based)
conversejs lastest release (v 3.0.2) // I cannot use conversejs lastest release because my server does not support mam:2 for message_archiving**

My conversejs setting looks as followed.

```
converse.initialize({
            
            prebind_url: prebind_url,
            //credentials_url: credentials_url,
            keepalive: true,
            jid: user_jid,
            authentication: 'prebind',
            //authentication: 'login',
            bosh_service_url: bosh_service_url,
            use_vcards: true,
            allow_logout: false,
            allow_muc: true,
            notification_icon: emojione_image_path + 'conversejs128.png',
            muc_instant_rooms: false,
            hide_muc_server: true,
            allow_muc_invitations: false,
            /*
            allow_bookmarks: true,
            hide_muc_server: true,*/
            //use_emojione: true,
            //emojione_image_path: emojione_image_path,
            allow_chat_pending_contacts: true,
            allow_contact_requests: true,
            auto_reconnect: true,
            auto_login: true,
            animate: true,
            message_archiving: 'always',
            i18n: locales[language_code],
            archived_messages_page_size: 50,
            //message_archiving_timeout: 8000,
            //muc_history_max_stanzas: 12,
            message_carbons: true,
            default_domain : userxmppdomain,
            allow_contact_removal: false,
            allow_registration: false,
            debug: true,
            sounds_path: sounds_path,
            play_sounds: true,
            xhr_user_search: true,
            show_controlbox_by_default: true,
            strict_plugin_dependencies: false,
            visible_toolbar_buttons: {
                call: true,
                clear: true,
                emoji: true,
                toggle_occupants: true
            },
    });
```

Best regard.

**Comment by jcbrand** [comment]
Did you read the documentation for [xhr_user_search](https://conversejs.org/docs/html/configuration.html#xhr-user-search)? It needs a backend server which returns the search results. This is not included by default.

**Comment by rheman** [comment]
I have setup xhr_user_search_url as followed:

```
xhr_user_search: true,
xhr_user_search_url: 'http://esfam-elggtest.auf.org/piwal',
```

My xhr_user_search_url return the following entries:

`[{"id": "user1", "fullname": "Puewe Pessek"}, {"id": "user2", "fullname": "Hermand Pessek"}]`

But The search is still not working.

Best regard

**Comment by rheman** [comment]
Everything is working perfectly .. I just forget to empty my cache..
Thanks a lot.
