### ISSUE TITLE
Cant able to connect chat room  with converse js+openfire

### ISSUE THREAD

**Issue by kvinayak1991** [jcbrand/converse.js#946]
openfire UI:

first i create group chat service named 'chatservice1' and add admin users
then create a room id chatroom1@chatservice1.domainname
name is chatroom1
desc is chatroom1
didnt fill password
room occupants is null
add admin and members to it vin1@domainname,vin2@domainname,vin3@domainname

in converse ui

and login with user 
goto room by passing server name got that chatroom1
fill nick name vin1@domainname
or to join i pass room name is  chatroom1@chatservice1.domainname//chatroom1 both passed and servser name as domain name

but cant able to connect with room 

please help.....

**Comment by jcbrand** [comment]
Set `debug` to `true` when calling `converse.initialize` and look in the browser console for errors and information.

**Comment by kvinayak1991** [comment]
> on show room

converse.min.js:253 DEBUG: _throttledRequestHandler called with 1 requests
converse.min.js:253 DEBUG: _processRequest: first request has readyState of 1
converse.min.js:253 DEBUG: _throttledRequestHandler called with 2 requests
converse.min.js:253 DEBUG: _processRequest: first request has readyState of 1
converse.min.js:253 DEBUG: request id 24.0 posting
converse.min.js:253 DEBUG: request id 24.0 state changed to 1
converse.min.js:253 DEBUG: <body rid="317933562" xmlns="http://jabber.org/protocol/httpbind" sid="88tbzkw0fe"><iq to="XCPSERVER23" from="vin3@xcpserver23/converse.js-5589473" type="get" xmlns="jabber:client" id="d4ebd4d0-5a9d-4156-b136-01ddeb188c03:sendIQ"><query xmlns="http://jabber.org/protocol/disco#items"/></iq></body>
converse.min.js:253 DEBUG: request id 23.1 state changed to 2
converse.min.js:253 DEBUG: request id 23.1 state changed to 3
converse.min.js:253 DEBUG: request id 23.1 state changed to 4
converse.min.js:253 DEBUG: removing request
converse.min.js:253 DEBUG: _throttledRequestHandler called with 1 requests
converse.min.js:253 DEBUG: _processRequest: first request has readyState of 1
converse.min.js:253 DEBUG: request id 23 should now be removed
converse.min.js:253 DEBUG: request id 23.1 got 200
converse.min.js:253 INFO: _dataRecv called
converse.min.js:253 DEBUG: <body xmlns="http://jabber.org/protocol/httpbind" ack="317933562"/>
converse.min.js:253 DEBUG: request id 24.1 state changed to 2
converse.min.js:253 DEBUG: request id 24.1 state changed to 3
converse.min.js:253 DEBUG: request id 24.1 state changed to 4
converse.min.js:253 DEBUG: removing request
converse.min.js:253 DEBUG: _throttledRequestHandler called with 0 requests
converse.min.js:253 DEBUG: request id 24 should now be removed
converse.min.js:253 DEBUG: request id 24.1 got 200
converse.min.js:253 INFO: _dataRecv called
converse.min.js:253 DEBUG: <body xmlns="http://jabber.org/protocol/httpbind" ack="317933562"><iq xmlns="jabber:client" type="result" id="d4ebd4d0-5a9d-4156-b136-01ddeb188c03:sendIQ" from="xcpserver23" to="vin3@xcpserver23/converse.js-5589473"><query xmlns="http://jabber.org/protocol/disco#items"><item jid="broadcast.xcpserver23" name="Broadcast service"/><item jid="conference.xcpserver23" name="Public Chatrooms"/><item jid="pubsub.xcpserver23" name="Publish-Subscribe service"/><item jid="search.xcpserver23" name="User Search"/><item jid="chatroom1.xcpserver23" name="chatroom1"/><item jid="proxy.xcpserver23" name="Socks 5 Bytestreams Proxy"/></query></iq></body>
converse.min.js:253 INFO: no requests during idle cycle, sending blank request
converse.min.js:253 DEBUG: _throttledRequestHandler called with 1 requests
converse.min.js:253 DEBUG: request id 25.0 posting
converse.min.js:253 DEBUG: request id 25.0 state changed to 1
converse.min.js:253 DEBUG: <body rid="317933563" xmlns="http://jabber.org/protocol/httpbind" sid="88tbzkw0fe"/>
=============================================================================
on connect to chat room
converse.min.js:253 DEBUG: _throttledRequestHandler called with 1 requests
converse.min.js:253 DEBUG: _processRequest: first request has readyState of 1
converse.min.js:237 [Violation] 'click' handler took 2802ms
converse.min.js:253 DEBUG: _throttledRequestHandler called with 2 requests
converse.min.js:253 DEBUG: _processRequest: first request has readyState of 1
converse.min.js:253 DEBUG: request id 28.0 posting
converse.min.js:253 DEBUG: request id 28.0 state changed to 1
converse.min.js:253 DEBUG: <body rid="317933566" xmlns="http://jabber.org/protocol/httpbind" sid="88tbzkw0fe"><iq from="vin3@xcpserver23/converse.js-5589473" to="chatroom1.xcpserver23" type="get" xmlns="jabber:client" id="34f11817-edac-43c9-af6b-1668942ef898:sendIQ"><query xmlns="http://jabber.org/protocol/disco#info"/></iq></body>
converse.min.js:253 DEBUG: request id 27.1 state changed to 2
converse.min.js:253 DEBUG: request id 27.1 state changed to 3
converse.min.js:253 DEBUG: request id 27.1 state changed to 4
converse.min.js:253 DEBUG: removing request
converse.min.js:253 DEBUG: _throttledRequestHandler called with 1 requests
converse.min.js:253 DEBUG: _processRequest: first request has readyState of 1
converse.min.js:253 DEBUG: request id 27 should now be removed
converse.min.js:253 DEBUG: request id 27.1 got 200
converse.min.js:253 INFO: _dataRecv called
converse.min.js:253 DEBUG: <body xmlns="http://jabber.org/protocol/httpbind" ack="317933566"/>
converse.min.js:253 DEBUG: request id 28.1 state changed to 2
converse.min.js:253 DEBUG: request id 28.1 state changed to 3
converse.min.js:253 DEBUG: request id 28.1 state changed to 4
converse.min.js:253 DEBUG: removing request
converse.min.js:253 DEBUG: _throttledRequestHandler called with 0 requests
converse.min.js:253 DEBUG: request id 28 should now be removed
converse.min.js:253 DEBUG: request id 28.1 got 200
converse.min.js:253 INFO: _dataRecv called
converse.min.js:253 DEBUG: <body xmlns="http://jabber.org/protocol/httpbind" ack="317933566"><iq xmlns="jabber:client" type="result" id="34f11817-edac-43c9-af6b-1668942ef898:sendIQ" from="chatroom1.xcpserver23" to="vin3@xcpserver23/converse.js-5589473"><query xmlns="http://jabber.org/protocol/disco#info"><identity category="conference" name="chatroom1" type="text"/><identity category="directory" name="Public Chatroom Search" type="chatroom"/><feature var="http://jabber.org/protocol/muc"/><feature var="http://jabber.org/protocol/disco#info"/><feature var="http://jabber.org/protocol/disco#items"/><feature var="jabber:iq:search"/><feature var="http://jabber.org/protocol/rsm"/></query></iq></body>
converse.min.js:253 DEBUG: _throttledRequestHandler called with 0 requests
converse.min.js:253 DEBUG: _throttledRequestHandler called with 1 requests
converse.min.js:253 DEBUG: request id 29.0 posting
converse.min.js:253 DEBUG: request id 29.0 state changed to 1
converse.min.js:253 DEBUG: <body rid="317933567" xmlns="http://jabber.org/protocol/httpbind" sid="88tbzkw0fe"><presence from="vin3@xcpserver23/converse.js-5589473" to="null@chatroom1.xcpserver23/vin3" xmlns="jabber:client"><x xmlns="http://jabber.org/protocol/muc"><history/></x></presence></body>
converse.min.js:253 DEBUG: request id 29.1 state changed to 2
converse.min.js:253 DEBUG: request id 29.1 state changed to 3
converse.min.js:253 DEBUG: request id 29.1 state changed to 4
converse.min.js:253 DEBUG: removing request
converse.min.js:253 DEBUG: _throttledRequestHandler called with 0 requests
converse.min.js:253 DEBUG: request id 29 should now be removed
converse.min.js:253 DEBUG: request id 29.1 got 200
converse.min.js:253 INFO: _dataRecv called
converse.min.js:253 DEBUG: <body xmlns="http://jabber.org/protocol/httpbind" ack="317933567"><presence xmlns="jabber:client" from="null@chatroom1.xcpserver23/vin3" to="vin3@xcpserver23/converse.js-5589473" type="error"><x xmlns="http://jabber.org/protocol/muc"><history/></x><error code="404" type="cancel"><item-not-found xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"/></error></presence></body>
converse.min.js:253 INFO: no requests during idle cycle, sending blank request
converse.min.js:253 DEBUG: _throttledRequestHandler called with 1 requests
converse.min.js:253 DEBUG: request id 30.0 posting
converse.min.js:253 DEBUG: request id 30.0 state changed to 1
converse.min.js:253 DEBUG: <body rid="317933568" xmlns="http://jabber.org/protocol/httpbind" sid="88tbzkw0fe"/>

**Comment by kvinayak1991** [comment]
on show room

converse.min.js:253 DEBUG: _throttledRequestHandler called with 1 requests
converse.min.js:253 DEBUG: _processRequest: first request has readyState of 1
converse.min.js:253 DEBUG: _throttledRequestHandler called with 2 requests
converse.min.js:253 DEBUG: _processRequest: first request has readyState of 1
converse.min.js:253 DEBUG: request id 24.0 posting
converse.min.js:253 DEBUG: request id 24.0 state changed to 1
converse.min.js:253 DEBUG: <body rid="317933562" xmlns="http://jabber.org/protocol/httpbind" sid="88tbzkw0fe"><iq to="XCPSERVER23" from="vin3@xcpserver23/converse.js-5589473" type="get" xmlns="jabber:client" id="d4ebd4d0-5a9d-4156-b136-01ddeb188c03:sendIQ"><query xmlns="http://jabber.org/protocol/disco#items"/></iq></body>
converse.min.js:253 DEBUG: request id 23.1 state changed to 2
converse.min.js:253 DEBUG: request id 23.1 state changed to 3
converse.min.js:253 DEBUG: request id 23.1 state changed to 4
converse.min.js:253 DEBUG: removing request
converse.min.js:253 DEBUG: _throttledRequestHandler called with 1 requests
converse.min.js:253 DEBUG: _processRequest: first request has readyState of 1
converse.min.js:253 DEBUG: request id 23 should now be removed
converse.min.js:253 DEBUG: request id 23.1 got 200
converse.min.js:253 INFO: _dataRecv called
converse.min.js:253 DEBUG: <body xmlns="http://jabber.org/protocol/httpbind" ack="317933562"/>
converse.min.js:253 DEBUG: request id 24.1 state changed to 2
converse.min.js:253 DEBUG: request id 24.1 state changed to 3
converse.min.js:253 DEBUG: request id 24.1 state changed to 4
converse.min.js:253 DEBUG: removing request
converse.min.js:253 DEBUG: _throttledRequestHandler called with 0 requests
converse.min.js:253 DEBUG: request id 24 should now be removed
converse.min.js:253 DEBUG: request id 24.1 got 200
converse.min.js:253 INFO: _dataRecv called
converse.min.js:253 DEBUG: <body xmlns="http://jabber.org/protocol/httpbind" ack="317933562"><iq xmlns="jabber:client" type="result" id="d4ebd4d0-5a9d-4156-b136-01ddeb188c03:sendIQ" from="xcpserver23" to="vin3@xcpserver23/converse.js-5589473"><query xmlns="http://jabber.org/protocol/disco#items"><item jid="broadcast.xcpserver23" name="Broadcast service"/><item jid="conference.xcpserver23" name="Public Chatrooms"/><item jid="pubsub.xcpserver23" name="Publish-Subscribe service"/><item jid="search.xcpserver23" name="User Search"/><item jid="chatroom1.xcpserver23" name="chatroom1"/><item jid="proxy.xcpserver23" name="Socks 5 Bytestreams Proxy"/></query></iq></body>
converse.min.js:253 INFO: no requests during idle cycle, sending blank request
converse.min.js:253 DEBUG: _throttledRequestHandler called with 1 requests
converse.min.js:253 DEBUG: request id 25.0 posting
converse.min.js:253 DEBUG: request id 25.0 state changed to 1
converse.min.js:253 DEBUG: <body rid="317933563" xmlns="http://jabber.org/protocol/httpbind" sid="88tbzkw0fe"/>
=============================================================================
on connect to chat room
converse.min.js:253 DEBUG: _throttledRequestHandler called with 1 requests
converse.min.js:253 DEBUG: _processRequest: first request has readyState of 1
converse.min.js:237 [Violation] 'click' handler took 2802ms
converse.min.js:253 DEBUG: _throttledRequestHandler called with 2 requests
converse.min.js:253 DEBUG: _processRequest: first request has readyState of 1
converse.min.js:253 DEBUG: request id 28.0 posting
converse.min.js:253 DEBUG: request id 28.0 state changed to 1
converse.min.js:253 DEBUG: <body rid="317933566" xmlns="http://jabber.org/protocol/httpbind" sid="88tbzkw0fe"><iq from="vin3@xcpserver23/converse.js-5589473" to="chatroom1.xcpserver23" type="get" xmlns="jabber:client" id="34f11817-edac-43c9-af6b-1668942ef898:sendIQ"><query xmlns="http://jabber.org/protocol/disco#info"/></iq></body>
converse.min.js:253 DEBUG: request id 27.1 state changed to 2
converse.min.js:253 DEBUG: request id 27.1 state changed to 3
converse.min.js:253 DEBUG: request id 27.1 state changed to 4
converse.min.js:253 DEBUG: removing request
converse.min.js:253 DEBUG: _throttledRequestHandler called with 1 requests
converse.min.js:253 DEBUG: _processRequest: first request has readyState of 1
converse.min.js:253 DEBUG: request id 27 should now be removed
converse.min.js:253 DEBUG: request id 27.1 got 200
converse.min.js:253 INFO: _dataRecv called
converse.min.js:253 DEBUG: <body xmlns="http://jabber.org/protocol/httpbind" ack="317933566"/>
converse.min.js:253 DEBUG: request id 28.1 state changed to 2
converse.min.js:253 DEBUG: request id 28.1 state changed to 3
converse.min.js:253 DEBUG: request id 28.1 state changed to 4
converse.min.js:253 DEBUG: removing request
converse.min.js:253 DEBUG: _throttledRequestHandler called with 0 requests
converse.min.js:253 DEBUG: request id 28 should now be removed
converse.min.js:253 DEBUG: request id 28.1 got 200
converse.min.js:253 INFO: _dataRecv called
converse.min.js:253 DEBUG: <body xmlns="http://jabber.org/protocol/httpbind" ack="317933566"><iq xmlns="jabber:client" type="result" id="34f11817-edac-43c9-af6b-1668942ef898:sendIQ" from="chatroom1.xcpserver23" to="vin3@xcpserver23/converse.js-5589473"><query xmlns="http://jabber.org/protocol/disco#info"><identity category="conference" name="chatroom1" type="text"/><identity category="directory" name="Public Chatroom Search" type="chatroom"/><feature var="http://jabber.org/protocol/muc"/><feature var="http://jabber.org/protocol/disco#info"/><feature var="http://jabber.org/protocol/disco#items"/><feature var="jabber:iq:search"/><feature var="http://jabber.org/protocol/rsm"/></query></iq></body>
converse.min.js:253 DEBUG: _throttledRequestHandler called with 0 requests
converse.min.js:253 DEBUG: _throttledRequestHandler called with 1 requests
converse.min.js:253 DEBUG: request id 29.0 posting
converse.min.js:253 DEBUG: request id 29.0 state changed to 1
converse.min.js:253 DEBUG: <body rid="317933567" xmlns="http://jabber.org/protocol/httpbind" sid="88tbzkw0fe"><presence from="vin3@xcpserver23/converse.js-5589473" to="null@chatroom1.xcpserver23/vin3" xmlns="jabber:client"><x xmlns="http://jabber.org/protocol/muc"><history/></x></presence></body>
converse.min.js:253 DEBUG: request id 29.1 state changed to 2
converse.min.js:253 DEBUG: request id 29.1 state changed to 3
converse.min.js:253 DEBUG: request id 29.1 state changed to 4
converse.min.js:253 DEBUG: removing request
converse.min.js:253 DEBUG: _throttledRequestHandler called with 0 requests
converse.min.js:253 DEBUG: request id 29 should now be removed
converse.min.js:253 DEBUG: request id 29.1 got 200
converse.min.js:253 INFO: _dataRecv called
converse.min.js:253 DEBUG: <body xmlns="http://jabber.org/protocol/httpbind" ack="317933567"><presence xmlns="jabber:client" from="null@chatroom1.xcpserver23/vin3" to="vin3@xcpserver23/converse.js-5589473" type="error"><x xmlns="http://jabber.org/protocol/muc"><history/></x><error code="404" type="cancel"><item-not-found xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"/></error></presence></body>
converse.min.js:253 INFO: no requests during idle cycle, sending blank request
converse.min.js:253 DEBUG: _throttledRequestHandler called with 1 requests
converse.min.js:253 DEBUG: request id 30.0 posting
converse.min.js:253 DEBUG: request id 30.0 state changed to 1
converse.min.js:253 DEBUG: <body rid="317933568" xmlns="http://jabber.org/protocol/httpbind" sid="88tbzkw0fe"/>

**Comment by kvinayak1991** [comment]
on show room

converse.min.js:253 DEBUG: _throttledRequestHandler called with 1 requests
converse.min.js:253 DEBUG: _processRequest: first request has readyState of 1
converse.min.js:253 DEBUG: _throttledRequestHandler called with 2 requests
converse.min.js:253 DEBUG: _processRequest: first request has readyState of 1
converse.min.js:253 DEBUG: request id 24.0 posting
converse.min.js:253 DEBUG: request id 24.0 state changed to 1
converse.min.js:253 DEBUG: <body rid="317933562" xmlns="http://jabber.org/protocol/httpbind" sid="88tbzkw0fe"><iq to="XCPSERVER23" from="vin3@xcpserver23/converse.js-5589473" type="get" xmlns="jabber:client" id="d4ebd4d0-5a9d-4156-b136-01ddeb188c03:sendIQ"><query xmlns="http://jabber.org/protocol/disco#items"/></iq></body>
converse.min.js:253 DEBUG: request id 23.1 state changed to 2
converse.min.js:253 DEBUG: request id 23.1 state changed to 3
converse.min.js:253 DEBUG: request id 23.1 state changed to 4
converse.min.js:253 DEBUG: removing request
converse.min.js:253 DEBUG: _throttledRequestHandler called with 1 requests
converse.min.js:253 DEBUG: _processRequest: first request has readyState of 1
converse.min.js:253 DEBUG: request id 23 should now be removed
converse.min.js:253 DEBUG: request id 23.1 got 200
converse.min.js:253 INFO: _dataRecv called
converse.min.js:253 DEBUG: <body xmlns="http://jabber.org/protocol/httpbind" ack="317933562"/>
converse.min.js:253 DEBUG: request id 24.1 state changed to 2
converse.min.js:253 DEBUG: request id 24.1 state changed to 3
converse.min.js:253 DEBUG: request id 24.1 state changed to 4
converse.min.js:253 DEBUG: removing request
converse.min.js:253 DEBUG: _throttledRequestHandler called with 0 requests
converse.min.js:253 DEBUG: request id 24 should now be removed
converse.min.js:253 DEBUG: request id 24.1 got 200
converse.min.js:253 INFO: _dataRecv called
converse.min.js:253 DEBUG: <body xmlns="http://jabber.org/protocol/httpbind" ack="317933562"><iq xmlns="jabber:client" type="result" id="d4ebd4d0-5a9d-4156-b136-01ddeb188c03:sendIQ" from="xcpserver23" to="vin3@xcpserver23/converse.js-5589473"><query xmlns="http://jabber.org/protocol/disco#items"><item jid="broadcast.xcpserver23" name="Broadcast service"/><item jid="conference.xcpserver23" name="Public Chatrooms"/><item jid="pubsub.xcpserver23" name="Publish-Subscribe service"/><item jid="search.xcpserver23" name="User Search"/><item jid="chatroom1.xcpserver23" name="chatroom1"/><item jid="proxy.xcpserver23" name="Socks 5 Bytestreams Proxy"/></query></iq></body>
converse.min.js:253 INFO: no requests during idle cycle, sending blank request
converse.min.js:253 DEBUG: _throttledRequestHandler called with 1 requests
converse.min.js:253 DEBUG: request id 25.0 posting
converse.min.js:253 DEBUG: request id 25.0 state changed to 1
converse.min.js:253 DEBUG: <body rid="317933563" xmlns="http://jabber.org/protocol/httpbind" sid="88tbzkw0fe"/>
=============================================================================
on connect to chat room
converse.min.js:253 DEBUG: _throttledRequestHandler called with 1 requests
converse.min.js:253 DEBUG: _processRequest: first request has readyState of 1
converse.min.js:237 [Violation] 'click' handler took 2802ms
converse.min.js:253 DEBUG: _throttledRequestHandler called with 2 requests
converse.min.js:253 DEBUG: _processRequest: first request has readyState of 1
converse.min.js:253 DEBUG: request id 28.0 posting
converse.min.js:253 DEBUG: request id 28.0 state changed to 1
converse.min.js:253 DEBUG: <body rid="317933566" xmlns="http://jabber.org/protocol/httpbind" sid="88tbzkw0fe"><iq from="vin3@xcpserver23/converse.js-5589473" to="chatroom1.xcpserver23" type="get" xmlns="jabber:client" id="34f11817-edac-43c9-af6b-1668942ef898:sendIQ"><query xmlns="http://jabber.org/protocol/disco#info"/></iq></body>
converse.min.js:253 DEBUG: request id 27.1 state changed to 2
converse.min.js:253 DEBUG: request id 27.1 state changed to 3
converse.min.js:253 DEBUG: request id 27.1 state changed to 4
converse.min.js:253 DEBUG: removing request
converse.min.js:253 DEBUG: _throttledRequestHandler called with 1 requests
converse.min.js:253 DEBUG: _processRequest: first request has readyState of 1
converse.min.js:253 DEBUG: request id 27 should now be removed
converse.min.js:253 DEBUG: request id 27.1 got 200
converse.min.js:253 INFO: _dataRecv called
converse.min.js:253 DEBUG: <body xmlns="http://jabber.org/protocol/httpbind" ack="317933566"/>
converse.min.js:253 DEBUG: request id 28.1 state changed to 2
converse.min.js:253 DEBUG: request id 28.1 state changed to 3
converse.min.js:253 DEBUG: request id 28.1 state changed to 4
converse.min.js:253 DEBUG: removing request
converse.min.js:253 DEBUG: _throttledRequestHandler called with 0 requests
converse.min.js:253 DEBUG: request id 28 should now be removed
converse.min.js:253 DEBUG: request id 28.1 got 200
converse.min.js:253 INFO: _dataRecv called
converse.min.js:253 DEBUG: <body xmlns="http://jabber.org/protocol/httpbind" ack="317933566"><iq xmlns="jabber:client" type="result" id="34f11817-edac-43c9-af6b-1668942ef898:sendIQ" from="chatroom1.xcpserver23" to="vin3@xcpserver23/converse.js-5589473"><query xmlns="http://jabber.org/protocol/disco#info"><identity category="conference" name="chatroom1" type="text"/><identity category="directory" name="Public Chatroom Search" type="chatroom"/><feature var="http://jabber.org/protocol/muc"/><feature var="http://jabber.org/protocol/disco#info"/><feature var="http://jabber.org/protocol/disco#items"/><feature var="jabber:iq:search"/><feature var="http://jabber.org/protocol/rsm"/></query></iq></body>
converse.min.js:253 DEBUG: _throttledRequestHandler called with 0 requests
converse.min.js:253 DEBUG: _throttledRequestHandler called with 1 requests
converse.min.js:253 DEBUG: request id 29.0 posting
converse.min.js:253 DEBUG: request id 29.0 state changed to 1
converse.min.js:253 DEBUG: <body rid="317933567" xmlns="http://jabber.org/protocol/httpbind" sid="88tbzkw0fe"><presence from="vin3@xcpserver23/converse.js-5589473" to="null@chatroom1.xcpserver23/vin3" xmlns="jabber:client"><x xmlns="http://jabber.org/protocol/muc"><history/></x></presence></body>
converse.min.js:253 DEBUG: request id 29.1 state changed to 2
converse.min.js:253 DEBUG: request id 29.1 state changed to 3
converse.min.js:253 DEBUG: request id 29.1 state changed to 4
converse.min.js:253 DEBUG: removing request
converse.min.js:253 DEBUG: _throttledRequestHandler called with 0 requests
converse.min.js:253 DEBUG: request id 29 should now be removed
converse.min.js:253 DEBUG: request id 29.1 got 200
converse.min.js:253 INFO: _dataRecv called
converse.min.js:253 DEBUG: <body xmlns="http://jabber.org/protocol/httpbind" ack="317933567"><presence xmlns="jabber:client" from="null@chatroom1.xcpserver23/vin3" to="vin3@xcpserver23/converse.js-5589473" type="error"><x xmlns="http://jabber.org/protocol/muc"><history/></x><error code="404" type="cancel"><item-not-found xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"/></error></presence></body>
converse.min.js:253 INFO: no requests during idle cycle, sending blank request
converse.min.js:253 DEBUG: _throttledRequestHandler called with 1 requests
converse.min.js:253 DEBUG: request id 30.0 posting
converse.min.js:253 DEBUG: request id 30.0 state changed to 1
converse.min.js:253 DEBUG: <body rid="317933568" xmlns="http://jabber.org/protocol/httpbind" sid="88tbzkw0fe"/>

**Comment by jcbrand** [comment]
```
<presence xmlns="jabber:client" from="null@chatroom1.xcpserver23/vin3"
```

You didn't seem to give the room a proper name?

**Comment by kvinayak1991** [comment]
![untitled](https://user-images.githubusercontent.com/32790386/32485090-28aeb1d4-c3c8-11e7-96c4-dacea5e3dcf3.jpg)

**Comment by kvinayak1991** [comment]
![untitled](https://user-images.githubusercontent.com/32790386/32485206-9026de5e-c3c8-11e7-889c-37d099e9e53e.jpg)

**Comment by kvinayak1991** [comment]
null room automatically get created

**Comment by kvinayak1991** [comment]
![untitled](https://user-images.githubusercontent.com/32790386/32485833-bb52e2ce-c3ca-11e7-8a76-7e52fc280591.jpg)

**Comment by kvinayak1991** [comment]
on join room

DEBUG: _throttledRequestHandler called with 1 requests
converse.min.js:253 DEBUG: _processRequest: first request has readyState of 1
converse.min.js:237 [Violation] 'submit' handler took 464ms
converse.min.js:253 DEBUG: _throttledRequestHandler called with 2 requests
converse.min.js:253 DEBUG: _processRequest: first request has readyState of 1
converse.min.js:253 DEBUG: request id 19.0 posting
converse.min.js:253 DEBUG: request id 19.0 state changed to 1
converse.min.js:253 DEBUG: <body rid="2229767664" xmlns="http://jabber.org/protocol/httpbind" sid="3feksdc1pt"><iq from="vin2@xcpserver23/converse.js-49128002" to="chatroom\40chatservice.xcpserver23@xcpserver23" type="get" xmlns="jabber:client" id="7acdc202-44f7-41b1-92bb-d6674ad6ddcb:sendIQ"><query xmlns="http://jabber.org/protocol/disco#info"/></iq></body>
converse.min.js:253 DEBUG: request id 18.1 state changed to 2
converse.min.js:253 DEBUG: request id 18.1 state changed to 3
converse.min.js:253 DEBUG: request id 18.1 state changed to 4
converse.min.js:253 DEBUG: removing request
converse.min.js:253 DEBUG: _throttledRequestHandler called with 1 requests
converse.min.js:253 DEBUG: _processRequest: first request has readyState of 1
converse.min.js:253 DEBUG: request id 18 should now be removed
converse.min.js:253 DEBUG: request id 18.1 got 200
converse.min.js:253 INFO: _dataRecv called
converse.min.js:253 DEBUG: <body xmlns="http://jabber.org/protocol/httpbind" ack="2229767664"/>
converse.min.js:253 DEBUG: request id 19.1 state changed to 2
converse.min.js:253 DEBUG: request id 19.1 state changed to 3
converse.min.js:253 DEBUG: request id 19.1 state changed to 4
converse.min.js:253 DEBUG: removing request
converse.min.js:253 DEBUG: _throttledRequestHandler called with 0 requests
converse.min.js:253 DEBUG: request id 19 should now be removed
converse.min.js:253 DEBUG: request id 19.1 got 200
converse.min.js:253 INFO: _dataRecv called
converse.min.js:253 DEBUG: <body xmlns="http://jabber.org/protocol/httpbind" ack="2229767664"><iq xmlns="jabber:client" type="error" id="7acdc202-44f7-41b1-92bb-d6674ad6ddcb:sendIQ" from="chatroom\40chatservice.xcpserver23@xcpserver23" to="vin2@xcpserver23/converse.js-49128002"><query xmlns="http://jabber.org/protocol/disco#info"/><error code="404" type="cancel"><item-not-found xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"/></error></iq></body>
converse.min.js:253 DEBUG: _throttledRequestHandler called with 0 requests
converse.min.js:253 DEBUG: _throttledRequestHandler called with 1 requests
converse.min.js:253 DEBUG: request id 20.0 posting
converse.min.js:253 DEBUG: request id 20.0 state changed to 1
converse.min.js:253 DEBUG: <body rid="2229767665" xmlns="http://jabber.org/protocol/httpbind" sid="3feksdc1pt"><iq to="chatroom\40chatservice.xcpserver23@xcpserver23" from="vin2@xcpserver23/converse.js-49128002" type="get" xmlns="jabber:client" id="8ac71285-9c6f-4063-a6ca-15cf4b143c9e:sendIQ"><query xmlns="http://jabber.org/protocol/disco#info" node="x-roomuser-item"/></iq></body>
converse.min.js:253 DEBUG: request id 20.1 state changed to 2
converse.min.js:253 DEBUG: request id 20.1 state changed to 3
converse.min.js:253 DEBUG: request id 20.1 state changed to 4
converse.min.js:253 DEBUG: removing request
converse.min.js:253 DEBUG: _throttledRequestHandler called with 0 requests
converse.min.js:253 DEBUG: request id 20 should now be removed
converse.min.js:253 DEBUG: request id 20.1 got 200
converse.min.js:253 INFO: _dataRecv called
converse.min.js:253 DEBUG: <body xmlns="http://jabber.org/protocol/httpbind" ack="2229767665"><iq xmlns="jabber:client" type="error" id="8ac71285-9c6f-4063-a6ca-15cf4b143c9e:sendIQ" from="chatroom\40chatservice.xcpserver23@xcpserver23" to="vin2@xcpserver23/converse.js-49128002"><query xmlns="http://jabber.org/protocol/disco#info" node="x-roomuser-item"/><error code="404" type="cancel"><item-not-found xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"/></error></iq></body>
converse.min.js:253 DEBUG: _throttledRequestHandler called with 0 requests
converse.min.js:253 DEBUG: _throttledRequestHandler called with 1 requests
converse.min.js:253 DEBUG: request id 21.0 posting
converse.min.js:253 DEBUG: request id 21.0 state changed to 1
converse.min.js:253 DEBUG: <body rid="2229767666" xmlns="http://jabber.org/protocol/httpbind" sid="3feksdc1pt"><presence from="vin2@xcpserver23/converse.js-49128002" to="chatroom\40chatservice.xcpserver23@xcpserver23/vin2" xmlns="jabber:client"><x xmlns="http://jabber.org/protocol/muc"><history/></x></presence></body>

**Comment by jcbrand** [comment]
I mean when you join the room with converse.js, not in OpenFire.

 When you paste logs, put three backticks arround then ``` ``` ```, otherwise they don't render properly.

**Comment by kvinayak1991** [comment]
![untitled](https://user-images.githubusercontent.com/32790386/32490725-3b8406d0-c3da-11e7-9829-f74df8c93284.jpg)

Yes

**Comment by jcbrand** [comment]
In "Room name" you should only give "chatroomfun".

In server, you should give "chatservice.xcpserver23" or whatever your MUC component's domain is.

**Comment by kvinayak1991** [comment]
Thanks alot its workin properly :-)
