### ISSUE TITLE
Inverse.js: The chat features panel is opened when configuring a room

### ISSUE THREAD

**Issue by Reventl0v** [jcbrand/converse.js#950]
Hi,
In inverse.js, if you click on the "configure this room" icon in a muc, with the "list of occupant" pane being closed, leaving the "configure this room" mode leaves the "Features" pane open, with the "list of occupant" pane being closed. The class "hidden" is not set on the parent div "occupant".
Screenshot of this issue: https://ptpb.pw/Yzho.png (browser tested: firefox 57 and chromium 62).

**Comment by jcbrand** [comment]
Fixed in master. Will be released soon.
