### ISSUE TITLE
Converse.js/InVerse not dealing correctly with MUC MAM/History and not clearing browser storage when leaving, causing duplicates.

### ISSUE THREAD

**Issue by maranda** [jcbrand/converse.js#951]
The first causes duplicates because both muc history and MAM query results are returned without proper deduplication, the second keeps duplicating messages because the browser storage isn't properly cleared when leaving the room.

I for now manually patched both the join() and leave() MUC functions but probably more proper changes are in order.
To join() I added:
```javascript
var max_stanzas = this.model.get('mam_enabled') ? "0" : _converse.muc_history_max_stanzas;
var stanza = $pres({
  'from': _converse.connection.jid,
  'to': this.getRoomJIDAndNick(nick)
}).c("x", { 'xmlns': Strophe.NS.MUC }).c("history", { 'maxstanzas': max_stanzas }).up();
```
to prevent requesting the room history if MAM is available, but deduplication checking the id of message returned by MAM and the History's is desiderable.
To leave() I added:
```javascript
this.model.messages.reset();
this.model.messages.browserStorage._clear();
```
To clear out the messages both in the ui and browser storage when a room is parted, and prevent further duplication.

**Comment by jcbrand** [comment]
Deduplication happens here:
https://github.com/jcbrand/converse.js/blob/master/src/converse-chatboxes.js#L198

I use converse.js daily and don't get duplicate messages, so there must be something peculiar about your setup or your XMPP server.

Perhaps your XMPP server doesn't always return the same archive message ids or something like that.

You can step through the above linked code with the debugger to see what happens.

Another section of the code you can check is this:
https://github.com/jcbrand/converse.js/blob/master/src/converse-mam.js#L154

**Comment by maranda** [comment]
@jcbrand I'm unable to find the bit which interests me, so... out of curiousity which message id does it check...? The "result" message stanza id attribute or the forwarded original message's? Because the former wouldn't be correct tbh.

**Comment by maranda** [comment]
@jcbrand okay that's indeed the culprit, InVerse relies on the id attribute of the first message stanza, while Metronome doesn't add any id to the result message closures but does for the forwarded message.

```xml
<message to='***'>
<result id='db9e6ff5-f291-4e0b-93c0-7a4fb641533c' queryid='f27' xmlns='urn:xmpp:mam:2'>
<forwarded xmlns='urn:xmpp:forward:0'>
<delay stamp='2017-11-08T00:24:29Z' xmlns='urn:xmpp:delay'/>
<message id='2b07b63b-425c-4748-afd6-74f0905c7425' type='groupchat' from='grimoire@muc.metronome.im/Maranda'>
<body>@ping</body>
</message>
</forwarded>
</result>
</message>
```

**Comment by maranda** [comment]
@jcbrand Sorry for the bourden and also sorry I deleted the previous messages but for cleanliness I better condense what I found investigating a bit more, since you talked about ids I thought the problem could be related with Metronome sending archive result message stanza enclosures without an id (which by a protocol perspective is perfectly fine) so I tried to set as the message stanza id attribute the result entry id. 
But that didn't work and to exclude it could be caused by any modification I did I also used your (http://inverse.chat)[InVerse Instance] and the dupes still happened not only with history (which was to be expected because the ids would still be different) but also leaving and rejoining the room caused the problem mentioned in the issue.

I'm at an empasse here, I'm honestly curious to know which server implementation of MAM do you use that doesn't cause this issue because if conversejs/inverse.js really solely rely (and I won't say that's the case because I barely scoured a little bit of the code) on IDs for deduplication I'd need to replicate the original message id attribute on the result enclosure which imho would also hickup with XEP-359.

I tried to make my server implementation to be strictly compliant to mam:2, and if the quirk is on my end I'd be glad to rectify it (this is the server (https://lightwitch.org/)[my server] if you need to test), but I can't seem to get a different answer from the issue topic, so maybe four eyes will help instead of just two 👍 .

**Comment by jcbrand** [comment]
@maranda To be honest, it's been more than a year that I worked on that code and I don't remember clearly anymore how it works :)

So to figure it out, I would have to spend some time debugging and going through the code again.

I haven't added support for [XEP-0359](https://xmpp.org/extensions/xep-0359.html) yet, but that would probably be the best way to do deduplication.

I'll try to find time to register an account on your server to test with.

**Comment by jcbrand** [comment]
I've taken a look at this issue yesterday and was able to reproduce it, also in a test.

The fix is in this commit: https://github.com/jcbrand/converse.js/commit/31e884f79ad47df3b8d758646ebbc38adabba9f3

That said, I think your server should also include `<stanza-id>` elements when it returns MAM archived messages. XEP-0313 is unclear to me on whether this is required or simply optional. I assume however it's required. I asked a question about that here: https://github.com/xsf/xeps/issues/567

**Comment by maranda** [comment]
Thanks, my server is compliant to mam:2 as I said so it does include stanza-id elements for stored messages, also for all reflected stanzas in mucs.

It did when I posted this issue 😃

**Comment by jcbrand** [comment]
From what I could tell, when I do a MAM query, I didn't get `<stanza-id>` elements.

I used stanzas from your server directly in my test, and you can see there that the MAM result stanza doesn't have a stanza-id:

https://github.com/jcbrand/converse.js/blob/master/spec/mam.js#L33

**Comment by maranda** [comment]
OH... no wait, you're not supposed to get it in the query results, stanza-ids are appended to the messages to tell a user a stanza was archived only (and only if said user has access to the archive), so they're either in the received or reflected messages.

**Comment by maranda** [comment]
@jcbrand see https://xmpp.org/extensions/xep-0313.html#archives_id

**Comment by maranda** [comment]
The correct approach would be matching against the result element id attribute https://github.com/jcbrand/converse.js/blob/master/spec/mam.js#L34 as I explained in my previous posts for deduplication.

**Comment by jcbrand** [comment]
This has been fixed.
