### ISSUE TITLE
Dead Link to list of XMPP providers

### ISSUE THREAD

**Issue by RainerBielefeld** [jcbrand/converse.js#952]
Hello,
[here](https://conversejs.org/) in the German Language Registration-TAB I see:
"Tipp: Eine Liste öffentlicher Provider ist verfügbar [hier](https://xmpp.net/directory.php)."

Clicking the link behind "hier" shows "404 Not Found   nginx/1.6.2" instead of a list.

**Comment by jcbrand** [comment]
The link is up again.
