### ISSUE TITLE
MUC "caracteristics" displayed when getting out of MUC configuration

### ISSUE THREAD

**Issue by StinGer-ShoGuN** [jcbrand/converse.js#953]
Hello all.

I spotted a visual glitch with Converse.js (not tested other tools). I searched the issues and it seems it's not reported yet.

I am using https://converse.js (don't know what version is there).

### Steps to reproduce
0. Join a MUC.
1. Hide the member list.
2. Go the the MUC administration (the little wrench, top right).
3. Cancel.
4. You've got the room caracteristics overlayed and you can't get rid of it.

Good luck tracking it ! 😉

**Comment by jcbrand** [comment]
Thanks for the bug report and explaining how to reproduce. I'll take a look before the next release.
