### ISSUE TITLE
ERROR: An error occured while trying to set archiving preferences.

### ISSUE THREAD

**Issue by RafalxM** [jcbrand/converse.js#958]
I'm using  Converse 3.2.1 with Ejabberd 17.8 

with option:
`message_archiving: 'always'`   

i get no archive from server, only console message:

`ERROR: An error occured while trying to set archiving preferences.`

ejabberd has mod_mam enabled, messages are stored in db.

any idea?

**Comment by jcbrand** [comment]
Not sure. Check your server's logs.

**Comment by RafalxM** [comment]
I found a reason...it's look like ejabberd 17.8(deb) stil using MAM0  ...
I will try to install 17.11  but not sure it will fix the problem,  so I have few questions:

1. is there an option iwth conversion 3.2.1 to use MAM0 instead  MAM2 ?
2. what is latest version of coverse that uses  MAM0?
3. is there any known jabber server that handle MAM2 ?

Thank you.

**Comment by jcbrand** [comment]
Converse.js doesn't support MAM:0 anymore. 3.1.1 is that last version that supported it. Prosody handles MAM2.

**Comment by RafalxM** [comment]
Some info after upgrade to  ejabberd 17.11(deb)  , converse 3.2.1

MAM:2  works  fine

With converse option `message_archiving: 'always'` now  I get  archive messages in chat boxes

Thank you.
