### ISSUE TITLE
iPhone x and position

### ISSUE THREAD

**Issue by camaran** [jcbrand/converse.js#959]
Fix position in iPhone X

**Comment by jcbrand** [comment]
This looks to be related: https://webkit.org/blog/7929/designing-websites-for-iphone-x/

Is it possible to do this without an iPhone X?

**Comment by camaran** [comment]
Yes it's for the reason you link.
Yes but you cannot try it, i can try if is fixed for you but you must give me a page to see

**Comment by camaran** [comment]
#conversejs {
        padding-left: env(safe-area-inset-left);
        padding-right: env(safe-area-inset-right);
    }
already tested

**Comment by jcbrand** [comment]
Please make a pull request @camaran, then I'll merge.
