### ISSUE TITLE
Uncaught SyntaxError: Invalid regular expression: /(+)/: Nothing to repeat

### ISSUE THREAD

**Issue by vitalii-kushnir** [jcbrand/converse.js#964]
1. I have created two test accounts (+49900000001 and +49900000002) on the **conversjs.com** domain. 
1. I joined to the testing room with the **+49900000001** account and want to invite another account (+49900000002) to this room
1. In the **Invite** input field I typed **+49**

**Expected**: I expect to see a list of account which I could invite
**Result**: Uncaught SyntaxError: Invalid regular expression: /(+)/: Nothing to repeat 

`converse.min.js:275 Uncaught SyntaxError: Invalid regular expression: /(+)/: Nothing to repeat
    at new RegExp (<anonymous>)
    at a.ITEM [as item] (converse.min.js:275)
    at converse.min.js:275
    at Array.forEach (<anonymous>)
    at a.evaluate (converse.min.js:275)
a.ITEM @ converse.min.js:275
(anonymous) @ converse.min.js:275
evaluate @ converse.min.js:275`

`converse.min.js:275 Uncaught SyntaxError: Invalid regular expression: /(+4)/: Nothing to repeat
    at new RegExp (<anonymous>)
    at a.ITEM [as item] (converse.min.js:275)
    at converse.min.js:275
    at Array.forEach (<anonymous>)
    at a.evaluate (converse.min.js:275)
a.ITEM @ converse.min.js:275`

`(anonymous) @ converse.min.js:275
evaluate @ converse.min.js:275
converse.min.js:275 Uncaught SyntaxError: Invalid regular expression: /(+49)/: Nothing to repeat
    at new RegExp (<anonymous>)
    at a.ITEM [as item] (converse.min.js:275)
    at converse.min.js:275
    at Array.forEach (<anonymous>)
    at a.evaluate (converse.min.js:275)`

![error](https://user-images.githubusercontent.com/30949148/33996301-1861eb08-e0e1-11e7-8b18-6042bec51977.png)

**Comment by jcbrand** [comment]
Thanks for the bug report.

This is a bug in [awesomplete.js](https://github.com/LeaVerou/awesomplete) and the fix should be made upstream in that project.

Relevant debug output:
```
VM420:1 Uncaught SyntaxError: Unexpected string
    at _.ITEM [as item] (awesomplete.js:329)
    at awesomplete.js:289
    at Array.forEach (<anonymous>)
    at _.evaluate (awesomplete.js:288)
_.ITEM @ awesomplete.js:329
(anonymous) @ awesomplete.js:289
evaluate @ awesomplete.js:288
```

I'm not going to fix this within converse.js nor am I going to make an attempt to fix it in awesomplete.js. I recommend you contact that project directly.
