### ISSUE TITLE
List joined rooms in the inverse UI

### ISSUE THREAD

**Issue by linkmauve** [jcbrand/converse.js#967]
There is currently no list of joined rooms (as tabs for example) from which I can select the one I want to go to now.  It is useful as soon as the user wants to join more than one room.

**Comment by jcbrand** [comment]
This is a bug. At first I thought it was a timing issue, as I mentioned to you in the Discuss chatroom. However at closer inspection it seems this has to do with the fact that your server doesn't support bookmarks and an expected event therefore didn't fire.

It's fixed now in a branch and will be included in the upcoming release.
