### ISSUE TITLE
Every message sent through Inverse is displayed twice

### ISSUE THREAD

**Issue by linkmauve** [jcbrand/converse.js#969]
I see it received only once in the BOSH payload as displayed by Firefox’s network console.

It happens only in groupchat messages, which leads me to think it could be related to displaying it first while sending it, and then when we receive it back.

**Comment by jcbrand** [comment]
I haven't been able to reproduce this.

**Comment by jcbrand** [comment]
I think this is a duplicate for #951, for which I have now committed a fix.
