### ISSUE TITLE
Setting chatbox "fullname" attribute prevents proper keepalive / auto_reconnect on page reload

### ISSUE THREAD

**Issue by rotorboy** [jcbrand/converse.js#975]
I'm not sure if this is a bug or not, or simply "not supported", but find behavior inconsistent, so thought I'd report it.

I am connecting to XMPP server via "prebind" and using Punjab as BOSH server. When a new chatbox is finished opening when receiving a text, I change the full name of the box to senders name rather than phone number via the set function:

chatbox.model.set({'fullname': name_string})

subsequent messages received from that number appear in the now-named chatbox. However, upon a page reload, the "refreshed" control-box no longer displays contact list, and chatbox is no longer visible. There is still a connection, as Inbound texts are "received" in that the notification sound plays, but no chatbox appears. The only way to reset is to close browser page and open a fresh connection.

Not setting the fullname allows proper refreshing of the page and conversejs windows (control box and chatbox).

**Comment by jcbrand** [comment]
Sounds like a bug. If you haven't already, set `debug` to true when calling `converse.initialize` and see whether you find any errors in the browser console.

**Comment by rotorboy** [comment]
Hi JC

Yes there are a couple “fatal errors” I see regularly in console, but they appear irrespective of the refresh issue I filed. I didn’t have debug to true, but setting it to true produced the ones already being displayed. Here are the two recurring ones

ERROR: An error occured while trying to enable message carbons.
p.log @ converse.min.js:253

AND

converse.min.js:253 FATAL: TypeError: Cannot read property 'querySelector' of null
    at e.onVCardData (https://cdn.conversejs.org/dist/converse.min.js:277:24613)
    at u (https://cdn.conversejs.org/dist/converse.min.js:234:20589)
    at s.Handler.handler (https://cdn.conversejs.org/dist/converse.min.js:251:8411)
    at s.Handler.run (https://cdn.conversejs.org/dist/converse.min.js:251:3853)
    at https://cdn.conversejs.org/dist/converse.min.js:251:12152
    at Object.forEachChild (https://cdn.conversejs.org/dist/converse.min.js:250:27695)
    at s.Connection._dataRecv (https://cdn.conversejs.org/dist/converse.min.js:251:11985)
    at e.Bosh._onRequestStateChange (https://cdn.conversejs.org/dist/converse.min.js:251:30891)

Quick trace seemed to be for fields not set, so not clear how “fatal” they really are.

Are you suggesting I file bugs against these?

Thanks


-Avi

**Comment by jcbrand** [comment]
Please use the non-minified build of converse.js. For minified builds the line numbers in the stack trace are useless.

**Comment by jcbrand** [comment]
@rotorboy Any update on this?

**Comment by rotorboy** [comment]
no longer see query error, but now see error attempting to enable message carbon:

ERROR: An error occured while trying to enable message carbons.
_converse.log @ converse.js:38289
(anonymous) @ converse.js:38905
run @ converse.js:30978
(anonymous) @ converse.js:32238
forEachChild @ converse.js:29946
_dataRecv @ converse.js:32226
_onRequestStateChange @ converse.js:33935
XMLHttpRequest.send (async)
sendFunc @ converse.js:34038
_processRequest @ converse.js:34053
_throttledRequestHandler @ converse.js:34205
_onIdle @ converse.js:33832
_onIdle @ converse.js:32860
(anonymous) @ converse.js:34165
setTimeout (async)
_send @ converse.js:34164
send @ converse.js:31691
sendIQ @ converse.js:31832
info @ converse.js:49673
queryInfo @ converse.js:49898
fetchFeatures @ converse.js:49882
initialize @ converse.js:49843
Backbone.Model @ converse.js:36183
child @ converse.js:37662
_prepareModel @ converse.js:36891
set @ converse.js:36658
options.success @ converse.js:36828
Backbone.BrowserStorage.sync.Backbone.localSync @ converse.js:38105
Backbone.sync @ converse.js:38146
sync @ converse.js:36576
fetch @ converse.js:36833
(anonymous) @ converse.js:49947
initializePromise @ converse.js:3197
Promise @ converse.js:3617
fetchEntities @ converse.js:49946
initialize @ converse.js:49941
Backbone.Collection @ converse.js:36538
child @ converse.js:37662
initializeDisco @ converse.js:49995
triggerEvents @ converse.js:36146
triggerApi @ converse.js:36134
eventsApi @ converse.js:35933
Events.trigger @ converse.js:36124
_converse.emit @ converse.js:38338
onConnected @ converse.js:39055
onConnectStatusChanged @ converse.js:38715
_changeConnectStatus @ converse.js:32102
_attach @ converse.js:33570
_restore @ converse.js:33608
restore @ converse.js:31539
restoreBOSHSession @ converse.js:39894
attemptPreboundSession @ converse.js:39910
logIn @ converse.js:40007
finishInitialization @ converse.js:40099
(anonymous) @ converse.js:40117
tryCatch @ converse.js:3148
invokeCallback @ converse.js:3163
(anonymous) @ converse.js:2909
flush @ converse.js:2860
characterData (async)
(anonymous) @ converse.js:2832
asap @ converse.js:2784
then @ converse.js:2908
_converse.initialize @ converse.js:40116
initialize @ converse.js:40288
(anonymous) @ status.php:1762

**Comment by jcbrand** [comment]
Ok, that's something else and warrants a new ticket if it's actually an issue. Might just be that your XMPP server doesn't have carbons enabled.
