### ISSUE TITLE
Closing chatbox and removing roster contact stops further text delivery

### ISSUE THREAD

**Issue by rotorboy** [jcbrand/converse.js#976]
Closing a chatbox associated with a phone number (SMS), and removing that number from contol box roster list prevents any new texts from appearing.

Sending a subsequent text from said number after it is removed from the roster causes the number to be added back to the roster, and delivery sound is played, but no chatbox appears. clicking on the roster contact will open a new chatbox, but any texts sent AFTER contact was removed from roster will not be displayed in the chatbox.

**Comment by jcbrand** [comment]
To receive messages from non-roster contacts, you need to set [allow_non_roster_messaging])https://conversejs.org/docs/html/configuration.html#allow-non-roster-messaging) to `true`.

> Sending a subsequent text from said number after it is removed from the roster causes the number to be added back to the roster, and delivery sound is played

Sounds like this might be a bug. I'm not sure. If you can reliably reproduce this, then please enable debug mode, save the output from the browser console and paste it here or send it to me.

**Comment by rotorboy** [comment]
sorry I didnt respond earlier. This fell through cracks. 

Here is the error when a previously rostered contact was removed from contact list, then that contact subsequently sends a message. The contact is added back to roster, but no window is opened with the received message


 ﻿
2
converse.js:48040 ERROR: Could not get roster item for JID 4084600630@sms and allow_non_roster_messaging is set to false
_converse.log	@	converse.js:48040
createChatBox	@	converse.js:50047
getChatBox	@	converse.js:50071
onMessage	@	converse.js:50012
run	@	converse.js:40937
(anonymous)	@	converse.js:42197
forEachChild	@	converse.js:39905
_dataRecv	@	converse.js:42185
_onRequestStateChange	@	converse.js:43894
XMLHttpRequest.send (async)		
sendFunc	@	converse.js:43997
_processRequest	@	converse.js:44012
_throttledRequestHandler	@	converse.js:44158
_onIdle	@	converse.js:43791
_onIdle	@	converse.js:42819
(anonymous)	@	converse.js:42825
setTimeout (async)		
_onIdle	@	converse.js:42824
(anonymous)	@	converse.js:42825
setTimeout (async)		
_onIdle	@	converse.js:42824
(anonymous)	@	converse.js:42825
setTimeout (async)		
_onIdle	@	converse.js:42824
(anonymous)	@	converse.js:42825
setTimeout (async)		
_onIdle	@	converse.js:42824
(anonymous)	@	converse.js:42825
setTimeout (async)		
_onIdle	@	converse.js:42824
(anonymous)	@	converse.js:42825
setTimeout (async)		
_onIdle	@	converse.js:42824
(anonymous)	@	converse.js:42825
setTimeout (async)		
_onIdle	@	converse.js:42824
(anonymous)	@	converse.js:42825
setTimeout (async)		
_onIdle	@	converse.js:42824
(anonymous)	@	converse.js:42825
setTimeout (async)		
_onIdle	@	converse.js:42824
(anonymous)	@	converse.js:42825
setTimeout (async)		
_onIdle	@	converse.js:42824
(anonymous)	@	converse.js:42825
setTimeout (async)		
_onIdle	@	converse.js:42824
(anonymous)	@	converse.js:42825
setTimeout (async)		
_onIdle	@	converse.js:42824
(anonymous)	@	converse.js:42825
setTimeout (async)		
_onIdle	@	converse.js:42824
(anonymous)	@	converse.js:42825
setTimeout (async)		
_onIdle	@	converse.js:42824
(anonymous)	@	converse.js:42825
setTimeout (async)		
_onIdle	@	converse.js:42824
(anonymous)	@	converse.js:42825
setTimeout (async)		
_onIdle	@	converse.js:42824
(anonymous)	@	converse.js:42825
setTimeout (async)		
_onIdle	@	converse.js:42824
(anonymous)	@	converse.js:42825
setTimeout (async)		
_onIdle	@	converse.js:42824
(anonymous)	@	converse.js:42825
setTimeout (async)		
_onIdle	@	converse.js:42824
(anonymous)	@	converse.js:42825
setTimeout (async)		
_onIdle	@	converse.js:42824
(anonymous)	@	converse.js:42825
setTimeout (async)		
_onIdle	@	converse.js:42824
(anonymous)	@	converse.js:42825
setTimeout (async)		
_onIdle	@	converse.js:42824
(anonymous)	@	converse.js:42825
setTimeout (async)		
_onIdle	@	converse.js:42824
(anonymous)	@	converse.js:42825
setTimeout (async)		
_onIdle	@	converse.js:42824
(anonymous)	@	converse.js:42825
setTimeout (async)		
_onIdle	@	converse.js:42824
(anonymous)	@	converse.js:42825
setTimeout (async)		
_onIdle	@	converse.js:42824
(anonymous)	@	converse.js:42825
setTimeout (async)		
_onIdle	@	converse.js:42824
(anonymous)	@	converse.js:42825
setTimeout (async)		
_onIdle	@	converse.js:42824
(anonymous)	@	converse.js:42825
setTimeout (async)		
_onIdle	@	converse.js:42824
(anonymous)	@	converse.js:42825
setTimeout (async)		
_onIdle	@	converse.js:42824
(anonymous)	@	converse.js:42825
setTimeout (async)		
_onIdle	@	converse.js:42824
(anonymous)	@	converse.js:42825
