### ISSUE TITLE
"invalid date" of messages forwarded in private browsing mode

### ISSUE THREAD

**Issue by happy-dev** [jcbrand/converse.js#978]
Hi, 

Thank you so much for this great library.
I intend to build a XMPP web component based on it and it is just amazing to be able to start further ahead than from scratch :-) 

I set up `forward_messages` to `true`, and it works great. 
However, if I use private tabs in Chrome, the forwarded message arrive with **invalid date** as a time : 
![screenshot from 2017-12-31 00-25-28](https://user-images.githubusercontent.com/9748542/34457945-3125ffca-edc1-11e7-8455-6d803f39b252.png)

I am willing to look into it if you set me on track.
Best regards

**Comment by jcbrand** [comment]
Thank you @happy-dev  :)

I just had a look at the relevant code (which is quite old) and it seems to me that the date was generated in the old format from [XEP-0091](https://xmpp.org/extensions/xep-0091.html) and not as it's required by [XEP-0082](https://xmpp.org/extensions/xep-0082.html).

I'll push a fix soon. That'll hopefully solve the problem. Why (or whether) this only breaks in private tabs I have no idea.

**Comment by jcbrand** [comment]
Version 3.3.0 has been released.
