### ISSUE TITLE
Registration Failed

### ISSUE THREAD

**Issue by fichie23** [jcbrand/converse.js#979]
I've tried to register my local ejabberd server domain to ConverseJS but always got this error : 
`Missing attribute 'id' in tag <iq/> qualified by namespace 'jabber:client'`
It might be related to #957 and fixed in master #800 , but it seems still not working, i've tried login ,it was succeeded, only when i tried to register it failed. Is there any additional configuration that i missed or i just found a new issue to fix ?

**Comment by jcbrand** [comment]
The fix is not yet released, only in the unbuilt source files in the master branch. I'm working hard on getting the release out ASAP.
