### ISSUE TITLE
Improve history loading behaviour

### ISSUE THREAD

**Issue by linkmauve** [jcbrand/converse.js#984]
Currently, when the user scrolls to the top of the messages, a huge spinner area pops up instantly, then older messages replace it, and if the user wants to load more they have to scroll down a bit, then scroll up again.

It would feel a lot better to react on further scroll ups the same way, and maybe add a very quick animation before and after the spinner.

**Comment by jcbrand** [comment]
The scroll position is now remembered and when messages first appear, there is short background animation.
