### ISSUE TITLE
moment.format is not a function error thrown (VM494 converse.js:44040)

### ISSUE THREAD

**Issue by henkdemarie** [jcbrand/converse.js#993]
Current version of https://cdn.conversejs.org/dist/converse.js (Version: 3.3.1)
On sending a message, using the chatbox:

<code>Uncaught TypeError: moment.format is not a function
    at child.sendMessage (VM494 converse.js:44040)</code>

Shouldn't this be moment().format() ?

**Comment by jcbrand** [comment]
Woops, how did that bug get through?

Thanks for reporting. Fixed and will be released soon.
