### ISSUE TITLE
Uncaught TypeError: Cannot read property 'get' of undefined

### ISSUE THREAD

**Issue by daniellucasss** [jcbrand/converse.js#994]
Hi everybody!
I'm having the error below when i try to use the login method.

> Uncaught TypeError: Cannot read property 'get' of undefined
>     at Object.get (inverse.min.js:49673)
>     at Object.initialize (testing.html:11)
>     at PluginSocket.initializePlugin (inverse.min.js:45578)
>     at arrayEach (inverse.min.js:4300)
>     at Object.forEach (inverse.min.js:13122)
>     at PluginSocket.initializePlugins (inverse.min.js:45610)
>     at Object.initPlugins (inverse.min.js:49615)
>     at Object._converse.initialize (inverse.min.js:49632)
>     at Object.initialize (inverse.min.js:49788)
>     at testing.html:21

I used this code:

```
<html>
    <head>
        <title>Testing</title>
        <link rel="stylesheet" type="text/css" media="screen" href="https://cdn.conversejs.org/css/inverse.min.css">
        <script src="https://cdn.conversejs.org/dist/inverse.min.js"></script>
    </head>
    <body>
            <script>
                converse.plugins.add('login', {
                    initialize: function () {
                        this._converse.api.user.login({
                            'jid': 'test@test',
                            'password': 'testing'
                        });
                    }
                });

                converse.initialize({
                    bosh_service_url: 'http://10.203.117.33:7070/http-bind/',
                    show_controlbox_by_default: true,
                    allow_logout: true,
                    debug: true,
                    prebind: false,
                    whitelisted_plugins: ['login']
                });
            </script>
    </body>
</html>
```

Have i missed something?

**Comment by jcbrand** [comment]
Hi there

You did everything right, you just happened to uncover a bug!

Should be fixed now. A new bugfix release should be out soon.

**Comment by jcbrand** [comment]
BTW, just to be clear, the CDN is only updated with the next release.

Also, you should no longer use `inverse.min.js`. Both inverse and the original layout are now available via one JS file: `converse.min.js`
