### ISSUE TITLE
version 3.3.1 - problem adding configuration options

### ISSUE THREAD

**Issue by turbocloud** [jcbrand/converse.js#998]
just starting with version 3.3.1 I am having problems to add more than 3 configuration options with the result that converse is not showing up.
This is reproducable.
This is my piece of code.
<script>
    converse.initialize({
        bosh_service_url: 'https://xxxxxxx:5281/http-bind',
        show_controlbox_by_default: true,
        allow_registration: false,
        show_send_button: true,
        play_sounds: true,
   });
</script>

no matter what option I add, no show. Any ideas?

Johannes

**Comment by jcbrand** [comment]
Check your browser console for errors. I pasted your code into index.html in the master branch and it worked fine.

**Comment by turbocloud** [comment]
This code is working fine, BUT adding only one more option will break it.
That is the problem.

**Comment by jcbrand** [comment]
I can't reproduce the issue. I pasted your code and then added one more option and it continues to work fine for me. I'll ask one last time. Check your browser console for errors.

Additionally, when calling `converse.initialize`, add `debug: true` as a config option.

**Comment by turbocloud** [comment]
ok, here is the output. This time I have added the option view_mode, before that, I had added locked_domain which I really want to use. Same error and no converse box on the page shown.

![converse1](https://user-images.githubusercontent.com/6852588/35421671-1b4bc0b0-020a-11e8-992c-6bedbf046e8f.jpg)

**Comment by jcbrand** [comment]
Options must be added as strings. In other words: `view_mode: 'mobile'`.
